# Copyright 2022 The StableHLO Authors.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# markdownlint-cli configuration file.

# Enable all markdownlint rules by default
default: true

# List formatting:
# 1. Lists must start following a blank line.
# 2. Unordered (bulleted) lists are indented by 2 spaces and must use the same
#    bullet symbol consistently (such as *, +, or -).
# 3. Ordered (numbered) lists are not indented.
# 4. Each nested list increases indentation by 2 spaces. This is checked
#    automatically for unordered lists with the following ul-indent rule,
#    but markdownlint currently does not check indentation for ordered lists.
#    Please also use 2-space indentation for nested ordered lists.
# 5. In multiline list items, subsequent lines are indented by 2 spaces.
#    This is not checked automatically, so we're documenting this convention
#    to make sure the codebase stays consistent. Example:
#
#      * This is a list item that has multiple
#        lines and each line aligns with the text
#        from the first line.
#
#    For ordered lists, that means three spaces for wrapped lines:
#
#    1. The intention is to keep the text aligned
#       on the left for readability.
ul-indent:
  indent: 2
  start_indented: true

# Limit to 80-char line length, except for tables and code blocks
line-length:
  line_length: 80
  tables: false
  code_blocks: false

# Allow inline HTML
no-inline-html: false

# Allow dupe heading names only if they're not siblings
no-duplicate-heading:
  siblings_only: true

# Allow images w/o alt-text
no-alt-text: false

# TODO(smain): Remove this once this error is resolved:
# https://github.com/DavidAnson/markdownlint/issues/686
reference-links-images: false
