# Copyright 2025 The StableHLO Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

package(
    # copybara:uncomment default_applicable_licenses = ["//:license"],
    default_visibility = [
        "//visibility:public",  # copybara:comment
        # copybara:uncomment "//:stablehlo_friends",
    ],
    licenses = ["notice"],
)

# copybara:uncomment_begin
# filegroup(
#     name = "all_files",
#     srcs = glob(["**"]),
#     visibility = ["//:__subpackages__"],
# )
# copybara:uncomment_end

exports_files(
    [
        "lit_test_suite.bzl",
        "utils.bzl",
    ],
    visibility = ["//:__subpackages__"],
)
