// RUN: stablehlo-opt --chlo-legalize-to-stablehlo --split-input-file %s | FileCheck %s
// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// CHECK-LABEL:   func.func @asin_bf16(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<bf16>) -> tensor<bf16> {
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<bf16>
// CHECK:           %[[SUBTRACT_0:.*]] = stablehlo.subtract %[[CONSTANT_0]], %[[ARG0]] : tensor<bf16>
// CHECK:           %[[ADD_0:.*]] = stablehlo.add %[[CONSTANT_0]], %[[ARG0]] : tensor<bf16>
// CHECK:           %[[MULTIPLY_0:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_0]] : tensor<bf16>
// CHECK:           %[[SQRT_0:.*]] = stablehlo.sqrt %[[MULTIPLY_0]] : tensor<bf16>
// CHECK:           %[[ADD_1:.*]] = stablehlo.add %[[CONSTANT_0]], %[[SQRT_0]] : tensor<bf16>
// CHECK:           %[[VAL_0:.*]] = stablehlo.atan2 %[[ARG0]], %[[ADD_1]] : tensor<bf16>
// CHECK:           %[[ADD_2:.*]] = stablehlo.add %[[VAL_0]], %[[VAL_0]] : tensor<bf16>
// CHECK:           return %[[ADD_2]] : tensor<bf16>
// CHECK:         }
func.func @asin_bf16(%arg : tensor<bf16>) -> tensor<bf16> {
  %result = "chlo.asin"(%arg) : (tensor<bf16>) -> tensor<bf16>
  func.return %result : tensor<bf16>
}

// -----

// CHECK-LABEL:   func.func @asin_f16(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<f16>) -> tensor<f16> {
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f16>
// CHECK:           %[[SUBTRACT_0:.*]] = stablehlo.subtract %[[CONSTANT_0]], %[[ARG0]] : tensor<f16>
// CHECK:           %[[ADD_0:.*]] = stablehlo.add %[[CONSTANT_0]], %[[ARG0]] : tensor<f16>
// CHECK:           %[[MULTIPLY_0:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_0]] : tensor<f16>
// CHECK:           %[[SQRT_0:.*]] = stablehlo.sqrt %[[MULTIPLY_0]] : tensor<f16>
// CHECK:           %[[ADD_1:.*]] = stablehlo.add %[[CONSTANT_0]], %[[SQRT_0]] : tensor<f16>
// CHECK:           %[[VAL_0:.*]] = stablehlo.atan2 %[[ARG0]], %[[ADD_1]] : tensor<f16>
// CHECK:           %[[ADD_2:.*]] = stablehlo.add %[[VAL_0]], %[[VAL_0]] : tensor<f16>
// CHECK:           return %[[ADD_2]] : tensor<f16>
// CHECK:         }
func.func @asin_f16(%arg : tensor<f16>) -> tensor<f16> {
  %result = "chlo.asin"(%arg) : (tensor<f16>) -> tensor<f16>
  func.return %result : tensor<f16>
}

// -----

// CHECK-LABEL:   func.func @asin_f32(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<f32>) -> tensor<f32> {
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[SUBTRACT_0:.*]] = stablehlo.subtract %[[CONSTANT_0]], %[[ARG0]] : tensor<f32>
// CHECK:           %[[ADD_0:.*]] = stablehlo.add %[[CONSTANT_0]], %[[ARG0]] : tensor<f32>
// CHECK:           %[[MULTIPLY_0:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_0]] : tensor<f32>
// CHECK:           %[[SQRT_0:.*]] = stablehlo.sqrt %[[MULTIPLY_0]] : tensor<f32>
// CHECK:           %[[ADD_1:.*]] = stablehlo.add %[[CONSTANT_0]], %[[SQRT_0]] : tensor<f32>
// CHECK:           %[[VAL_0:.*]] = stablehlo.atan2 %[[ARG0]], %[[ADD_1]] : tensor<f32>
// CHECK:           %[[ADD_2:.*]] = stablehlo.add %[[VAL_0]], %[[VAL_0]] : tensor<f32>
// CHECK:           return %[[ADD_2]] : tensor<f32>
// CHECK:         }
func.func @asin_f32(%arg : tensor<f32>) -> tensor<f32> {
  %result = "chlo.asin"(%arg) : (tensor<f32>) -> tensor<f32>
  func.return %result : tensor<f32>
}

// -----

// CHECK-LABEL:   func.func @asin_f64(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<f64>) -> tensor<f64> {
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f64>
// CHECK:           %[[SUBTRACT_0:.*]] = stablehlo.subtract %[[CONSTANT_0]], %[[ARG0]] : tensor<f64>
// CHECK:           %[[ADD_0:.*]] = stablehlo.add %[[CONSTANT_0]], %[[ARG0]] : tensor<f64>
// CHECK:           %[[MULTIPLY_0:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_0]] : tensor<f64>
// CHECK:           %[[SQRT_0:.*]] = stablehlo.sqrt %[[MULTIPLY_0]] : tensor<f64>
// CHECK:           %[[ADD_1:.*]] = stablehlo.add %[[CONSTANT_0]], %[[SQRT_0]] : tensor<f64>
// CHECK:           %[[VAL_0:.*]] = stablehlo.atan2 %[[ARG0]], %[[ADD_1]] : tensor<f64>
// CHECK:           %[[ADD_2:.*]] = stablehlo.add %[[VAL_0]], %[[VAL_0]] : tensor<f64>
// CHECK:           return %[[ADD_2]] : tensor<f64>
// CHECK:         }
func.func @asin_f64(%arg : tensor<f64>) -> tensor<f64> {
  %result = "chlo.asin"(%arg) : (tensor<f64>) -> tensor<f64>
  func.return %result : tensor<f64>
}

// -----

// CHECK-LABEL:   func.func @asin_complex_f32(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<complex<f32>>) -> tensor<complex<f32>> {
// CHECK:           %[[REAL_0:.*]] = stablehlo.real %[[ARG0]] : (tensor<complex<f32>>) -> tensor<f32>
// CHECK:           %[[REAL_1:.*]] = stablehlo.real %[[ARG0]] : (tensor<complex<f32>>) -> tensor<f32>
// CHECK:           %[[ABS_0:.*]] = stablehlo.abs %[[REAL_1]] : tensor<f32>
// CHECK:           %[[IMAG_0:.*]] = stablehlo.imag %[[ARG0]] : (tensor<complex<f32>>) -> tensor<f32>
// CHECK:           %[[ABS_1:.*]] = stablehlo.abs %[[IMAG_0]] : tensor<f32>
// CHECK:           %[[MAXIMUM_0:.*]] = stablehlo.maximum %[[ABS_0]], %[[ABS_1]] : tensor<f32>
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<3.40282347E+38> : tensor<f32>
// CHECK:           %[[SQRT_0:.*]] = stablehlo.sqrt %[[CONSTANT_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_1:.*]] = stablehlo.constant dense<8.000000e+00> : tensor<f32>
// CHECK:           %[[DIVIDE_0:.*]] = stablehlo.divide %[[SQRT_0]], %[[CONSTANT_1]] : tensor<f32>
// CHECK:           %[[COMPARE_0:.*]] = stablehlo.compare  GE, %[[MAXIMUM_0]], %[[DIVIDE_0]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[CONSTANT_2:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[COMPARE_1:.*]] = stablehlo.compare  LE, %[[ABS_0]], %[[CONSTANT_2]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[CONSTANT_3:.*]] = stablehlo.constant dense<5.000000e-01> : tensor<f32>
// CHECK:           %[[ADD_0:.*]] = stablehlo.add %[[ABS_0]], %[[CONSTANT_2]] : tensor<f32>
// CHECK:           %[[ABS_2:.*]] = stablehlo.abs %[[ADD_0]] : tensor<f32>
// CHECK:           %[[MAXIMUM_1:.*]] = stablehlo.maximum %[[ABS_2]], %[[ABS_1]] : tensor<f32>
// CHECK:           %[[MINIMUM_0:.*]] = stablehlo.minimum %[[ABS_2]], %[[ABS_1]] : tensor<f32>
// CHECK:           %[[COMPARE_2:.*]] = stablehlo.compare  EQ, %[[MAXIMUM_1]], %[[MINIMUM_0]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[CONSTANT_4:.*]] = stablehlo.constant dense<1.41421354> : tensor<f32>
// CHECK:           %[[MULTIPLY_0:.*]] = stablehlo.multiply %[[CONSTANT_4]], %[[MAXIMUM_1]] : tensor<f32>
// CHECK:           %[[DIVIDE_1:.*]] = stablehlo.divide %[[MINIMUM_0]], %[[MAXIMUM_1]] : tensor<f32>
// CHECK:           %[[MULTIPLY_1:.*]] = stablehlo.multiply %[[DIVIDE_1]], %[[DIVIDE_1]] : tensor<f32>
// CHECK:           %[[ADD_1:.*]] = stablehlo.add %[[CONSTANT_2]], %[[MULTIPLY_1]] : tensor<f32>
// CHECK:           %[[SQRT_1:.*]] = stablehlo.sqrt %[[ADD_1]] : tensor<f32>
// CHECK:           %[[COMPARE_3:.*]] = stablehlo.compare  EQ, %[[SQRT_1]], %[[CONSTANT_2]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[CONSTANT_5:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<f32>
// CHECK:           %[[COMPARE_4:.*]] = stablehlo.compare  GT, %[[MULTIPLY_1]], %[[CONSTANT_5]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[AND_0:.*]] = stablehlo.and %[[COMPARE_3]], %[[COMPARE_4]] : tensor<i1>
// CHECK:           %[[MULTIPLY_2:.*]] = stablehlo.multiply %[[MAXIMUM_1]], %[[MULTIPLY_1]] : tensor<f32>
// CHECK:           %[[CONSTANT_6:.*]] = stablehlo.constant dense<2.000000e+00> : tensor<f32>
// CHECK:           %[[DIVIDE_2:.*]] = stablehlo.divide %[[MULTIPLY_2]], %[[CONSTANT_6]] : tensor<f32>
// CHECK:           %[[ADD_2:.*]] = stablehlo.add %[[MAXIMUM_1]], %[[DIVIDE_2]] : tensor<f32>
// CHECK:           %[[MULTIPLY_3:.*]] = stablehlo.multiply %[[MAXIMUM_1]], %[[SQRT_1]] : tensor<f32>
// CHECK:           %[[SELECT_0:.*]] = stablehlo.select %[[AND_0]], %[[ADD_2]], %[[MULTIPLY_3]] : tensor<i1>, tensor<f32>
// CHECK:           %[[SELECT_1:.*]] = stablehlo.select %[[COMPARE_2]], %[[MULTIPLY_0]], %[[SELECT_0]] : tensor<i1>, tensor<f32>
// CHECK:           %[[SUBTRACT_0:.*]] = stablehlo.subtract %[[ABS_0]], %[[CONSTANT_2]] : tensor<f32>
// CHECK:           %[[ABS_3:.*]] = stablehlo.abs %[[SUBTRACT_0]] : tensor<f32>
// CHECK:           %[[MAXIMUM_2:.*]] = stablehlo.maximum %[[ABS_3]], %[[ABS_1]] : tensor<f32>
// CHECK:           %[[MINIMUM_1:.*]] = stablehlo.minimum %[[ABS_3]], %[[ABS_1]] : tensor<f32>
// CHECK:           %[[COMPARE_5:.*]] = stablehlo.compare  EQ, %[[MAXIMUM_2]], %[[MINIMUM_1]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[MULTIPLY_4:.*]] = stablehlo.multiply %[[CONSTANT_4]], %[[MAXIMUM_2]] : tensor<f32>
// CHECK:           %[[DIVIDE_3:.*]] = stablehlo.divide %[[MINIMUM_1]], %[[MAXIMUM_2]] : tensor<f32>
// CHECK:           %[[MULTIPLY_5:.*]] = stablehlo.multiply %[[DIVIDE_3]], %[[DIVIDE_3]] : tensor<f32>
// CHECK:           %[[ADD_3:.*]] = stablehlo.add %[[CONSTANT_2]], %[[MULTIPLY_5]] : tensor<f32>
// CHECK:           %[[SQRT_2:.*]] = stablehlo.sqrt %[[ADD_3]] : tensor<f32>
// CHECK:           %[[COMPARE_6:.*]] = stablehlo.compare  EQ, %[[SQRT_2]], %[[CONSTANT_2]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[COMPARE_7:.*]] = stablehlo.compare  GT, %[[MULTIPLY_5]], %[[CONSTANT_5]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[AND_1:.*]] = stablehlo.and %[[COMPARE_6]], %[[COMPARE_7]] : tensor<i1>
// CHECK:           %[[MULTIPLY_6:.*]] = stablehlo.multiply %[[MAXIMUM_2]], %[[MULTIPLY_5]] : tensor<f32>
// CHECK:           %[[DIVIDE_4:.*]] = stablehlo.divide %[[MULTIPLY_6]], %[[CONSTANT_6]] : tensor<f32>
// CHECK:           %[[ADD_4:.*]] = stablehlo.add %[[MAXIMUM_2]], %[[DIVIDE_4]] : tensor<f32>
// CHECK:           %[[MULTIPLY_7:.*]] = stablehlo.multiply %[[MAXIMUM_2]], %[[SQRT_2]] : tensor<f32>
// CHECK:           %[[SELECT_2:.*]] = stablehlo.select %[[AND_1]], %[[ADD_4]], %[[MULTIPLY_7]] : tensor<i1>, tensor<f32>
// CHECK:           %[[SELECT_3:.*]] = stablehlo.select %[[COMPARE_5]], %[[MULTIPLY_4]], %[[SELECT_2]] : tensor<i1>, tensor<f32>
// CHECK:           %[[ADD_5:.*]] = stablehlo.add %[[SELECT_1]], %[[SELECT_3]] : tensor<f32>
// CHECK:           %[[MULTIPLY_8:.*]] = stablehlo.multiply %[[CONSTANT_3]], %[[ADD_5]] : tensor<f32>
// CHECK:           %[[ADD_6:.*]] = stablehlo.add %[[MULTIPLY_8]], %[[ABS_0]] : tensor<f32>
// CHECK:           %[[MULTIPLY_9:.*]] = stablehlo.multiply %[[CONSTANT_3]], %[[ADD_6]] : tensor<f32>
// CHECK:           %[[MULTIPLY_10:.*]] = stablehlo.multiply %[[ABS_1]], %[[ABS_1]] : tensor<f32>
// CHECK:           %[[ADD_7:.*]] = stablehlo.add %[[SELECT_1]], %[[ADD_0]] : tensor<f32>
// CHECK:           %[[DIVIDE_5:.*]] = stablehlo.divide %[[MULTIPLY_10]], %[[ADD_7]] : tensor<f32>
// CHECK:           %[[SUBTRACT_1:.*]] = stablehlo.subtract %[[SELECT_3]], %[[SUBTRACT_0]] : tensor<f32>
// CHECK:           %[[ADD_8:.*]] = stablehlo.add %[[DIVIDE_5]], %[[SUBTRACT_1]] : tensor<f32>
// CHECK:           %[[MULTIPLY_11:.*]] = stablehlo.multiply %[[MULTIPLY_9]], %[[ADD_8]] : tensor<f32>
// CHECK:           %[[SQRT_3:.*]] = stablehlo.sqrt %[[MULTIPLY_11]] : tensor<f32>
// CHECK:           %[[DIVIDE_6:.*]] = stablehlo.divide %[[MULTIPLY_9]], %[[ADD_7]] : tensor<f32>
// CHECK:           %[[ADD_9:.*]] = stablehlo.add %[[SELECT_3]], %[[SUBTRACT_0]] : tensor<f32>
// CHECK:           %[[DIVIDE_7:.*]] = stablehlo.divide %[[MULTIPLY_9]], %[[ADD_9]] : tensor<f32>
// CHECK:           %[[ADD_10:.*]] = stablehlo.add %[[DIVIDE_6]], %[[DIVIDE_7]] : tensor<f32>
// CHECK:           %[[SQRT_4:.*]] = stablehlo.sqrt %[[ADD_10]] : tensor<f32>
// CHECK:           %[[MULTIPLY_12:.*]] = stablehlo.multiply %[[ABS_1]], %[[SQRT_4]] : tensor<f32>
// CHECK:           %[[SELECT_4:.*]] = stablehlo.select %[[COMPARE_1]], %[[SQRT_3]], %[[MULTIPLY_12]] : tensor<i1>, tensor<f32>
// CHECK:           %[[SELECT_5:.*]] = stablehlo.select %[[COMPARE_0]], %[[ABS_1]], %[[SELECT_4]] : tensor<i1>, tensor<f32>
// CHECK:           %[[CONSTANT_7:.*]] = stablehlo.constant dense<9.99999995E+11> : tensor<f32>
// CHECK:           %[[MULTIPLY_13:.*]] = stablehlo.multiply %[[DIVIDE_0]], %[[CONSTANT_7]] : tensor<f32>
// CHECK:           %[[COMPARE_8:.*]] = stablehlo.compare  LT, %[[ABS_0]], %[[MULTIPLY_13]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[CONSTANT_8:.*]] = stablehlo.constant dense<9.99999997E-7> : tensor<f32>
// CHECK:           %[[MULTIPLY_14:.*]] = stablehlo.multiply %[[DIVIDE_0]], %[[CONSTANT_8]] : tensor<f32>
// CHECK:           %[[CONSTANT_9:.*]] = stablehlo.constant dense<1.000000e+02> : tensor<f32>
// CHECK:           %[[MULTIPLY_15:.*]] = stablehlo.multiply %[[DIVIDE_0]], %[[CONSTANT_9]] : tensor<f32>
// CHECK:           %[[SELECT_6:.*]] = stablehlo.select %[[COMPARE_8]], %[[MULTIPLY_14]], %[[MULTIPLY_15]] : tensor<i1>, tensor<f32>
// CHECK:           %[[COMPARE_9:.*]] = stablehlo.compare  GE, %[[ABS_1]], %[[SELECT_6]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[SELECT_7:.*]] = stablehlo.select %[[COMPARE_9]], %[[ABS_1]], %[[ABS_0]] : tensor<i1>, tensor<f32>
// CHECK:           %[[SELECT_8:.*]] = stablehlo.select %[[COMPARE_9]], %[[SELECT_6]], %[[DIVIDE_0]] : tensor<i1>, tensor<f32>
// CHECK:           %[[COMPARE_10:.*]] = stablehlo.compare  GE, %[[SELECT_7]], %[[SELECT_8]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[LOG_0:.*]] = stablehlo.log %[[CONSTANT_6]] : tensor<f32>
// CHECK:           %[[LOG_1:.*]] = stablehlo.log %[[SELECT_7]] : tensor<f32>
// CHECK:           %[[ADD_11:.*]] = stablehlo.add %[[LOG_0]], %[[LOG_1]] : tensor<f32>
// CHECK:           %[[CONSTANT_10:.*]] = stablehlo.constant dense<0x7F800000> : tensor<f32>
// CHECK:           %[[COMPARE_11:.*]] = stablehlo.compare  EQ, %[[ABS_1]], %[[CONSTANT_10]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[NOT_0:.*]] = stablehlo.not %[[COMPARE_11]] : tensor<i1>
// CHECK:           %[[AND_2:.*]] = stablehlo.and %[[COMPARE_9]], %[[NOT_0]] : tensor<i1>
// CHECK:           %[[DIVIDE_8:.*]] = stablehlo.divide %[[ABS_0]], %[[ABS_1]] : tensor<f32>
// CHECK:           %[[SELECT_9:.*]] = stablehlo.select %[[AND_2]], %[[DIVIDE_8]], %[[CONSTANT_5]] : tensor<i1>, tensor<f32>
// CHECK:           %[[MULTIPLY_16:.*]] = stablehlo.multiply %[[SELECT_9]], %[[SELECT_9]] : tensor<f32>
// CHECK:           %[[LOG_PLUS_ONE_0:.*]] = stablehlo.log_plus_one %[[MULTIPLY_16]] : tensor<f32>
// CHECK:           %[[MULTIPLY_17:.*]] = stablehlo.multiply %[[CONSTANT_3]], %[[LOG_PLUS_ONE_0]] : tensor<f32>
// CHECK:           %[[ADD_12:.*]] = stablehlo.add %[[ADD_11]], %[[MULTIPLY_17]] : tensor<f32>
// CHECK:           %[[CONSTANT_11:.*]] = stablehlo.constant dense<1.17549435E-38> : tensor<f32>
// CHECK:           %[[SQRT_5:.*]] = stablehlo.sqrt %[[CONSTANT_11]] : tensor<f32>
// CHECK:           %[[CONSTANT_12:.*]] = stablehlo.constant dense<4.000000e+00> : tensor<f32>
// CHECK:           %[[MULTIPLY_18:.*]] = stablehlo.multiply %[[SQRT_5]], %[[CONSTANT_12]] : tensor<f32>
// CHECK:           %[[COMPARE_12:.*]] = stablehlo.compare  LT, %[[ABS_1]], %[[MULTIPLY_18]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[COMPARE_13:.*]] = stablehlo.compare  LT, %[[ABS_0]], %[[CONSTANT_2]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[AND_3:.*]] = stablehlo.and %[[COMPARE_12]], %[[COMPARE_13]] : tensor<i1>
// CHECK:           %[[MULTIPLY_19:.*]] = stablehlo.multiply %[[ADD_0]], %[[SUBTRACT_0]] : tensor<f32>
// CHECK:           %[[ADD_13:.*]] = stablehlo.add %[[MULTIPLY_8]], %[[CONSTANT_2]] : tensor<f32>
// CHECK:           %[[DIVIDE_9:.*]] = stablehlo.divide %[[MULTIPLY_19]], %[[ADD_13]] : tensor<f32>
// CHECK:           %[[NEGATE_0:.*]] = stablehlo.negate %[[DIVIDE_9]] : tensor<f32>
// CHECK:           %[[COMPARE_14:.*]] = stablehlo.compare  GE, %[[ABS_0]], %[[CONSTANT_2]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[MULTIPLY_20:.*]] = stablehlo.multiply %[[CONSTANT_3]], %[[MULTIPLY_10]] : tensor<f32>
// CHECK:           %[[DIVIDE_10:.*]] = stablehlo.divide %[[MULTIPLY_20]], %[[ADD_7]] : tensor<f32>
// CHECK:           %[[MULTIPLY_21:.*]] = stablehlo.multiply %[[CONSTANT_3]], %[[ADD_9]] : tensor<f32>
// CHECK:           %[[ADD_14:.*]] = stablehlo.add %[[DIVIDE_10]], %[[MULTIPLY_21]] : tensor<f32>
// CHECK:           %[[CONSTANT_13:.*]] = stablehlo.constant dense<1.500000e+00> : tensor<f32>
// CHECK:           %[[COMPARE_15:.*]] = stablehlo.compare  LE, %[[MULTIPLY_8]], %[[CONSTANT_13]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[DIVIDE_11:.*]] = stablehlo.divide %[[MULTIPLY_20]], %[[SUBTRACT_1]] : tensor<f32>
// CHECK:           %[[ADD_15:.*]] = stablehlo.add %[[DIVIDE_10]], %[[DIVIDE_11]] : tensor<f32>
// CHECK:           %[[SUBTRACT_2:.*]] = stablehlo.subtract %[[MULTIPLY_8]], %[[CONSTANT_2]] : tensor<f32>
// CHECK:           %[[SELECT_10:.*]] = stablehlo.select %[[COMPARE_15]], %[[ADD_15]], %[[SUBTRACT_2]] : tensor<i1>, tensor<f32>
// CHECK:           %[[SELECT_11:.*]] = stablehlo.select %[[COMPARE_14]], %[[ADD_14]], %[[SELECT_10]] : tensor<i1>, tensor<f32>
// CHECK:           %[[SELECT_12:.*]] = stablehlo.select %[[AND_3]], %[[NEGATE_0]], %[[SELECT_11]] : tensor<i1>, tensor<f32>
// CHECK:           %[[MULTIPLY_22:.*]] = stablehlo.multiply %[[SELECT_12]], %[[ADD_13]] : tensor<f32>
// CHECK:           %[[SQRT_6:.*]] = stablehlo.sqrt %[[MULTIPLY_22]] : tensor<f32>
// CHECK:           %[[DIVIDE_12:.*]] = stablehlo.divide %[[ABS_1]], %[[SQRT_6]] : tensor<f32>
// CHECK:           %[[ADD_16:.*]] = stablehlo.add %[[SELECT_12]], %[[SQRT_6]] : tensor<f32>
// CHECK:           %[[LOG_PLUS_ONE_1:.*]] = stablehlo.log_plus_one %[[ADD_16]] : tensor<f32>
// CHECK:           %[[SELECT_13:.*]] = stablehlo.select %[[AND_3]], %[[DIVIDE_12]], %[[LOG_PLUS_ONE_1]] : tensor<i1>, tensor<f32>
// CHECK:           %[[SELECT_14:.*]] = stablehlo.select %[[COMPARE_10]], %[[ADD_12]], %[[SELECT_13]] : tensor<i1>, tensor<f32>
// CHECK:           %[[COMPLEX_0:.*]] = stablehlo.complex %[[SELECT_5]], %[[SELECT_14]] : tensor<complex<f32>>
// CHECK:           %[[REAL_2:.*]] = stablehlo.real %[[COMPLEX_0]] : (tensor<complex<f32>>) -> tensor<f32>
// CHECK:           %[[VAL_0:.*]] = stablehlo.atan2 %[[REAL_0]], %[[REAL_2]] : tensor<f32>
// CHECK:           %[[IMAG_1:.*]] = stablehlo.imag %[[ARG0]] : (tensor<complex<f32>>) -> tensor<f32>
// CHECK:           %[[CONSTANT_14:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<f32>
// CHECK:           %[[COMPARE_16:.*]] = stablehlo.compare  LT, %[[IMAG_1]], %[[CONSTANT_14]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[IMAG_2:.*]] = stablehlo.imag %[[COMPLEX_0]] : (tensor<complex<f32>>) -> tensor<f32>
// CHECK:           %[[NEGATE_1:.*]] = stablehlo.negate %[[IMAG_2]] : tensor<f32>
// CHECK:           %[[SELECT_15:.*]] = stablehlo.select %[[COMPARE_16]], %[[NEGATE_1]], %[[IMAG_2]] : tensor<i1>, tensor<f32>
// CHECK:           %[[COMPLEX_1:.*]] = stablehlo.complex %[[VAL_0]], %[[SELECT_15]] : tensor<complex<f32>>
// CHECK:           return %[[COMPLEX_1]] : tensor<complex<f32>>
// CHECK:         }
func.func @asin_complex_f32(%arg : tensor<complex<f32>>) -> tensor<complex<f32>> {
  %result = "chlo.asin"(%arg) : (tensor<complex<f32>>) -> tensor<complex<f32>>
  func.return %result : tensor<complex<f32>>
}

// -----

// CHECK-LABEL:   func.func @asin_complex_f64_dynamic(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<?xcomplex<f64>>) -> tensor<?xcomplex<f64>> {
// CHECK:           %[[REAL_0:.*]] = stablehlo.real %[[ARG0]] : (tensor<?xcomplex<f64>>) -> tensor<?xf64>
// CHECK:           %[[REAL_1:.*]] = stablehlo.real %[[ARG0]] : (tensor<?xcomplex<f64>>) -> tensor<?xf64>
// CHECK:           %[[ABS_0:.*]] = stablehlo.abs %[[REAL_1]] : tensor<?xf64>
// CHECK:           %[[IMAG_0:.*]] = stablehlo.imag %[[ARG0]] : (tensor<?xcomplex<f64>>) -> tensor<?xf64>
// CHECK:           %[[ABS_1:.*]] = stablehlo.abs %[[IMAG_0]] : tensor<?xf64>
// CHECK:           %[[MAXIMUM_0:.*]] = stablehlo.maximum %[[ABS_0]], %[[ABS_1]] : tensor<?xf64>
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<1.7976931348623157E+308> : tensor<f64>
// CHECK:           %[[SHAPE_OF_0:.*]] = shape.shape_of %[[REAL_1]] : tensor<?xf64> -> tensor<1xindex>
// CHECK:           %[[DYNAMIC_BROADCAST_IN_DIM_0:.*]] = stablehlo.dynamic_broadcast_in_dim %[[CONSTANT_0]], %[[SHAPE_OF_0]], dims = [] : (tensor<f64>, tensor<1xindex>) -> tensor<?xf64>
// CHECK:           %[[SQRT_0:.*]] = stablehlo.sqrt %[[DYNAMIC_BROADCAST_IN_DIM_0]] : tensor<?xf64>
// CHECK:           %[[CONSTANT_1:.*]] = stablehlo.constant dense<8.000000e+00> : tensor<f64>
// CHECK:           %[[SHAPE_OF_1:.*]] = shape.shape_of %[[REAL_1]] : tensor<?xf64> -> tensor<1xindex>
// CHECK:           %[[DYNAMIC_BROADCAST_IN_DIM_1:.*]] = stablehlo.dynamic_broadcast_in_dim %[[CONSTANT_1]], %[[SHAPE_OF_1]], dims = [] : (tensor<f64>, tensor<1xindex>) -> tensor<?xf64>
// CHECK:           %[[DIVIDE_0:.*]] = stablehlo.divide %[[SQRT_0]], %[[DYNAMIC_BROADCAST_IN_DIM_1]] : tensor<?xf64>
// CHECK:           %[[COMPARE_0:.*]] = stablehlo.compare  GE, %[[MAXIMUM_0]], %[[DIVIDE_0]] : (tensor<?xf64>, tensor<?xf64>) -> tensor<?xi1>
// CHECK:           %[[CONSTANT_2:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f64>
// CHECK:           %[[SHAPE_OF_2:.*]] = shape.shape_of %[[REAL_1]] : tensor<?xf64> -> tensor<1xindex>
// CHECK:           %[[DYNAMIC_BROADCAST_IN_DIM_2:.*]] = stablehlo.dynamic_broadcast_in_dim %[[CONSTANT_2]], %[[SHAPE_OF_2]], dims = [] : (tensor<f64>, tensor<1xindex>) -> tensor<?xf64>
// CHECK:           %[[COMPARE_1:.*]] = stablehlo.compare  LE, %[[ABS_0]], %[[DYNAMIC_BROADCAST_IN_DIM_2]] : (tensor<?xf64>, tensor<?xf64>) -> tensor<?xi1>
// CHECK:           %[[CONSTANT_3:.*]] = stablehlo.constant dense<5.000000e-01> : tensor<f64>
// CHECK:           %[[SHAPE_OF_3:.*]] = shape.shape_of %[[REAL_1]] : tensor<?xf64> -> tensor<1xindex>
// CHECK:           %[[DYNAMIC_BROADCAST_IN_DIM_3:.*]] = stablehlo.dynamic_broadcast_in_dim %[[CONSTANT_3]], %[[SHAPE_OF_3]], dims = [] : (tensor<f64>, tensor<1xindex>) -> tensor<?xf64>
// CHECK:           %[[ADD_0:.*]] = stablehlo.add %[[ABS_0]], %[[DYNAMIC_BROADCAST_IN_DIM_2]] : tensor<?xf64>
// CHECK:           %[[ABS_2:.*]] = stablehlo.abs %[[ADD_0]] : tensor<?xf64>
// CHECK:           %[[MAXIMUM_1:.*]] = stablehlo.maximum %[[ABS_2]], %[[ABS_1]] : tensor<?xf64>
// CHECK:           %[[MINIMUM_0:.*]] = stablehlo.minimum %[[ABS_2]], %[[ABS_1]] : tensor<?xf64>
// CHECK:           %[[COMPARE_2:.*]] = stablehlo.compare  EQ, %[[MAXIMUM_1]], %[[MINIMUM_0]] : (tensor<?xf64>, tensor<?xf64>) -> tensor<?xi1>
// CHECK:           %[[CONSTANT_4:.*]] = stablehlo.constant dense<1.4142135623730951> : tensor<f64>
// CHECK:           %[[SHAPE_OF_4:.*]] = shape.shape_of %[[REAL_1]] : tensor<?xf64> -> tensor<1xindex>
// CHECK:           %[[DYNAMIC_BROADCAST_IN_DIM_4:.*]] = stablehlo.dynamic_broadcast_in_dim %[[CONSTANT_4]], %[[SHAPE_OF_4]], dims = [] : (tensor<f64>, tensor<1xindex>) -> tensor<?xf64>
// CHECK:           %[[MULTIPLY_0:.*]] = stablehlo.multiply %[[DYNAMIC_BROADCAST_IN_DIM_4]], %[[MAXIMUM_1]] : tensor<?xf64>
// CHECK:           %[[DIVIDE_1:.*]] = stablehlo.divide %[[MINIMUM_0]], %[[MAXIMUM_1]] : tensor<?xf64>
// CHECK:           %[[MULTIPLY_1:.*]] = stablehlo.multiply %[[DIVIDE_1]], %[[DIVIDE_1]] : tensor<?xf64>
// CHECK:           %[[ADD_1:.*]] = stablehlo.add %[[DYNAMIC_BROADCAST_IN_DIM_2]], %[[MULTIPLY_1]] : tensor<?xf64>
// CHECK:           %[[SQRT_1:.*]] = stablehlo.sqrt %[[ADD_1]] : tensor<?xf64>
// CHECK:           %[[COMPARE_3:.*]] = stablehlo.compare  EQ, %[[SQRT_1]], %[[DYNAMIC_BROADCAST_IN_DIM_2]] : (tensor<?xf64>, tensor<?xf64>) -> tensor<?xi1>
// CHECK:           %[[CONSTANT_5:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<f64>
// CHECK:           %[[SHAPE_OF_5:.*]] = shape.shape_of %[[REAL_1]] : tensor<?xf64> -> tensor<1xindex>
// CHECK:           %[[DYNAMIC_BROADCAST_IN_DIM_5:.*]] = stablehlo.dynamic_broadcast_in_dim %[[CONSTANT_5]], %[[SHAPE_OF_5]], dims = [] : (tensor<f64>, tensor<1xindex>) -> tensor<?xf64>
// CHECK:           %[[COMPARE_4:.*]] = stablehlo.compare  GT, %[[MULTIPLY_1]], %[[DYNAMIC_BROADCAST_IN_DIM_5]] : (tensor<?xf64>, tensor<?xf64>) -> tensor<?xi1>
// CHECK:           %[[AND_0:.*]] = stablehlo.and %[[COMPARE_3]], %[[COMPARE_4]] : tensor<?xi1>
// CHECK:           %[[MULTIPLY_2:.*]] = stablehlo.multiply %[[MAXIMUM_1]], %[[MULTIPLY_1]] : tensor<?xf64>
// CHECK:           %[[CONSTANT_6:.*]] = stablehlo.constant dense<2.000000e+00> : tensor<f64>
// CHECK:           %[[SHAPE_OF_6:.*]] = shape.shape_of %[[REAL_1]] : tensor<?xf64> -> tensor<1xindex>
// CHECK:           %[[DYNAMIC_BROADCAST_IN_DIM_6:.*]] = stablehlo.dynamic_broadcast_in_dim %[[CONSTANT_6]], %[[SHAPE_OF_6]], dims = [] : (tensor<f64>, tensor<1xindex>) -> tensor<?xf64>
// CHECK:           %[[DIVIDE_2:.*]] = stablehlo.divide %[[MULTIPLY_2]], %[[DYNAMIC_BROADCAST_IN_DIM_6]] : tensor<?xf64>
// CHECK:           %[[ADD_2:.*]] = stablehlo.add %[[MAXIMUM_1]], %[[DIVIDE_2]] : tensor<?xf64>
// CHECK:           %[[MULTIPLY_3:.*]] = stablehlo.multiply %[[MAXIMUM_1]], %[[SQRT_1]] : tensor<?xf64>
// CHECK:           %[[SELECT_0:.*]] = stablehlo.select %[[AND_0]], %[[ADD_2]], %[[MULTIPLY_3]] : tensor<?xi1>, tensor<?xf64>
// CHECK:           %[[SELECT_1:.*]] = stablehlo.select %[[COMPARE_2]], %[[MULTIPLY_0]], %[[SELECT_0]] : tensor<?xi1>, tensor<?xf64>
// CHECK:           %[[SUBTRACT_0:.*]] = stablehlo.subtract %[[ABS_0]], %[[DYNAMIC_BROADCAST_IN_DIM_2]] : tensor<?xf64>
// CHECK:           %[[ABS_3:.*]] = stablehlo.abs %[[SUBTRACT_0]] : tensor<?xf64>
// CHECK:           %[[MAXIMUM_2:.*]] = stablehlo.maximum %[[ABS_3]], %[[ABS_1]] : tensor<?xf64>
// CHECK:           %[[MINIMUM_1:.*]] = stablehlo.minimum %[[ABS_3]], %[[ABS_1]] : tensor<?xf64>
// CHECK:           %[[COMPARE_5:.*]] = stablehlo.compare  EQ, %[[MAXIMUM_2]], %[[MINIMUM_1]] : (tensor<?xf64>, tensor<?xf64>) -> tensor<?xi1>
// CHECK:           %[[MULTIPLY_4:.*]] = stablehlo.multiply %[[DYNAMIC_BROADCAST_IN_DIM_4]], %[[MAXIMUM_2]] : tensor<?xf64>
// CHECK:           %[[DIVIDE_3:.*]] = stablehlo.divide %[[MINIMUM_1]], %[[MAXIMUM_2]] : tensor<?xf64>
// CHECK:           %[[MULTIPLY_5:.*]] = stablehlo.multiply %[[DIVIDE_3]], %[[DIVIDE_3]] : tensor<?xf64>
// CHECK:           %[[ADD_3:.*]] = stablehlo.add %[[DYNAMIC_BROADCAST_IN_DIM_2]], %[[MULTIPLY_5]] : tensor<?xf64>
// CHECK:           %[[SQRT_2:.*]] = stablehlo.sqrt %[[ADD_3]] : tensor<?xf64>
// CHECK:           %[[COMPARE_6:.*]] = stablehlo.compare  EQ, %[[SQRT_2]], %[[DYNAMIC_BROADCAST_IN_DIM_2]] : (tensor<?xf64>, tensor<?xf64>) -> tensor<?xi1>
// CHECK:           %[[COMPARE_7:.*]] = stablehlo.compare  GT, %[[MULTIPLY_5]], %[[DYNAMIC_BROADCAST_IN_DIM_5]] : (tensor<?xf64>, tensor<?xf64>) -> tensor<?xi1>
// CHECK:           %[[AND_1:.*]] = stablehlo.and %[[COMPARE_6]], %[[COMPARE_7]] : tensor<?xi1>
// CHECK:           %[[MULTIPLY_6:.*]] = stablehlo.multiply %[[MAXIMUM_2]], %[[MULTIPLY_5]] : tensor<?xf64>
// CHECK:           %[[DIVIDE_4:.*]] = stablehlo.divide %[[MULTIPLY_6]], %[[DYNAMIC_BROADCAST_IN_DIM_6]] : tensor<?xf64>
// CHECK:           %[[ADD_4:.*]] = stablehlo.add %[[MAXIMUM_2]], %[[DIVIDE_4]] : tensor<?xf64>
// CHECK:           %[[MULTIPLY_7:.*]] = stablehlo.multiply %[[MAXIMUM_2]], %[[SQRT_2]] : tensor<?xf64>
// CHECK:           %[[SELECT_2:.*]] = stablehlo.select %[[AND_1]], %[[ADD_4]], %[[MULTIPLY_7]] : tensor<?xi1>, tensor<?xf64>
// CHECK:           %[[SELECT_3:.*]] = stablehlo.select %[[COMPARE_5]], %[[MULTIPLY_4]], %[[SELECT_2]] : tensor<?xi1>, tensor<?xf64>
// CHECK:           %[[ADD_5:.*]] = stablehlo.add %[[SELECT_1]], %[[SELECT_3]] : tensor<?xf64>
// CHECK:           %[[MULTIPLY_8:.*]] = stablehlo.multiply %[[DYNAMIC_BROADCAST_IN_DIM_3]], %[[ADD_5]] : tensor<?xf64>
// CHECK:           %[[ADD_6:.*]] = stablehlo.add %[[MULTIPLY_8]], %[[ABS_0]] : tensor<?xf64>
// CHECK:           %[[MULTIPLY_9:.*]] = stablehlo.multiply %[[DYNAMIC_BROADCAST_IN_DIM_3]], %[[ADD_6]] : tensor<?xf64>
// CHECK:           %[[MULTIPLY_10:.*]] = stablehlo.multiply %[[ABS_1]], %[[ABS_1]] : tensor<?xf64>
// CHECK:           %[[ADD_7:.*]] = stablehlo.add %[[SELECT_1]], %[[ADD_0]] : tensor<?xf64>
// CHECK:           %[[DIVIDE_5:.*]] = stablehlo.divide %[[MULTIPLY_10]], %[[ADD_7]] : tensor<?xf64>
// CHECK:           %[[SUBTRACT_1:.*]] = stablehlo.subtract %[[SELECT_3]], %[[SUBTRACT_0]] : tensor<?xf64>
// CHECK:           %[[ADD_8:.*]] = stablehlo.add %[[DIVIDE_5]], %[[SUBTRACT_1]] : tensor<?xf64>
// CHECK:           %[[MULTIPLY_11:.*]] = stablehlo.multiply %[[MULTIPLY_9]], %[[ADD_8]] : tensor<?xf64>
// CHECK:           %[[SQRT_3:.*]] = stablehlo.sqrt %[[MULTIPLY_11]] : tensor<?xf64>
// CHECK:           %[[DIVIDE_6:.*]] = stablehlo.divide %[[MULTIPLY_9]], %[[ADD_7]] : tensor<?xf64>
// CHECK:           %[[ADD_9:.*]] = stablehlo.add %[[SELECT_3]], %[[SUBTRACT_0]] : tensor<?xf64>
// CHECK:           %[[DIVIDE_7:.*]] = stablehlo.divide %[[MULTIPLY_9]], %[[ADD_9]] : tensor<?xf64>
// CHECK:           %[[ADD_10:.*]] = stablehlo.add %[[DIVIDE_6]], %[[DIVIDE_7]] : tensor<?xf64>
// CHECK:           %[[SQRT_4:.*]] = stablehlo.sqrt %[[ADD_10]] : tensor<?xf64>
// CHECK:           %[[MULTIPLY_12:.*]] = stablehlo.multiply %[[ABS_1]], %[[SQRT_4]] : tensor<?xf64>
// CHECK:           %[[SELECT_4:.*]] = stablehlo.select %[[COMPARE_1]], %[[SQRT_3]], %[[MULTIPLY_12]] : tensor<?xi1>, tensor<?xf64>
// CHECK:           %[[SELECT_5:.*]] = stablehlo.select %[[COMPARE_0]], %[[ABS_1]], %[[SELECT_4]] : tensor<?xi1>, tensor<?xf64>
// CHECK:           %[[CONSTANT_7:.*]] = stablehlo.constant dense<1.000000e+12> : tensor<f64>
// CHECK:           %[[SHAPE_OF_7:.*]] = shape.shape_of %[[REAL_1]] : tensor<?xf64> -> tensor<1xindex>
// CHECK:           %[[DYNAMIC_BROADCAST_IN_DIM_7:.*]] = stablehlo.dynamic_broadcast_in_dim %[[CONSTANT_7]], %[[SHAPE_OF_7]], dims = [] : (tensor<f64>, tensor<1xindex>) -> tensor<?xf64>
// CHECK:           %[[MULTIPLY_13:.*]] = stablehlo.multiply %[[DIVIDE_0]], %[[DYNAMIC_BROADCAST_IN_DIM_7]] : tensor<?xf64>
// CHECK:           %[[COMPARE_8:.*]] = stablehlo.compare  LT, %[[ABS_0]], %[[MULTIPLY_13]] : (tensor<?xf64>, tensor<?xf64>) -> tensor<?xi1>
// CHECK:           %[[CONSTANT_8:.*]] = stablehlo.constant dense<9.9999999999999995E-7> : tensor<f64>
// CHECK:           %[[SHAPE_OF_8:.*]] = shape.shape_of %[[REAL_1]] : tensor<?xf64> -> tensor<1xindex>
// CHECK:           %[[DYNAMIC_BROADCAST_IN_DIM_8:.*]] = stablehlo.dynamic_broadcast_in_dim %[[CONSTANT_8]], %[[SHAPE_OF_8]], dims = [] : (tensor<f64>, tensor<1xindex>) -> tensor<?xf64>
// CHECK:           %[[MULTIPLY_14:.*]] = stablehlo.multiply %[[DIVIDE_0]], %[[DYNAMIC_BROADCAST_IN_DIM_8]] : tensor<?xf64>
// CHECK:           %[[CONSTANT_9:.*]] = stablehlo.constant dense<1.000000e+02> : tensor<f64>
// CHECK:           %[[SHAPE_OF_9:.*]] = shape.shape_of %[[REAL_1]] : tensor<?xf64> -> tensor<1xindex>
// CHECK:           %[[DYNAMIC_BROADCAST_IN_DIM_9:.*]] = stablehlo.dynamic_broadcast_in_dim %[[CONSTANT_9]], %[[SHAPE_OF_9]], dims = [] : (tensor<f64>, tensor<1xindex>) -> tensor<?xf64>
// CHECK:           %[[MULTIPLY_15:.*]] = stablehlo.multiply %[[DIVIDE_0]], %[[DYNAMIC_BROADCAST_IN_DIM_9]] : tensor<?xf64>
// CHECK:           %[[SELECT_6:.*]] = stablehlo.select %[[COMPARE_8]], %[[MULTIPLY_14]], %[[MULTIPLY_15]] : tensor<?xi1>, tensor<?xf64>
// CHECK:           %[[COMPARE_9:.*]] = stablehlo.compare  GE, %[[ABS_1]], %[[SELECT_6]] : (tensor<?xf64>, tensor<?xf64>) -> tensor<?xi1>
// CHECK:           %[[SELECT_7:.*]] = stablehlo.select %[[COMPARE_9]], %[[ABS_1]], %[[ABS_0]] : tensor<?xi1>, tensor<?xf64>
// CHECK:           %[[SELECT_8:.*]] = stablehlo.select %[[COMPARE_9]], %[[SELECT_6]], %[[DIVIDE_0]] : tensor<?xi1>, tensor<?xf64>
// CHECK:           %[[COMPARE_10:.*]] = stablehlo.compare  GE, %[[SELECT_7]], %[[SELECT_8]] : (tensor<?xf64>, tensor<?xf64>) -> tensor<?xi1>
// CHECK:           %[[LOG_0:.*]] = stablehlo.log %[[DYNAMIC_BROADCAST_IN_DIM_6]] : tensor<?xf64>
// CHECK:           %[[LOG_1:.*]] = stablehlo.log %[[SELECT_7]] : tensor<?xf64>
// CHECK:           %[[ADD_11:.*]] = stablehlo.add %[[LOG_0]], %[[LOG_1]] : tensor<?xf64>
// CHECK:           %[[CONSTANT_10:.*]] = stablehlo.constant dense<0x7FF0000000000000> : tensor<f64>
// CHECK:           %[[SHAPE_OF_10:.*]] = shape.shape_of %[[IMAG_0]] : tensor<?xf64> -> tensor<1xindex>
// CHECK:           %[[DYNAMIC_BROADCAST_IN_DIM_10:.*]] = stablehlo.dynamic_broadcast_in_dim %[[CONSTANT_10]], %[[SHAPE_OF_10]], dims = [] : (tensor<f64>, tensor<1xindex>) -> tensor<?xf64>
// CHECK:           %[[COMPARE_11:.*]] = stablehlo.compare  EQ, %[[ABS_1]], %[[DYNAMIC_BROADCAST_IN_DIM_10]] : (tensor<?xf64>, tensor<?xf64>) -> tensor<?xi1>
// CHECK:           %[[NOT_0:.*]] = stablehlo.not %[[COMPARE_11]] : tensor<?xi1>
// CHECK:           %[[AND_2:.*]] = stablehlo.and %[[COMPARE_9]], %[[NOT_0]] : tensor<?xi1>
// CHECK:           %[[DIVIDE_8:.*]] = stablehlo.divide %[[ABS_0]], %[[ABS_1]] : tensor<?xf64>
// CHECK:           %[[SELECT_9:.*]] = stablehlo.select %[[AND_2]], %[[DIVIDE_8]], %[[DYNAMIC_BROADCAST_IN_DIM_5]] : tensor<?xi1>, tensor<?xf64>
// CHECK:           %[[MULTIPLY_16:.*]] = stablehlo.multiply %[[SELECT_9]], %[[SELECT_9]] : tensor<?xf64>
// CHECK:           %[[LOG_PLUS_ONE_0:.*]] = stablehlo.log_plus_one %[[MULTIPLY_16]] : tensor<?xf64>
// CHECK:           %[[MULTIPLY_17:.*]] = stablehlo.multiply %[[DYNAMIC_BROADCAST_IN_DIM_3]], %[[LOG_PLUS_ONE_0]] : tensor<?xf64>
// CHECK:           %[[ADD_12:.*]] = stablehlo.add %[[ADD_11]], %[[MULTIPLY_17]] : tensor<?xf64>
// CHECK:           %[[CONSTANT_11:.*]] = stablehlo.constant dense<2.2250738585072014E-308> : tensor<f64>
// CHECK:           %[[SHAPE_OF_11:.*]] = shape.shape_of %[[REAL_1]] : tensor<?xf64> -> tensor<1xindex>
// CHECK:           %[[DYNAMIC_BROADCAST_IN_DIM_11:.*]] = stablehlo.dynamic_broadcast_in_dim %[[CONSTANT_11]], %[[SHAPE_OF_11]], dims = [] : (tensor<f64>, tensor<1xindex>) -> tensor<?xf64>
// CHECK:           %[[SQRT_5:.*]] = stablehlo.sqrt %[[DYNAMIC_BROADCAST_IN_DIM_11]] : tensor<?xf64>
// CHECK:           %[[CONSTANT_12:.*]] = stablehlo.constant dense<4.000000e+00> : tensor<f64>
// CHECK:           %[[SHAPE_OF_12:.*]] = shape.shape_of %[[REAL_1]] : tensor<?xf64> -> tensor<1xindex>
// CHECK:           %[[DYNAMIC_BROADCAST_IN_DIM_12:.*]] = stablehlo.dynamic_broadcast_in_dim %[[CONSTANT_12]], %[[SHAPE_OF_12]], dims = [] : (tensor<f64>, tensor<1xindex>) -> tensor<?xf64>
// CHECK:           %[[MULTIPLY_18:.*]] = stablehlo.multiply %[[SQRT_5]], %[[DYNAMIC_BROADCAST_IN_DIM_12]] : tensor<?xf64>
// CHECK:           %[[COMPARE_12:.*]] = stablehlo.compare  LT, %[[ABS_1]], %[[MULTIPLY_18]] : (tensor<?xf64>, tensor<?xf64>) -> tensor<?xi1>
// CHECK:           %[[COMPARE_13:.*]] = stablehlo.compare  LT, %[[ABS_0]], %[[DYNAMIC_BROADCAST_IN_DIM_2]] : (tensor<?xf64>, tensor<?xf64>) -> tensor<?xi1>
// CHECK:           %[[AND_3:.*]] = stablehlo.and %[[COMPARE_12]], %[[COMPARE_13]] : tensor<?xi1>
// CHECK:           %[[MULTIPLY_19:.*]] = stablehlo.multiply %[[ADD_0]], %[[SUBTRACT_0]] : tensor<?xf64>
// CHECK:           %[[ADD_13:.*]] = stablehlo.add %[[MULTIPLY_8]], %[[DYNAMIC_BROADCAST_IN_DIM_2]] : tensor<?xf64>
// CHECK:           %[[DIVIDE_9:.*]] = stablehlo.divide %[[MULTIPLY_19]], %[[ADD_13]] : tensor<?xf64>
// CHECK:           %[[NEGATE_0:.*]] = stablehlo.negate %[[DIVIDE_9]] : tensor<?xf64>
// CHECK:           %[[COMPARE_14:.*]] = stablehlo.compare  GE, %[[ABS_0]], %[[DYNAMIC_BROADCAST_IN_DIM_2]] : (tensor<?xf64>, tensor<?xf64>) -> tensor<?xi1>
// CHECK:           %[[MULTIPLY_20:.*]] = stablehlo.multiply %[[DYNAMIC_BROADCAST_IN_DIM_3]], %[[MULTIPLY_10]] : tensor<?xf64>
// CHECK:           %[[DIVIDE_10:.*]] = stablehlo.divide %[[MULTIPLY_20]], %[[ADD_7]] : tensor<?xf64>
// CHECK:           %[[MULTIPLY_21:.*]] = stablehlo.multiply %[[DYNAMIC_BROADCAST_IN_DIM_3]], %[[ADD_9]] : tensor<?xf64>
// CHECK:           %[[ADD_14:.*]] = stablehlo.add %[[DIVIDE_10]], %[[MULTIPLY_21]] : tensor<?xf64>
// CHECK:           %[[CONSTANT_13:.*]] = stablehlo.constant dense<1.500000e+00> : tensor<f64>
// CHECK:           %[[SHAPE_OF_13:.*]] = shape.shape_of %[[REAL_1]] : tensor<?xf64> -> tensor<1xindex>
// CHECK:           %[[DYNAMIC_BROADCAST_IN_DIM_13:.*]] = stablehlo.dynamic_broadcast_in_dim %[[CONSTANT_13]], %[[SHAPE_OF_13]], dims = [] : (tensor<f64>, tensor<1xindex>) -> tensor<?xf64>
// CHECK:           %[[COMPARE_15:.*]] = stablehlo.compare  LE, %[[MULTIPLY_8]], %[[DYNAMIC_BROADCAST_IN_DIM_13]] : (tensor<?xf64>, tensor<?xf64>) -> tensor<?xi1>
// CHECK:           %[[DIVIDE_11:.*]] = stablehlo.divide %[[MULTIPLY_20]], %[[SUBTRACT_1]] : tensor<?xf64>
// CHECK:           %[[ADD_15:.*]] = stablehlo.add %[[DIVIDE_10]], %[[DIVIDE_11]] : tensor<?xf64>
// CHECK:           %[[SUBTRACT_2:.*]] = stablehlo.subtract %[[MULTIPLY_8]], %[[DYNAMIC_BROADCAST_IN_DIM_2]] : tensor<?xf64>
// CHECK:           %[[SELECT_10:.*]] = stablehlo.select %[[COMPARE_15]], %[[ADD_15]], %[[SUBTRACT_2]] : tensor<?xi1>, tensor<?xf64>
// CHECK:           %[[SELECT_11:.*]] = stablehlo.select %[[COMPARE_14]], %[[ADD_14]], %[[SELECT_10]] : tensor<?xi1>, tensor<?xf64>
// CHECK:           %[[SELECT_12:.*]] = stablehlo.select %[[AND_3]], %[[NEGATE_0]], %[[SELECT_11]] : tensor<?xi1>, tensor<?xf64>
// CHECK:           %[[MULTIPLY_22:.*]] = stablehlo.multiply %[[SELECT_12]], %[[ADD_13]] : tensor<?xf64>
// CHECK:           %[[SQRT_6:.*]] = stablehlo.sqrt %[[MULTIPLY_22]] : tensor<?xf64>
// CHECK:           %[[DIVIDE_12:.*]] = stablehlo.divide %[[ABS_1]], %[[SQRT_6]] : tensor<?xf64>
// CHECK:           %[[ADD_16:.*]] = stablehlo.add %[[SELECT_12]], %[[SQRT_6]] : tensor<?xf64>
// CHECK:           %[[LOG_PLUS_ONE_1:.*]] = stablehlo.log_plus_one %[[ADD_16]] : tensor<?xf64>
// CHECK:           %[[SELECT_13:.*]] = stablehlo.select %[[AND_3]], %[[DIVIDE_12]], %[[LOG_PLUS_ONE_1]] : tensor<?xi1>, tensor<?xf64>
// CHECK:           %[[SELECT_14:.*]] = stablehlo.select %[[COMPARE_10]], %[[ADD_12]], %[[SELECT_13]] : tensor<?xi1>, tensor<?xf64>
// CHECK:           %[[COMPLEX_0:.*]] = stablehlo.complex %[[SELECT_5]], %[[SELECT_14]] : tensor<?xcomplex<f64>>
// CHECK:           %[[REAL_2:.*]] = stablehlo.real %[[COMPLEX_0]] : (tensor<?xcomplex<f64>>) -> tensor<?xf64>
// CHECK:           %[[VAL_0:.*]] = stablehlo.atan2 %[[REAL_0]], %[[REAL_2]] : tensor<?xf64>
// CHECK:           %[[IMAG_1:.*]] = stablehlo.imag %[[ARG0]] : (tensor<?xcomplex<f64>>) -> tensor<?xf64>
// CHECK:           %[[CONSTANT_14:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<f64>
// CHECK:           %[[SHAPE_OF_14:.*]] = shape.shape_of %[[REAL_0]] : tensor<?xf64> -> tensor<1xindex>
// CHECK:           %[[DYNAMIC_BROADCAST_IN_DIM_14:.*]] = stablehlo.dynamic_broadcast_in_dim %[[CONSTANT_14]], %[[SHAPE_OF_14]], dims = [] : (tensor<f64>, tensor<1xindex>) -> tensor<?xf64>
// CHECK:           %[[COMPARE_16:.*]] = stablehlo.compare  LT, %[[IMAG_1]], %[[DYNAMIC_BROADCAST_IN_DIM_14]] : (tensor<?xf64>, tensor<?xf64>) -> tensor<?xi1>
// CHECK:           %[[IMAG_2:.*]] = stablehlo.imag %[[COMPLEX_0]] : (tensor<?xcomplex<f64>>) -> tensor<?xf64>
// CHECK:           %[[NEGATE_1:.*]] = stablehlo.negate %[[IMAG_2]] : tensor<?xf64>
// CHECK:           %[[SELECT_15:.*]] = stablehlo.select %[[COMPARE_16]], %[[NEGATE_1]], %[[IMAG_2]] : tensor<?xi1>, tensor<?xf64>
// CHECK:           %[[COMPLEX_1:.*]] = stablehlo.complex %[[VAL_0]], %[[SELECT_15]] : tensor<?xcomplex<f64>>
// CHECK:           return %[[COMPLEX_1]] : tensor<?xcomplex<f64>>
// CHECK:         }
func.func @asin_complex_f64_dynamic(%arg : tensor<?xcomplex<f64>>) -> tensor<?xcomplex<f64>> {
  %result = "chlo.asin"(%arg) : (tensor<?xcomplex<f64>>) -> tensor<?xcomplex<f64>>
  func.return %result : tensor<?xcomplex<f64>>
}

// -----

// CHECK-LABEL:   func.func @asinh_bf16(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<bf16>) -> tensor<bf16> {
// CHECK:           %[[SIGN_0:.*]] = stablehlo.sign %[[ARG0]] : tensor<bf16>
// CHECK:           %[[ABS_0:.*]] = stablehlo.abs %[[ARG0]] : tensor<bf16>
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<3.389530e+38> : tensor<bf16>
// CHECK:           %[[SQRT_0:.*]] = stablehlo.sqrt %[[CONSTANT_0]] : tensor<bf16>
// CHECK:           %[[COMPARE_0:.*]] = stablehlo.compare  GE, %[[ABS_0]], %[[SQRT_0]] : (tensor<bf16>, tensor<bf16>) -> tensor<i1>
// CHECK:           %[[CONSTANT_1:.*]] = stablehlo.constant dense<2.000000e+00> : tensor<bf16>
// CHECK:           %[[LOG_0:.*]] = stablehlo.log %[[CONSTANT_1]] : tensor<bf16>
// CHECK:           %[[LOG_1:.*]] = stablehlo.log %[[ABS_0]] : tensor<bf16>
// CHECK:           %[[ADD_0:.*]] = stablehlo.add %[[LOG_0]], %[[LOG_1]] : tensor<bf16>
// CHECK:           %[[MULTIPLY_0:.*]] = stablehlo.multiply %[[ABS_0]], %[[ABS_0]] : tensor<bf16>
// CHECK:           %[[CONSTANT_2:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<bf16>
// CHECK:           %[[ADD_1:.*]] = stablehlo.add %[[CONSTANT_2]], %[[MULTIPLY_0]] : tensor<bf16>
// CHECK:           %[[SQRT_1:.*]] = stablehlo.sqrt %[[ADD_1]] : tensor<bf16>
// CHECK:           %[[ADD_2:.*]] = stablehlo.add %[[CONSTANT_2]], %[[SQRT_1]] : tensor<bf16>
// CHECK:           %[[DIVIDE_0:.*]] = stablehlo.divide %[[MULTIPLY_0]], %[[ADD_2]] : tensor<bf16>
// CHECK:           %[[ADD_3:.*]] = stablehlo.add %[[ABS_0]], %[[DIVIDE_0]] : tensor<bf16>
// CHECK:           %[[LOG_PLUS_ONE_0:.*]] = stablehlo.log_plus_one %[[ADD_3]] : tensor<bf16>
// CHECK:           %[[SELECT_0:.*]] = stablehlo.select %[[COMPARE_0]], %[[ADD_0]], %[[LOG_PLUS_ONE_0]] : tensor<i1>, tensor<bf16>
// CHECK:           %[[MULTIPLY_1:.*]] = stablehlo.multiply %[[SIGN_0]], %[[SELECT_0]] : tensor<bf16>
// CHECK:           return %[[MULTIPLY_1]] : tensor<bf16>
// CHECK:         }
func.func @asinh_bf16(%arg : tensor<bf16>) -> tensor<bf16> {
  // Check for the bf16-specific max value.
  %result = "chlo.asinh"(%arg) : (tensor<bf16>) -> tensor<bf16>
  func.return %result : tensor<bf16>
}

// -----

// CHECK-LABEL:   func.func @asinh_f16(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<f16>) -> tensor<f16> {
// CHECK:           %[[SIGN_0:.*]] = stablehlo.sign %[[ARG0]] : tensor<f16>
// CHECK:           %[[ABS_0:.*]] = stablehlo.abs %[[ARG0]] : tensor<f16>
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<6.550400e+04> : tensor<f16>
// CHECK:           %[[SQRT_0:.*]] = stablehlo.sqrt %[[CONSTANT_0]] : tensor<f16>
// CHECK:           %[[COMPARE_0:.*]] = stablehlo.compare  GE, %[[ABS_0]], %[[SQRT_0]] : (tensor<f16>, tensor<f16>) -> tensor<i1>
// CHECK:           %[[CONSTANT_1:.*]] = stablehlo.constant dense<2.000000e+00> : tensor<f16>
// CHECK:           %[[LOG_0:.*]] = stablehlo.log %[[CONSTANT_1]] : tensor<f16>
// CHECK:           %[[LOG_1:.*]] = stablehlo.log %[[ABS_0]] : tensor<f16>
// CHECK:           %[[ADD_0:.*]] = stablehlo.add %[[LOG_0]], %[[LOG_1]] : tensor<f16>
// CHECK:           %[[MULTIPLY_0:.*]] = stablehlo.multiply %[[ABS_0]], %[[ABS_0]] : tensor<f16>
// CHECK:           %[[CONSTANT_2:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f16>
// CHECK:           %[[ADD_1:.*]] = stablehlo.add %[[CONSTANT_2]], %[[MULTIPLY_0]] : tensor<f16>
// CHECK:           %[[SQRT_1:.*]] = stablehlo.sqrt %[[ADD_1]] : tensor<f16>
// CHECK:           %[[ADD_2:.*]] = stablehlo.add %[[CONSTANT_2]], %[[SQRT_1]] : tensor<f16>
// CHECK:           %[[DIVIDE_0:.*]] = stablehlo.divide %[[MULTIPLY_0]], %[[ADD_2]] : tensor<f16>
// CHECK:           %[[ADD_3:.*]] = stablehlo.add %[[ABS_0]], %[[DIVIDE_0]] : tensor<f16>
// CHECK:           %[[LOG_PLUS_ONE_0:.*]] = stablehlo.log_plus_one %[[ADD_3]] : tensor<f16>
// CHECK:           %[[SELECT_0:.*]] = stablehlo.select %[[COMPARE_0]], %[[ADD_0]], %[[LOG_PLUS_ONE_0]] : tensor<i1>, tensor<f16>
// CHECK:           %[[MULTIPLY_1:.*]] = stablehlo.multiply %[[SIGN_0]], %[[SELECT_0]] : tensor<f16>
// CHECK:           return %[[MULTIPLY_1]] : tensor<f16>
// CHECK:         }
func.func @asinh_f16(%arg : tensor<f16>) -> tensor<f16> {
  // Check for the f16-specific max value.
  %result = "chlo.asinh"(%arg) : (tensor<f16>) -> tensor<f16>
  func.return %result : tensor<f16>
}

// -----

// CHECK-LABEL:   func.func @asinh_f32(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<f32>) -> tensor<f32> {
// CHECK:           %[[SIGN_0:.*]] = stablehlo.sign %[[ARG0]] : tensor<f32>
// CHECK:           %[[ABS_0:.*]] = stablehlo.abs %[[ARG0]] : tensor<f32>
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<3.40282347E+38> : tensor<f32>
// CHECK:           %[[SQRT_0:.*]] = stablehlo.sqrt %[[CONSTANT_0]] : tensor<f32>
// CHECK:           %[[COMPARE_0:.*]] = stablehlo.compare  GE, %[[ABS_0]], %[[SQRT_0]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[CONSTANT_1:.*]] = stablehlo.constant dense<2.000000e+00> : tensor<f32>
// CHECK:           %[[LOG_0:.*]] = stablehlo.log %[[CONSTANT_1]] : tensor<f32>
// CHECK:           %[[LOG_1:.*]] = stablehlo.log %[[ABS_0]] : tensor<f32>
// CHECK:           %[[ADD_0:.*]] = stablehlo.add %[[LOG_0]], %[[LOG_1]] : tensor<f32>
// CHECK:           %[[MULTIPLY_0:.*]] = stablehlo.multiply %[[ABS_0]], %[[ABS_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_2:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_1:.*]] = stablehlo.add %[[CONSTANT_2]], %[[MULTIPLY_0]] : tensor<f32>
// CHECK:           %[[SQRT_1:.*]] = stablehlo.sqrt %[[ADD_1]] : tensor<f32>
// CHECK:           %[[ADD_2:.*]] = stablehlo.add %[[CONSTANT_2]], %[[SQRT_1]] : tensor<f32>
// CHECK:           %[[DIVIDE_0:.*]] = stablehlo.divide %[[MULTIPLY_0]], %[[ADD_2]] : tensor<f32>
// CHECK:           %[[ADD_3:.*]] = stablehlo.add %[[ABS_0]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[LOG_PLUS_ONE_0:.*]] = stablehlo.log_plus_one %[[ADD_3]] : tensor<f32>
// CHECK:           %[[SELECT_0:.*]] = stablehlo.select %[[COMPARE_0]], %[[ADD_0]], %[[LOG_PLUS_ONE_0]] : tensor<i1>, tensor<f32>
// CHECK:           %[[MULTIPLY_1:.*]] = stablehlo.multiply %[[SIGN_0]], %[[SELECT_0]] : tensor<f32>
// CHECK:           return %[[MULTIPLY_1]] : tensor<f32>
// CHECK:         }
func.func @asinh_f32(%arg : tensor<f32>) -> tensor<f32> {
  // Check for the f32-specific max value.
  %result = "chlo.asinh"(%arg) : (tensor<f32>) -> tensor<f32>
  func.return %result : tensor<f32>
}

// -----

// CHECK-LABEL:   func.func @asinh_f64(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<f64>) -> tensor<f64> {
// CHECK:           %[[SIGN_0:.*]] = stablehlo.sign %[[ARG0]] : tensor<f64>
// CHECK:           %[[ABS_0:.*]] = stablehlo.abs %[[ARG0]] : tensor<f64>
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<1.7976931348623157E+308> : tensor<f64>
// CHECK:           %[[SQRT_0:.*]] = stablehlo.sqrt %[[CONSTANT_0]] : tensor<f64>
// CHECK:           %[[COMPARE_0:.*]] = stablehlo.compare  GE, %[[ABS_0]], %[[SQRT_0]] : (tensor<f64>, tensor<f64>) -> tensor<i1>
// CHECK:           %[[CONSTANT_1:.*]] = stablehlo.constant dense<2.000000e+00> : tensor<f64>
// CHECK:           %[[LOG_0:.*]] = stablehlo.log %[[CONSTANT_1]] : tensor<f64>
// CHECK:           %[[LOG_1:.*]] = stablehlo.log %[[ABS_0]] : tensor<f64>
// CHECK:           %[[ADD_0:.*]] = stablehlo.add %[[LOG_0]], %[[LOG_1]] : tensor<f64>
// CHECK:           %[[MULTIPLY_0:.*]] = stablehlo.multiply %[[ABS_0]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_2:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f64>
// CHECK:           %[[ADD_1:.*]] = stablehlo.add %[[CONSTANT_2]], %[[MULTIPLY_0]] : tensor<f64>
// CHECK:           %[[SQRT_1:.*]] = stablehlo.sqrt %[[ADD_1]] : tensor<f64>
// CHECK:           %[[ADD_2:.*]] = stablehlo.add %[[CONSTANT_2]], %[[SQRT_1]] : tensor<f64>
// CHECK:           %[[DIVIDE_0:.*]] = stablehlo.divide %[[MULTIPLY_0]], %[[ADD_2]] : tensor<f64>
// CHECK:           %[[ADD_3:.*]] = stablehlo.add %[[ABS_0]], %[[DIVIDE_0]] : tensor<f64>
// CHECK:           %[[LOG_PLUS_ONE_0:.*]] = stablehlo.log_plus_one %[[ADD_3]] : tensor<f64>
// CHECK:           %[[SELECT_0:.*]] = stablehlo.select %[[COMPARE_0]], %[[ADD_0]], %[[LOG_PLUS_ONE_0]] : tensor<i1>, tensor<f64>
// CHECK:           %[[MULTIPLY_1:.*]] = stablehlo.multiply %[[SIGN_0]], %[[SELECT_0]] : tensor<f64>
// CHECK:           return %[[MULTIPLY_1]] : tensor<f64>
// CHECK:         }
func.func @asinh_f64(%arg : tensor<f64>) -> tensor<f64> {
  %result = "chlo.asinh"(%arg) : (tensor<f64>) -> tensor<f64>
  func.return %result : tensor<f64>
}

// -----

// CHECK-LABEL:   func.func @asinh_complex_f32(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<complex<f32>>) -> tensor<complex<f32>> {
// CHECK:           %[[REAL_0:.*]] = stablehlo.real %[[ARG0]] : (tensor<complex<f32>>) -> tensor<f32>
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<f32>
// CHECK:           %[[COMPARE_0:.*]] = stablehlo.compare  LT, %[[REAL_0]], %[[CONSTANT_0]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[IMAG_0:.*]] = stablehlo.imag %[[ARG0]] : (tensor<complex<f32>>) -> tensor<f32>
// CHECK:           %[[NEGATE_0:.*]] = stablehlo.negate %[[IMAG_0]] : tensor<f32>
// CHECK:           %[[COMPLEX_0:.*]] = stablehlo.complex %[[NEGATE_0]], %[[REAL_0]] : tensor<complex<f32>>
// CHECK:           %[[REAL_1:.*]] = stablehlo.real %[[COMPLEX_0]] : (tensor<complex<f32>>) -> tensor<f32>
// CHECK:           %[[ABS_0:.*]] = stablehlo.abs %[[REAL_1]] : tensor<f32>
// CHECK:           %[[IMAG_1:.*]] = stablehlo.imag %[[COMPLEX_0]] : (tensor<complex<f32>>) -> tensor<f32>
// CHECK:           %[[ABS_1:.*]] = stablehlo.abs %[[IMAG_1]] : tensor<f32>
// CHECK:           %[[MAXIMUM_0:.*]] = stablehlo.maximum %[[ABS_0]], %[[ABS_1]] : tensor<f32>
// CHECK:           %[[CONSTANT_1:.*]] = stablehlo.constant dense<3.40282347E+38> : tensor<f32>
// CHECK:           %[[SQRT_0:.*]] = stablehlo.sqrt %[[CONSTANT_1]] : tensor<f32>
// CHECK:           %[[CONSTANT_2:.*]] = stablehlo.constant dense<8.000000e+00> : tensor<f32>
// CHECK:           %[[DIVIDE_0:.*]] = stablehlo.divide %[[SQRT_0]], %[[CONSTANT_2]] : tensor<f32>
// CHECK:           %[[COMPARE_1:.*]] = stablehlo.compare  GE, %[[MAXIMUM_0]], %[[DIVIDE_0]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[CONSTANT_3:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[COMPARE_2:.*]] = stablehlo.compare  LE, %[[ABS_0]], %[[CONSTANT_3]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[CONSTANT_4:.*]] = stablehlo.constant dense<5.000000e-01> : tensor<f32>
// CHECK:           %[[ADD_0:.*]] = stablehlo.add %[[ABS_0]], %[[CONSTANT_3]] : tensor<f32>
// CHECK:           %[[ABS_2:.*]] = stablehlo.abs %[[ADD_0]] : tensor<f32>
// CHECK:           %[[MAXIMUM_1:.*]] = stablehlo.maximum %[[ABS_2]], %[[ABS_1]] : tensor<f32>
// CHECK:           %[[MINIMUM_0:.*]] = stablehlo.minimum %[[ABS_2]], %[[ABS_1]] : tensor<f32>
// CHECK:           %[[COMPARE_3:.*]] = stablehlo.compare  EQ, %[[MAXIMUM_1]], %[[MINIMUM_0]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[CONSTANT_5:.*]] = stablehlo.constant dense<1.41421354> : tensor<f32>
// CHECK:           %[[MULTIPLY_0:.*]] = stablehlo.multiply %[[CONSTANT_5]], %[[MAXIMUM_1]] : tensor<f32>
// CHECK:           %[[DIVIDE_1:.*]] = stablehlo.divide %[[MINIMUM_0]], %[[MAXIMUM_1]] : tensor<f32>
// CHECK:           %[[MULTIPLY_1:.*]] = stablehlo.multiply %[[DIVIDE_1]], %[[DIVIDE_1]] : tensor<f32>
// CHECK:           %[[ADD_1:.*]] = stablehlo.add %[[CONSTANT_3]], %[[MULTIPLY_1]] : tensor<f32>
// CHECK:           %[[SQRT_1:.*]] = stablehlo.sqrt %[[ADD_1]] : tensor<f32>
// CHECK:           %[[COMPARE_4:.*]] = stablehlo.compare  EQ, %[[SQRT_1]], %[[CONSTANT_3]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[CONSTANT_6:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<f32>
// CHECK:           %[[COMPARE_5:.*]] = stablehlo.compare  GT, %[[MULTIPLY_1]], %[[CONSTANT_6]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[AND_0:.*]] = stablehlo.and %[[COMPARE_4]], %[[COMPARE_5]] : tensor<i1>
// CHECK:           %[[MULTIPLY_2:.*]] = stablehlo.multiply %[[MAXIMUM_1]], %[[MULTIPLY_1]] : tensor<f32>
// CHECK:           %[[CONSTANT_7:.*]] = stablehlo.constant dense<2.000000e+00> : tensor<f32>
// CHECK:           %[[DIVIDE_2:.*]] = stablehlo.divide %[[MULTIPLY_2]], %[[CONSTANT_7]] : tensor<f32>
// CHECK:           %[[ADD_2:.*]] = stablehlo.add %[[MAXIMUM_1]], %[[DIVIDE_2]] : tensor<f32>
// CHECK:           %[[MULTIPLY_3:.*]] = stablehlo.multiply %[[MAXIMUM_1]], %[[SQRT_1]] : tensor<f32>
// CHECK:           %[[SELECT_0:.*]] = stablehlo.select %[[AND_0]], %[[ADD_2]], %[[MULTIPLY_3]] : tensor<i1>, tensor<f32>
// CHECK:           %[[SELECT_1:.*]] = stablehlo.select %[[COMPARE_3]], %[[MULTIPLY_0]], %[[SELECT_0]] : tensor<i1>, tensor<f32>
// CHECK:           %[[SUBTRACT_0:.*]] = stablehlo.subtract %[[ABS_0]], %[[CONSTANT_3]] : tensor<f32>
// CHECK:           %[[ABS_3:.*]] = stablehlo.abs %[[SUBTRACT_0]] : tensor<f32>
// CHECK:           %[[MAXIMUM_2:.*]] = stablehlo.maximum %[[ABS_3]], %[[ABS_1]] : tensor<f32>
// CHECK:           %[[MINIMUM_1:.*]] = stablehlo.minimum %[[ABS_3]], %[[ABS_1]] : tensor<f32>
// CHECK:           %[[COMPARE_6:.*]] = stablehlo.compare  EQ, %[[MAXIMUM_2]], %[[MINIMUM_1]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[MULTIPLY_4:.*]] = stablehlo.multiply %[[CONSTANT_5]], %[[MAXIMUM_2]] : tensor<f32>
// CHECK:           %[[DIVIDE_3:.*]] = stablehlo.divide %[[MINIMUM_1]], %[[MAXIMUM_2]] : tensor<f32>
// CHECK:           %[[MULTIPLY_5:.*]] = stablehlo.multiply %[[DIVIDE_3]], %[[DIVIDE_3]] : tensor<f32>
// CHECK:           %[[ADD_3:.*]] = stablehlo.add %[[CONSTANT_3]], %[[MULTIPLY_5]] : tensor<f32>
// CHECK:           %[[SQRT_2:.*]] = stablehlo.sqrt %[[ADD_3]] : tensor<f32>
// CHECK:           %[[COMPARE_7:.*]] = stablehlo.compare  EQ, %[[SQRT_2]], %[[CONSTANT_3]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[COMPARE_8:.*]] = stablehlo.compare  GT, %[[MULTIPLY_5]], %[[CONSTANT_6]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[AND_1:.*]] = stablehlo.and %[[COMPARE_7]], %[[COMPARE_8]] : tensor<i1>
// CHECK:           %[[MULTIPLY_6:.*]] = stablehlo.multiply %[[MAXIMUM_2]], %[[MULTIPLY_5]] : tensor<f32>
// CHECK:           %[[DIVIDE_4:.*]] = stablehlo.divide %[[MULTIPLY_6]], %[[CONSTANT_7]] : tensor<f32>
// CHECK:           %[[ADD_4:.*]] = stablehlo.add %[[MAXIMUM_2]], %[[DIVIDE_4]] : tensor<f32>
// CHECK:           %[[MULTIPLY_7:.*]] = stablehlo.multiply %[[MAXIMUM_2]], %[[SQRT_2]] : tensor<f32>
// CHECK:           %[[SELECT_2:.*]] = stablehlo.select %[[AND_1]], %[[ADD_4]], %[[MULTIPLY_7]] : tensor<i1>, tensor<f32>
// CHECK:           %[[SELECT_3:.*]] = stablehlo.select %[[COMPARE_6]], %[[MULTIPLY_4]], %[[SELECT_2]] : tensor<i1>, tensor<f32>
// CHECK:           %[[ADD_5:.*]] = stablehlo.add %[[SELECT_1]], %[[SELECT_3]] : tensor<f32>
// CHECK:           %[[MULTIPLY_8:.*]] = stablehlo.multiply %[[CONSTANT_4]], %[[ADD_5]] : tensor<f32>
// CHECK:           %[[ADD_6:.*]] = stablehlo.add %[[MULTIPLY_8]], %[[ABS_0]] : tensor<f32>
// CHECK:           %[[MULTIPLY_9:.*]] = stablehlo.multiply %[[CONSTANT_4]], %[[ADD_6]] : tensor<f32>
// CHECK:           %[[MULTIPLY_10:.*]] = stablehlo.multiply %[[ABS_1]], %[[ABS_1]] : tensor<f32>
// CHECK:           %[[ADD_7:.*]] = stablehlo.add %[[SELECT_1]], %[[ADD_0]] : tensor<f32>
// CHECK:           %[[DIVIDE_5:.*]] = stablehlo.divide %[[MULTIPLY_10]], %[[ADD_7]] : tensor<f32>
// CHECK:           %[[SUBTRACT_1:.*]] = stablehlo.subtract %[[SELECT_3]], %[[SUBTRACT_0]] : tensor<f32>
// CHECK:           %[[ADD_8:.*]] = stablehlo.add %[[DIVIDE_5]], %[[SUBTRACT_1]] : tensor<f32>
// CHECK:           %[[MULTIPLY_11:.*]] = stablehlo.multiply %[[MULTIPLY_9]], %[[ADD_8]] : tensor<f32>
// CHECK:           %[[SQRT_3:.*]] = stablehlo.sqrt %[[MULTIPLY_11]] : tensor<f32>
// CHECK:           %[[DIVIDE_6:.*]] = stablehlo.divide %[[MULTIPLY_9]], %[[ADD_7]] : tensor<f32>
// CHECK:           %[[ADD_9:.*]] = stablehlo.add %[[SELECT_3]], %[[SUBTRACT_0]] : tensor<f32>
// CHECK:           %[[DIVIDE_7:.*]] = stablehlo.divide %[[MULTIPLY_9]], %[[ADD_9]] : tensor<f32>
// CHECK:           %[[ADD_10:.*]] = stablehlo.add %[[DIVIDE_6]], %[[DIVIDE_7]] : tensor<f32>
// CHECK:           %[[SQRT_4:.*]] = stablehlo.sqrt %[[ADD_10]] : tensor<f32>
// CHECK:           %[[MULTIPLY_12:.*]] = stablehlo.multiply %[[ABS_1]], %[[SQRT_4]] : tensor<f32>
// CHECK:           %[[SELECT_4:.*]] = stablehlo.select %[[COMPARE_2]], %[[SQRT_3]], %[[MULTIPLY_12]] : tensor<i1>, tensor<f32>
// CHECK:           %[[SELECT_5:.*]] = stablehlo.select %[[COMPARE_1]], %[[ABS_1]], %[[SELECT_4]] : tensor<i1>, tensor<f32>
// CHECK:           %[[CONSTANT_8:.*]] = stablehlo.constant dense<9.99999995E+11> : tensor<f32>
// CHECK:           %[[MULTIPLY_13:.*]] = stablehlo.multiply %[[DIVIDE_0]], %[[CONSTANT_8]] : tensor<f32>
// CHECK:           %[[COMPARE_9:.*]] = stablehlo.compare  LT, %[[ABS_0]], %[[MULTIPLY_13]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[CONSTANT_9:.*]] = stablehlo.constant dense<9.99999997E-7> : tensor<f32>
// CHECK:           %[[MULTIPLY_14:.*]] = stablehlo.multiply %[[DIVIDE_0]], %[[CONSTANT_9]] : tensor<f32>
// CHECK:           %[[CONSTANT_10:.*]] = stablehlo.constant dense<1.000000e+02> : tensor<f32>
// CHECK:           %[[MULTIPLY_15:.*]] = stablehlo.multiply %[[DIVIDE_0]], %[[CONSTANT_10]] : tensor<f32>
// CHECK:           %[[SELECT_6:.*]] = stablehlo.select %[[COMPARE_9]], %[[MULTIPLY_14]], %[[MULTIPLY_15]] : tensor<i1>, tensor<f32>
// CHECK:           %[[COMPARE_10:.*]] = stablehlo.compare  GE, %[[ABS_1]], %[[SELECT_6]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[SELECT_7:.*]] = stablehlo.select %[[COMPARE_10]], %[[ABS_1]], %[[ABS_0]] : tensor<i1>, tensor<f32>
// CHECK:           %[[SELECT_8:.*]] = stablehlo.select %[[COMPARE_10]], %[[SELECT_6]], %[[DIVIDE_0]] : tensor<i1>, tensor<f32>
// CHECK:           %[[COMPARE_11:.*]] = stablehlo.compare  GE, %[[SELECT_7]], %[[SELECT_8]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[LOG_0:.*]] = stablehlo.log %[[CONSTANT_7]] : tensor<f32>
// CHECK:           %[[LOG_1:.*]] = stablehlo.log %[[SELECT_7]] : tensor<f32>
// CHECK:           %[[ADD_11:.*]] = stablehlo.add %[[LOG_0]], %[[LOG_1]] : tensor<f32>
// CHECK:           %[[CONSTANT_11:.*]] = stablehlo.constant dense<0x7F800000> : tensor<f32>
// CHECK:           %[[COMPARE_12:.*]] = stablehlo.compare  EQ, %[[ABS_1]], %[[CONSTANT_11]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[NOT_0:.*]] = stablehlo.not %[[COMPARE_12]] : tensor<i1>
// CHECK:           %[[AND_2:.*]] = stablehlo.and %[[COMPARE_10]], %[[NOT_0]] : tensor<i1>
// CHECK:           %[[DIVIDE_8:.*]] = stablehlo.divide %[[ABS_0]], %[[ABS_1]] : tensor<f32>
// CHECK:           %[[SELECT_9:.*]] = stablehlo.select %[[AND_2]], %[[DIVIDE_8]], %[[CONSTANT_6]] : tensor<i1>, tensor<f32>
// CHECK:           %[[MULTIPLY_16:.*]] = stablehlo.multiply %[[SELECT_9]], %[[SELECT_9]] : tensor<f32>
// CHECK:           %[[LOG_PLUS_ONE_0:.*]] = stablehlo.log_plus_one %[[MULTIPLY_16]] : tensor<f32>
// CHECK:           %[[MULTIPLY_17:.*]] = stablehlo.multiply %[[CONSTANT_4]], %[[LOG_PLUS_ONE_0]] : tensor<f32>
// CHECK:           %[[ADD_12:.*]] = stablehlo.add %[[ADD_11]], %[[MULTIPLY_17]] : tensor<f32>
// CHECK:           %[[CONSTANT_12:.*]] = stablehlo.constant dense<1.17549435E-38> : tensor<f32>
// CHECK:           %[[SQRT_5:.*]] = stablehlo.sqrt %[[CONSTANT_12]] : tensor<f32>
// CHECK:           %[[CONSTANT_13:.*]] = stablehlo.constant dense<4.000000e+00> : tensor<f32>
// CHECK:           %[[MULTIPLY_18:.*]] = stablehlo.multiply %[[SQRT_5]], %[[CONSTANT_13]] : tensor<f32>
// CHECK:           %[[COMPARE_13:.*]] = stablehlo.compare  LT, %[[ABS_1]], %[[MULTIPLY_18]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[COMPARE_14:.*]] = stablehlo.compare  LT, %[[ABS_0]], %[[CONSTANT_3]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[AND_3:.*]] = stablehlo.and %[[COMPARE_13]], %[[COMPARE_14]] : tensor<i1>
// CHECK:           %[[MULTIPLY_19:.*]] = stablehlo.multiply %[[ADD_0]], %[[SUBTRACT_0]] : tensor<f32>
// CHECK:           %[[ADD_13:.*]] = stablehlo.add %[[MULTIPLY_8]], %[[CONSTANT_3]] : tensor<f32>
// CHECK:           %[[DIVIDE_9:.*]] = stablehlo.divide %[[MULTIPLY_19]], %[[ADD_13]] : tensor<f32>
// CHECK:           %[[NEGATE_1:.*]] = stablehlo.negate %[[DIVIDE_9]] : tensor<f32>
// CHECK:           %[[COMPARE_15:.*]] = stablehlo.compare  GE, %[[ABS_0]], %[[CONSTANT_3]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[MULTIPLY_20:.*]] = stablehlo.multiply %[[CONSTANT_4]], %[[MULTIPLY_10]] : tensor<f32>
// CHECK:           %[[DIVIDE_10:.*]] = stablehlo.divide %[[MULTIPLY_20]], %[[ADD_7]] : tensor<f32>
// CHECK:           %[[MULTIPLY_21:.*]] = stablehlo.multiply %[[CONSTANT_4]], %[[ADD_9]] : tensor<f32>
// CHECK:           %[[ADD_14:.*]] = stablehlo.add %[[DIVIDE_10]], %[[MULTIPLY_21]] : tensor<f32>
// CHECK:           %[[CONSTANT_14:.*]] = stablehlo.constant dense<1.500000e+00> : tensor<f32>
// CHECK:           %[[COMPARE_16:.*]] = stablehlo.compare  LE, %[[MULTIPLY_8]], %[[CONSTANT_14]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[DIVIDE_11:.*]] = stablehlo.divide %[[MULTIPLY_20]], %[[SUBTRACT_1]] : tensor<f32>
// CHECK:           %[[ADD_15:.*]] = stablehlo.add %[[DIVIDE_10]], %[[DIVIDE_11]] : tensor<f32>
// CHECK:           %[[SUBTRACT_2:.*]] = stablehlo.subtract %[[MULTIPLY_8]], %[[CONSTANT_3]] : tensor<f32>
// CHECK:           %[[SELECT_10:.*]] = stablehlo.select %[[COMPARE_16]], %[[ADD_15]], %[[SUBTRACT_2]] : tensor<i1>, tensor<f32>
// CHECK:           %[[SELECT_11:.*]] = stablehlo.select %[[COMPARE_15]], %[[ADD_14]], %[[SELECT_10]] : tensor<i1>, tensor<f32>
// CHECK:           %[[SELECT_12:.*]] = stablehlo.select %[[AND_3]], %[[NEGATE_1]], %[[SELECT_11]] : tensor<i1>, tensor<f32>
// CHECK:           %[[MULTIPLY_22:.*]] = stablehlo.multiply %[[SELECT_12]], %[[ADD_13]] : tensor<f32>
// CHECK:           %[[SQRT_6:.*]] = stablehlo.sqrt %[[MULTIPLY_22]] : tensor<f32>
// CHECK:           %[[DIVIDE_12:.*]] = stablehlo.divide %[[ABS_1]], %[[SQRT_6]] : tensor<f32>
// CHECK:           %[[ADD_16:.*]] = stablehlo.add %[[SELECT_12]], %[[SQRT_6]] : tensor<f32>
// CHECK:           %[[LOG_PLUS_ONE_1:.*]] = stablehlo.log_plus_one %[[ADD_16]] : tensor<f32>
// CHECK:           %[[SELECT_13:.*]] = stablehlo.select %[[AND_3]], %[[DIVIDE_12]], %[[LOG_PLUS_ONE_1]] : tensor<i1>, tensor<f32>
// CHECK:           %[[SELECT_14:.*]] = stablehlo.select %[[COMPARE_11]], %[[ADD_12]], %[[SELECT_13]] : tensor<i1>, tensor<f32>
// CHECK:           %[[COMPLEX_1:.*]] = stablehlo.complex %[[SELECT_5]], %[[SELECT_14]] : tensor<complex<f32>>
// CHECK:           %[[IMAG_2:.*]] = stablehlo.imag %[[COMPLEX_1]] : (tensor<complex<f32>>) -> tensor<f32>
// CHECK:           %[[NEGATE_2:.*]] = stablehlo.negate %[[IMAG_2]] : tensor<f32>
// CHECK:           %[[SELECT_15:.*]] = stablehlo.select %[[COMPARE_0]], %[[NEGATE_2]], %[[IMAG_2]] : tensor<i1>, tensor<f32>
// CHECK:           %[[REAL_2:.*]] = stablehlo.real %[[COMPLEX_1]] : (tensor<complex<f32>>) -> tensor<f32>
// CHECK:           %[[VAL_0:.*]] = stablehlo.atan2 %[[IMAG_0]], %[[REAL_2]] : tensor<f32>
// CHECK:           %[[COMPLEX_2:.*]] = stablehlo.complex %[[SELECT_15]], %[[VAL_0]] : tensor<complex<f32>>
// CHECK:           return %[[COMPLEX_2]] : tensor<complex<f32>>
// CHECK:         }
func.func @asinh_complex_f32(%arg : tensor<complex<f32>>) -> tensor<complex<f32>> {
  %result = "chlo.asinh"(%arg) : (tensor<complex<f32>>) -> tensor<complex<f32>>
  func.return %result : tensor<complex<f32>>
}

//////
// Broadcast binary elementwise ops tests are located in
// chlo_legalize_to_stablehlo_broadcast.mlir

// -----

// Lower statically shaped `constant_like` to constant.
// CHECK-LABEL:   func.func @constant_like_static_shape(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<1x2xi64>) -> tensor<1x2xf32> {
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<3.200000e+00> : tensor<1x2xf32>
// CHECK:           return %[[CONSTANT_0]] : tensor<1x2xf32>
// CHECK:         }
func.func @constant_like_static_shape(%arg : tensor<1x2xi64>) -> tensor<1x2xf32> {
  %result = "chlo.constant_like"(%arg) { value = 3.2 : f32 }
      : (tensor<1x2xi64>) -> tensor<1x2xf32>
  func.return %result : tensor<1x2xf32>
}

// -----

// Lower dynamically shaped `constant_like` to broadcasted constant.
// CHECK-LABEL:   func.func @constant_like_bounded_dynamic_shape(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<2xi64>,
// CHECK-SAME:      %[[ARG1:.*]]: tensor<i32>) -> tensor<?xi32, #stablehlo.bounds<2>> {
// CHECK:           %[[SET_DIMENSION_SIZE_0:.*]] = stablehlo.set_dimension_size %[[ARG0]], %[[ARG1]], dim = 0 : (tensor<2xi64>, tensor<i32>) -> tensor<?xi64, #stablehlo.bounds<2>>
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<1> : tensor<i32>
// CHECK:           %[[BROADCAST_IN_DIM_0:.*]] = stablehlo.broadcast_in_dim %[[CONSTANT_0]], dims = [] : (tensor<i32>) -> tensor<2xi32>
// CHECK:           %[[GET_DIMENSION_SIZE_0:.*]] = stablehlo.get_dimension_size %[[SET_DIMENSION_SIZE_0]], dim = 0 : (tensor<?xi64, #stablehlo.bounds<2>>) -> tensor<i32>
// CHECK:           %[[SET_DIMENSION_SIZE_1:.*]] = stablehlo.set_dimension_size %[[BROADCAST_IN_DIM_0]], %[[GET_DIMENSION_SIZE_0]], dim = 0 : (tensor<2xi32>, tensor<i32>) -> tensor<?xi32, #stablehlo.bounds<2>>
// CHECK:           return %[[SET_DIMENSION_SIZE_1]] : tensor<?xi32, #stablehlo.bounds<2>>
// CHECK:         }
func.func @constant_like_bounded_dynamic_shape(%arg0: tensor<2xi64>, %arg1: tensor<i32>) -> tensor<?xi32, #stablehlo.bounds<2>> {
  %0 = stablehlo.set_dimension_size %arg0, %arg1, dim = 0 : (tensor<2xi64>, tensor<i32>) -> tensor<?xi64, #stablehlo.bounds<2>>
  %1 = "chlo.constant_like"(%0) <{value = 1 : i32}> : (tensor<?xi64, #stablehlo.bounds<2>>) -> tensor<?xi32, #stablehlo.bounds<2>>
  return %1 : tensor<?xi32, #stablehlo.bounds<2>>
}

// -----

// Lower dynamically shaped `constant_like` to broadcasted constant.
// CHECK-LABEL:   func.func @constant_like_dynamic_shape(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<?x?xi64>) -> tensor<?x?xf32> {
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<3.200000e+00> : tensor<f32>
// CHECK:           %[[SHAPE_OF_0:.*]] = shape.shape_of %[[ARG0]] : tensor<?x?xi64> -> tensor<2xindex>
// CHECK:           %[[DYNAMIC_BROADCAST_IN_DIM_0:.*]] = stablehlo.dynamic_broadcast_in_dim %[[CONSTANT_0]], %[[SHAPE_OF_0]], dims = [] : (tensor<f32>, tensor<2xindex>) -> tensor<?x?xf32>
// CHECK:           return %[[DYNAMIC_BROADCAST_IN_DIM_0]] : tensor<?x?xf32>
// CHECK:         }
func.func @constant_like_dynamic_shape(%arg : tensor<?x?xi64>) -> tensor<?x?xf32> {
  %result = "chlo.constant_like"(%arg) { value = 3.2 : f32 }
      : (tensor<?x?xi64>) -> tensor<?x?xf32>
  func.return %result : tensor<?x?xf32>
}

// -----

// CHECK-LABEL:   func.func @conj(
// CHECK-SAME:                    %[[ARG0:.*]]: tensor<3xcomplex<f32>>) -> tensor<3xcomplex<f32>> {
// CHECK:           %[[REAL_0:.*]] = stablehlo.real %[[ARG0]] : (tensor<3xcomplex<f32>>) -> tensor<3xf32>
// CHECK:           %[[IMAG_0:.*]] = stablehlo.imag %[[ARG0]] : (tensor<3xcomplex<f32>>) -> tensor<3xf32>
// CHECK:           %[[NEGATE_0:.*]] = stablehlo.negate %[[IMAG_0]] : tensor<3xf32>
// CHECK:           %[[COMPLEX_0:.*]] = stablehlo.complex %[[REAL_0]], %[[NEGATE_0]] : tensor<3xcomplex<f32>>
// CHECK:           return %[[COMPLEX_0]] : tensor<3xcomplex<f32>>
// CHECK:         }
func.func @conj(%arg0: tensor<3xcomplex<f32>>) -> tensor<3xcomplex<f32>> {
  %1 = "chlo.conj"(%arg0) : (tensor<3xcomplex<f32>>) -> tensor<3xcomplex<f32>>
  func.return %1 : tensor<3xcomplex<f32>>
}

// -----

// CHECK-LABEL:   func.func @erf_f64(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<f64>) -> tensor<f64> {
// CHECK:           %[[MULTIPLY_0:.*]] = stablehlo.multiply %[[ARG0]], %[[ARG0]] : tensor<f64>
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<9.6049737398705161> : tensor<f64>
// CHECK:           %[[MULTIPLY_1:.*]] = stablehlo.multiply %[[CONSTANT_0]], %[[MULTIPLY_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_1:.*]] = stablehlo.constant dense<90.026019720384269> : tensor<f64>
// CHECK:           %[[ADD_0:.*]] = stablehlo.add %[[MULTIPLY_1]], %[[CONSTANT_1]] : tensor<f64>
// CHECK:           %[[MULTIPLY_2:.*]] = stablehlo.multiply %[[ADD_0]], %[[MULTIPLY_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_2:.*]] = stablehlo.constant dense<2232.0053459468431> : tensor<f64>
// CHECK:           %[[ADD_1:.*]] = stablehlo.add %[[MULTIPLY_2]], %[[CONSTANT_2]] : tensor<f64>
// CHECK:           %[[MULTIPLY_3:.*]] = stablehlo.multiply %[[ADD_1]], %[[MULTIPLY_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_3:.*]] = stablehlo.constant dense<7003.3251411280507> : tensor<f64>
// CHECK:           %[[ADD_2:.*]] = stablehlo.add %[[MULTIPLY_3]], %[[CONSTANT_3]] : tensor<f64>
// CHECK:           %[[MULTIPLY_4:.*]] = stablehlo.multiply %[[ADD_2]], %[[MULTIPLY_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_4:.*]] = stablehlo.constant dense<55592.301301039493> : tensor<f64>
// CHECK:           %[[ADD_3:.*]] = stablehlo.add %[[MULTIPLY_4]], %[[CONSTANT_4]] : tensor<f64>
// CHECK:           %[[MULTIPLY_5:.*]] = stablehlo.multiply %[[ARG0]], %[[ADD_3]] : tensor<f64>
// CHECK:           %[[CONSTANT_5:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f64>
// CHECK:           %[[MULTIPLY_6:.*]] = stablehlo.multiply %[[CONSTANT_5]], %[[MULTIPLY_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_6:.*]] = stablehlo.constant dense<33.561714164750313> : tensor<f64>
// CHECK:           %[[ADD_4:.*]] = stablehlo.add %[[MULTIPLY_6]], %[[CONSTANT_6]] : tensor<f64>
// CHECK:           %[[MULTIPLY_7:.*]] = stablehlo.multiply %[[ADD_4]], %[[MULTIPLY_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_7:.*]] = stablehlo.constant dense<521.35794978015269> : tensor<f64>
// CHECK:           %[[ADD_5:.*]] = stablehlo.add %[[MULTIPLY_7]], %[[CONSTANT_7]] : tensor<f64>
// CHECK:           %[[MULTIPLY_8:.*]] = stablehlo.multiply %[[ADD_5]], %[[MULTIPLY_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_8:.*]] = stablehlo.constant dense<4594.3238297098014> : tensor<f64>
// CHECK:           %[[ADD_6:.*]] = stablehlo.add %[[MULTIPLY_8]], %[[CONSTANT_8]] : tensor<f64>
// CHECK:           %[[MULTIPLY_9:.*]] = stablehlo.multiply %[[ADD_6]], %[[MULTIPLY_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_9:.*]] = stablehlo.constant dense<22629.000061389095> : tensor<f64>
// CHECK:           %[[ADD_7:.*]] = stablehlo.add %[[MULTIPLY_9]], %[[CONSTANT_9]] : tensor<f64>
// CHECK:           %[[MULTIPLY_10:.*]] = stablehlo.multiply %[[ADD_7]], %[[MULTIPLY_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_10:.*]] = stablehlo.constant dense<49267.394260863592> : tensor<f64>
// CHECK:           %[[ADD_8:.*]] = stablehlo.add %[[MULTIPLY_10]], %[[CONSTANT_10]] : tensor<f64>
// CHECK:           %[[DIVIDE_0:.*]] = stablehlo.divide %[[MULTIPLY_5]], %[[ADD_8]] : tensor<f64>
// CHECK:           %[[CONSTANT_11:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f64>
// CHECK:           %[[MULTIPLY_11:.*]] = stablehlo.multiply %[[ARG0]], %[[ARG0]] : tensor<f64>
// CHECK:           %[[NEGATE_0:.*]] = stablehlo.negate %[[MULTIPLY_11]] : tensor<f64>
// CHECK:           %[[EXPONENTIAL_0:.*]] = stablehlo.exponential %[[NEGATE_0]] : tensor<f64>
// CHECK:           %[[ABS_0:.*]] = stablehlo.abs %[[ARG0]] : tensor<f64>
// CHECK:           %[[CONSTANT_12:.*]] = stablehlo.constant dense<2.4619698147353052E-10> : tensor<f64>
// CHECK:           %[[MULTIPLY_12:.*]] = stablehlo.multiply %[[CONSTANT_12]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_13:.*]] = stablehlo.constant dense<0.56418956483106886> : tensor<f64>
// CHECK:           %[[ADD_9:.*]] = stablehlo.add %[[MULTIPLY_12]], %[[CONSTANT_13]] : tensor<f64>
// CHECK:           %[[MULTIPLY_13:.*]] = stablehlo.multiply %[[ADD_9]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_14:.*]] = stablehlo.constant dense<7.4632105644226989> : tensor<f64>
// CHECK:           %[[ADD_10:.*]] = stablehlo.add %[[MULTIPLY_13]], %[[CONSTANT_14]] : tensor<f64>
// CHECK:           %[[MULTIPLY_14:.*]] = stablehlo.multiply %[[ADD_10]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_15:.*]] = stablehlo.constant dense<48.637197098568137> : tensor<f64>
// CHECK:           %[[ADD_11:.*]] = stablehlo.add %[[MULTIPLY_14]], %[[CONSTANT_15]] : tensor<f64>
// CHECK:           %[[MULTIPLY_15:.*]] = stablehlo.multiply %[[ADD_11]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_16:.*]] = stablehlo.constant dense<196.5208329560771> : tensor<f64>
// CHECK:           %[[ADD_12:.*]] = stablehlo.add %[[MULTIPLY_15]], %[[CONSTANT_16]] : tensor<f64>
// CHECK:           %[[MULTIPLY_16:.*]] = stablehlo.multiply %[[ADD_12]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_17:.*]] = stablehlo.constant dense<526.44519499547732> : tensor<f64>
// CHECK:           %[[ADD_13:.*]] = stablehlo.add %[[MULTIPLY_16]], %[[CONSTANT_17]] : tensor<f64>
// CHECK:           %[[MULTIPLY_17:.*]] = stablehlo.multiply %[[ADD_13]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_18:.*]] = stablehlo.constant dense<934.52852717195765> : tensor<f64>
// CHECK:           %[[ADD_14:.*]] = stablehlo.add %[[MULTIPLY_17]], %[[CONSTANT_18]] : tensor<f64>
// CHECK:           %[[MULTIPLY_18:.*]] = stablehlo.multiply %[[ADD_14]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_19:.*]] = stablehlo.constant dense<1027.5518868951572> : tensor<f64>
// CHECK:           %[[ADD_15:.*]] = stablehlo.add %[[MULTIPLY_18]], %[[CONSTANT_19]] : tensor<f64>
// CHECK:           %[[MULTIPLY_19:.*]] = stablehlo.multiply %[[ADD_15]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_20:.*]] = stablehlo.constant dense<557.53533536939938> : tensor<f64>
// CHECK:           %[[ADD_16:.*]] = stablehlo.add %[[MULTIPLY_19]], %[[CONSTANT_20]] : tensor<f64>
// CHECK:           %[[MULTIPLY_20:.*]] = stablehlo.multiply %[[EXPONENTIAL_0]], %[[ADD_16]] : tensor<f64>
// CHECK:           %[[CONSTANT_21:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f64>
// CHECK:           %[[MULTIPLY_21:.*]] = stablehlo.multiply %[[CONSTANT_21]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_22:.*]] = stablehlo.constant dense<13.228195115474499> : tensor<f64>
// CHECK:           %[[ADD_17:.*]] = stablehlo.add %[[MULTIPLY_21]], %[[CONSTANT_22]] : tensor<f64>
// CHECK:           %[[MULTIPLY_22:.*]] = stablehlo.multiply %[[ADD_17]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_23:.*]] = stablehlo.constant dense<86.707214088598973> : tensor<f64>
// CHECK:           %[[ADD_18:.*]] = stablehlo.add %[[MULTIPLY_22]], %[[CONSTANT_23]] : tensor<f64>
// CHECK:           %[[MULTIPLY_23:.*]] = stablehlo.multiply %[[ADD_18]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_24:.*]] = stablehlo.constant dense<354.93777888781989> : tensor<f64>
// CHECK:           %[[ADD_19:.*]] = stablehlo.add %[[MULTIPLY_23]], %[[CONSTANT_24]] : tensor<f64>
// CHECK:           %[[MULTIPLY_24:.*]] = stablehlo.multiply %[[ADD_19]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_25:.*]] = stablehlo.constant dense<975.70850174320549> : tensor<f64>
// CHECK:           %[[ADD_20:.*]] = stablehlo.add %[[MULTIPLY_24]], %[[CONSTANT_25]] : tensor<f64>
// CHECK:           %[[MULTIPLY_25:.*]] = stablehlo.multiply %[[ADD_20]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_26:.*]] = stablehlo.constant dense<1823.9091668790973> : tensor<f64>
// CHECK:           %[[ADD_21:.*]] = stablehlo.add %[[MULTIPLY_25]], %[[CONSTANT_26]] : tensor<f64>
// CHECK:           %[[MULTIPLY_26:.*]] = stablehlo.multiply %[[ADD_21]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_27:.*]] = stablehlo.constant dense<2246.3376081871097> : tensor<f64>
// CHECK:           %[[ADD_22:.*]] = stablehlo.add %[[MULTIPLY_26]], %[[CONSTANT_27]] : tensor<f64>
// CHECK:           %[[MULTIPLY_27:.*]] = stablehlo.multiply %[[ADD_22]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_28:.*]] = stablehlo.constant dense<1656.6630919416134> : tensor<f64>
// CHECK:           %[[ADD_23:.*]] = stablehlo.add %[[MULTIPLY_27]], %[[CONSTANT_28]] : tensor<f64>
// CHECK:           %[[MULTIPLY_28:.*]] = stablehlo.multiply %[[ADD_23]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_29:.*]] = stablehlo.constant dense<557.53534081772773> : tensor<f64>
// CHECK:           %[[ADD_24:.*]] = stablehlo.add %[[MULTIPLY_28]], %[[CONSTANT_29]] : tensor<f64>
// CHECK:           %[[DIVIDE_1:.*]] = stablehlo.divide %[[MULTIPLY_20]], %[[ADD_24]] : tensor<f64>
// CHECK:           %[[CONSTANT_30:.*]] = stablehlo.constant dense<0.56418958354775506> : tensor<f64>
// CHECK:           %[[MULTIPLY_29:.*]] = stablehlo.multiply %[[CONSTANT_30]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_31:.*]] = stablehlo.constant dense<1.275366707599781> : tensor<f64>
// CHECK:           %[[ADD_25:.*]] = stablehlo.add %[[MULTIPLY_29]], %[[CONSTANT_31]] : tensor<f64>
// CHECK:           %[[MULTIPLY_30:.*]] = stablehlo.multiply %[[ADD_25]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_32:.*]] = stablehlo.constant dense<5.0190504225118051> : tensor<f64>
// CHECK:           %[[ADD_26:.*]] = stablehlo.add %[[MULTIPLY_30]], %[[CONSTANT_32]] : tensor<f64>
// CHECK:           %[[MULTIPLY_31:.*]] = stablehlo.multiply %[[ADD_26]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_33:.*]] = stablehlo.constant dense<6.160210979930536> : tensor<f64>
// CHECK:           %[[ADD_27:.*]] = stablehlo.add %[[MULTIPLY_31]], %[[CONSTANT_33]] : tensor<f64>
// CHECK:           %[[MULTIPLY_32:.*]] = stablehlo.multiply %[[ADD_27]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_34:.*]] = stablehlo.constant dense<7.4097426995044895> : tensor<f64>
// CHECK:           %[[ADD_28:.*]] = stablehlo.add %[[MULTIPLY_32]], %[[CONSTANT_34]] : tensor<f64>
// CHECK:           %[[MULTIPLY_33:.*]] = stablehlo.multiply %[[ADD_28]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_35:.*]] = stablehlo.constant dense<2.9788666537210022> : tensor<f64>
// CHECK:           %[[ADD_29:.*]] = stablehlo.add %[[MULTIPLY_33]], %[[CONSTANT_35]] : tensor<f64>
// CHECK:           %[[MULTIPLY_34:.*]] = stablehlo.multiply %[[EXPONENTIAL_0]], %[[ADD_29]] : tensor<f64>
// CHECK:           %[[CONSTANT_36:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f64>
// CHECK:           %[[MULTIPLY_35:.*]] = stablehlo.multiply %[[CONSTANT_36]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_37:.*]] = stablehlo.constant dense<2.2605286322011726> : tensor<f64>
// CHECK:           %[[ADD_30:.*]] = stablehlo.add %[[MULTIPLY_35]], %[[CONSTANT_37]] : tensor<f64>
// CHECK:           %[[MULTIPLY_36:.*]] = stablehlo.multiply %[[ADD_30]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_38:.*]] = stablehlo.constant dense<9.3960352493800147> : tensor<f64>
// CHECK:           %[[ADD_31:.*]] = stablehlo.add %[[MULTIPLY_36]], %[[CONSTANT_38]] : tensor<f64>
// CHECK:           %[[MULTIPLY_37:.*]] = stablehlo.multiply %[[ADD_31]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_39:.*]] = stablehlo.constant dense<12.048953980809666> : tensor<f64>
// CHECK:           %[[ADD_32:.*]] = stablehlo.add %[[MULTIPLY_37]], %[[CONSTANT_39]] : tensor<f64>
// CHECK:           %[[MULTIPLY_38:.*]] = stablehlo.multiply %[[ADD_32]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_40:.*]] = stablehlo.constant dense<17.081445074756591> : tensor<f64>
// CHECK:           %[[ADD_33:.*]] = stablehlo.add %[[MULTIPLY_38]], %[[CONSTANT_40]] : tensor<f64>
// CHECK:           %[[MULTIPLY_39:.*]] = stablehlo.multiply %[[ADD_33]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_41:.*]] = stablehlo.constant dense<9.6089680906328585> : tensor<f64>
// CHECK:           %[[ADD_34:.*]] = stablehlo.add %[[MULTIPLY_39]], %[[CONSTANT_41]] : tensor<f64>
// CHECK:           %[[MULTIPLY_40:.*]] = stablehlo.multiply %[[ADD_34]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_42:.*]] = stablehlo.constant dense<3.3690764510008151> : tensor<f64>
// CHECK:           %[[ADD_35:.*]] = stablehlo.add %[[MULTIPLY_40]], %[[CONSTANT_42]] : tensor<f64>
// CHECK:           %[[DIVIDE_2:.*]] = stablehlo.divide %[[MULTIPLY_34]], %[[ADD_35]] : tensor<f64>
// CHECK:           %[[CONSTANT_43:.*]] = stablehlo.constant dense<8.000000e+00> : tensor<f64>
// CHECK:           %[[COMPARE_0:.*]] = stablehlo.compare  LT, %[[ABS_0]], %[[CONSTANT_43]] : (tensor<f64>, tensor<f64>) -> tensor<i1>
// CHECK:           %[[SELECT_0:.*]] = stablehlo.select %[[COMPARE_0]], %[[DIVIDE_1]], %[[DIVIDE_2]] : tensor<i1>, tensor<f64>
// CHECK:           %[[CONSTANT_44:.*]] = stablehlo.constant dense<-709.78271289338397> : tensor<f64>
// CHECK:           %[[COMPARE_1:.*]] = stablehlo.compare  LT, %[[NEGATE_0]], %[[CONSTANT_44]] : (tensor<f64>, tensor<f64>) -> tensor<i1>
// CHECK:           %[[CONSTANT_45:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<f64>
// CHECK:           %[[SELECT_1:.*]] = stablehlo.select %[[COMPARE_1]], %[[CONSTANT_45]], %[[SELECT_0]] : tensor<i1>, tensor<f64>
// CHECK:           %[[COMPARE_2:.*]] = stablehlo.compare  LT, %[[ARG0]], %[[CONSTANT_45]] : (tensor<f64>, tensor<f64>) -> tensor<i1>
// CHECK:           %[[CONSTANT_46:.*]] = stablehlo.constant dense<2.000000e+00> : tensor<f64>
// CHECK:           %[[SUBTRACT_0:.*]] = stablehlo.subtract %[[CONSTANT_46]], %[[SELECT_1]] : tensor<f64>
// CHECK:           %[[SELECT_2:.*]] = stablehlo.select %[[COMPARE_2]], %[[SUBTRACT_0]], %[[SELECT_1]] : tensor<i1>, tensor<f64>
// CHECK:           %[[SUBTRACT_1:.*]] = stablehlo.subtract %[[CONSTANT_11]], %[[SELECT_2]] : tensor<f64>
// CHECK:           %[[ABS_1:.*]] = stablehlo.abs %[[ARG0]] : tensor<f64>
// CHECK:           %[[COMPARE_3:.*]] = stablehlo.compare  LT, %[[ABS_1]], %[[CONSTANT_11]] : (tensor<f64>, tensor<f64>) -> tensor<i1>
// CHECK:           %[[SELECT_3:.*]] = stablehlo.select %[[COMPARE_3]], %[[DIVIDE_0]], %[[SUBTRACT_1]] : tensor<i1>, tensor<f64>
// CHECK:           return %[[SELECT_3]] : tensor<f64>
// CHECK:         }
func.func @erf_f64(%arg : tensor<f64>) -> tensor<f64> {
  %1 = "chlo.erf"(%arg) : (tensor<f64>) -> tensor<f64>
  func.return %1 : tensor<f64>
}

// -----

// CHECK-LABEL:   func.func @erf_f32(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<f32>) -> tensor<f32> {
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<-4.000000e+00> : tensor<f32>
// CHECK:           %[[CONSTANT_1:.*]] = stablehlo.constant dense<4.000000e+00> : tensor<f32>
// CHECK:           %[[CLAMP_0:.*]] = stablehlo.clamp %[[CONSTANT_0]], %[[ARG0]], %[[CONSTANT_1]] : tensor<f32>
// CHECK:           %[[MULTIPLY_0:.*]] = stablehlo.multiply %[[CLAMP_0]], %[[CLAMP_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_2:.*]] = stablehlo.constant dense<-2.72614237E-10> : tensor<f32>
// CHECK:           %[[MULTIPLY_1:.*]] = stablehlo.multiply %[[CONSTANT_2]], %[[MULTIPLY_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_3:.*]] = stablehlo.constant dense<2.77068146E-8> : tensor<f32>
// CHECK:           %[[ADD_0:.*]] = stablehlo.add %[[MULTIPLY_1]], %[[CONSTANT_3]] : tensor<f32>
// CHECK:           %[[MULTIPLY_2:.*]] = stablehlo.multiply %[[ADD_0]], %[[MULTIPLY_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_4:.*]] = stablehlo.constant dense<-2.10102394E-6> : tensor<f32>
// CHECK:           %[[ADD_1:.*]] = stablehlo.add %[[MULTIPLY_2]], %[[CONSTANT_4]] : tensor<f32>
// CHECK:           %[[MULTIPLY_3:.*]] = stablehlo.multiply %[[ADD_1]], %[[MULTIPLY_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_5:.*]] = stablehlo.constant dense<-5.69250624E-5> : tensor<f32>
// CHECK:           %[[ADD_2:.*]] = stablehlo.add %[[MULTIPLY_3]], %[[CONSTANT_5]] : tensor<f32>
// CHECK:           %[[MULTIPLY_4:.*]] = stablehlo.multiply %[[ADD_2]], %[[MULTIPLY_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_6:.*]] = stablehlo.constant dense<-7.34990637E-4> : tensor<f32>
// CHECK:           %[[ADD_3:.*]] = stablehlo.add %[[MULTIPLY_4]], %[[CONSTANT_6]] : tensor<f32>
// CHECK:           %[[MULTIPLY_5:.*]] = stablehlo.multiply %[[ADD_3]], %[[MULTIPLY_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_7:.*]] = stablehlo.constant dense<-2.954600e-03> : tensor<f32>
// CHECK:           %[[ADD_4:.*]] = stablehlo.add %[[MULTIPLY_5]], %[[CONSTANT_7]] : tensor<f32>
// CHECK:           %[[MULTIPLY_6:.*]] = stablehlo.multiply %[[ADD_4]], %[[MULTIPLY_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_8:.*]] = stablehlo.constant dense<-0.0160960332> : tensor<f32>
// CHECK:           %[[ADD_5:.*]] = stablehlo.add %[[MULTIPLY_6]], %[[CONSTANT_8]] : tensor<f32>
// CHECK:           %[[CONSTANT_9:.*]] = stablehlo.constant dense<-1.45660715E-5> : tensor<f32>
// CHECK:           %[[MULTIPLY_7:.*]] = stablehlo.multiply %[[CONSTANT_9]], %[[MULTIPLY_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_10:.*]] = stablehlo.constant dense<-2.13374049E-4> : tensor<f32>
// CHECK:           %[[ADD_6:.*]] = stablehlo.add %[[MULTIPLY_7]], %[[CONSTANT_10]] : tensor<f32>
// CHECK:           %[[MULTIPLY_8:.*]] = stablehlo.multiply %[[ADD_6]], %[[MULTIPLY_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_11:.*]] = stablehlo.constant dense<-0.00168282702> : tensor<f32>
// CHECK:           %[[ADD_7:.*]] = stablehlo.add %[[MULTIPLY_8]], %[[CONSTANT_11]] : tensor<f32>
// CHECK:           %[[MULTIPLY_9:.*]] = stablehlo.multiply %[[ADD_7]], %[[MULTIPLY_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_12:.*]] = stablehlo.constant dense<-0.00737332925> : tensor<f32>
// CHECK:           %[[ADD_8:.*]] = stablehlo.add %[[MULTIPLY_9]], %[[CONSTANT_12]] : tensor<f32>
// CHECK:           %[[MULTIPLY_10:.*]] = stablehlo.multiply %[[ADD_8]], %[[MULTIPLY_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_13:.*]] = stablehlo.constant dense<-0.0142647391> : tensor<f32>
// CHECK:           %[[ADD_9:.*]] = stablehlo.add %[[MULTIPLY_10]], %[[CONSTANT_13]] : tensor<f32>
// CHECK:           %[[MULTIPLY_11:.*]] = stablehlo.multiply %[[CLAMP_0]], %[[ADD_5]] : tensor<f32>
// CHECK:           %[[DIVIDE_0:.*]] = stablehlo.divide %[[MULTIPLY_11]], %[[ADD_9]] : tensor<f32>
// CHECK:           %[[CONSTANT_14:.*]] = stablehlo.constant dense<-1.000000e+00> : tensor<f32>
// CHECK:           %[[CONSTANT_15:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[CLAMP_1:.*]] = stablehlo.clamp %[[CONSTANT_14]], %[[DIVIDE_0]], %[[CONSTANT_15]] : tensor<f32>
// CHECK:           return %[[CLAMP_1]] : tensor<f32>
// CHECK:         }
func.func @erf_f32(%arg : tensor<f32>) -> tensor<f32> {
  %1 = "chlo.erf"(%arg) : (tensor<f32>) -> tensor<f32>
  func.return %1 : tensor<f32>
}

// -----

// CHECK-LABEL:   func.func @erf_f16(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<f16>) -> tensor<f16> {
// CHECK:           %[[CONVERT_0:.*]] = stablehlo.convert %[[ARG0]] : (tensor<f16>) -> tensor<f32>
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<-4.000000e+00> : tensor<f32>
// CHECK:           %[[CONSTANT_1:.*]] = stablehlo.constant dense<4.000000e+00> : tensor<f32>
// CHECK:           %[[CLAMP_0:.*]] = stablehlo.clamp %[[CONSTANT_0]], %[[CONVERT_0]], %[[CONSTANT_1]] : tensor<f32>
// CHECK:           %[[MULTIPLY_0:.*]] = stablehlo.multiply %[[CLAMP_0]], %[[CLAMP_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_2:.*]] = stablehlo.constant dense<-2.72614237E-10> : tensor<f32>
// CHECK:           %[[MULTIPLY_1:.*]] = stablehlo.multiply %[[CONSTANT_2]], %[[MULTIPLY_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_3:.*]] = stablehlo.constant dense<2.77068146E-8> : tensor<f32>
// CHECK:           %[[ADD_0:.*]] = stablehlo.add %[[MULTIPLY_1]], %[[CONSTANT_3]] : tensor<f32>
// CHECK:           %[[MULTIPLY_2:.*]] = stablehlo.multiply %[[ADD_0]], %[[MULTIPLY_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_4:.*]] = stablehlo.constant dense<-2.10102394E-6> : tensor<f32>
// CHECK:           %[[ADD_1:.*]] = stablehlo.add %[[MULTIPLY_2]], %[[CONSTANT_4]] : tensor<f32>
// CHECK:           %[[MULTIPLY_3:.*]] = stablehlo.multiply %[[ADD_1]], %[[MULTIPLY_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_5:.*]] = stablehlo.constant dense<-5.69250624E-5> : tensor<f32>
// CHECK:           %[[ADD_2:.*]] = stablehlo.add %[[MULTIPLY_3]], %[[CONSTANT_5]] : tensor<f32>
// CHECK:           %[[MULTIPLY_4:.*]] = stablehlo.multiply %[[ADD_2]], %[[MULTIPLY_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_6:.*]] = stablehlo.constant dense<-7.34990637E-4> : tensor<f32>
// CHECK:           %[[ADD_3:.*]] = stablehlo.add %[[MULTIPLY_4]], %[[CONSTANT_6]] : tensor<f32>
// CHECK:           %[[MULTIPLY_5:.*]] = stablehlo.multiply %[[ADD_3]], %[[MULTIPLY_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_7:.*]] = stablehlo.constant dense<-2.954600e-03> : tensor<f32>
// CHECK:           %[[ADD_4:.*]] = stablehlo.add %[[MULTIPLY_5]], %[[CONSTANT_7]] : tensor<f32>
// CHECK:           %[[MULTIPLY_6:.*]] = stablehlo.multiply %[[ADD_4]], %[[MULTIPLY_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_8:.*]] = stablehlo.constant dense<-0.0160960332> : tensor<f32>
// CHECK:           %[[ADD_5:.*]] = stablehlo.add %[[MULTIPLY_6]], %[[CONSTANT_8]] : tensor<f32>
// CHECK:           %[[CONSTANT_9:.*]] = stablehlo.constant dense<-1.45660715E-5> : tensor<f32>
// CHECK:           %[[MULTIPLY_7:.*]] = stablehlo.multiply %[[CONSTANT_9]], %[[MULTIPLY_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_10:.*]] = stablehlo.constant dense<-2.13374049E-4> : tensor<f32>
// CHECK:           %[[ADD_6:.*]] = stablehlo.add %[[MULTIPLY_7]], %[[CONSTANT_10]] : tensor<f32>
// CHECK:           %[[MULTIPLY_8:.*]] = stablehlo.multiply %[[ADD_6]], %[[MULTIPLY_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_11:.*]] = stablehlo.constant dense<-0.00168282702> : tensor<f32>
// CHECK:           %[[ADD_7:.*]] = stablehlo.add %[[MULTIPLY_8]], %[[CONSTANT_11]] : tensor<f32>
// CHECK:           %[[MULTIPLY_9:.*]] = stablehlo.multiply %[[ADD_7]], %[[MULTIPLY_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_12:.*]] = stablehlo.constant dense<-0.00737332925> : tensor<f32>
// CHECK:           %[[ADD_8:.*]] = stablehlo.add %[[MULTIPLY_9]], %[[CONSTANT_12]] : tensor<f32>
// CHECK:           %[[MULTIPLY_10:.*]] = stablehlo.multiply %[[ADD_8]], %[[MULTIPLY_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_13:.*]] = stablehlo.constant dense<-0.0142647391> : tensor<f32>
// CHECK:           %[[ADD_9:.*]] = stablehlo.add %[[MULTIPLY_10]], %[[CONSTANT_13]] : tensor<f32>
// CHECK:           %[[MULTIPLY_11:.*]] = stablehlo.multiply %[[CLAMP_0]], %[[ADD_5]] : tensor<f32>
// CHECK:           %[[DIVIDE_0:.*]] = stablehlo.divide %[[MULTIPLY_11]], %[[ADD_9]] : tensor<f32>
// CHECK:           %[[CONSTANT_14:.*]] = stablehlo.constant dense<-1.000000e+00> : tensor<f32>
// CHECK:           %[[CONSTANT_15:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[CLAMP_1:.*]] = stablehlo.clamp %[[CONSTANT_14]], %[[DIVIDE_0]], %[[CONSTANT_15]] : tensor<f32>
// CHECK:           %[[CONVERT_1:.*]] = stablehlo.convert %[[CLAMP_1]] : (tensor<f32>) -> tensor<f16>
// CHECK:           return %[[CONVERT_1]] : tensor<f16>
// CHECK:         }
func.func @erf_f16(%arg : tensor<f16>) -> tensor<f16> {
  %1 = "chlo.erf"(%arg) : (tensor<f16>) -> tensor<f16>
  func.return %1 : tensor<f16>
}

// -----

// CHECK-LABEL:   func.func @erf_bf16(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<bf16>) -> tensor<bf16> {
// CHECK:           %[[CONVERT_0:.*]] = stablehlo.convert %[[ARG0]] : (tensor<bf16>) -> tensor<f32>
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<-4.000000e+00> : tensor<f32>
// CHECK:           %[[CONSTANT_1:.*]] = stablehlo.constant dense<4.000000e+00> : tensor<f32>
// CHECK:           %[[CLAMP_0:.*]] = stablehlo.clamp %[[CONSTANT_0]], %[[CONVERT_0]], %[[CONSTANT_1]] : tensor<f32>
// CHECK:           %[[MULTIPLY_0:.*]] = stablehlo.multiply %[[CLAMP_0]], %[[CLAMP_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_2:.*]] = stablehlo.constant dense<-2.72614237E-10> : tensor<f32>
// CHECK:           %[[MULTIPLY_1:.*]] = stablehlo.multiply %[[CONSTANT_2]], %[[MULTIPLY_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_3:.*]] = stablehlo.constant dense<2.77068146E-8> : tensor<f32>
// CHECK:           %[[ADD_0:.*]] = stablehlo.add %[[MULTIPLY_1]], %[[CONSTANT_3]] : tensor<f32>
// CHECK:           %[[MULTIPLY_2:.*]] = stablehlo.multiply %[[ADD_0]], %[[MULTIPLY_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_4:.*]] = stablehlo.constant dense<-2.10102394E-6> : tensor<f32>
// CHECK:           %[[ADD_1:.*]] = stablehlo.add %[[MULTIPLY_2]], %[[CONSTANT_4]] : tensor<f32>
// CHECK:           %[[MULTIPLY_3:.*]] = stablehlo.multiply %[[ADD_1]], %[[MULTIPLY_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_5:.*]] = stablehlo.constant dense<-5.69250624E-5> : tensor<f32>
// CHECK:           %[[ADD_2:.*]] = stablehlo.add %[[MULTIPLY_3]], %[[CONSTANT_5]] : tensor<f32>
// CHECK:           %[[MULTIPLY_4:.*]] = stablehlo.multiply %[[ADD_2]], %[[MULTIPLY_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_6:.*]] = stablehlo.constant dense<-7.34990637E-4> : tensor<f32>
// CHECK:           %[[ADD_3:.*]] = stablehlo.add %[[MULTIPLY_4]], %[[CONSTANT_6]] : tensor<f32>
// CHECK:           %[[MULTIPLY_5:.*]] = stablehlo.multiply %[[ADD_3]], %[[MULTIPLY_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_7:.*]] = stablehlo.constant dense<-2.954600e-03> : tensor<f32>
// CHECK:           %[[ADD_4:.*]] = stablehlo.add %[[MULTIPLY_5]], %[[CONSTANT_7]] : tensor<f32>
// CHECK:           %[[MULTIPLY_6:.*]] = stablehlo.multiply %[[ADD_4]], %[[MULTIPLY_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_8:.*]] = stablehlo.constant dense<-0.0160960332> : tensor<f32>
// CHECK:           %[[ADD_5:.*]] = stablehlo.add %[[MULTIPLY_6]], %[[CONSTANT_8]] : tensor<f32>
// CHECK:           %[[CONSTANT_9:.*]] = stablehlo.constant dense<-1.45660715E-5> : tensor<f32>
// CHECK:           %[[MULTIPLY_7:.*]] = stablehlo.multiply %[[CONSTANT_9]], %[[MULTIPLY_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_10:.*]] = stablehlo.constant dense<-2.13374049E-4> : tensor<f32>
// CHECK:           %[[ADD_6:.*]] = stablehlo.add %[[MULTIPLY_7]], %[[CONSTANT_10]] : tensor<f32>
// CHECK:           %[[MULTIPLY_8:.*]] = stablehlo.multiply %[[ADD_6]], %[[MULTIPLY_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_11:.*]] = stablehlo.constant dense<-0.00168282702> : tensor<f32>
// CHECK:           %[[ADD_7:.*]] = stablehlo.add %[[MULTIPLY_8]], %[[CONSTANT_11]] : tensor<f32>
// CHECK:           %[[MULTIPLY_9:.*]] = stablehlo.multiply %[[ADD_7]], %[[MULTIPLY_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_12:.*]] = stablehlo.constant dense<-0.00737332925> : tensor<f32>
// CHECK:           %[[ADD_8:.*]] = stablehlo.add %[[MULTIPLY_9]], %[[CONSTANT_12]] : tensor<f32>
// CHECK:           %[[MULTIPLY_10:.*]] = stablehlo.multiply %[[ADD_8]], %[[MULTIPLY_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_13:.*]] = stablehlo.constant dense<-0.0142647391> : tensor<f32>
// CHECK:           %[[ADD_9:.*]] = stablehlo.add %[[MULTIPLY_10]], %[[CONSTANT_13]] : tensor<f32>
// CHECK:           %[[MULTIPLY_11:.*]] = stablehlo.multiply %[[CLAMP_0]], %[[ADD_5]] : tensor<f32>
// CHECK:           %[[DIVIDE_0:.*]] = stablehlo.divide %[[MULTIPLY_11]], %[[ADD_9]] : tensor<f32>
// CHECK:           %[[CONSTANT_14:.*]] = stablehlo.constant dense<-1.000000e+00> : tensor<f32>
// CHECK:           %[[CONSTANT_15:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[CLAMP_1:.*]] = stablehlo.clamp %[[CONSTANT_14]], %[[DIVIDE_0]], %[[CONSTANT_15]] : tensor<f32>
// CHECK:           %[[CONVERT_1:.*]] = stablehlo.convert %[[CLAMP_1]] : (tensor<f32>) -> tensor<bf16>
// CHECK:           return %[[CONVERT_1]] : tensor<bf16>
// CHECK:         }
func.func @erf_bf16(%arg : tensor<bf16>) -> tensor<bf16> {
  %1 = "chlo.erf"(%arg) : (tensor<bf16>) -> tensor<bf16>
  func.return %1 : tensor<bf16>
}

// -----

// CHECK-LABEL:   func.func @acosh(
// CHECK-SAME:                     %[[ARG0:.*]]: tensor<f16>) -> tensor<f16> {
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<6.550400e+04> : tensor<f16>
// CHECK:           %[[CONSTANT_1:.*]] = stablehlo.constant dense<2.000000e+00> : tensor<f16>
// CHECK:           %[[DIVIDE_0:.*]] = stablehlo.divide %[[CONSTANT_0]], %[[CONSTANT_1]] : tensor<f16>
// CHECK:           %[[COMPARE_0:.*]] = stablehlo.compare  GE, %[[ARG0]], %[[DIVIDE_0]] : (tensor<f16>, tensor<f16>) -> tensor<i1>
// CHECK:           %[[LOG_0:.*]] = stablehlo.log %[[CONSTANT_1]] : tensor<f16>
// CHECK:           %[[LOG_1:.*]] = stablehlo.log %[[ARG0]] : tensor<f16>
// CHECK:           %[[ADD_0:.*]] = stablehlo.add %[[LOG_0]], %[[LOG_1]] : tensor<f16>
// CHECK:           %[[CONSTANT_2:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f16>
// CHECK:           %[[SUBTRACT_0:.*]] = stablehlo.subtract %[[ARG0]], %[[CONSTANT_2]] : tensor<f16>
// CHECK:           %[[SQRT_0:.*]] = stablehlo.sqrt %[[SUBTRACT_0]] : tensor<f16>
// CHECK:           %[[ADD_1:.*]] = stablehlo.add %[[ARG0]], %[[CONSTANT_2]] : tensor<f16>
// CHECK:           %[[SQRT_1:.*]] = stablehlo.sqrt %[[ADD_1]] : tensor<f16>
// CHECK:           %[[ADD_2:.*]] = stablehlo.add %[[SQRT_1]], %[[SQRT_0]] : tensor<f16>
// CHECK:           %[[MULTIPLY_0:.*]] = stablehlo.multiply %[[SQRT_0]], %[[ADD_2]] : tensor<f16>
// CHECK:           %[[LOG_PLUS_ONE_0:.*]] = stablehlo.log_plus_one %[[MULTIPLY_0]] : tensor<f16>
// CHECK:           %[[SELECT_0:.*]] = stablehlo.select %[[COMPARE_0]], %[[ADD_0]], %[[LOG_PLUS_ONE_0]] : tensor<i1>, tensor<f16>
// CHECK:           return %[[SELECT_0]] : tensor<f16>
// CHECK:         }
func.func @acosh(%arg: tensor<f16>) -> tensor<f16> {
  %1 = "chlo.acosh"(%arg) : (tensor<f16>) -> tensor<f16>
  func.return %1 : tensor<f16>
}

// -----

// CHECK-LABEL:   func.func @acosh_complex_f32(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<complex<f32>>) -> tensor<complex<f32>> {
// CHECK:           %[[REAL_0:.*]] = stablehlo.real %[[ARG0]] : (tensor<complex<f32>>) -> tensor<f32>
// CHECK:           %[[ABS_0:.*]] = stablehlo.abs %[[REAL_0]] : tensor<f32>
// CHECK:           %[[IMAG_0:.*]] = stablehlo.imag %[[ARG0]] : (tensor<complex<f32>>) -> tensor<f32>
// CHECK:           %[[ABS_1:.*]] = stablehlo.abs %[[IMAG_0]] : tensor<f32>
// CHECK:           %[[MAXIMUM_0:.*]] = stablehlo.maximum %[[ABS_0]], %[[ABS_1]] : tensor<f32>
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<3.40282347E+38> : tensor<f32>
// CHECK:           %[[SQRT_0:.*]] = stablehlo.sqrt %[[CONSTANT_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_1:.*]] = stablehlo.constant dense<8.000000e+00> : tensor<f32>
// CHECK:           %[[DIVIDE_0:.*]] = stablehlo.divide %[[SQRT_0]], %[[CONSTANT_1]] : tensor<f32>
// CHECK:           %[[COMPARE_0:.*]] = stablehlo.compare  GE, %[[MAXIMUM_0]], %[[DIVIDE_0]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[CONSTANT_2:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[COMPARE_1:.*]] = stablehlo.compare  LE, %[[ABS_0]], %[[CONSTANT_2]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[CONSTANT_3:.*]] = stablehlo.constant dense<5.000000e-01> : tensor<f32>
// CHECK:           %[[ADD_0:.*]] = stablehlo.add %[[ABS_0]], %[[CONSTANT_2]] : tensor<f32>
// CHECK:           %[[ABS_2:.*]] = stablehlo.abs %[[ADD_0]] : tensor<f32>
// CHECK:           %[[MAXIMUM_1:.*]] = stablehlo.maximum %[[ABS_2]], %[[ABS_1]] : tensor<f32>
// CHECK:           %[[MINIMUM_0:.*]] = stablehlo.minimum %[[ABS_2]], %[[ABS_1]] : tensor<f32>
// CHECK:           %[[COMPARE_2:.*]] = stablehlo.compare  EQ, %[[MAXIMUM_1]], %[[MINIMUM_0]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[CONSTANT_4:.*]] = stablehlo.constant dense<1.41421354> : tensor<f32>
// CHECK:           %[[MULTIPLY_0:.*]] = stablehlo.multiply %[[CONSTANT_4]], %[[MAXIMUM_1]] : tensor<f32>
// CHECK:           %[[DIVIDE_1:.*]] = stablehlo.divide %[[MINIMUM_0]], %[[MAXIMUM_1]] : tensor<f32>
// CHECK:           %[[MULTIPLY_1:.*]] = stablehlo.multiply %[[DIVIDE_1]], %[[DIVIDE_1]] : tensor<f32>
// CHECK:           %[[ADD_1:.*]] = stablehlo.add %[[CONSTANT_2]], %[[MULTIPLY_1]] : tensor<f32>
// CHECK:           %[[SQRT_1:.*]] = stablehlo.sqrt %[[ADD_1]] : tensor<f32>
// CHECK:           %[[COMPARE_3:.*]] = stablehlo.compare  EQ, %[[SQRT_1]], %[[CONSTANT_2]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[CONSTANT_5:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<f32>
// CHECK:           %[[COMPARE_4:.*]] = stablehlo.compare  GT, %[[MULTIPLY_1]], %[[CONSTANT_5]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[AND_0:.*]] = stablehlo.and %[[COMPARE_3]], %[[COMPARE_4]] : tensor<i1>
// CHECK:           %[[MULTIPLY_2:.*]] = stablehlo.multiply %[[MAXIMUM_1]], %[[MULTIPLY_1]] : tensor<f32>
// CHECK:           %[[CONSTANT_6:.*]] = stablehlo.constant dense<2.000000e+00> : tensor<f32>
// CHECK:           %[[DIVIDE_2:.*]] = stablehlo.divide %[[MULTIPLY_2]], %[[CONSTANT_6]] : tensor<f32>
// CHECK:           %[[ADD_2:.*]] = stablehlo.add %[[MAXIMUM_1]], %[[DIVIDE_2]] : tensor<f32>
// CHECK:           %[[MULTIPLY_3:.*]] = stablehlo.multiply %[[MAXIMUM_1]], %[[SQRT_1]] : tensor<f32>
// CHECK:           %[[SELECT_0:.*]] = stablehlo.select %[[AND_0]], %[[ADD_2]], %[[MULTIPLY_3]] : tensor<i1>, tensor<f32>
// CHECK:           %[[SELECT_1:.*]] = stablehlo.select %[[COMPARE_2]], %[[MULTIPLY_0]], %[[SELECT_0]] : tensor<i1>, tensor<f32>
// CHECK:           %[[SUBTRACT_0:.*]] = stablehlo.subtract %[[ABS_0]], %[[CONSTANT_2]] : tensor<f32>
// CHECK:           %[[ABS_3:.*]] = stablehlo.abs %[[SUBTRACT_0]] : tensor<f32>
// CHECK:           %[[MAXIMUM_2:.*]] = stablehlo.maximum %[[ABS_3]], %[[ABS_1]] : tensor<f32>
// CHECK:           %[[MINIMUM_1:.*]] = stablehlo.minimum %[[ABS_3]], %[[ABS_1]] : tensor<f32>
// CHECK:           %[[COMPARE_5:.*]] = stablehlo.compare  EQ, %[[MAXIMUM_2]], %[[MINIMUM_1]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[MULTIPLY_4:.*]] = stablehlo.multiply %[[CONSTANT_4]], %[[MAXIMUM_2]] : tensor<f32>
// CHECK:           %[[DIVIDE_3:.*]] = stablehlo.divide %[[MINIMUM_1]], %[[MAXIMUM_2]] : tensor<f32>
// CHECK:           %[[MULTIPLY_5:.*]] = stablehlo.multiply %[[DIVIDE_3]], %[[DIVIDE_3]] : tensor<f32>
// CHECK:           %[[ADD_3:.*]] = stablehlo.add %[[CONSTANT_2]], %[[MULTIPLY_5]] : tensor<f32>
// CHECK:           %[[SQRT_2:.*]] = stablehlo.sqrt %[[ADD_3]] : tensor<f32>
// CHECK:           %[[COMPARE_6:.*]] = stablehlo.compare  EQ, %[[SQRT_2]], %[[CONSTANT_2]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[COMPARE_7:.*]] = stablehlo.compare  GT, %[[MULTIPLY_5]], %[[CONSTANT_5]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[AND_1:.*]] = stablehlo.and %[[COMPARE_6]], %[[COMPARE_7]] : tensor<i1>
// CHECK:           %[[MULTIPLY_6:.*]] = stablehlo.multiply %[[MAXIMUM_2]], %[[MULTIPLY_5]] : tensor<f32>
// CHECK:           %[[DIVIDE_4:.*]] = stablehlo.divide %[[MULTIPLY_6]], %[[CONSTANT_6]] : tensor<f32>
// CHECK:           %[[ADD_4:.*]] = stablehlo.add %[[MAXIMUM_2]], %[[DIVIDE_4]] : tensor<f32>
// CHECK:           %[[MULTIPLY_7:.*]] = stablehlo.multiply %[[MAXIMUM_2]], %[[SQRT_2]] : tensor<f32>
// CHECK:           %[[SELECT_2:.*]] = stablehlo.select %[[AND_1]], %[[ADD_4]], %[[MULTIPLY_7]] : tensor<i1>, tensor<f32>
// CHECK:           %[[SELECT_3:.*]] = stablehlo.select %[[COMPARE_5]], %[[MULTIPLY_4]], %[[SELECT_2]] : tensor<i1>, tensor<f32>
// CHECK:           %[[ADD_5:.*]] = stablehlo.add %[[SELECT_1]], %[[SELECT_3]] : tensor<f32>
// CHECK:           %[[MULTIPLY_8:.*]] = stablehlo.multiply %[[CONSTANT_3]], %[[ADD_5]] : tensor<f32>
// CHECK:           %[[ADD_6:.*]] = stablehlo.add %[[MULTIPLY_8]], %[[ABS_0]] : tensor<f32>
// CHECK:           %[[MULTIPLY_9:.*]] = stablehlo.multiply %[[CONSTANT_3]], %[[ADD_6]] : tensor<f32>
// CHECK:           %[[MULTIPLY_10:.*]] = stablehlo.multiply %[[ABS_1]], %[[ABS_1]] : tensor<f32>
// CHECK:           %[[ADD_7:.*]] = stablehlo.add %[[SELECT_1]], %[[ADD_0]] : tensor<f32>
// CHECK:           %[[DIVIDE_5:.*]] = stablehlo.divide %[[MULTIPLY_10]], %[[ADD_7]] : tensor<f32>
// CHECK:           %[[SUBTRACT_1:.*]] = stablehlo.subtract %[[SELECT_3]], %[[SUBTRACT_0]] : tensor<f32>
// CHECK:           %[[ADD_8:.*]] = stablehlo.add %[[DIVIDE_5]], %[[SUBTRACT_1]] : tensor<f32>
// CHECK:           %[[MULTIPLY_11:.*]] = stablehlo.multiply %[[MULTIPLY_9]], %[[ADD_8]] : tensor<f32>
// CHECK:           %[[SQRT_3:.*]] = stablehlo.sqrt %[[MULTIPLY_11]] : tensor<f32>
// CHECK:           %[[DIVIDE_6:.*]] = stablehlo.divide %[[MULTIPLY_9]], %[[ADD_7]] : tensor<f32>
// CHECK:           %[[ADD_9:.*]] = stablehlo.add %[[SELECT_3]], %[[SUBTRACT_0]] : tensor<f32>
// CHECK:           %[[DIVIDE_7:.*]] = stablehlo.divide %[[MULTIPLY_9]], %[[ADD_9]] : tensor<f32>
// CHECK:           %[[ADD_10:.*]] = stablehlo.add %[[DIVIDE_6]], %[[DIVIDE_7]] : tensor<f32>
// CHECK:           %[[SQRT_4:.*]] = stablehlo.sqrt %[[ADD_10]] : tensor<f32>
// CHECK:           %[[MULTIPLY_12:.*]] = stablehlo.multiply %[[ABS_1]], %[[SQRT_4]] : tensor<f32>
// CHECK:           %[[SELECT_4:.*]] = stablehlo.select %[[COMPARE_1]], %[[SQRT_3]], %[[MULTIPLY_12]] : tensor<i1>, tensor<f32>
// CHECK:           %[[SELECT_5:.*]] = stablehlo.select %[[COMPARE_0]], %[[ABS_1]], %[[SELECT_4]] : tensor<i1>, tensor<f32>
// CHECK:           %[[CONSTANT_7:.*]] = stablehlo.constant dense<9.99999995E+11> : tensor<f32>
// CHECK:           %[[MULTIPLY_13:.*]] = stablehlo.multiply %[[DIVIDE_0]], %[[CONSTANT_7]] : tensor<f32>
// CHECK:           %[[COMPARE_8:.*]] = stablehlo.compare  LT, %[[ABS_0]], %[[MULTIPLY_13]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[CONSTANT_8:.*]] = stablehlo.constant dense<9.99999997E-7> : tensor<f32>
// CHECK:           %[[MULTIPLY_14:.*]] = stablehlo.multiply %[[DIVIDE_0]], %[[CONSTANT_8]] : tensor<f32>
// CHECK:           %[[CONSTANT_9:.*]] = stablehlo.constant dense<1.000000e+02> : tensor<f32>
// CHECK:           %[[MULTIPLY_15:.*]] = stablehlo.multiply %[[DIVIDE_0]], %[[CONSTANT_9]] : tensor<f32>
// CHECK:           %[[SELECT_6:.*]] = stablehlo.select %[[COMPARE_8]], %[[MULTIPLY_14]], %[[MULTIPLY_15]] : tensor<i1>, tensor<f32>
// CHECK:           %[[COMPARE_9:.*]] = stablehlo.compare  GE, %[[ABS_1]], %[[SELECT_6]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[SELECT_7:.*]] = stablehlo.select %[[COMPARE_9]], %[[ABS_1]], %[[ABS_0]] : tensor<i1>, tensor<f32>
// CHECK:           %[[SELECT_8:.*]] = stablehlo.select %[[COMPARE_9]], %[[SELECT_6]], %[[DIVIDE_0]] : tensor<i1>, tensor<f32>
// CHECK:           %[[COMPARE_10:.*]] = stablehlo.compare  GE, %[[SELECT_7]], %[[SELECT_8]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[LOG_0:.*]] = stablehlo.log %[[CONSTANT_6]] : tensor<f32>
// CHECK:           %[[LOG_1:.*]] = stablehlo.log %[[SELECT_7]] : tensor<f32>
// CHECK:           %[[ADD_11:.*]] = stablehlo.add %[[LOG_0]], %[[LOG_1]] : tensor<f32>
// CHECK:           %[[CONSTANT_10:.*]] = stablehlo.constant dense<0x7F800000> : tensor<f32>
// CHECK:           %[[COMPARE_11:.*]] = stablehlo.compare  EQ, %[[ABS_1]], %[[CONSTANT_10]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[NOT_0:.*]] = stablehlo.not %[[COMPARE_11]] : tensor<i1>
// CHECK:           %[[AND_2:.*]] = stablehlo.and %[[COMPARE_9]], %[[NOT_0]] : tensor<i1>
// CHECK:           %[[DIVIDE_8:.*]] = stablehlo.divide %[[ABS_0]], %[[ABS_1]] : tensor<f32>
// CHECK:           %[[SELECT_9:.*]] = stablehlo.select %[[AND_2]], %[[DIVIDE_8]], %[[CONSTANT_5]] : tensor<i1>, tensor<f32>
// CHECK:           %[[MULTIPLY_16:.*]] = stablehlo.multiply %[[SELECT_9]], %[[SELECT_9]] : tensor<f32>
// CHECK:           %[[LOG_PLUS_ONE_0:.*]] = stablehlo.log_plus_one %[[MULTIPLY_16]] : tensor<f32>
// CHECK:           %[[MULTIPLY_17:.*]] = stablehlo.multiply %[[CONSTANT_3]], %[[LOG_PLUS_ONE_0]] : tensor<f32>
// CHECK:           %[[ADD_12:.*]] = stablehlo.add %[[ADD_11]], %[[MULTIPLY_17]] : tensor<f32>
// CHECK:           %[[CONSTANT_11:.*]] = stablehlo.constant dense<1.17549435E-38> : tensor<f32>
// CHECK:           %[[SQRT_5:.*]] = stablehlo.sqrt %[[CONSTANT_11]] : tensor<f32>
// CHECK:           %[[CONSTANT_12:.*]] = stablehlo.constant dense<4.000000e+00> : tensor<f32>
// CHECK:           %[[MULTIPLY_18:.*]] = stablehlo.multiply %[[SQRT_5]], %[[CONSTANT_12]] : tensor<f32>
// CHECK:           %[[COMPARE_12:.*]] = stablehlo.compare  LT, %[[ABS_1]], %[[MULTIPLY_18]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[COMPARE_13:.*]] = stablehlo.compare  LT, %[[ABS_0]], %[[CONSTANT_2]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[AND_3:.*]] = stablehlo.and %[[COMPARE_12]], %[[COMPARE_13]] : tensor<i1>
// CHECK:           %[[MULTIPLY_19:.*]] = stablehlo.multiply %[[ADD_0]], %[[SUBTRACT_0]] : tensor<f32>
// CHECK:           %[[ADD_13:.*]] = stablehlo.add %[[MULTIPLY_8]], %[[CONSTANT_2]] : tensor<f32>
// CHECK:           %[[DIVIDE_9:.*]] = stablehlo.divide %[[MULTIPLY_19]], %[[ADD_13]] : tensor<f32>
// CHECK:           %[[NEGATE_0:.*]] = stablehlo.negate %[[DIVIDE_9]] : tensor<f32>
// CHECK:           %[[COMPARE_14:.*]] = stablehlo.compare  GE, %[[ABS_0]], %[[CONSTANT_2]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[MULTIPLY_20:.*]] = stablehlo.multiply %[[CONSTANT_3]], %[[MULTIPLY_10]] : tensor<f32>
// CHECK:           %[[DIVIDE_10:.*]] = stablehlo.divide %[[MULTIPLY_20]], %[[ADD_7]] : tensor<f32>
// CHECK:           %[[MULTIPLY_21:.*]] = stablehlo.multiply %[[CONSTANT_3]], %[[ADD_9]] : tensor<f32>
// CHECK:           %[[ADD_14:.*]] = stablehlo.add %[[DIVIDE_10]], %[[MULTIPLY_21]] : tensor<f32>
// CHECK:           %[[CONSTANT_13:.*]] = stablehlo.constant dense<1.500000e+00> : tensor<f32>
// CHECK:           %[[COMPARE_15:.*]] = stablehlo.compare  LE, %[[MULTIPLY_8]], %[[CONSTANT_13]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[DIVIDE_11:.*]] = stablehlo.divide %[[MULTIPLY_20]], %[[SUBTRACT_1]] : tensor<f32>
// CHECK:           %[[ADD_15:.*]] = stablehlo.add %[[DIVIDE_10]], %[[DIVIDE_11]] : tensor<f32>
// CHECK:           %[[SUBTRACT_2:.*]] = stablehlo.subtract %[[MULTIPLY_8]], %[[CONSTANT_2]] : tensor<f32>
// CHECK:           %[[SELECT_10:.*]] = stablehlo.select %[[COMPARE_15]], %[[ADD_15]], %[[SUBTRACT_2]] : tensor<i1>, tensor<f32>
// CHECK:           %[[SELECT_11:.*]] = stablehlo.select %[[COMPARE_14]], %[[ADD_14]], %[[SELECT_10]] : tensor<i1>, tensor<f32>
// CHECK:           %[[SELECT_12:.*]] = stablehlo.select %[[AND_3]], %[[NEGATE_0]], %[[SELECT_11]] : tensor<i1>, tensor<f32>
// CHECK:           %[[MULTIPLY_22:.*]] = stablehlo.multiply %[[SELECT_12]], %[[ADD_13]] : tensor<f32>
// CHECK:           %[[SQRT_6:.*]] = stablehlo.sqrt %[[MULTIPLY_22]] : tensor<f32>
// CHECK:           %[[DIVIDE_12:.*]] = stablehlo.divide %[[ABS_1]], %[[SQRT_6]] : tensor<f32>
// CHECK:           %[[ADD_16:.*]] = stablehlo.add %[[SELECT_12]], %[[SQRT_6]] : tensor<f32>
// CHECK:           %[[LOG_PLUS_ONE_1:.*]] = stablehlo.log_plus_one %[[ADD_16]] : tensor<f32>
// CHECK:           %[[SELECT_13:.*]] = stablehlo.select %[[AND_3]], %[[DIVIDE_12]], %[[LOG_PLUS_ONE_1]] : tensor<i1>, tensor<f32>
// CHECK:           %[[SELECT_14:.*]] = stablehlo.select %[[COMPARE_10]], %[[ADD_12]], %[[SELECT_13]] : tensor<i1>, tensor<f32>
// CHECK:           %[[COMPLEX_0:.*]] = stablehlo.complex %[[SELECT_5]], %[[SELECT_14]] : tensor<complex<f32>>
// CHECK:           %[[IMAG_1:.*]] = stablehlo.imag %[[COMPLEX_0]] : (tensor<complex<f32>>) -> tensor<f32>
// CHECK:           %[[IMAG_2:.*]] = stablehlo.imag %[[ARG0]] : (tensor<complex<f32>>) -> tensor<f32>
// CHECK:           %[[CONSTANT_14:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<f32>
// CHECK:           %[[COMPARE_16:.*]] = stablehlo.compare  LT, %[[IMAG_2]], %[[CONSTANT_14]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[REAL_1:.*]] = stablehlo.real %[[COMPLEX_0]] : (tensor<complex<f32>>) -> tensor<f32>
// CHECK:           %[[REAL_2:.*]] = stablehlo.real %[[ARG0]] : (tensor<complex<f32>>) -> tensor<f32>
// CHECK:           %[[VAL_0:.*]] = stablehlo.atan2 %[[REAL_1]], %[[REAL_2]] : tensor<f32>
// CHECK:           %[[NEGATE_1:.*]] = stablehlo.negate %[[VAL_0]] : tensor<f32>
// CHECK:           %[[SELECT_15:.*]] = stablehlo.select %[[COMPARE_16]], %[[NEGATE_1]], %[[VAL_0]] : tensor<i1>, tensor<f32>
// CHECK:           %[[COMPLEX_1:.*]] = stablehlo.complex %[[IMAG_1]], %[[SELECT_15]] : tensor<complex<f32>>
// CHECK:           return %[[COMPLEX_1]] : tensor<complex<f32>>
// CHECK:         }
func.func @acosh_complex_f32(%arg : tensor<complex<f32>>) -> tensor<complex<f32>> {
  %result = "chlo.acosh"(%arg) : (tensor<complex<f32>>) -> tensor<complex<f32>>
  func.return %result : tensor<complex<f32>>
}

// -----

// CHECK-LABEL:   func.func @erfc_f64(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<f64>) -> tensor<f64> {
// CHECK:           %[[MULTIPLY_0:.*]] = stablehlo.multiply %[[ARG0]], %[[ARG0]] : tensor<f64>
// CHECK:           %[[NEGATE_0:.*]] = stablehlo.negate %[[MULTIPLY_0]] : tensor<f64>
// CHECK:           %[[EXPONENTIAL_0:.*]] = stablehlo.exponential %[[NEGATE_0]] : tensor<f64>
// CHECK:           %[[ABS_0:.*]] = stablehlo.abs %[[ARG0]] : tensor<f64>
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<2.4619698147353052E-10> : tensor<f64>
// CHECK:           %[[MULTIPLY_1:.*]] = stablehlo.multiply %[[CONSTANT_0]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_1:.*]] = stablehlo.constant dense<0.56418956483106886> : tensor<f64>
// CHECK:           %[[ADD_0:.*]] = stablehlo.add %[[MULTIPLY_1]], %[[CONSTANT_1]] : tensor<f64>
// CHECK:           %[[MULTIPLY_2:.*]] = stablehlo.multiply %[[ADD_0]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_2:.*]] = stablehlo.constant dense<7.4632105644226989> : tensor<f64>
// CHECK:           %[[ADD_1:.*]] = stablehlo.add %[[MULTIPLY_2]], %[[CONSTANT_2]] : tensor<f64>
// CHECK:           %[[MULTIPLY_3:.*]] = stablehlo.multiply %[[ADD_1]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_3:.*]] = stablehlo.constant dense<48.637197098568137> : tensor<f64>
// CHECK:           %[[ADD_2:.*]] = stablehlo.add %[[MULTIPLY_3]], %[[CONSTANT_3]] : tensor<f64>
// CHECK:           %[[MULTIPLY_4:.*]] = stablehlo.multiply %[[ADD_2]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_4:.*]] = stablehlo.constant dense<196.5208329560771> : tensor<f64>
// CHECK:           %[[ADD_3:.*]] = stablehlo.add %[[MULTIPLY_4]], %[[CONSTANT_4]] : tensor<f64>
// CHECK:           %[[MULTIPLY_5:.*]] = stablehlo.multiply %[[ADD_3]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_5:.*]] = stablehlo.constant dense<526.44519499547732> : tensor<f64>
// CHECK:           %[[ADD_4:.*]] = stablehlo.add %[[MULTIPLY_5]], %[[CONSTANT_5]] : tensor<f64>
// CHECK:           %[[MULTIPLY_6:.*]] = stablehlo.multiply %[[ADD_4]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_6:.*]] = stablehlo.constant dense<934.52852717195765> : tensor<f64>
// CHECK:           %[[ADD_5:.*]] = stablehlo.add %[[MULTIPLY_6]], %[[CONSTANT_6]] : tensor<f64>
// CHECK:           %[[MULTIPLY_7:.*]] = stablehlo.multiply %[[ADD_5]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_7:.*]] = stablehlo.constant dense<1027.5518868951572> : tensor<f64>
// CHECK:           %[[ADD_6:.*]] = stablehlo.add %[[MULTIPLY_7]], %[[CONSTANT_7]] : tensor<f64>
// CHECK:           %[[MULTIPLY_8:.*]] = stablehlo.multiply %[[ADD_6]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_8:.*]] = stablehlo.constant dense<557.53533536939938> : tensor<f64>
// CHECK:           %[[ADD_7:.*]] = stablehlo.add %[[MULTIPLY_8]], %[[CONSTANT_8]] : tensor<f64>
// CHECK:           %[[MULTIPLY_9:.*]] = stablehlo.multiply %[[EXPONENTIAL_0]], %[[ADD_7]] : tensor<f64>
// CHECK:           %[[CONSTANT_9:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f64>
// CHECK:           %[[MULTIPLY_10:.*]] = stablehlo.multiply %[[CONSTANT_9]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_10:.*]] = stablehlo.constant dense<13.228195115474499> : tensor<f64>
// CHECK:           %[[ADD_8:.*]] = stablehlo.add %[[MULTIPLY_10]], %[[CONSTANT_10]] : tensor<f64>
// CHECK:           %[[MULTIPLY_11:.*]] = stablehlo.multiply %[[ADD_8]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_11:.*]] = stablehlo.constant dense<86.707214088598973> : tensor<f64>
// CHECK:           %[[ADD_9:.*]] = stablehlo.add %[[MULTIPLY_11]], %[[CONSTANT_11]] : tensor<f64>
// CHECK:           %[[MULTIPLY_12:.*]] = stablehlo.multiply %[[ADD_9]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_12:.*]] = stablehlo.constant dense<354.93777888781989> : tensor<f64>
// CHECK:           %[[ADD_10:.*]] = stablehlo.add %[[MULTIPLY_12]], %[[CONSTANT_12]] : tensor<f64>
// CHECK:           %[[MULTIPLY_13:.*]] = stablehlo.multiply %[[ADD_10]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_13:.*]] = stablehlo.constant dense<975.70850174320549> : tensor<f64>
// CHECK:           %[[ADD_11:.*]] = stablehlo.add %[[MULTIPLY_13]], %[[CONSTANT_13]] : tensor<f64>
// CHECK:           %[[MULTIPLY_14:.*]] = stablehlo.multiply %[[ADD_11]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_14:.*]] = stablehlo.constant dense<1823.9091668790973> : tensor<f64>
// CHECK:           %[[ADD_12:.*]] = stablehlo.add %[[MULTIPLY_14]], %[[CONSTANT_14]] : tensor<f64>
// CHECK:           %[[MULTIPLY_15:.*]] = stablehlo.multiply %[[ADD_12]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_15:.*]] = stablehlo.constant dense<2246.3376081871097> : tensor<f64>
// CHECK:           %[[ADD_13:.*]] = stablehlo.add %[[MULTIPLY_15]], %[[CONSTANT_15]] : tensor<f64>
// CHECK:           %[[MULTIPLY_16:.*]] = stablehlo.multiply %[[ADD_13]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_16:.*]] = stablehlo.constant dense<1656.6630919416134> : tensor<f64>
// CHECK:           %[[ADD_14:.*]] = stablehlo.add %[[MULTIPLY_16]], %[[CONSTANT_16]] : tensor<f64>
// CHECK:           %[[MULTIPLY_17:.*]] = stablehlo.multiply %[[ADD_14]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_17:.*]] = stablehlo.constant dense<557.53534081772773> : tensor<f64>
// CHECK:           %[[ADD_15:.*]] = stablehlo.add %[[MULTIPLY_17]], %[[CONSTANT_17]] : tensor<f64>
// CHECK:           %[[DIVIDE_0:.*]] = stablehlo.divide %[[MULTIPLY_9]], %[[ADD_15]] : tensor<f64>
// CHECK:           %[[CONSTANT_18:.*]] = stablehlo.constant dense<0.56418958354775506> : tensor<f64>
// CHECK:           %[[MULTIPLY_18:.*]] = stablehlo.multiply %[[CONSTANT_18]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_19:.*]] = stablehlo.constant dense<1.275366707599781> : tensor<f64>
// CHECK:           %[[ADD_16:.*]] = stablehlo.add %[[MULTIPLY_18]], %[[CONSTANT_19]] : tensor<f64>
// CHECK:           %[[MULTIPLY_19:.*]] = stablehlo.multiply %[[ADD_16]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_20:.*]] = stablehlo.constant dense<5.0190504225118051> : tensor<f64>
// CHECK:           %[[ADD_17:.*]] = stablehlo.add %[[MULTIPLY_19]], %[[CONSTANT_20]] : tensor<f64>
// CHECK:           %[[MULTIPLY_20:.*]] = stablehlo.multiply %[[ADD_17]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_21:.*]] = stablehlo.constant dense<6.160210979930536> : tensor<f64>
// CHECK:           %[[ADD_18:.*]] = stablehlo.add %[[MULTIPLY_20]], %[[CONSTANT_21]] : tensor<f64>
// CHECK:           %[[MULTIPLY_21:.*]] = stablehlo.multiply %[[ADD_18]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_22:.*]] = stablehlo.constant dense<7.4097426995044895> : tensor<f64>
// CHECK:           %[[ADD_19:.*]] = stablehlo.add %[[MULTIPLY_21]], %[[CONSTANT_22]] : tensor<f64>
// CHECK:           %[[MULTIPLY_22:.*]] = stablehlo.multiply %[[ADD_19]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_23:.*]] = stablehlo.constant dense<2.9788666537210022> : tensor<f64>
// CHECK:           %[[ADD_20:.*]] = stablehlo.add %[[MULTIPLY_22]], %[[CONSTANT_23]] : tensor<f64>
// CHECK:           %[[MULTIPLY_23:.*]] = stablehlo.multiply %[[EXPONENTIAL_0]], %[[ADD_20]] : tensor<f64>
// CHECK:           %[[CONSTANT_24:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f64>
// CHECK:           %[[MULTIPLY_24:.*]] = stablehlo.multiply %[[CONSTANT_24]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_25:.*]] = stablehlo.constant dense<2.2605286322011726> : tensor<f64>
// CHECK:           %[[ADD_21:.*]] = stablehlo.add %[[MULTIPLY_24]], %[[CONSTANT_25]] : tensor<f64>
// CHECK:           %[[MULTIPLY_25:.*]] = stablehlo.multiply %[[ADD_21]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_26:.*]] = stablehlo.constant dense<9.3960352493800147> : tensor<f64>
// CHECK:           %[[ADD_22:.*]] = stablehlo.add %[[MULTIPLY_25]], %[[CONSTANT_26]] : tensor<f64>
// CHECK:           %[[MULTIPLY_26:.*]] = stablehlo.multiply %[[ADD_22]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_27:.*]] = stablehlo.constant dense<12.048953980809666> : tensor<f64>
// CHECK:           %[[ADD_23:.*]] = stablehlo.add %[[MULTIPLY_26]], %[[CONSTANT_27]] : tensor<f64>
// CHECK:           %[[MULTIPLY_27:.*]] = stablehlo.multiply %[[ADD_23]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_28:.*]] = stablehlo.constant dense<17.081445074756591> : tensor<f64>
// CHECK:           %[[ADD_24:.*]] = stablehlo.add %[[MULTIPLY_27]], %[[CONSTANT_28]] : tensor<f64>
// CHECK:           %[[MULTIPLY_28:.*]] = stablehlo.multiply %[[ADD_24]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_29:.*]] = stablehlo.constant dense<9.6089680906328585> : tensor<f64>
// CHECK:           %[[ADD_25:.*]] = stablehlo.add %[[MULTIPLY_28]], %[[CONSTANT_29]] : tensor<f64>
// CHECK:           %[[MULTIPLY_29:.*]] = stablehlo.multiply %[[ADD_25]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_30:.*]] = stablehlo.constant dense<3.3690764510008151> : tensor<f64>
// CHECK:           %[[ADD_26:.*]] = stablehlo.add %[[MULTIPLY_29]], %[[CONSTANT_30]] : tensor<f64>
// CHECK:           %[[DIVIDE_1:.*]] = stablehlo.divide %[[MULTIPLY_23]], %[[ADD_26]] : tensor<f64>
// CHECK:           %[[CONSTANT_31:.*]] = stablehlo.constant dense<8.000000e+00> : tensor<f64>
// CHECK:           %[[COMPARE_0:.*]] = stablehlo.compare  LT, %[[ABS_0]], %[[CONSTANT_31]] : (tensor<f64>, tensor<f64>) -> tensor<i1>
// CHECK:           %[[SELECT_0:.*]] = stablehlo.select %[[COMPARE_0]], %[[DIVIDE_0]], %[[DIVIDE_1]] : tensor<i1>, tensor<f64>
// CHECK:           %[[CONSTANT_32:.*]] = stablehlo.constant dense<-709.78271289338397> : tensor<f64>
// CHECK:           %[[COMPARE_1:.*]] = stablehlo.compare  LT, %[[NEGATE_0]], %[[CONSTANT_32]] : (tensor<f64>, tensor<f64>) -> tensor<i1>
// CHECK:           %[[CONSTANT_33:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<f64>
// CHECK:           %[[SELECT_1:.*]] = stablehlo.select %[[COMPARE_1]], %[[CONSTANT_33]], %[[SELECT_0]] : tensor<i1>, tensor<f64>
// CHECK:           %[[COMPARE_2:.*]] = stablehlo.compare  LT, %[[ARG0]], %[[CONSTANT_33]] : (tensor<f64>, tensor<f64>) -> tensor<i1>
// CHECK:           %[[CONSTANT_34:.*]] = stablehlo.constant dense<2.000000e+00> : tensor<f64>
// CHECK:           %[[SUBTRACT_0:.*]] = stablehlo.subtract %[[CONSTANT_34]], %[[SELECT_1]] : tensor<f64>
// CHECK:           %[[SELECT_2:.*]] = stablehlo.select %[[COMPARE_2]], %[[SUBTRACT_0]], %[[SELECT_1]] : tensor<i1>, tensor<f64>
// CHECK:           %[[CONSTANT_35:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f64>
// CHECK:           %[[MULTIPLY_30:.*]] = stablehlo.multiply %[[ARG0]], %[[ARG0]] : tensor<f64>
// CHECK:           %[[CONSTANT_36:.*]] = stablehlo.constant dense<9.6049737398705161> : tensor<f64>
// CHECK:           %[[MULTIPLY_31:.*]] = stablehlo.multiply %[[CONSTANT_36]], %[[MULTIPLY_30]] : tensor<f64>
// CHECK:           %[[CONSTANT_37:.*]] = stablehlo.constant dense<90.026019720384269> : tensor<f64>
// CHECK:           %[[ADD_27:.*]] = stablehlo.add %[[MULTIPLY_31]], %[[CONSTANT_37]] : tensor<f64>
// CHECK:           %[[MULTIPLY_32:.*]] = stablehlo.multiply %[[ADD_27]], %[[MULTIPLY_30]] : tensor<f64>
// CHECK:           %[[CONSTANT_38:.*]] = stablehlo.constant dense<2232.0053459468431> : tensor<f64>
// CHECK:           %[[ADD_28:.*]] = stablehlo.add %[[MULTIPLY_32]], %[[CONSTANT_38]] : tensor<f64>
// CHECK:           %[[MULTIPLY_33:.*]] = stablehlo.multiply %[[ADD_28]], %[[MULTIPLY_30]] : tensor<f64>
// CHECK:           %[[CONSTANT_39:.*]] = stablehlo.constant dense<7003.3251411280507> : tensor<f64>
// CHECK:           %[[ADD_29:.*]] = stablehlo.add %[[MULTIPLY_33]], %[[CONSTANT_39]] : tensor<f64>
// CHECK:           %[[MULTIPLY_34:.*]] = stablehlo.multiply %[[ADD_29]], %[[MULTIPLY_30]] : tensor<f64>
// CHECK:           %[[CONSTANT_40:.*]] = stablehlo.constant dense<55592.301301039493> : tensor<f64>
// CHECK:           %[[ADD_30:.*]] = stablehlo.add %[[MULTIPLY_34]], %[[CONSTANT_40]] : tensor<f64>
// CHECK:           %[[MULTIPLY_35:.*]] = stablehlo.multiply %[[ARG0]], %[[ADD_30]] : tensor<f64>
// CHECK:           %[[CONSTANT_41:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f64>
// CHECK:           %[[MULTIPLY_36:.*]] = stablehlo.multiply %[[CONSTANT_41]], %[[MULTIPLY_30]] : tensor<f64>
// CHECK:           %[[CONSTANT_42:.*]] = stablehlo.constant dense<33.561714164750313> : tensor<f64>
// CHECK:           %[[ADD_31:.*]] = stablehlo.add %[[MULTIPLY_36]], %[[CONSTANT_42]] : tensor<f64>
// CHECK:           %[[MULTIPLY_37:.*]] = stablehlo.multiply %[[ADD_31]], %[[MULTIPLY_30]] : tensor<f64>
// CHECK:           %[[CONSTANT_43:.*]] = stablehlo.constant dense<521.35794978015269> : tensor<f64>
// CHECK:           %[[ADD_32:.*]] = stablehlo.add %[[MULTIPLY_37]], %[[CONSTANT_43]] : tensor<f64>
// CHECK:           %[[MULTIPLY_38:.*]] = stablehlo.multiply %[[ADD_32]], %[[MULTIPLY_30]] : tensor<f64>
// CHECK:           %[[CONSTANT_44:.*]] = stablehlo.constant dense<4594.3238297098014> : tensor<f64>
// CHECK:           %[[ADD_33:.*]] = stablehlo.add %[[MULTIPLY_38]], %[[CONSTANT_44]] : tensor<f64>
// CHECK:           %[[MULTIPLY_39:.*]] = stablehlo.multiply %[[ADD_33]], %[[MULTIPLY_30]] : tensor<f64>
// CHECK:           %[[CONSTANT_45:.*]] = stablehlo.constant dense<22629.000061389095> : tensor<f64>
// CHECK:           %[[ADD_34:.*]] = stablehlo.add %[[MULTIPLY_39]], %[[CONSTANT_45]] : tensor<f64>
// CHECK:           %[[MULTIPLY_40:.*]] = stablehlo.multiply %[[ADD_34]], %[[MULTIPLY_30]] : tensor<f64>
// CHECK:           %[[CONSTANT_46:.*]] = stablehlo.constant dense<49267.394260863592> : tensor<f64>
// CHECK:           %[[ADD_35:.*]] = stablehlo.add %[[MULTIPLY_40]], %[[CONSTANT_46]] : tensor<f64>
// CHECK:           %[[DIVIDE_2:.*]] = stablehlo.divide %[[MULTIPLY_35]], %[[ADD_35]] : tensor<f64>
// CHECK:           %[[SUBTRACT_1:.*]] = stablehlo.subtract %[[CONSTANT_35]], %[[DIVIDE_2]] : tensor<f64>
// CHECK:           %[[ABS_1:.*]] = stablehlo.abs %[[ARG0]] : tensor<f64>
// CHECK:           %[[COMPARE_3:.*]] = stablehlo.compare  LT, %[[ABS_1]], %[[CONSTANT_35]] : (tensor<f64>, tensor<f64>) -> tensor<i1>
// CHECK:           %[[SELECT_3:.*]] = stablehlo.select %[[COMPARE_3]], %[[SUBTRACT_1]], %[[SELECT_2]] : tensor<i1>, tensor<f64>
// CHECK:           return %[[SELECT_3]] : tensor<f64>
// CHECK:         }
func.func @erfc_f64(%arg : tensor<f64>) -> tensor<f64> {
  %1 = "chlo.erfc"(%arg) : (tensor<f64>) -> tensor<f64>
  func.return %1 : tensor<f64>
}

// -----

// CHECK-LABEL:   func.func @erfc_f32(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<f32>) -> tensor<f32> {
// CHECK:           %[[MULTIPLY_0:.*]] = stablehlo.multiply %[[ARG0]], %[[ARG0]] : tensor<f32>
// CHECK:           %[[NEGATE_0:.*]] = stablehlo.negate %[[MULTIPLY_0]] : tensor<f32>
// CHECK:           %[[ABS_0:.*]] = stablehlo.abs %[[ARG0]] : tensor<f32>
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[DIVIDE_0:.*]] = stablehlo.divide %[[CONSTANT_0]], %[[MULTIPLY_0]] : tensor<f32>
// CHECK:           %[[EXPONENTIAL_0:.*]] = stablehlo.exponential %[[NEGATE_0]] : tensor<f32>
// CHECK:           %[[DIVIDE_1:.*]] = stablehlo.divide %[[CONSTANT_0]], %[[ABS_0]] : tensor<f32>
// CHECK:           %[[MULTIPLY_1:.*]] = stablehlo.multiply %[[EXPONENTIAL_0]], %[[DIVIDE_1]] : tensor<f32>
// CHECK:           %[[CONSTANT_1:.*]] = stablehlo.constant dense<2.000000e+00> : tensor<f32>
// CHECK:           %[[COMPARE_0:.*]] = stablehlo.compare  LT, %[[ABS_0]], %[[CONSTANT_1]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[CONSTANT_2:.*]] = stablehlo.constant dense<2.326820e-02> : tensor<f32>
// CHECK:           %[[MULTIPLY_2:.*]] = stablehlo.multiply %[[CONSTANT_2]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_3:.*]] = stablehlo.constant dense<-0.138703942> : tensor<f32>
// CHECK:           %[[ADD_0:.*]] = stablehlo.add %[[MULTIPLY_2]], %[[CONSTANT_3]] : tensor<f32>
// CHECK:           %[[MULTIPLY_3:.*]] = stablehlo.multiply %[[ADD_0]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_4:.*]] = stablehlo.constant dense<0.368742466> : tensor<f32>
// CHECK:           %[[ADD_1:.*]] = stablehlo.add %[[MULTIPLY_3]], %[[CONSTANT_4]] : tensor<f32>
// CHECK:           %[[MULTIPLY_4:.*]] = stablehlo.multiply %[[ADD_1]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_5:.*]] = stablehlo.constant dense<-0.582473278> : tensor<f32>
// CHECK:           %[[ADD_2:.*]] = stablehlo.add %[[MULTIPLY_4]], %[[CONSTANT_5]] : tensor<f32>
// CHECK:           %[[MULTIPLY_5:.*]] = stablehlo.multiply %[[ADD_2]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_6:.*]] = stablehlo.constant dense<0.621000468> : tensor<f32>
// CHECK:           %[[ADD_3:.*]] = stablehlo.add %[[MULTIPLY_5]], %[[CONSTANT_6]] : tensor<f32>
// CHECK:           %[[MULTIPLY_6:.*]] = stablehlo.multiply %[[ADD_3]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_7:.*]] = stablehlo.constant dense<-0.494451523> : tensor<f32>
// CHECK:           %[[ADD_4:.*]] = stablehlo.add %[[MULTIPLY_6]], %[[CONSTANT_7]] : tensor<f32>
// CHECK:           %[[MULTIPLY_7:.*]] = stablehlo.multiply %[[ADD_4]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_8:.*]] = stablehlo.constant dense<3.404880e-01> : tensor<f32>
// CHECK:           %[[ADD_5:.*]] = stablehlo.add %[[MULTIPLY_7]], %[[CONSTANT_8]] : tensor<f32>
// CHECK:           %[[MULTIPLY_8:.*]] = stablehlo.multiply %[[ADD_5]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_9:.*]] = stablehlo.constant dense<-0.274112701> : tensor<f32>
// CHECK:           %[[ADD_6:.*]] = stablehlo.add %[[MULTIPLY_8]], %[[CONSTANT_9]] : tensor<f32>
// CHECK:           %[[MULTIPLY_9:.*]] = stablehlo.multiply %[[ADD_6]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_10:.*]] = stablehlo.constant dense<0.563825965> : tensor<f32>
// CHECK:           %[[ADD_7:.*]] = stablehlo.add %[[MULTIPLY_9]], %[[CONSTANT_10]] : tensor<f32>
// CHECK:           %[[CONSTANT_11:.*]] = stablehlo.constant dense<-10.477664> : tensor<f32>
// CHECK:           %[[MULTIPLY_10:.*]] = stablehlo.multiply %[[CONSTANT_11]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_12:.*]] = stablehlo.constant dense<1.297720e+01> : tensor<f32>
// CHECK:           %[[ADD_8:.*]] = stablehlo.add %[[MULTIPLY_10]], %[[CONSTANT_12]] : tensor<f32>
// CHECK:           %[[MULTIPLY_11:.*]] = stablehlo.multiply %[[ADD_8]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_13:.*]] = stablehlo.constant dense<-7.49551868> : tensor<f32>
// CHECK:           %[[ADD_9:.*]] = stablehlo.add %[[MULTIPLY_11]], %[[CONSTANT_13]] : tensor<f32>
// CHECK:           %[[MULTIPLY_12:.*]] = stablehlo.multiply %[[ADD_9]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_14:.*]] = stablehlo.constant dense<2.92101908> : tensor<f32>
// CHECK:           %[[ADD_10:.*]] = stablehlo.add %[[MULTIPLY_12]], %[[CONSTANT_14]] : tensor<f32>
// CHECK:           %[[MULTIPLY_13:.*]] = stablehlo.multiply %[[ADD_10]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_15:.*]] = stablehlo.constant dense<-1.01526523> : tensor<f32>
// CHECK:           %[[ADD_11:.*]] = stablehlo.add %[[MULTIPLY_13]], %[[CONSTANT_15]] : tensor<f32>
// CHECK:           %[[MULTIPLY_14:.*]] = stablehlo.multiply %[[ADD_11]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_16:.*]] = stablehlo.constant dense<0.42184633> : tensor<f32>
// CHECK:           %[[ADD_12:.*]] = stablehlo.add %[[MULTIPLY_14]], %[[CONSTANT_16]] : tensor<f32>
// CHECK:           %[[MULTIPLY_15:.*]] = stablehlo.multiply %[[ADD_12]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_17:.*]] = stablehlo.constant dense<-0.282076746> : tensor<f32>
// CHECK:           %[[ADD_13:.*]] = stablehlo.add %[[MULTIPLY_15]], %[[CONSTANT_17]] : tensor<f32>
// CHECK:           %[[MULTIPLY_16:.*]] = stablehlo.multiply %[[ADD_13]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_18:.*]] = stablehlo.constant dense<0.564189494> : tensor<f32>
// CHECK:           %[[ADD_14:.*]] = stablehlo.add %[[MULTIPLY_16]], %[[CONSTANT_18]] : tensor<f32>
// CHECK:           %[[SELECT_0:.*]] = stablehlo.select %[[COMPARE_0]], %[[ADD_7]], %[[ADD_14]] : tensor<i1>, tensor<f32>
// CHECK:           %[[MULTIPLY_17:.*]] = stablehlo.multiply %[[MULTIPLY_1]], %[[SELECT_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_19:.*]] = stablehlo.constant dense<-88.7228394> : tensor<f32>
// CHECK:           %[[COMPARE_1:.*]] = stablehlo.compare  LT, %[[NEGATE_0]], %[[CONSTANT_19]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[CONSTANT_20:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<f32>
// CHECK:           %[[SELECT_1:.*]] = stablehlo.select %[[COMPARE_1]], %[[CONSTANT_20]], %[[MULTIPLY_17]] : tensor<i1>, tensor<f32>
// CHECK:           %[[COMPARE_2:.*]] = stablehlo.compare  LT, %[[ARG0]], %[[CONSTANT_20]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[SUBTRACT_0:.*]] = stablehlo.subtract %[[CONSTANT_1]], %[[SELECT_1]] : tensor<f32>
// CHECK:           %[[SELECT_2:.*]] = stablehlo.select %[[COMPARE_2]], %[[SUBTRACT_0]], %[[SELECT_1]] : tensor<i1>, tensor<f32>
// CHECK:           %[[CONSTANT_21:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[MULTIPLY_18:.*]] = stablehlo.multiply %[[ARG0]], %[[ARG0]] : tensor<f32>
// CHECK:           %[[CONSTANT_22:.*]] = stablehlo.constant dense<7.85386146E-5> : tensor<f32>
// CHECK:           %[[MULTIPLY_19:.*]] = stablehlo.multiply %[[CONSTANT_22]], %[[MULTIPLY_18]] : tensor<f32>
// CHECK:           %[[CONSTANT_23:.*]] = stablehlo.constant dense<-8.0101937E-4> : tensor<f32>
// CHECK:           %[[ADD_15:.*]] = stablehlo.add %[[MULTIPLY_19]], %[[CONSTANT_23]] : tensor<f32>
// CHECK:           %[[MULTIPLY_20:.*]] = stablehlo.multiply %[[ADD_15]], %[[MULTIPLY_18]] : tensor<f32>
// CHECK:           %[[CONSTANT_24:.*]] = stablehlo.constant dense<0.00518832775> : tensor<f32>
// CHECK:           %[[ADD_16:.*]] = stablehlo.add %[[MULTIPLY_20]], %[[CONSTANT_24]] : tensor<f32>
// CHECK:           %[[MULTIPLY_21:.*]] = stablehlo.multiply %[[ADD_16]], %[[MULTIPLY_18]] : tensor<f32>
// CHECK:           %[[CONSTANT_25:.*]] = stablehlo.constant dense<-0.0268538129> : tensor<f32>
// CHECK:           %[[ADD_17:.*]] = stablehlo.add %[[MULTIPLY_21]], %[[CONSTANT_25]] : tensor<f32>
// CHECK:           %[[MULTIPLY_22:.*]] = stablehlo.multiply %[[ADD_17]], %[[MULTIPLY_18]] : tensor<f32>
// CHECK:           %[[CONSTANT_26:.*]] = stablehlo.constant dense<0.112835854> : tensor<f32>
// CHECK:           %[[ADD_18:.*]] = stablehlo.add %[[MULTIPLY_22]], %[[CONSTANT_26]] : tensor<f32>
// CHECK:           %[[MULTIPLY_23:.*]] = stablehlo.multiply %[[ADD_18]], %[[MULTIPLY_18]] : tensor<f32>
// CHECK:           %[[CONSTANT_27:.*]] = stablehlo.constant dense<-0.37612626> : tensor<f32>
// CHECK:           %[[ADD_19:.*]] = stablehlo.add %[[MULTIPLY_23]], %[[CONSTANT_27]] : tensor<f32>
// CHECK:           %[[MULTIPLY_24:.*]] = stablehlo.multiply %[[ADD_19]], %[[MULTIPLY_18]] : tensor<f32>
// CHECK:           %[[CONSTANT_28:.*]] = stablehlo.constant dense<1.12837911> : tensor<f32>
// CHECK:           %[[ADD_20:.*]] = stablehlo.add %[[MULTIPLY_24]], %[[CONSTANT_28]] : tensor<f32>
// CHECK:           %[[MULTIPLY_25:.*]] = stablehlo.multiply %[[ARG0]], %[[ADD_20]] : tensor<f32>
// CHECK:           %[[SUBTRACT_1:.*]] = stablehlo.subtract %[[CONSTANT_21]], %[[MULTIPLY_25]] : tensor<f32>
// CHECK:           %[[ABS_1:.*]] = stablehlo.abs %[[ARG0]] : tensor<f32>
// CHECK:           %[[COMPARE_3:.*]] = stablehlo.compare  LT, %[[ABS_1]], %[[CONSTANT_21]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[SELECT_3:.*]] = stablehlo.select %[[COMPARE_3]], %[[SUBTRACT_1]], %[[SELECT_2]] : tensor<i1>, tensor<f32>
// CHECK:           return %[[SELECT_3]] : tensor<f32>
// CHECK:         }
func.func @erfc_f32(%arg : tensor<f32>) -> tensor<f32> {
  %1 = "chlo.erfc"(%arg) : (tensor<f32>) -> tensor<f32>
  func.return %1 : tensor<f32>
}

// -----

// CHECK-LABEL:   func.func @erfc_f16(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<f16>) -> tensor<f16> {
// CHECK:           %[[CONVERT_0:.*]] = stablehlo.convert %[[ARG0]] : (tensor<f16>) -> tensor<f32>
// CHECK:           %[[MULTIPLY_0:.*]] = stablehlo.multiply %[[CONVERT_0]], %[[CONVERT_0]] : tensor<f32>
// CHECK:           %[[NEGATE_0:.*]] = stablehlo.negate %[[MULTIPLY_0]] : tensor<f32>
// CHECK:           %[[ABS_0:.*]] = stablehlo.abs %[[CONVERT_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[DIVIDE_0:.*]] = stablehlo.divide %[[CONSTANT_0]], %[[MULTIPLY_0]] : tensor<f32>
// CHECK:           %[[EXPONENTIAL_0:.*]] = stablehlo.exponential %[[NEGATE_0]] : tensor<f32>
// CHECK:           %[[DIVIDE_1:.*]] = stablehlo.divide %[[CONSTANT_0]], %[[ABS_0]] : tensor<f32>
// CHECK:           %[[MULTIPLY_1:.*]] = stablehlo.multiply %[[EXPONENTIAL_0]], %[[DIVIDE_1]] : tensor<f32>
// CHECK:           %[[CONSTANT_1:.*]] = stablehlo.constant dense<2.000000e+00> : tensor<f32>
// CHECK:           %[[COMPARE_0:.*]] = stablehlo.compare  LT, %[[ABS_0]], %[[CONSTANT_1]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[CONSTANT_2:.*]] = stablehlo.constant dense<2.326820e-02> : tensor<f32>
// CHECK:           %[[MULTIPLY_2:.*]] = stablehlo.multiply %[[CONSTANT_2]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_3:.*]] = stablehlo.constant dense<-0.138703942> : tensor<f32>
// CHECK:           %[[ADD_0:.*]] = stablehlo.add %[[MULTIPLY_2]], %[[CONSTANT_3]] : tensor<f32>
// CHECK:           %[[MULTIPLY_3:.*]] = stablehlo.multiply %[[ADD_0]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_4:.*]] = stablehlo.constant dense<0.368742466> : tensor<f32>
// CHECK:           %[[ADD_1:.*]] = stablehlo.add %[[MULTIPLY_3]], %[[CONSTANT_4]] : tensor<f32>
// CHECK:           %[[MULTIPLY_4:.*]] = stablehlo.multiply %[[ADD_1]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_5:.*]] = stablehlo.constant dense<-0.582473278> : tensor<f32>
// CHECK:           %[[ADD_2:.*]] = stablehlo.add %[[MULTIPLY_4]], %[[CONSTANT_5]] : tensor<f32>
// CHECK:           %[[MULTIPLY_5:.*]] = stablehlo.multiply %[[ADD_2]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_6:.*]] = stablehlo.constant dense<0.621000468> : tensor<f32>
// CHECK:           %[[ADD_3:.*]] = stablehlo.add %[[MULTIPLY_5]], %[[CONSTANT_6]] : tensor<f32>
// CHECK:           %[[MULTIPLY_6:.*]] = stablehlo.multiply %[[ADD_3]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_7:.*]] = stablehlo.constant dense<-0.494451523> : tensor<f32>
// CHECK:           %[[ADD_4:.*]] = stablehlo.add %[[MULTIPLY_6]], %[[CONSTANT_7]] : tensor<f32>
// CHECK:           %[[MULTIPLY_7:.*]] = stablehlo.multiply %[[ADD_4]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_8:.*]] = stablehlo.constant dense<3.404880e-01> : tensor<f32>
// CHECK:           %[[ADD_5:.*]] = stablehlo.add %[[MULTIPLY_7]], %[[CONSTANT_8]] : tensor<f32>
// CHECK:           %[[MULTIPLY_8:.*]] = stablehlo.multiply %[[ADD_5]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_9:.*]] = stablehlo.constant dense<-0.274112701> : tensor<f32>
// CHECK:           %[[ADD_6:.*]] = stablehlo.add %[[MULTIPLY_8]], %[[CONSTANT_9]] : tensor<f32>
// CHECK:           %[[MULTIPLY_9:.*]] = stablehlo.multiply %[[ADD_6]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_10:.*]] = stablehlo.constant dense<0.563825965> : tensor<f32>
// CHECK:           %[[ADD_7:.*]] = stablehlo.add %[[MULTIPLY_9]], %[[CONSTANT_10]] : tensor<f32>
// CHECK:           %[[CONSTANT_11:.*]] = stablehlo.constant dense<-10.477664> : tensor<f32>
// CHECK:           %[[MULTIPLY_10:.*]] = stablehlo.multiply %[[CONSTANT_11]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_12:.*]] = stablehlo.constant dense<1.297720e+01> : tensor<f32>
// CHECK:           %[[ADD_8:.*]] = stablehlo.add %[[MULTIPLY_10]], %[[CONSTANT_12]] : tensor<f32>
// CHECK:           %[[MULTIPLY_11:.*]] = stablehlo.multiply %[[ADD_8]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_13:.*]] = stablehlo.constant dense<-7.49551868> : tensor<f32>
// CHECK:           %[[ADD_9:.*]] = stablehlo.add %[[MULTIPLY_11]], %[[CONSTANT_13]] : tensor<f32>
// CHECK:           %[[MULTIPLY_12:.*]] = stablehlo.multiply %[[ADD_9]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_14:.*]] = stablehlo.constant dense<2.92101908> : tensor<f32>
// CHECK:           %[[ADD_10:.*]] = stablehlo.add %[[MULTIPLY_12]], %[[CONSTANT_14]] : tensor<f32>
// CHECK:           %[[MULTIPLY_13:.*]] = stablehlo.multiply %[[ADD_10]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_15:.*]] = stablehlo.constant dense<-1.01526523> : tensor<f32>
// CHECK:           %[[ADD_11:.*]] = stablehlo.add %[[MULTIPLY_13]], %[[CONSTANT_15]] : tensor<f32>
// CHECK:           %[[MULTIPLY_14:.*]] = stablehlo.multiply %[[ADD_11]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_16:.*]] = stablehlo.constant dense<0.42184633> : tensor<f32>
// CHECK:           %[[ADD_12:.*]] = stablehlo.add %[[MULTIPLY_14]], %[[CONSTANT_16]] : tensor<f32>
// CHECK:           %[[MULTIPLY_15:.*]] = stablehlo.multiply %[[ADD_12]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_17:.*]] = stablehlo.constant dense<-0.282076746> : tensor<f32>
// CHECK:           %[[ADD_13:.*]] = stablehlo.add %[[MULTIPLY_15]], %[[CONSTANT_17]] : tensor<f32>
// CHECK:           %[[MULTIPLY_16:.*]] = stablehlo.multiply %[[ADD_13]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_18:.*]] = stablehlo.constant dense<0.564189494> : tensor<f32>
// CHECK:           %[[ADD_14:.*]] = stablehlo.add %[[MULTIPLY_16]], %[[CONSTANT_18]] : tensor<f32>
// CHECK:           %[[SELECT_0:.*]] = stablehlo.select %[[COMPARE_0]], %[[ADD_7]], %[[ADD_14]] : tensor<i1>, tensor<f32>
// CHECK:           %[[MULTIPLY_17:.*]] = stablehlo.multiply %[[MULTIPLY_1]], %[[SELECT_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_19:.*]] = stablehlo.constant dense<-88.7228394> : tensor<f32>
// CHECK:           %[[COMPARE_1:.*]] = stablehlo.compare  LT, %[[NEGATE_0]], %[[CONSTANT_19]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[CONSTANT_20:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<f32>
// CHECK:           %[[SELECT_1:.*]] = stablehlo.select %[[COMPARE_1]], %[[CONSTANT_20]], %[[MULTIPLY_17]] : tensor<i1>, tensor<f32>
// CHECK:           %[[COMPARE_2:.*]] = stablehlo.compare  LT, %[[CONVERT_0]], %[[CONSTANT_20]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[SUBTRACT_0:.*]] = stablehlo.subtract %[[CONSTANT_1]], %[[SELECT_1]] : tensor<f32>
// CHECK:           %[[SELECT_2:.*]] = stablehlo.select %[[COMPARE_2]], %[[SUBTRACT_0]], %[[SELECT_1]] : tensor<i1>, tensor<f32>
// CHECK:           %[[CONSTANT_21:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[MULTIPLY_18:.*]] = stablehlo.multiply %[[CONVERT_0]], %[[CONVERT_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_22:.*]] = stablehlo.constant dense<7.85386146E-5> : tensor<f32>
// CHECK:           %[[MULTIPLY_19:.*]] = stablehlo.multiply %[[CONSTANT_22]], %[[MULTIPLY_18]] : tensor<f32>
// CHECK:           %[[CONSTANT_23:.*]] = stablehlo.constant dense<-8.0101937E-4> : tensor<f32>
// CHECK:           %[[ADD_15:.*]] = stablehlo.add %[[MULTIPLY_19]], %[[CONSTANT_23]] : tensor<f32>
// CHECK:           %[[MULTIPLY_20:.*]] = stablehlo.multiply %[[ADD_15]], %[[MULTIPLY_18]] : tensor<f32>
// CHECK:           %[[CONSTANT_24:.*]] = stablehlo.constant dense<0.00518832775> : tensor<f32>
// CHECK:           %[[ADD_16:.*]] = stablehlo.add %[[MULTIPLY_20]], %[[CONSTANT_24]] : tensor<f32>
// CHECK:           %[[MULTIPLY_21:.*]] = stablehlo.multiply %[[ADD_16]], %[[MULTIPLY_18]] : tensor<f32>
// CHECK:           %[[CONSTANT_25:.*]] = stablehlo.constant dense<-0.0268538129> : tensor<f32>
// CHECK:           %[[ADD_17:.*]] = stablehlo.add %[[MULTIPLY_21]], %[[CONSTANT_25]] : tensor<f32>
// CHECK:           %[[MULTIPLY_22:.*]] = stablehlo.multiply %[[ADD_17]], %[[MULTIPLY_18]] : tensor<f32>
// CHECK:           %[[CONSTANT_26:.*]] = stablehlo.constant dense<0.112835854> : tensor<f32>
// CHECK:           %[[ADD_18:.*]] = stablehlo.add %[[MULTIPLY_22]], %[[CONSTANT_26]] : tensor<f32>
// CHECK:           %[[MULTIPLY_23:.*]] = stablehlo.multiply %[[ADD_18]], %[[MULTIPLY_18]] : tensor<f32>
// CHECK:           %[[CONSTANT_27:.*]] = stablehlo.constant dense<-0.37612626> : tensor<f32>
// CHECK:           %[[ADD_19:.*]] = stablehlo.add %[[MULTIPLY_23]], %[[CONSTANT_27]] : tensor<f32>
// CHECK:           %[[MULTIPLY_24:.*]] = stablehlo.multiply %[[ADD_19]], %[[MULTIPLY_18]] : tensor<f32>
// CHECK:           %[[CONSTANT_28:.*]] = stablehlo.constant dense<1.12837911> : tensor<f32>
// CHECK:           %[[ADD_20:.*]] = stablehlo.add %[[MULTIPLY_24]], %[[CONSTANT_28]] : tensor<f32>
// CHECK:           %[[MULTIPLY_25:.*]] = stablehlo.multiply %[[CONVERT_0]], %[[ADD_20]] : tensor<f32>
// CHECK:           %[[SUBTRACT_1:.*]] = stablehlo.subtract %[[CONSTANT_21]], %[[MULTIPLY_25]] : tensor<f32>
// CHECK:           %[[ABS_1:.*]] = stablehlo.abs %[[CONVERT_0]] : tensor<f32>
// CHECK:           %[[COMPARE_3:.*]] = stablehlo.compare  LT, %[[ABS_1]], %[[CONSTANT_21]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[SELECT_3:.*]] = stablehlo.select %[[COMPARE_3]], %[[SUBTRACT_1]], %[[SELECT_2]] : tensor<i1>, tensor<f32>
// CHECK:           %[[CONVERT_1:.*]] = stablehlo.convert %[[SELECT_3]] : (tensor<f32>) -> tensor<f16>
// CHECK:           return %[[CONVERT_1]] : tensor<f16>
// CHECK:         }
func.func @erfc_f16(%arg : tensor<f16>) -> tensor<f16> {
  %1 = "chlo.erfc"(%arg) : (tensor<f16>) -> tensor<f16>
  func.return %1 : tensor<f16>
}

// -----

// CHECK-LABEL:   func.func @erfc_bf16(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<bf16>) -> tensor<bf16> {
// CHECK:           %[[CONVERT_0:.*]] = stablehlo.convert %[[ARG0]] : (tensor<bf16>) -> tensor<f32>
// CHECK:           %[[MULTIPLY_0:.*]] = stablehlo.multiply %[[CONVERT_0]], %[[CONVERT_0]] : tensor<f32>
// CHECK:           %[[NEGATE_0:.*]] = stablehlo.negate %[[MULTIPLY_0]] : tensor<f32>
// CHECK:           %[[ABS_0:.*]] = stablehlo.abs %[[CONVERT_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[DIVIDE_0:.*]] = stablehlo.divide %[[CONSTANT_0]], %[[MULTIPLY_0]] : tensor<f32>
// CHECK:           %[[EXPONENTIAL_0:.*]] = stablehlo.exponential %[[NEGATE_0]] : tensor<f32>
// CHECK:           %[[DIVIDE_1:.*]] = stablehlo.divide %[[CONSTANT_0]], %[[ABS_0]] : tensor<f32>
// CHECK:           %[[MULTIPLY_1:.*]] = stablehlo.multiply %[[EXPONENTIAL_0]], %[[DIVIDE_1]] : tensor<f32>
// CHECK:           %[[CONSTANT_1:.*]] = stablehlo.constant dense<2.000000e+00> : tensor<f32>
// CHECK:           %[[COMPARE_0:.*]] = stablehlo.compare  LT, %[[ABS_0]], %[[CONSTANT_1]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[CONSTANT_2:.*]] = stablehlo.constant dense<2.326820e-02> : tensor<f32>
// CHECK:           %[[MULTIPLY_2:.*]] = stablehlo.multiply %[[CONSTANT_2]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_3:.*]] = stablehlo.constant dense<-0.138703942> : tensor<f32>
// CHECK:           %[[ADD_0:.*]] = stablehlo.add %[[MULTIPLY_2]], %[[CONSTANT_3]] : tensor<f32>
// CHECK:           %[[MULTIPLY_3:.*]] = stablehlo.multiply %[[ADD_0]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_4:.*]] = stablehlo.constant dense<0.368742466> : tensor<f32>
// CHECK:           %[[ADD_1:.*]] = stablehlo.add %[[MULTIPLY_3]], %[[CONSTANT_4]] : tensor<f32>
// CHECK:           %[[MULTIPLY_4:.*]] = stablehlo.multiply %[[ADD_1]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_5:.*]] = stablehlo.constant dense<-0.582473278> : tensor<f32>
// CHECK:           %[[ADD_2:.*]] = stablehlo.add %[[MULTIPLY_4]], %[[CONSTANT_5]] : tensor<f32>
// CHECK:           %[[MULTIPLY_5:.*]] = stablehlo.multiply %[[ADD_2]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_6:.*]] = stablehlo.constant dense<0.621000468> : tensor<f32>
// CHECK:           %[[ADD_3:.*]] = stablehlo.add %[[MULTIPLY_5]], %[[CONSTANT_6]] : tensor<f32>
// CHECK:           %[[MULTIPLY_6:.*]] = stablehlo.multiply %[[ADD_3]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_7:.*]] = stablehlo.constant dense<-0.494451523> : tensor<f32>
// CHECK:           %[[ADD_4:.*]] = stablehlo.add %[[MULTIPLY_6]], %[[CONSTANT_7]] : tensor<f32>
// CHECK:           %[[MULTIPLY_7:.*]] = stablehlo.multiply %[[ADD_4]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_8:.*]] = stablehlo.constant dense<3.404880e-01> : tensor<f32>
// CHECK:           %[[ADD_5:.*]] = stablehlo.add %[[MULTIPLY_7]], %[[CONSTANT_8]] : tensor<f32>
// CHECK:           %[[MULTIPLY_8:.*]] = stablehlo.multiply %[[ADD_5]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_9:.*]] = stablehlo.constant dense<-0.274112701> : tensor<f32>
// CHECK:           %[[ADD_6:.*]] = stablehlo.add %[[MULTIPLY_8]], %[[CONSTANT_9]] : tensor<f32>
// CHECK:           %[[MULTIPLY_9:.*]] = stablehlo.multiply %[[ADD_6]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_10:.*]] = stablehlo.constant dense<0.563825965> : tensor<f32>
// CHECK:           %[[ADD_7:.*]] = stablehlo.add %[[MULTIPLY_9]], %[[CONSTANT_10]] : tensor<f32>
// CHECK:           %[[CONSTANT_11:.*]] = stablehlo.constant dense<-10.477664> : tensor<f32>
// CHECK:           %[[MULTIPLY_10:.*]] = stablehlo.multiply %[[CONSTANT_11]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_12:.*]] = stablehlo.constant dense<1.297720e+01> : tensor<f32>
// CHECK:           %[[ADD_8:.*]] = stablehlo.add %[[MULTIPLY_10]], %[[CONSTANT_12]] : tensor<f32>
// CHECK:           %[[MULTIPLY_11:.*]] = stablehlo.multiply %[[ADD_8]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_13:.*]] = stablehlo.constant dense<-7.49551868> : tensor<f32>
// CHECK:           %[[ADD_9:.*]] = stablehlo.add %[[MULTIPLY_11]], %[[CONSTANT_13]] : tensor<f32>
// CHECK:           %[[MULTIPLY_12:.*]] = stablehlo.multiply %[[ADD_9]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_14:.*]] = stablehlo.constant dense<2.92101908> : tensor<f32>
// CHECK:           %[[ADD_10:.*]] = stablehlo.add %[[MULTIPLY_12]], %[[CONSTANT_14]] : tensor<f32>
// CHECK:           %[[MULTIPLY_13:.*]] = stablehlo.multiply %[[ADD_10]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_15:.*]] = stablehlo.constant dense<-1.01526523> : tensor<f32>
// CHECK:           %[[ADD_11:.*]] = stablehlo.add %[[MULTIPLY_13]], %[[CONSTANT_15]] : tensor<f32>
// CHECK:           %[[MULTIPLY_14:.*]] = stablehlo.multiply %[[ADD_11]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_16:.*]] = stablehlo.constant dense<0.42184633> : tensor<f32>
// CHECK:           %[[ADD_12:.*]] = stablehlo.add %[[MULTIPLY_14]], %[[CONSTANT_16]] : tensor<f32>
// CHECK:           %[[MULTIPLY_15:.*]] = stablehlo.multiply %[[ADD_12]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_17:.*]] = stablehlo.constant dense<-0.282076746> : tensor<f32>
// CHECK:           %[[ADD_13:.*]] = stablehlo.add %[[MULTIPLY_15]], %[[CONSTANT_17]] : tensor<f32>
// CHECK:           %[[MULTIPLY_16:.*]] = stablehlo.multiply %[[ADD_13]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_18:.*]] = stablehlo.constant dense<0.564189494> : tensor<f32>
// CHECK:           %[[ADD_14:.*]] = stablehlo.add %[[MULTIPLY_16]], %[[CONSTANT_18]] : tensor<f32>
// CHECK:           %[[SELECT_0:.*]] = stablehlo.select %[[COMPARE_0]], %[[ADD_7]], %[[ADD_14]] : tensor<i1>, tensor<f32>
// CHECK:           %[[MULTIPLY_17:.*]] = stablehlo.multiply %[[MULTIPLY_1]], %[[SELECT_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_19:.*]] = stablehlo.constant dense<-88.7228394> : tensor<f32>
// CHECK:           %[[COMPARE_1:.*]] = stablehlo.compare  LT, %[[NEGATE_0]], %[[CONSTANT_19]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[CONSTANT_20:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<f32>
// CHECK:           %[[SELECT_1:.*]] = stablehlo.select %[[COMPARE_1]], %[[CONSTANT_20]], %[[MULTIPLY_17]] : tensor<i1>, tensor<f32>
// CHECK:           %[[COMPARE_2:.*]] = stablehlo.compare  LT, %[[CONVERT_0]], %[[CONSTANT_20]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[SUBTRACT_0:.*]] = stablehlo.subtract %[[CONSTANT_1]], %[[SELECT_1]] : tensor<f32>
// CHECK:           %[[SELECT_2:.*]] = stablehlo.select %[[COMPARE_2]], %[[SUBTRACT_0]], %[[SELECT_1]] : tensor<i1>, tensor<f32>
// CHECK:           %[[CONSTANT_21:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[MULTIPLY_18:.*]] = stablehlo.multiply %[[CONVERT_0]], %[[CONVERT_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_22:.*]] = stablehlo.constant dense<7.85386146E-5> : tensor<f32>
// CHECK:           %[[MULTIPLY_19:.*]] = stablehlo.multiply %[[CONSTANT_22]], %[[MULTIPLY_18]] : tensor<f32>
// CHECK:           %[[CONSTANT_23:.*]] = stablehlo.constant dense<-8.0101937E-4> : tensor<f32>
// CHECK:           %[[ADD_15:.*]] = stablehlo.add %[[MULTIPLY_19]], %[[CONSTANT_23]] : tensor<f32>
// CHECK:           %[[MULTIPLY_20:.*]] = stablehlo.multiply %[[ADD_15]], %[[MULTIPLY_18]] : tensor<f32>
// CHECK:           %[[CONSTANT_24:.*]] = stablehlo.constant dense<0.00518832775> : tensor<f32>
// CHECK:           %[[ADD_16:.*]] = stablehlo.add %[[MULTIPLY_20]], %[[CONSTANT_24]] : tensor<f32>
// CHECK:           %[[MULTIPLY_21:.*]] = stablehlo.multiply %[[ADD_16]], %[[MULTIPLY_18]] : tensor<f32>
// CHECK:           %[[CONSTANT_25:.*]] = stablehlo.constant dense<-0.0268538129> : tensor<f32>
// CHECK:           %[[ADD_17:.*]] = stablehlo.add %[[MULTIPLY_21]], %[[CONSTANT_25]] : tensor<f32>
// CHECK:           %[[MULTIPLY_22:.*]] = stablehlo.multiply %[[ADD_17]], %[[MULTIPLY_18]] : tensor<f32>
// CHECK:           %[[CONSTANT_26:.*]] = stablehlo.constant dense<0.112835854> : tensor<f32>
// CHECK:           %[[ADD_18:.*]] = stablehlo.add %[[MULTIPLY_22]], %[[CONSTANT_26]] : tensor<f32>
// CHECK:           %[[MULTIPLY_23:.*]] = stablehlo.multiply %[[ADD_18]], %[[MULTIPLY_18]] : tensor<f32>
// CHECK:           %[[CONSTANT_27:.*]] = stablehlo.constant dense<-0.37612626> : tensor<f32>
// CHECK:           %[[ADD_19:.*]] = stablehlo.add %[[MULTIPLY_23]], %[[CONSTANT_27]] : tensor<f32>
// CHECK:           %[[MULTIPLY_24:.*]] = stablehlo.multiply %[[ADD_19]], %[[MULTIPLY_18]] : tensor<f32>
// CHECK:           %[[CONSTANT_28:.*]] = stablehlo.constant dense<1.12837911> : tensor<f32>
// CHECK:           %[[ADD_20:.*]] = stablehlo.add %[[MULTIPLY_24]], %[[CONSTANT_28]] : tensor<f32>
// CHECK:           %[[MULTIPLY_25:.*]] = stablehlo.multiply %[[CONVERT_0]], %[[ADD_20]] : tensor<f32>
// CHECK:           %[[SUBTRACT_1:.*]] = stablehlo.subtract %[[CONSTANT_21]], %[[MULTIPLY_25]] : tensor<f32>
// CHECK:           %[[ABS_1:.*]] = stablehlo.abs %[[CONVERT_0]] : tensor<f32>
// CHECK:           %[[COMPARE_3:.*]] = stablehlo.compare  LT, %[[ABS_1]], %[[CONSTANT_21]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[SELECT_3:.*]] = stablehlo.select %[[COMPARE_3]], %[[SUBTRACT_1]], %[[SELECT_2]] : tensor<i1>, tensor<f32>
// CHECK:           %[[CONVERT_1:.*]] = stablehlo.convert %[[SELECT_3]] : (tensor<f32>) -> tensor<bf16>
// CHECK:           return %[[CONVERT_1]] : tensor<bf16>
// CHECK:         }
func.func @erfc_bf16(%arg : tensor<bf16>) -> tensor<bf16> {
  %1 = "chlo.erfc"(%arg) : (tensor<bf16>) -> tensor<bf16>
  func.return %1 : tensor<bf16>
}

// -----

// CHECK-LABEL:   func.func @is_inf_f32(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<f32>) -> tensor<i1> {
// CHECK:           %[[ABS_0:.*]] = stablehlo.abs %[[ARG0]] : tensor<f32>
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<0x7F800000> : tensor<f32>
// CHECK:           %[[COMPARE_0:.*]] = stablehlo.compare  EQ, %[[ABS_0]], %[[CONSTANT_0]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           return %[[COMPARE_0]] : tensor<i1>
// CHECK:         }
func.func @is_inf_f32(%arg : tensor<f32>) -> tensor<i1> {
  %1 = chlo.is_inf %arg : tensor<f32> -> tensor<i1>
  func.return %1 : tensor<i1>
}

// -----

// CHECK-LABEL:   func.func @is_pos_inf_f32(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<f32>) -> tensor<i1> {
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<0x7F800000> : tensor<f32>
// CHECK:           %[[COMPARE_0:.*]] = stablehlo.compare  EQ, %[[ARG0]], %[[CONSTANT_0]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           return %[[COMPARE_0]] : tensor<i1>
// CHECK:         }
func.func @is_pos_inf_f32(%arg : tensor<f32>) -> tensor<i1> {
  %1 = chlo.is_pos_inf %arg : tensor<f32> -> tensor<i1>
  func.return %1 : tensor<i1>
}

// -----

// CHECK-LABEL:   func.func @is_neg_inf_f32(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<f32>) -> tensor<i1> {
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<0xFF800000> : tensor<f32>
// CHECK:           %[[COMPARE_0:.*]] = stablehlo.compare  EQ, %[[ARG0]], %[[CONSTANT_0]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           return %[[COMPARE_0]] : tensor<i1>
// CHECK:         }
func.func @is_neg_inf_f32(%arg : tensor<f32>) -> tensor<i1> {
  %1 = chlo.is_neg_inf %arg : tensor<f32> -> tensor<i1>
  func.return %1 : tensor<i1>
}

// -----

// CHECK-LABEL:   func.func @lgamma_f64(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<f64>) -> tensor<f64> {
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<5.000000e-01> : tensor<f64>
// CHECK:           %[[COMPARE_0:.*]] = stablehlo.compare  LT, %[[ARG0]], %[[CONSTANT_0]] : (tensor<f64>, tensor<f64>) -> tensor<i1>
// CHECK:           %[[NEGATE_0:.*]] = stablehlo.negate %[[ARG0]] : tensor<f64>
// CHECK:           %[[CONSTANT_1:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f64>
// CHECK:           %[[SUBTRACT_0:.*]] = stablehlo.subtract %[[ARG0]], %[[CONSTANT_1]] : tensor<f64>
// CHECK:           %[[SELECT_0:.*]] = stablehlo.select %[[COMPARE_0]], %[[NEGATE_0]], %[[SUBTRACT_0]] : tensor<i1>, tensor<f64>
// CHECK:           %[[CONSTANT_2:.*]] = stablehlo.constant dense<0.99999999999980993> : tensor<f64>
// CHECK:           %[[CONSTANT_3:.*]] = stablehlo.constant dense<676.5203681218851> : tensor<f64>
// CHECK:           %[[CONSTANT_4:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f64>
// CHECK:           %[[ADD_0:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_4]] : tensor<f64>
// CHECK:           %[[DIVIDE_0:.*]] = stablehlo.divide %[[CONSTANT_3]], %[[ADD_0]] : tensor<f64>
// CHECK:           %[[ADD_1:.*]] = stablehlo.add %[[CONSTANT_2]], %[[DIVIDE_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_5:.*]] = stablehlo.constant dense<-1259.1392167224028> : tensor<f64>
// CHECK:           %[[CONSTANT_6:.*]] = stablehlo.constant dense<2.000000e+00> : tensor<f64>
// CHECK:           %[[ADD_2:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_6]] : tensor<f64>
// CHECK:           %[[DIVIDE_1:.*]] = stablehlo.divide %[[CONSTANT_5]], %[[ADD_2]] : tensor<f64>
// CHECK:           %[[ADD_3:.*]] = stablehlo.add %[[ADD_1]], %[[DIVIDE_1]] : tensor<f64>
// CHECK:           %[[CONSTANT_7:.*]] = stablehlo.constant dense<771.32342877765313> : tensor<f64>
// CHECK:           %[[CONSTANT_8:.*]] = stablehlo.constant dense<3.000000e+00> : tensor<f64>
// CHECK:           %[[ADD_4:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_8]] : tensor<f64>
// CHECK:           %[[DIVIDE_2:.*]] = stablehlo.divide %[[CONSTANT_7]], %[[ADD_4]] : tensor<f64>
// CHECK:           %[[ADD_5:.*]] = stablehlo.add %[[ADD_3]], %[[DIVIDE_2]] : tensor<f64>
// CHECK:           %[[CONSTANT_9:.*]] = stablehlo.constant dense<-176.61502916214059> : tensor<f64>
// CHECK:           %[[CONSTANT_10:.*]] = stablehlo.constant dense<4.000000e+00> : tensor<f64>
// CHECK:           %[[ADD_6:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_10]] : tensor<f64>
// CHECK:           %[[DIVIDE_3:.*]] = stablehlo.divide %[[CONSTANT_9]], %[[ADD_6]] : tensor<f64>
// CHECK:           %[[ADD_7:.*]] = stablehlo.add %[[ADD_5]], %[[DIVIDE_3]] : tensor<f64>
// CHECK:           %[[CONSTANT_11:.*]] = stablehlo.constant dense<12.507343278686905> : tensor<f64>
// CHECK:           %[[CONSTANT_12:.*]] = stablehlo.constant dense<5.000000e+00> : tensor<f64>
// CHECK:           %[[ADD_8:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_12]] : tensor<f64>
// CHECK:           %[[DIVIDE_4:.*]] = stablehlo.divide %[[CONSTANT_11]], %[[ADD_8]] : tensor<f64>
// CHECK:           %[[ADD_9:.*]] = stablehlo.add %[[ADD_7]], %[[DIVIDE_4]] : tensor<f64>
// CHECK:           %[[CONSTANT_13:.*]] = stablehlo.constant dense<-0.13857109526572012> : tensor<f64>
// CHECK:           %[[CONSTANT_14:.*]] = stablehlo.constant dense<6.000000e+00> : tensor<f64>
// CHECK:           %[[ADD_10:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_14]] : tensor<f64>
// CHECK:           %[[DIVIDE_5:.*]] = stablehlo.divide %[[CONSTANT_13]], %[[ADD_10]] : tensor<f64>
// CHECK:           %[[ADD_11:.*]] = stablehlo.add %[[ADD_9]], %[[DIVIDE_5]] : tensor<f64>
// CHECK:           %[[CONSTANT_15:.*]] = stablehlo.constant dense<9.9843695780195716E-6> : tensor<f64>
// CHECK:           %[[CONSTANT_16:.*]] = stablehlo.constant dense<7.000000e+00> : tensor<f64>
// CHECK:           %[[ADD_12:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_16]] : tensor<f64>
// CHECK:           %[[DIVIDE_6:.*]] = stablehlo.divide %[[CONSTANT_15]], %[[ADD_12]] : tensor<f64>
// CHECK:           %[[ADD_13:.*]] = stablehlo.add %[[ADD_11]], %[[DIVIDE_6]] : tensor<f64>
// CHECK:           %[[CONSTANT_17:.*]] = stablehlo.constant dense<1.5056327351493116E-7> : tensor<f64>
// CHECK:           %[[CONSTANT_18:.*]] = stablehlo.constant dense<8.000000e+00> : tensor<f64>
// CHECK:           %[[ADD_14:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_18]] : tensor<f64>
// CHECK:           %[[DIVIDE_7:.*]] = stablehlo.divide %[[CONSTANT_17]], %[[ADD_14]] : tensor<f64>
// CHECK:           %[[ADD_15:.*]] = stablehlo.add %[[ADD_13]], %[[DIVIDE_7]] : tensor<f64>
// CHECK:           %[[CONSTANT_19:.*]] = stablehlo.constant dense<7.500000e+00> : tensor<f64>
// CHECK:           %[[ADD_16:.*]] = stablehlo.add %[[CONSTANT_19]], %[[SELECT_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_20:.*]] = stablehlo.constant dense<2.0149030205422647> : tensor<f64>
// CHECK:           %[[DIVIDE_8:.*]] = stablehlo.divide %[[SELECT_0]], %[[CONSTANT_19]] : tensor<f64>
// CHECK:           %[[LOG_PLUS_ONE_0:.*]] = stablehlo.log_plus_one %[[DIVIDE_8]] : tensor<f64>
// CHECK:           %[[ADD_17:.*]] = stablehlo.add %[[CONSTANT_20]], %[[LOG_PLUS_ONE_0]] : tensor<f64>
// CHECK:           %[[DIVIDE_9:.*]] = stablehlo.divide %[[ADD_16]], %[[ADD_17]] : tensor<f64>
// CHECK:           %[[ADD_18:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_0]] : tensor<f64>
// CHECK:           %[[SUBTRACT_1:.*]] = stablehlo.subtract %[[ADD_18]], %[[DIVIDE_9]] : tensor<f64>
// CHECK:           %[[MULTIPLY_0:.*]] = stablehlo.multiply %[[SUBTRACT_1]], %[[ADD_17]] : tensor<f64>
// CHECK:           %[[LOG_0:.*]] = stablehlo.log %[[ADD_15]] : tensor<f64>
// CHECK:           %[[CONSTANT_21:.*]] = stablehlo.constant dense<0.91893853320467266> : tensor<f64>
// CHECK:           %[[ADD_19:.*]] = stablehlo.add %[[CONSTANT_21]], %[[MULTIPLY_0]] : tensor<f64>
// CHECK:           %[[ADD_20:.*]] = stablehlo.add %[[ADD_19]], %[[LOG_0]] : tensor<f64>
// CHECK:           %[[ABS_0:.*]] = stablehlo.abs %[[ARG0]] : tensor<f64>
// CHECK:           %[[FLOOR_0:.*]] = stablehlo.floor %[[ABS_0]] : tensor<f64>
// CHECK:           %[[SUBTRACT_2:.*]] = stablehlo.subtract %[[ABS_0]], %[[FLOOR_0]] : tensor<f64>
// CHECK:           %[[COMPARE_1:.*]] = stablehlo.compare  LT, %[[CONSTANT_0]], %[[SUBTRACT_2]] : (tensor<f64>, tensor<f64>) -> tensor<i1>
// CHECK:           %[[SUBTRACT_3:.*]] = stablehlo.subtract %[[CONSTANT_1]], %[[SUBTRACT_2]] : tensor<f64>
// CHECK:           %[[SELECT_1:.*]] = stablehlo.select %[[COMPARE_1]], %[[SUBTRACT_3]], %[[SUBTRACT_2]] : tensor<i1>, tensor<f64>
// CHECK:           %[[CONSTANT_22:.*]] = stablehlo.constant dense<3.1415926535897931> : tensor<f64>
// CHECK:           %[[MULTIPLY_1:.*]] = stablehlo.multiply %[[CONSTANT_22]], %[[SELECT_1]] : tensor<f64>
// CHECK:           %[[SINE_0:.*]] = stablehlo.sine %[[MULTIPLY_1]] : tensor<f64>
// CHECK:           %[[LOG_1:.*]] = stablehlo.log %[[SINE_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_23:.*]] = stablehlo.constant dense<1.1447298858494002> : tensor<f64>
// CHECK:           %[[SUBTRACT_4:.*]] = stablehlo.subtract %[[CONSTANT_23]], %[[LOG_1]] : tensor<f64>
// CHECK:           %[[SUBTRACT_5:.*]] = stablehlo.subtract %[[SUBTRACT_4]], %[[ADD_20]] : tensor<f64>
// CHECK:           %[[IS_FINITE_0:.*]] = stablehlo.is_finite %[[LOG_1]] : (tensor<f64>) -> tensor<i1>
// CHECK:           %[[NEGATE_1:.*]] = stablehlo.negate %[[LOG_1]] : tensor<f64>
// CHECK:           %[[SELECT_2:.*]] = stablehlo.select %[[IS_FINITE_0]], %[[SUBTRACT_5]], %[[NEGATE_1]] : tensor<i1>, tensor<f64>
// CHECK:           %[[SELECT_3:.*]] = stablehlo.select %[[COMPARE_0]], %[[SELECT_2]], %[[ADD_20]] : tensor<i1>, tensor<f64>
// CHECK:           %[[ABS_1:.*]] = stablehlo.abs %[[ARG0]] : tensor<f64>
// CHECK:           %[[CONSTANT_24:.*]] = stablehlo.constant dense<0x7FF0000000000000> : tensor<f64>
// CHECK:           %[[COMPARE_2:.*]] = stablehlo.compare  EQ, %[[ABS_1]], %[[CONSTANT_24]] : (tensor<f64>, tensor<f64>) -> tensor<i1>
// CHECK:           %[[CONSTANT_25:.*]] = stablehlo.constant dense<0x7FF0000000000000> : tensor<f64>
// CHECK:           %[[SELECT_4:.*]] = stablehlo.select %[[COMPARE_2]], %[[CONSTANT_25]], %[[SELECT_3]] : tensor<i1>, tensor<f64>
// CHECK:           return %[[SELECT_4]] : tensor<f64>
// CHECK:         }
func.func @lgamma_f64(%arg : tensor<f64>) -> tensor<f64> {
  %1 = chlo.lgamma %arg : tensor<f64> -> tensor<f64>
  func.return %1 : tensor<f64>
}

// -----

// CHECK-LABEL:   func.func @lgamma_f32(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<f32>) -> tensor<f32> {
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<5.000000e-01> : tensor<f32>
// CHECK:           %[[COMPARE_0:.*]] = stablehlo.compare  LT, %[[ARG0]], %[[CONSTANT_0]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[NEGATE_0:.*]] = stablehlo.negate %[[ARG0]] : tensor<f32>
// CHECK:           %[[CONSTANT_1:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[SUBTRACT_0:.*]] = stablehlo.subtract %[[ARG0]], %[[CONSTANT_1]] : tensor<f32>
// CHECK:           %[[SELECT_0:.*]] = stablehlo.select %[[COMPARE_0]], %[[NEGATE_0]], %[[SUBTRACT_0]] : tensor<i1>, tensor<f32>
// CHECK:           %[[CONSTANT_2:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[CONSTANT_3:.*]] = stablehlo.constant dense<676.520386> : tensor<f32>
// CHECK:           %[[CONSTANT_4:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_0:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_4]] : tensor<f32>
// CHECK:           %[[DIVIDE_0:.*]] = stablehlo.divide %[[CONSTANT_3]], %[[ADD_0]] : tensor<f32>
// CHECK:           %[[ADD_1:.*]] = stablehlo.add %[[CONSTANT_2]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_5:.*]] = stablehlo.constant dense<-1259.13916> : tensor<f32>
// CHECK:           %[[CONSTANT_6:.*]] = stablehlo.constant dense<2.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_2:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_6]] : tensor<f32>
// CHECK:           %[[DIVIDE_1:.*]] = stablehlo.divide %[[CONSTANT_5]], %[[ADD_2]] : tensor<f32>
// CHECK:           %[[ADD_3:.*]] = stablehlo.add %[[ADD_1]], %[[DIVIDE_1]] : tensor<f32>
// CHECK:           %[[CONSTANT_7:.*]] = stablehlo.constant dense<771.323425> : tensor<f32>
// CHECK:           %[[CONSTANT_8:.*]] = stablehlo.constant dense<3.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_4:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_8]] : tensor<f32>
// CHECK:           %[[DIVIDE_2:.*]] = stablehlo.divide %[[CONSTANT_7]], %[[ADD_4]] : tensor<f32>
// CHECK:           %[[ADD_5:.*]] = stablehlo.add %[[ADD_3]], %[[DIVIDE_2]] : tensor<f32>
// CHECK:           %[[CONSTANT_9:.*]] = stablehlo.constant dense<-176.615036> : tensor<f32>
// CHECK:           %[[CONSTANT_10:.*]] = stablehlo.constant dense<4.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_6:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_10]] : tensor<f32>
// CHECK:           %[[DIVIDE_3:.*]] = stablehlo.divide %[[CONSTANT_9]], %[[ADD_6]] : tensor<f32>
// CHECK:           %[[ADD_7:.*]] = stablehlo.add %[[ADD_5]], %[[DIVIDE_3]] : tensor<f32>
// CHECK:           %[[CONSTANT_11:.*]] = stablehlo.constant dense<12.5073433> : tensor<f32>
// CHECK:           %[[CONSTANT_12:.*]] = stablehlo.constant dense<5.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_8:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_12]] : tensor<f32>
// CHECK:           %[[DIVIDE_4:.*]] = stablehlo.divide %[[CONSTANT_11]], %[[ADD_8]] : tensor<f32>
// CHECK:           %[[ADD_9:.*]] = stablehlo.add %[[ADD_7]], %[[DIVIDE_4]] : tensor<f32>
// CHECK:           %[[CONSTANT_13:.*]] = stablehlo.constant dense<-0.138571098> : tensor<f32>
// CHECK:           %[[CONSTANT_14:.*]] = stablehlo.constant dense<6.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_10:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_14]] : tensor<f32>
// CHECK:           %[[DIVIDE_5:.*]] = stablehlo.divide %[[CONSTANT_13]], %[[ADD_10]] : tensor<f32>
// CHECK:           %[[ADD_11:.*]] = stablehlo.add %[[ADD_9]], %[[DIVIDE_5]] : tensor<f32>
// CHECK:           %[[CONSTANT_15:.*]] = stablehlo.constant dense<9.98436917E-6> : tensor<f32>
// CHECK:           %[[CONSTANT_16:.*]] = stablehlo.constant dense<7.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_12:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_16]] : tensor<f32>
// CHECK:           %[[DIVIDE_6:.*]] = stablehlo.divide %[[CONSTANT_15]], %[[ADD_12]] : tensor<f32>
// CHECK:           %[[ADD_13:.*]] = stablehlo.add %[[ADD_11]], %[[DIVIDE_6]] : tensor<f32>
// CHECK:           %[[CONSTANT_17:.*]] = stablehlo.constant dense<1.50563267E-7> : tensor<f32>
// CHECK:           %[[CONSTANT_18:.*]] = stablehlo.constant dense<8.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_14:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_18]] : tensor<f32>
// CHECK:           %[[DIVIDE_7:.*]] = stablehlo.divide %[[CONSTANT_17]], %[[ADD_14]] : tensor<f32>
// CHECK:           %[[ADD_15:.*]] = stablehlo.add %[[ADD_13]], %[[DIVIDE_7]] : tensor<f32>
// CHECK:           %[[CONSTANT_19:.*]] = stablehlo.constant dense<7.500000e+00> : tensor<f32>
// CHECK:           %[[ADD_16:.*]] = stablehlo.add %[[CONSTANT_19]], %[[SELECT_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_20:.*]] = stablehlo.constant dense<2.01490307> : tensor<f32>
// CHECK:           %[[DIVIDE_8:.*]] = stablehlo.divide %[[SELECT_0]], %[[CONSTANT_19]] : tensor<f32>
// CHECK:           %[[LOG_PLUS_ONE_0:.*]] = stablehlo.log_plus_one %[[DIVIDE_8]] : tensor<f32>
// CHECK:           %[[ADD_17:.*]] = stablehlo.add %[[CONSTANT_20]], %[[LOG_PLUS_ONE_0]] : tensor<f32>
// CHECK:           %[[DIVIDE_9:.*]] = stablehlo.divide %[[ADD_16]], %[[ADD_17]] : tensor<f32>
// CHECK:           %[[ADD_18:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_0]] : tensor<f32>
// CHECK:           %[[SUBTRACT_1:.*]] = stablehlo.subtract %[[ADD_18]], %[[DIVIDE_9]] : tensor<f32>
// CHECK:           %[[MULTIPLY_0:.*]] = stablehlo.multiply %[[SUBTRACT_1]], %[[ADD_17]] : tensor<f32>
// CHECK:           %[[LOG_0:.*]] = stablehlo.log %[[ADD_15]] : tensor<f32>
// CHECK:           %[[CONSTANT_21:.*]] = stablehlo.constant dense<0.918938517> : tensor<f32>
// CHECK:           %[[ADD_19:.*]] = stablehlo.add %[[CONSTANT_21]], %[[MULTIPLY_0]] : tensor<f32>
// CHECK:           %[[ADD_20:.*]] = stablehlo.add %[[ADD_19]], %[[LOG_0]] : tensor<f32>
// CHECK:           %[[ABS_0:.*]] = stablehlo.abs %[[ARG0]] : tensor<f32>
// CHECK:           %[[FLOOR_0:.*]] = stablehlo.floor %[[ABS_0]] : tensor<f32>
// CHECK:           %[[SUBTRACT_2:.*]] = stablehlo.subtract %[[ABS_0]], %[[FLOOR_0]] : tensor<f32>
// CHECK:           %[[COMPARE_1:.*]] = stablehlo.compare  LT, %[[CONSTANT_0]], %[[SUBTRACT_2]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[SUBTRACT_3:.*]] = stablehlo.subtract %[[CONSTANT_1]], %[[SUBTRACT_2]] : tensor<f32>
// CHECK:           %[[SELECT_1:.*]] = stablehlo.select %[[COMPARE_1]], %[[SUBTRACT_3]], %[[SUBTRACT_2]] : tensor<i1>, tensor<f32>
// CHECK:           %[[CONSTANT_22:.*]] = stablehlo.constant dense<3.14159274> : tensor<f32>
// CHECK:           %[[MULTIPLY_1:.*]] = stablehlo.multiply %[[CONSTANT_22]], %[[SELECT_1]] : tensor<f32>
// CHECK:           %[[SINE_0:.*]] = stablehlo.sine %[[MULTIPLY_1]] : tensor<f32>
// CHECK:           %[[LOG_1:.*]] = stablehlo.log %[[SINE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_23:.*]] = stablehlo.constant dense<1.14472985> : tensor<f32>
// CHECK:           %[[SUBTRACT_4:.*]] = stablehlo.subtract %[[CONSTANT_23]], %[[LOG_1]] : tensor<f32>
// CHECK:           %[[SUBTRACT_5:.*]] = stablehlo.subtract %[[SUBTRACT_4]], %[[ADD_20]] : tensor<f32>
// CHECK:           %[[IS_FINITE_0:.*]] = stablehlo.is_finite %[[LOG_1]] : (tensor<f32>) -> tensor<i1>
// CHECK:           %[[NEGATE_1:.*]] = stablehlo.negate %[[LOG_1]] : tensor<f32>
// CHECK:           %[[SELECT_2:.*]] = stablehlo.select %[[IS_FINITE_0]], %[[SUBTRACT_5]], %[[NEGATE_1]] : tensor<i1>, tensor<f32>
// CHECK:           %[[SELECT_3:.*]] = stablehlo.select %[[COMPARE_0]], %[[SELECT_2]], %[[ADD_20]] : tensor<i1>, tensor<f32>
// CHECK:           %[[ABS_1:.*]] = stablehlo.abs %[[ARG0]] : tensor<f32>
// CHECK:           %[[CONSTANT_24:.*]] = stablehlo.constant dense<0x7F800000> : tensor<f32>
// CHECK:           %[[COMPARE_2:.*]] = stablehlo.compare  EQ, %[[ABS_1]], %[[CONSTANT_24]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[CONSTANT_25:.*]] = stablehlo.constant dense<0x7F800000> : tensor<f32>
// CHECK:           %[[SELECT_4:.*]] = stablehlo.select %[[COMPARE_2]], %[[CONSTANT_25]], %[[SELECT_3]] : tensor<i1>, tensor<f32>
// CHECK:           return %[[SELECT_4]] : tensor<f32>
// CHECK:         }
func.func @lgamma_f32(%arg : tensor<f32>) -> tensor<f32> {
  %1 = chlo.lgamma %arg : tensor<f32> -> tensor<f32>
  func.return %1 : tensor<f32>
}

// -----

// CHECK-LABEL:   func.func @lgamma_f16(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<f16>) -> tensor<f16> {
// CHECK:           %[[CONVERT_0:.*]] = stablehlo.convert %[[ARG0]] : (tensor<f16>) -> tensor<f32>
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<5.000000e-01> : tensor<f32>
// CHECK:           %[[COMPARE_0:.*]] = stablehlo.compare  LT, %[[CONVERT_0]], %[[CONSTANT_0]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[NEGATE_0:.*]] = stablehlo.negate %[[CONVERT_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_1:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[SUBTRACT_0:.*]] = stablehlo.subtract %[[CONVERT_0]], %[[CONSTANT_1]] : tensor<f32>
// CHECK:           %[[SELECT_0:.*]] = stablehlo.select %[[COMPARE_0]], %[[NEGATE_0]], %[[SUBTRACT_0]] : tensor<i1>, tensor<f32>
// CHECK:           %[[CONSTANT_2:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[CONSTANT_3:.*]] = stablehlo.constant dense<676.520386> : tensor<f32>
// CHECK:           %[[CONSTANT_4:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_0:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_4]] : tensor<f32>
// CHECK:           %[[DIVIDE_0:.*]] = stablehlo.divide %[[CONSTANT_3]], %[[ADD_0]] : tensor<f32>
// CHECK:           %[[ADD_1:.*]] = stablehlo.add %[[CONSTANT_2]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_5:.*]] = stablehlo.constant dense<-1259.13916> : tensor<f32>
// CHECK:           %[[CONSTANT_6:.*]] = stablehlo.constant dense<2.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_2:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_6]] : tensor<f32>
// CHECK:           %[[DIVIDE_1:.*]] = stablehlo.divide %[[CONSTANT_5]], %[[ADD_2]] : tensor<f32>
// CHECK:           %[[ADD_3:.*]] = stablehlo.add %[[ADD_1]], %[[DIVIDE_1]] : tensor<f32>
// CHECK:           %[[CONSTANT_7:.*]] = stablehlo.constant dense<771.323425> : tensor<f32>
// CHECK:           %[[CONSTANT_8:.*]] = stablehlo.constant dense<3.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_4:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_8]] : tensor<f32>
// CHECK:           %[[DIVIDE_2:.*]] = stablehlo.divide %[[CONSTANT_7]], %[[ADD_4]] : tensor<f32>
// CHECK:           %[[ADD_5:.*]] = stablehlo.add %[[ADD_3]], %[[DIVIDE_2]] : tensor<f32>
// CHECK:           %[[CONSTANT_9:.*]] = stablehlo.constant dense<-176.615036> : tensor<f32>
// CHECK:           %[[CONSTANT_10:.*]] = stablehlo.constant dense<4.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_6:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_10]] : tensor<f32>
// CHECK:           %[[DIVIDE_3:.*]] = stablehlo.divide %[[CONSTANT_9]], %[[ADD_6]] : tensor<f32>
// CHECK:           %[[ADD_7:.*]] = stablehlo.add %[[ADD_5]], %[[DIVIDE_3]] : tensor<f32>
// CHECK:           %[[CONSTANT_11:.*]] = stablehlo.constant dense<12.5073433> : tensor<f32>
// CHECK:           %[[CONSTANT_12:.*]] = stablehlo.constant dense<5.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_8:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_12]] : tensor<f32>
// CHECK:           %[[DIVIDE_4:.*]] = stablehlo.divide %[[CONSTANT_11]], %[[ADD_8]] : tensor<f32>
// CHECK:           %[[ADD_9:.*]] = stablehlo.add %[[ADD_7]], %[[DIVIDE_4]] : tensor<f32>
// CHECK:           %[[CONSTANT_13:.*]] = stablehlo.constant dense<-0.138571098> : tensor<f32>
// CHECK:           %[[CONSTANT_14:.*]] = stablehlo.constant dense<6.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_10:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_14]] : tensor<f32>
// CHECK:           %[[DIVIDE_5:.*]] = stablehlo.divide %[[CONSTANT_13]], %[[ADD_10]] : tensor<f32>
// CHECK:           %[[ADD_11:.*]] = stablehlo.add %[[ADD_9]], %[[DIVIDE_5]] : tensor<f32>
// CHECK:           %[[CONSTANT_15:.*]] = stablehlo.constant dense<9.98436917E-6> : tensor<f32>
// CHECK:           %[[CONSTANT_16:.*]] = stablehlo.constant dense<7.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_12:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_16]] : tensor<f32>
// CHECK:           %[[DIVIDE_6:.*]] = stablehlo.divide %[[CONSTANT_15]], %[[ADD_12]] : tensor<f32>
// CHECK:           %[[ADD_13:.*]] = stablehlo.add %[[ADD_11]], %[[DIVIDE_6]] : tensor<f32>
// CHECK:           %[[CONSTANT_17:.*]] = stablehlo.constant dense<1.50563267E-7> : tensor<f32>
// CHECK:           %[[CONSTANT_18:.*]] = stablehlo.constant dense<8.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_14:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_18]] : tensor<f32>
// CHECK:           %[[DIVIDE_7:.*]] = stablehlo.divide %[[CONSTANT_17]], %[[ADD_14]] : tensor<f32>
// CHECK:           %[[ADD_15:.*]] = stablehlo.add %[[ADD_13]], %[[DIVIDE_7]] : tensor<f32>
// CHECK:           %[[CONSTANT_19:.*]] = stablehlo.constant dense<7.500000e+00> : tensor<f32>
// CHECK:           %[[ADD_16:.*]] = stablehlo.add %[[CONSTANT_19]], %[[SELECT_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_20:.*]] = stablehlo.constant dense<2.01490307> : tensor<f32>
// CHECK:           %[[DIVIDE_8:.*]] = stablehlo.divide %[[SELECT_0]], %[[CONSTANT_19]] : tensor<f32>
// CHECK:           %[[LOG_PLUS_ONE_0:.*]] = stablehlo.log_plus_one %[[DIVIDE_8]] : tensor<f32>
// CHECK:           %[[ADD_17:.*]] = stablehlo.add %[[CONSTANT_20]], %[[LOG_PLUS_ONE_0]] : tensor<f32>
// CHECK:           %[[DIVIDE_9:.*]] = stablehlo.divide %[[ADD_16]], %[[ADD_17]] : tensor<f32>
// CHECK:           %[[ADD_18:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_0]] : tensor<f32>
// CHECK:           %[[SUBTRACT_1:.*]] = stablehlo.subtract %[[ADD_18]], %[[DIVIDE_9]] : tensor<f32>
// CHECK:           %[[MULTIPLY_0:.*]] = stablehlo.multiply %[[SUBTRACT_1]], %[[ADD_17]] : tensor<f32>
// CHECK:           %[[LOG_0:.*]] = stablehlo.log %[[ADD_15]] : tensor<f32>
// CHECK:           %[[CONSTANT_21:.*]] = stablehlo.constant dense<0.918938517> : tensor<f32>
// CHECK:           %[[ADD_19:.*]] = stablehlo.add %[[CONSTANT_21]], %[[MULTIPLY_0]] : tensor<f32>
// CHECK:           %[[ADD_20:.*]] = stablehlo.add %[[ADD_19]], %[[LOG_0]] : tensor<f32>
// CHECK:           %[[ABS_0:.*]] = stablehlo.abs %[[CONVERT_0]] : tensor<f32>
// CHECK:           %[[FLOOR_0:.*]] = stablehlo.floor %[[ABS_0]] : tensor<f32>
// CHECK:           %[[SUBTRACT_2:.*]] = stablehlo.subtract %[[ABS_0]], %[[FLOOR_0]] : tensor<f32>
// CHECK:           %[[COMPARE_1:.*]] = stablehlo.compare  LT, %[[CONSTANT_0]], %[[SUBTRACT_2]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[SUBTRACT_3:.*]] = stablehlo.subtract %[[CONSTANT_1]], %[[SUBTRACT_2]] : tensor<f32>
// CHECK:           %[[SELECT_1:.*]] = stablehlo.select %[[COMPARE_1]], %[[SUBTRACT_3]], %[[SUBTRACT_2]] : tensor<i1>, tensor<f32>
// CHECK:           %[[CONSTANT_22:.*]] = stablehlo.constant dense<3.14159274> : tensor<f32>
// CHECK:           %[[MULTIPLY_1:.*]] = stablehlo.multiply %[[CONSTANT_22]], %[[SELECT_1]] : tensor<f32>
// CHECK:           %[[SINE_0:.*]] = stablehlo.sine %[[MULTIPLY_1]] : tensor<f32>
// CHECK:           %[[LOG_1:.*]] = stablehlo.log %[[SINE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_23:.*]] = stablehlo.constant dense<1.14472985> : tensor<f32>
// CHECK:           %[[SUBTRACT_4:.*]] = stablehlo.subtract %[[CONSTANT_23]], %[[LOG_1]] : tensor<f32>
// CHECK:           %[[SUBTRACT_5:.*]] = stablehlo.subtract %[[SUBTRACT_4]], %[[ADD_20]] : tensor<f32>
// CHECK:           %[[IS_FINITE_0:.*]] = stablehlo.is_finite %[[LOG_1]] : (tensor<f32>) -> tensor<i1>
// CHECK:           %[[NEGATE_1:.*]] = stablehlo.negate %[[LOG_1]] : tensor<f32>
// CHECK:           %[[SELECT_2:.*]] = stablehlo.select %[[IS_FINITE_0]], %[[SUBTRACT_5]], %[[NEGATE_1]] : tensor<i1>, tensor<f32>
// CHECK:           %[[SELECT_3:.*]] = stablehlo.select %[[COMPARE_0]], %[[SELECT_2]], %[[ADD_20]] : tensor<i1>, tensor<f32>
// CHECK:           %[[ABS_1:.*]] = stablehlo.abs %[[CONVERT_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_24:.*]] = stablehlo.constant dense<0x7F800000> : tensor<f32>
// CHECK:           %[[COMPARE_2:.*]] = stablehlo.compare  EQ, %[[ABS_1]], %[[CONSTANT_24]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[CONSTANT_25:.*]] = stablehlo.constant dense<0x7F800000> : tensor<f32>
// CHECK:           %[[SELECT_4:.*]] = stablehlo.select %[[COMPARE_2]], %[[CONSTANT_25]], %[[SELECT_3]] : tensor<i1>, tensor<f32>
// CHECK:           %[[CONVERT_1:.*]] = stablehlo.convert %[[SELECT_4]] : (tensor<f32>) -> tensor<f16>
// CHECK:           return %[[CONVERT_1]] : tensor<f16>
// CHECK:         }
func.func @lgamma_f16(%arg : tensor<f16>) -> tensor<f16> {
  %1 = chlo.lgamma %arg : tensor<f16> -> tensor<f16>
  func.return %1 : tensor<f16>
}

// -----

// CHECK-LABEL:   func.func @digamma_f64(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<f64>) -> tensor<f64> {
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<5.000000e-01> : tensor<f64>
// CHECK:           %[[COMPARE_0:.*]] = stablehlo.compare  LT, %[[ARG0]], %[[CONSTANT_0]] : (tensor<f64>, tensor<f64>) -> tensor<i1>
// CHECK:           %[[NEGATE_0:.*]] = stablehlo.negate %[[ARG0]] : tensor<f64>
// CHECK:           %[[CONSTANT_1:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f64>
// CHECK:           %[[SUBTRACT_0:.*]] = stablehlo.subtract %[[ARG0]], %[[CONSTANT_1]] : tensor<f64>
// CHECK:           %[[SELECT_0:.*]] = stablehlo.select %[[COMPARE_0]], %[[NEGATE_0]], %[[SUBTRACT_0]] : tensor<i1>, tensor<f64>
// CHECK:           %[[CONSTANT_2:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<f64>
// CHECK:           %[[CONSTANT_3:.*]] = stablehlo.constant dense<0.99999999999980993> : tensor<f64>
// CHECK:           %[[CONSTANT_4:.*]] = stablehlo.constant dense<676.5203681218851> : tensor<f64>
// CHECK:           %[[CONSTANT_5:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f64>
// CHECK:           %[[ADD_0:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_5]] : tensor<f64>
// CHECK:           %[[MULTIPLY_0:.*]] = stablehlo.multiply %[[ADD_0]], %[[ADD_0]] : tensor<f64>
// CHECK:           %[[DIVIDE_0:.*]] = stablehlo.divide %[[CONSTANT_4]], %[[MULTIPLY_0]] : tensor<f64>
// CHECK:           %[[SUBTRACT_1:.*]] = stablehlo.subtract %[[CONSTANT_2]], %[[DIVIDE_0]] : tensor<f64>
// CHECK:           %[[DIVIDE_1:.*]] = stablehlo.divide %[[CONSTANT_4]], %[[ADD_0]] : tensor<f64>
// CHECK:           %[[ADD_1:.*]] = stablehlo.add %[[CONSTANT_3]], %[[DIVIDE_1]] : tensor<f64>
// CHECK:           %[[CONSTANT_6:.*]] = stablehlo.constant dense<-1259.1392167224028> : tensor<f64>
// CHECK:           %[[CONSTANT_7:.*]] = stablehlo.constant dense<2.000000e+00> : tensor<f64>
// CHECK:           %[[ADD_2:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_7]] : tensor<f64>
// CHECK:           %[[MULTIPLY_1:.*]] = stablehlo.multiply %[[ADD_2]], %[[ADD_2]] : tensor<f64>
// CHECK:           %[[DIVIDE_2:.*]] = stablehlo.divide %[[CONSTANT_6]], %[[MULTIPLY_1]] : tensor<f64>
// CHECK:           %[[SUBTRACT_2:.*]] = stablehlo.subtract %[[SUBTRACT_1]], %[[DIVIDE_2]] : tensor<f64>
// CHECK:           %[[DIVIDE_3:.*]] = stablehlo.divide %[[CONSTANT_6]], %[[ADD_2]] : tensor<f64>
// CHECK:           %[[ADD_3:.*]] = stablehlo.add %[[ADD_1]], %[[DIVIDE_3]] : tensor<f64>
// CHECK:           %[[CONSTANT_8:.*]] = stablehlo.constant dense<771.32342877765313> : tensor<f64>
// CHECK:           %[[CONSTANT_9:.*]] = stablehlo.constant dense<3.000000e+00> : tensor<f64>
// CHECK:           %[[ADD_4:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_9]] : tensor<f64>
// CHECK:           %[[MULTIPLY_2:.*]] = stablehlo.multiply %[[ADD_4]], %[[ADD_4]] : tensor<f64>
// CHECK:           %[[DIVIDE_4:.*]] = stablehlo.divide %[[CONSTANT_8]], %[[MULTIPLY_2]] : tensor<f64>
// CHECK:           %[[SUBTRACT_3:.*]] = stablehlo.subtract %[[SUBTRACT_2]], %[[DIVIDE_4]] : tensor<f64>
// CHECK:           %[[DIVIDE_5:.*]] = stablehlo.divide %[[CONSTANT_8]], %[[ADD_4]] : tensor<f64>
// CHECK:           %[[ADD_5:.*]] = stablehlo.add %[[ADD_3]], %[[DIVIDE_5]] : tensor<f64>
// CHECK:           %[[CONSTANT_10:.*]] = stablehlo.constant dense<-176.61502916214059> : tensor<f64>
// CHECK:           %[[CONSTANT_11:.*]] = stablehlo.constant dense<4.000000e+00> : tensor<f64>
// CHECK:           %[[ADD_6:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_11]] : tensor<f64>
// CHECK:           %[[MULTIPLY_3:.*]] = stablehlo.multiply %[[ADD_6]], %[[ADD_6]] : tensor<f64>
// CHECK:           %[[DIVIDE_6:.*]] = stablehlo.divide %[[CONSTANT_10]], %[[MULTIPLY_3]] : tensor<f64>
// CHECK:           %[[SUBTRACT_4:.*]] = stablehlo.subtract %[[SUBTRACT_3]], %[[DIVIDE_6]] : tensor<f64>
// CHECK:           %[[DIVIDE_7:.*]] = stablehlo.divide %[[CONSTANT_10]], %[[ADD_6]] : tensor<f64>
// CHECK:           %[[ADD_7:.*]] = stablehlo.add %[[ADD_5]], %[[DIVIDE_7]] : tensor<f64>
// CHECK:           %[[CONSTANT_12:.*]] = stablehlo.constant dense<12.507343278686905> : tensor<f64>
// CHECK:           %[[CONSTANT_13:.*]] = stablehlo.constant dense<5.000000e+00> : tensor<f64>
// CHECK:           %[[ADD_8:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_13]] : tensor<f64>
// CHECK:           %[[MULTIPLY_4:.*]] = stablehlo.multiply %[[ADD_8]], %[[ADD_8]] : tensor<f64>
// CHECK:           %[[DIVIDE_8:.*]] = stablehlo.divide %[[CONSTANT_12]], %[[MULTIPLY_4]] : tensor<f64>
// CHECK:           %[[SUBTRACT_5:.*]] = stablehlo.subtract %[[SUBTRACT_4]], %[[DIVIDE_8]] : tensor<f64>
// CHECK:           %[[DIVIDE_9:.*]] = stablehlo.divide %[[CONSTANT_12]], %[[ADD_8]] : tensor<f64>
// CHECK:           %[[ADD_9:.*]] = stablehlo.add %[[ADD_7]], %[[DIVIDE_9]] : tensor<f64>
// CHECK:           %[[CONSTANT_14:.*]] = stablehlo.constant dense<-0.13857109526572012> : tensor<f64>
// CHECK:           %[[CONSTANT_15:.*]] = stablehlo.constant dense<6.000000e+00> : tensor<f64>
// CHECK:           %[[ADD_10:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_15]] : tensor<f64>
// CHECK:           %[[MULTIPLY_5:.*]] = stablehlo.multiply %[[ADD_10]], %[[ADD_10]] : tensor<f64>
// CHECK:           %[[DIVIDE_10:.*]] = stablehlo.divide %[[CONSTANT_14]], %[[MULTIPLY_5]] : tensor<f64>
// CHECK:           %[[SUBTRACT_6:.*]] = stablehlo.subtract %[[SUBTRACT_5]], %[[DIVIDE_10]] : tensor<f64>
// CHECK:           %[[DIVIDE_11:.*]] = stablehlo.divide %[[CONSTANT_14]], %[[ADD_10]] : tensor<f64>
// CHECK:           %[[ADD_11:.*]] = stablehlo.add %[[ADD_9]], %[[DIVIDE_11]] : tensor<f64>
// CHECK:           %[[CONSTANT_16:.*]] = stablehlo.constant dense<9.9843695780195716E-6> : tensor<f64>
// CHECK:           %[[CONSTANT_17:.*]] = stablehlo.constant dense<7.000000e+00> : tensor<f64>
// CHECK:           %[[ADD_12:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_17]] : tensor<f64>
// CHECK:           %[[MULTIPLY_6:.*]] = stablehlo.multiply %[[ADD_12]], %[[ADD_12]] : tensor<f64>
// CHECK:           %[[DIVIDE_12:.*]] = stablehlo.divide %[[CONSTANT_16]], %[[MULTIPLY_6]] : tensor<f64>
// CHECK:           %[[SUBTRACT_7:.*]] = stablehlo.subtract %[[SUBTRACT_6]], %[[DIVIDE_12]] : tensor<f64>
// CHECK:           %[[DIVIDE_13:.*]] = stablehlo.divide %[[CONSTANT_16]], %[[ADD_12]] : tensor<f64>
// CHECK:           %[[ADD_13:.*]] = stablehlo.add %[[ADD_11]], %[[DIVIDE_13]] : tensor<f64>
// CHECK:           %[[CONSTANT_18:.*]] = stablehlo.constant dense<1.5056327351493116E-7> : tensor<f64>
// CHECK:           %[[CONSTANT_19:.*]] = stablehlo.constant dense<8.000000e+00> : tensor<f64>
// CHECK:           %[[ADD_14:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_19]] : tensor<f64>
// CHECK:           %[[MULTIPLY_7:.*]] = stablehlo.multiply %[[ADD_14]], %[[ADD_14]] : tensor<f64>
// CHECK:           %[[DIVIDE_14:.*]] = stablehlo.divide %[[CONSTANT_18]], %[[MULTIPLY_7]] : tensor<f64>
// CHECK:           %[[SUBTRACT_8:.*]] = stablehlo.subtract %[[SUBTRACT_7]], %[[DIVIDE_14]] : tensor<f64>
// CHECK:           %[[DIVIDE_15:.*]] = stablehlo.divide %[[CONSTANT_18]], %[[ADD_14]] : tensor<f64>
// CHECK:           %[[ADD_15:.*]] = stablehlo.add %[[ADD_13]], %[[DIVIDE_15]] : tensor<f64>
// CHECK:           %[[CONSTANT_20:.*]] = stablehlo.constant dense<7.500000e+00> : tensor<f64>
// CHECK:           %[[ADD_16:.*]] = stablehlo.add %[[CONSTANT_20]], %[[SELECT_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_21:.*]] = stablehlo.constant dense<2.0149030205422647> : tensor<f64>
// CHECK:           %[[DIVIDE_16:.*]] = stablehlo.divide %[[SELECT_0]], %[[CONSTANT_20]] : tensor<f64>
// CHECK:           %[[LOG_PLUS_ONE_0:.*]] = stablehlo.log_plus_one %[[DIVIDE_16]] : tensor<f64>
// CHECK:           %[[ADD_17:.*]] = stablehlo.add %[[CONSTANT_21]], %[[LOG_PLUS_ONE_0]] : tensor<f64>
// CHECK:           %[[DIVIDE_17:.*]] = stablehlo.divide %[[SUBTRACT_8]], %[[ADD_15]] : tensor<f64>
// CHECK:           %[[CONSTANT_22:.*]] = stablehlo.constant dense<7.000000e+00> : tensor<f64>
// CHECK:           %[[DIVIDE_18:.*]] = stablehlo.divide %[[CONSTANT_22]], %[[ADD_16]] : tensor<f64>
// CHECK:           %[[ADD_18:.*]] = stablehlo.add %[[ADD_17]], %[[DIVIDE_17]] : tensor<f64>
// CHECK:           %[[SUBTRACT_9:.*]] = stablehlo.subtract %[[ADD_18]], %[[DIVIDE_18]] : tensor<f64>
// CHECK:           %[[CONSTANT_23:.*]] = stablehlo.constant dense<5.000000e-01> : tensor<f64>
// CHECK:           %[[ADD_19:.*]] = stablehlo.add %[[ARG0]], %[[CONSTANT_23]] : tensor<f64>
// CHECK:           %[[FLOOR_0:.*]] = stablehlo.floor %[[ADD_19]] : tensor<f64>
// CHECK:           %[[ABS_0:.*]] = stablehlo.abs %[[FLOOR_0]] : tensor<f64>
// CHECK:           %[[ADD_20:.*]] = stablehlo.add %[[ARG0]], %[[ABS_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_24:.*]] = stablehlo.constant dense<3.1415926535897931> : tensor<f64>
// CHECK:           %[[MULTIPLY_8:.*]] = stablehlo.multiply %[[CONSTANT_24]], %[[ADD_20]] : tensor<f64>
// CHECK:           %[[COSINE_0:.*]] = stablehlo.cosine %[[MULTIPLY_8]] : tensor<f64>
// CHECK:           %[[SINE_0:.*]] = stablehlo.sine %[[MULTIPLY_8]] : tensor<f64>
// CHECK:           %[[MULTIPLY_9:.*]] = stablehlo.multiply %[[CONSTANT_24]], %[[COSINE_0]] : tensor<f64>
// CHECK:           %[[DIVIDE_19:.*]] = stablehlo.divide %[[MULTIPLY_9]], %[[SINE_0]] : tensor<f64>
// CHECK:           %[[SUBTRACT_10:.*]] = stablehlo.subtract %[[SUBTRACT_9]], %[[DIVIDE_19]] : tensor<f64>
// CHECK:           %[[SELECT_1:.*]] = stablehlo.select %[[COMPARE_0]], %[[SUBTRACT_10]], %[[SUBTRACT_9]] : tensor<i1>, tensor<f64>
// CHECK:           %[[COMPARE_1:.*]] = stablehlo.compare  LE, %[[ARG0]], %[[CONSTANT_2]] : (tensor<f64>, tensor<f64>) -> tensor<i1>
// CHECK:           %[[FLOOR_1:.*]] = stablehlo.floor %[[ARG0]] : tensor<f64>
// CHECK:           %[[COMPARE_2:.*]] = stablehlo.compare  EQ, %[[ARG0]], %[[FLOOR_1]] : (tensor<f64>, tensor<f64>) -> tensor<i1>
// CHECK:           %[[AND_0:.*]] = stablehlo.and %[[COMPARE_1]], %[[COMPARE_2]] : tensor<i1>
// CHECK:           %[[CONSTANT_25:.*]] = stablehlo.constant dense<0x7FF8000000000000> : tensor<f64>
// CHECK:           %[[SELECT_2:.*]] = stablehlo.select %[[AND_0]], %[[CONSTANT_25]], %[[SELECT_1]] : tensor<i1>, tensor<f64>
// CHECK:           return %[[SELECT_2]] : tensor<f64>
// CHECK:         }
func.func @digamma_f64(%arg : tensor<f64>) -> tensor<f64> {
  %1 = chlo.digamma %arg : tensor<f64> -> tensor<f64>
  func.return %1 : tensor<f64>
}

// -----

// CHECK-LABEL:   func.func @digamma_f32(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<f32>) -> tensor<f32> {
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<5.000000e-01> : tensor<f32>
// CHECK:           %[[COMPARE_0:.*]] = stablehlo.compare  LT, %[[ARG0]], %[[CONSTANT_0]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[NEGATE_0:.*]] = stablehlo.negate %[[ARG0]] : tensor<f32>
// CHECK:           %[[CONSTANT_1:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[SUBTRACT_0:.*]] = stablehlo.subtract %[[ARG0]], %[[CONSTANT_1]] : tensor<f32>
// CHECK:           %[[SELECT_0:.*]] = stablehlo.select %[[COMPARE_0]], %[[NEGATE_0]], %[[SUBTRACT_0]] : tensor<i1>, tensor<f32>
// CHECK:           %[[CONSTANT_2:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<f32>
// CHECK:           %[[CONSTANT_3:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[CONSTANT_4:.*]] = stablehlo.constant dense<676.520386> : tensor<f32>
// CHECK:           %[[CONSTANT_5:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_0:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_5]] : tensor<f32>
// CHECK:           %[[MULTIPLY_0:.*]] = stablehlo.multiply %[[ADD_0]], %[[ADD_0]] : tensor<f32>
// CHECK:           %[[DIVIDE_0:.*]] = stablehlo.divide %[[CONSTANT_4]], %[[MULTIPLY_0]] : tensor<f32>
// CHECK:           %[[SUBTRACT_1:.*]] = stablehlo.subtract %[[CONSTANT_2]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[DIVIDE_1:.*]] = stablehlo.divide %[[CONSTANT_4]], %[[ADD_0]] : tensor<f32>
// CHECK:           %[[ADD_1:.*]] = stablehlo.add %[[CONSTANT_3]], %[[DIVIDE_1]] : tensor<f32>
// CHECK:           %[[CONSTANT_6:.*]] = stablehlo.constant dense<-1259.13916> : tensor<f32>
// CHECK:           %[[CONSTANT_7:.*]] = stablehlo.constant dense<2.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_2:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_7]] : tensor<f32>
// CHECK:           %[[MULTIPLY_1:.*]] = stablehlo.multiply %[[ADD_2]], %[[ADD_2]] : tensor<f32>
// CHECK:           %[[DIVIDE_2:.*]] = stablehlo.divide %[[CONSTANT_6]], %[[MULTIPLY_1]] : tensor<f32>
// CHECK:           %[[SUBTRACT_2:.*]] = stablehlo.subtract %[[SUBTRACT_1]], %[[DIVIDE_2]] : tensor<f32>
// CHECK:           %[[DIVIDE_3:.*]] = stablehlo.divide %[[CONSTANT_6]], %[[ADD_2]] : tensor<f32>
// CHECK:           %[[ADD_3:.*]] = stablehlo.add %[[ADD_1]], %[[DIVIDE_3]] : tensor<f32>
// CHECK:           %[[CONSTANT_8:.*]] = stablehlo.constant dense<771.323425> : tensor<f32>
// CHECK:           %[[CONSTANT_9:.*]] = stablehlo.constant dense<3.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_4:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_9]] : tensor<f32>
// CHECK:           %[[MULTIPLY_2:.*]] = stablehlo.multiply %[[ADD_4]], %[[ADD_4]] : tensor<f32>
// CHECK:           %[[DIVIDE_4:.*]] = stablehlo.divide %[[CONSTANT_8]], %[[MULTIPLY_2]] : tensor<f32>
// CHECK:           %[[SUBTRACT_3:.*]] = stablehlo.subtract %[[SUBTRACT_2]], %[[DIVIDE_4]] : tensor<f32>
// CHECK:           %[[DIVIDE_5:.*]] = stablehlo.divide %[[CONSTANT_8]], %[[ADD_4]] : tensor<f32>
// CHECK:           %[[ADD_5:.*]] = stablehlo.add %[[ADD_3]], %[[DIVIDE_5]] : tensor<f32>
// CHECK:           %[[CONSTANT_10:.*]] = stablehlo.constant dense<-176.615036> : tensor<f32>
// CHECK:           %[[CONSTANT_11:.*]] = stablehlo.constant dense<4.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_6:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_11]] : tensor<f32>
// CHECK:           %[[MULTIPLY_3:.*]] = stablehlo.multiply %[[ADD_6]], %[[ADD_6]] : tensor<f32>
// CHECK:           %[[DIVIDE_6:.*]] = stablehlo.divide %[[CONSTANT_10]], %[[MULTIPLY_3]] : tensor<f32>
// CHECK:           %[[SUBTRACT_4:.*]] = stablehlo.subtract %[[SUBTRACT_3]], %[[DIVIDE_6]] : tensor<f32>
// CHECK:           %[[DIVIDE_7:.*]] = stablehlo.divide %[[CONSTANT_10]], %[[ADD_6]] : tensor<f32>
// CHECK:           %[[ADD_7:.*]] = stablehlo.add %[[ADD_5]], %[[DIVIDE_7]] : tensor<f32>
// CHECK:           %[[CONSTANT_12:.*]] = stablehlo.constant dense<12.5073433> : tensor<f32>
// CHECK:           %[[CONSTANT_13:.*]] = stablehlo.constant dense<5.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_8:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_13]] : tensor<f32>
// CHECK:           %[[MULTIPLY_4:.*]] = stablehlo.multiply %[[ADD_8]], %[[ADD_8]] : tensor<f32>
// CHECK:           %[[DIVIDE_8:.*]] = stablehlo.divide %[[CONSTANT_12]], %[[MULTIPLY_4]] : tensor<f32>
// CHECK:           %[[SUBTRACT_5:.*]] = stablehlo.subtract %[[SUBTRACT_4]], %[[DIVIDE_8]] : tensor<f32>
// CHECK:           %[[DIVIDE_9:.*]] = stablehlo.divide %[[CONSTANT_12]], %[[ADD_8]] : tensor<f32>
// CHECK:           %[[ADD_9:.*]] = stablehlo.add %[[ADD_7]], %[[DIVIDE_9]] : tensor<f32>
// CHECK:           %[[CONSTANT_14:.*]] = stablehlo.constant dense<-0.138571098> : tensor<f32>
// CHECK:           %[[CONSTANT_15:.*]] = stablehlo.constant dense<6.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_10:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_15]] : tensor<f32>
// CHECK:           %[[MULTIPLY_5:.*]] = stablehlo.multiply %[[ADD_10]], %[[ADD_10]] : tensor<f32>
// CHECK:           %[[DIVIDE_10:.*]] = stablehlo.divide %[[CONSTANT_14]], %[[MULTIPLY_5]] : tensor<f32>
// CHECK:           %[[SUBTRACT_6:.*]] = stablehlo.subtract %[[SUBTRACT_5]], %[[DIVIDE_10]] : tensor<f32>
// CHECK:           %[[DIVIDE_11:.*]] = stablehlo.divide %[[CONSTANT_14]], %[[ADD_10]] : tensor<f32>
// CHECK:           %[[ADD_11:.*]] = stablehlo.add %[[ADD_9]], %[[DIVIDE_11]] : tensor<f32>
// CHECK:           %[[CONSTANT_16:.*]] = stablehlo.constant dense<9.98436917E-6> : tensor<f32>
// CHECK:           %[[CONSTANT_17:.*]] = stablehlo.constant dense<7.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_12:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_17]] : tensor<f32>
// CHECK:           %[[MULTIPLY_6:.*]] = stablehlo.multiply %[[ADD_12]], %[[ADD_12]] : tensor<f32>
// CHECK:           %[[DIVIDE_12:.*]] = stablehlo.divide %[[CONSTANT_16]], %[[MULTIPLY_6]] : tensor<f32>
// CHECK:           %[[SUBTRACT_7:.*]] = stablehlo.subtract %[[SUBTRACT_6]], %[[DIVIDE_12]] : tensor<f32>
// CHECK:           %[[DIVIDE_13:.*]] = stablehlo.divide %[[CONSTANT_16]], %[[ADD_12]] : tensor<f32>
// CHECK:           %[[ADD_13:.*]] = stablehlo.add %[[ADD_11]], %[[DIVIDE_13]] : tensor<f32>
// CHECK:           %[[CONSTANT_18:.*]] = stablehlo.constant dense<1.50563267E-7> : tensor<f32>
// CHECK:           %[[CONSTANT_19:.*]] = stablehlo.constant dense<8.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_14:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_19]] : tensor<f32>
// CHECK:           %[[MULTIPLY_7:.*]] = stablehlo.multiply %[[ADD_14]], %[[ADD_14]] : tensor<f32>
// CHECK:           %[[DIVIDE_14:.*]] = stablehlo.divide %[[CONSTANT_18]], %[[MULTIPLY_7]] : tensor<f32>
// CHECK:           %[[SUBTRACT_8:.*]] = stablehlo.subtract %[[SUBTRACT_7]], %[[DIVIDE_14]] : tensor<f32>
// CHECK:           %[[DIVIDE_15:.*]] = stablehlo.divide %[[CONSTANT_18]], %[[ADD_14]] : tensor<f32>
// CHECK:           %[[ADD_15:.*]] = stablehlo.add %[[ADD_13]], %[[DIVIDE_15]] : tensor<f32>
// CHECK:           %[[CONSTANT_20:.*]] = stablehlo.constant dense<7.500000e+00> : tensor<f32>
// CHECK:           %[[ADD_16:.*]] = stablehlo.add %[[CONSTANT_20]], %[[SELECT_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_21:.*]] = stablehlo.constant dense<2.01490307> : tensor<f32>
// CHECK:           %[[DIVIDE_16:.*]] = stablehlo.divide %[[SELECT_0]], %[[CONSTANT_20]] : tensor<f32>
// CHECK:           %[[LOG_PLUS_ONE_0:.*]] = stablehlo.log_plus_one %[[DIVIDE_16]] : tensor<f32>
// CHECK:           %[[ADD_17:.*]] = stablehlo.add %[[CONSTANT_21]], %[[LOG_PLUS_ONE_0]] : tensor<f32>
// CHECK:           %[[DIVIDE_17:.*]] = stablehlo.divide %[[SUBTRACT_8]], %[[ADD_15]] : tensor<f32>
// CHECK:           %[[CONSTANT_22:.*]] = stablehlo.constant dense<7.000000e+00> : tensor<f32>
// CHECK:           %[[DIVIDE_18:.*]] = stablehlo.divide %[[CONSTANT_22]], %[[ADD_16]] : tensor<f32>
// CHECK:           %[[ADD_18:.*]] = stablehlo.add %[[ADD_17]], %[[DIVIDE_17]] : tensor<f32>
// CHECK:           %[[SUBTRACT_9:.*]] = stablehlo.subtract %[[ADD_18]], %[[DIVIDE_18]] : tensor<f32>
// CHECK:           %[[CONSTANT_23:.*]] = stablehlo.constant dense<5.000000e-01> : tensor<f32>
// CHECK:           %[[ADD_19:.*]] = stablehlo.add %[[ARG0]], %[[CONSTANT_23]] : tensor<f32>
// CHECK:           %[[FLOOR_0:.*]] = stablehlo.floor %[[ADD_19]] : tensor<f32>
// CHECK:           %[[ABS_0:.*]] = stablehlo.abs %[[FLOOR_0]] : tensor<f32>
// CHECK:           %[[ADD_20:.*]] = stablehlo.add %[[ARG0]], %[[ABS_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_24:.*]] = stablehlo.constant dense<3.14159274> : tensor<f32>
// CHECK:           %[[MULTIPLY_8:.*]] = stablehlo.multiply %[[CONSTANT_24]], %[[ADD_20]] : tensor<f32>
// CHECK:           %[[COSINE_0:.*]] = stablehlo.cosine %[[MULTIPLY_8]] : tensor<f32>
// CHECK:           %[[SINE_0:.*]] = stablehlo.sine %[[MULTIPLY_8]] : tensor<f32>
// CHECK:           %[[MULTIPLY_9:.*]] = stablehlo.multiply %[[CONSTANT_24]], %[[COSINE_0]] : tensor<f32>
// CHECK:           %[[DIVIDE_19:.*]] = stablehlo.divide %[[MULTIPLY_9]], %[[SINE_0]] : tensor<f32>
// CHECK:           %[[SUBTRACT_10:.*]] = stablehlo.subtract %[[SUBTRACT_9]], %[[DIVIDE_19]] : tensor<f32>
// CHECK:           %[[SELECT_1:.*]] = stablehlo.select %[[COMPARE_0]], %[[SUBTRACT_10]], %[[SUBTRACT_9]] : tensor<i1>, tensor<f32>
// CHECK:           %[[COMPARE_1:.*]] = stablehlo.compare  LE, %[[ARG0]], %[[CONSTANT_2]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[FLOOR_1:.*]] = stablehlo.floor %[[ARG0]] : tensor<f32>
// CHECK:           %[[COMPARE_2:.*]] = stablehlo.compare  EQ, %[[ARG0]], %[[FLOOR_1]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[AND_0:.*]] = stablehlo.and %[[COMPARE_1]], %[[COMPARE_2]] : tensor<i1>
// CHECK:           %[[CONSTANT_25:.*]] = stablehlo.constant dense<0x7FC00000> : tensor<f32>
// CHECK:           %[[SELECT_2:.*]] = stablehlo.select %[[AND_0]], %[[CONSTANT_25]], %[[SELECT_1]] : tensor<i1>, tensor<f32>
// CHECK:           return %[[SELECT_2]] : tensor<f32>
// CHECK:         }
func.func @digamma_f32(%arg : tensor<f32>) -> tensor<f32> {
  %1 = chlo.digamma %arg : tensor<f32> -> tensor<f32>
  func.return %1 : tensor<f32>
}

// -----

// CHECK-LABEL:   func.func @digamma_f16(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<f16>) -> tensor<f16> {
// CHECK:           %[[CONVERT_0:.*]] = stablehlo.convert %[[ARG0]] : (tensor<f16>) -> tensor<f32>
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<5.000000e-01> : tensor<f32>
// CHECK:           %[[COMPARE_0:.*]] = stablehlo.compare  LT, %[[CONVERT_0]], %[[CONSTANT_0]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[NEGATE_0:.*]] = stablehlo.negate %[[CONVERT_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_1:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[SUBTRACT_0:.*]] = stablehlo.subtract %[[CONVERT_0]], %[[CONSTANT_1]] : tensor<f32>
// CHECK:           %[[SELECT_0:.*]] = stablehlo.select %[[COMPARE_0]], %[[NEGATE_0]], %[[SUBTRACT_0]] : tensor<i1>, tensor<f32>
// CHECK:           %[[CONSTANT_2:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<f32>
// CHECK:           %[[CONSTANT_3:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[CONSTANT_4:.*]] = stablehlo.constant dense<676.520386> : tensor<f32>
// CHECK:           %[[CONSTANT_5:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_0:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_5]] : tensor<f32>
// CHECK:           %[[MULTIPLY_0:.*]] = stablehlo.multiply %[[ADD_0]], %[[ADD_0]] : tensor<f32>
// CHECK:           %[[DIVIDE_0:.*]] = stablehlo.divide %[[CONSTANT_4]], %[[MULTIPLY_0]] : tensor<f32>
// CHECK:           %[[SUBTRACT_1:.*]] = stablehlo.subtract %[[CONSTANT_2]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[DIVIDE_1:.*]] = stablehlo.divide %[[CONSTANT_4]], %[[ADD_0]] : tensor<f32>
// CHECK:           %[[ADD_1:.*]] = stablehlo.add %[[CONSTANT_3]], %[[DIVIDE_1]] : tensor<f32>
// CHECK:           %[[CONSTANT_6:.*]] = stablehlo.constant dense<-1259.13916> : tensor<f32>
// CHECK:           %[[CONSTANT_7:.*]] = stablehlo.constant dense<2.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_2:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_7]] : tensor<f32>
// CHECK:           %[[MULTIPLY_1:.*]] = stablehlo.multiply %[[ADD_2]], %[[ADD_2]] : tensor<f32>
// CHECK:           %[[DIVIDE_2:.*]] = stablehlo.divide %[[CONSTANT_6]], %[[MULTIPLY_1]] : tensor<f32>
// CHECK:           %[[SUBTRACT_2:.*]] = stablehlo.subtract %[[SUBTRACT_1]], %[[DIVIDE_2]] : tensor<f32>
// CHECK:           %[[DIVIDE_3:.*]] = stablehlo.divide %[[CONSTANT_6]], %[[ADD_2]] : tensor<f32>
// CHECK:           %[[ADD_3:.*]] = stablehlo.add %[[ADD_1]], %[[DIVIDE_3]] : tensor<f32>
// CHECK:           %[[CONSTANT_8:.*]] = stablehlo.constant dense<771.323425> : tensor<f32>
// CHECK:           %[[CONSTANT_9:.*]] = stablehlo.constant dense<3.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_4:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_9]] : tensor<f32>
// CHECK:           %[[MULTIPLY_2:.*]] = stablehlo.multiply %[[ADD_4]], %[[ADD_4]] : tensor<f32>
// CHECK:           %[[DIVIDE_4:.*]] = stablehlo.divide %[[CONSTANT_8]], %[[MULTIPLY_2]] : tensor<f32>
// CHECK:           %[[SUBTRACT_3:.*]] = stablehlo.subtract %[[SUBTRACT_2]], %[[DIVIDE_4]] : tensor<f32>
// CHECK:           %[[DIVIDE_5:.*]] = stablehlo.divide %[[CONSTANT_8]], %[[ADD_4]] : tensor<f32>
// CHECK:           %[[ADD_5:.*]] = stablehlo.add %[[ADD_3]], %[[DIVIDE_5]] : tensor<f32>
// CHECK:           %[[CONSTANT_10:.*]] = stablehlo.constant dense<-176.615036> : tensor<f32>
// CHECK:           %[[CONSTANT_11:.*]] = stablehlo.constant dense<4.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_6:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_11]] : tensor<f32>
// CHECK:           %[[MULTIPLY_3:.*]] = stablehlo.multiply %[[ADD_6]], %[[ADD_6]] : tensor<f32>
// CHECK:           %[[DIVIDE_6:.*]] = stablehlo.divide %[[CONSTANT_10]], %[[MULTIPLY_3]] : tensor<f32>
// CHECK:           %[[SUBTRACT_4:.*]] = stablehlo.subtract %[[SUBTRACT_3]], %[[DIVIDE_6]] : tensor<f32>
// CHECK:           %[[DIVIDE_7:.*]] = stablehlo.divide %[[CONSTANT_10]], %[[ADD_6]] : tensor<f32>
// CHECK:           %[[ADD_7:.*]] = stablehlo.add %[[ADD_5]], %[[DIVIDE_7]] : tensor<f32>
// CHECK:           %[[CONSTANT_12:.*]] = stablehlo.constant dense<12.5073433> : tensor<f32>
// CHECK:           %[[CONSTANT_13:.*]] = stablehlo.constant dense<5.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_8:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_13]] : tensor<f32>
// CHECK:           %[[MULTIPLY_4:.*]] = stablehlo.multiply %[[ADD_8]], %[[ADD_8]] : tensor<f32>
// CHECK:           %[[DIVIDE_8:.*]] = stablehlo.divide %[[CONSTANT_12]], %[[MULTIPLY_4]] : tensor<f32>
// CHECK:           %[[SUBTRACT_5:.*]] = stablehlo.subtract %[[SUBTRACT_4]], %[[DIVIDE_8]] : tensor<f32>
// CHECK:           %[[DIVIDE_9:.*]] = stablehlo.divide %[[CONSTANT_12]], %[[ADD_8]] : tensor<f32>
// CHECK:           %[[ADD_9:.*]] = stablehlo.add %[[ADD_7]], %[[DIVIDE_9]] : tensor<f32>
// CHECK:           %[[CONSTANT_14:.*]] = stablehlo.constant dense<-0.138571098> : tensor<f32>
// CHECK:           %[[CONSTANT_15:.*]] = stablehlo.constant dense<6.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_10:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_15]] : tensor<f32>
// CHECK:           %[[MULTIPLY_5:.*]] = stablehlo.multiply %[[ADD_10]], %[[ADD_10]] : tensor<f32>
// CHECK:           %[[DIVIDE_10:.*]] = stablehlo.divide %[[CONSTANT_14]], %[[MULTIPLY_5]] : tensor<f32>
// CHECK:           %[[SUBTRACT_6:.*]] = stablehlo.subtract %[[SUBTRACT_5]], %[[DIVIDE_10]] : tensor<f32>
// CHECK:           %[[DIVIDE_11:.*]] = stablehlo.divide %[[CONSTANT_14]], %[[ADD_10]] : tensor<f32>
// CHECK:           %[[ADD_11:.*]] = stablehlo.add %[[ADD_9]], %[[DIVIDE_11]] : tensor<f32>
// CHECK:           %[[CONSTANT_16:.*]] = stablehlo.constant dense<9.98436917E-6> : tensor<f32>
// CHECK:           %[[CONSTANT_17:.*]] = stablehlo.constant dense<7.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_12:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_17]] : tensor<f32>
// CHECK:           %[[MULTIPLY_6:.*]] = stablehlo.multiply %[[ADD_12]], %[[ADD_12]] : tensor<f32>
// CHECK:           %[[DIVIDE_12:.*]] = stablehlo.divide %[[CONSTANT_16]], %[[MULTIPLY_6]] : tensor<f32>
// CHECK:           %[[SUBTRACT_7:.*]] = stablehlo.subtract %[[SUBTRACT_6]], %[[DIVIDE_12]] : tensor<f32>
// CHECK:           %[[DIVIDE_13:.*]] = stablehlo.divide %[[CONSTANT_16]], %[[ADD_12]] : tensor<f32>
// CHECK:           %[[ADD_13:.*]] = stablehlo.add %[[ADD_11]], %[[DIVIDE_13]] : tensor<f32>
// CHECK:           %[[CONSTANT_18:.*]] = stablehlo.constant dense<1.50563267E-7> : tensor<f32>
// CHECK:           %[[CONSTANT_19:.*]] = stablehlo.constant dense<8.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_14:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_19]] : tensor<f32>
// CHECK:           %[[MULTIPLY_7:.*]] = stablehlo.multiply %[[ADD_14]], %[[ADD_14]] : tensor<f32>
// CHECK:           %[[DIVIDE_14:.*]] = stablehlo.divide %[[CONSTANT_18]], %[[MULTIPLY_7]] : tensor<f32>
// CHECK:           %[[SUBTRACT_8:.*]] = stablehlo.subtract %[[SUBTRACT_7]], %[[DIVIDE_14]] : tensor<f32>
// CHECK:           %[[DIVIDE_15:.*]] = stablehlo.divide %[[CONSTANT_18]], %[[ADD_14]] : tensor<f32>
// CHECK:           %[[ADD_15:.*]] = stablehlo.add %[[ADD_13]], %[[DIVIDE_15]] : tensor<f32>
// CHECK:           %[[CONSTANT_20:.*]] = stablehlo.constant dense<7.500000e+00> : tensor<f32>
// CHECK:           %[[ADD_16:.*]] = stablehlo.add %[[CONSTANT_20]], %[[SELECT_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_21:.*]] = stablehlo.constant dense<2.01490307> : tensor<f32>
// CHECK:           %[[DIVIDE_16:.*]] = stablehlo.divide %[[SELECT_0]], %[[CONSTANT_20]] : tensor<f32>
// CHECK:           %[[LOG_PLUS_ONE_0:.*]] = stablehlo.log_plus_one %[[DIVIDE_16]] : tensor<f32>
// CHECK:           %[[ADD_17:.*]] = stablehlo.add %[[CONSTANT_21]], %[[LOG_PLUS_ONE_0]] : tensor<f32>
// CHECK:           %[[DIVIDE_17:.*]] = stablehlo.divide %[[SUBTRACT_8]], %[[ADD_15]] : tensor<f32>
// CHECK:           %[[CONSTANT_22:.*]] = stablehlo.constant dense<7.000000e+00> : tensor<f32>
// CHECK:           %[[DIVIDE_18:.*]] = stablehlo.divide %[[CONSTANT_22]], %[[ADD_16]] : tensor<f32>
// CHECK:           %[[ADD_18:.*]] = stablehlo.add %[[ADD_17]], %[[DIVIDE_17]] : tensor<f32>
// CHECK:           %[[SUBTRACT_9:.*]] = stablehlo.subtract %[[ADD_18]], %[[DIVIDE_18]] : tensor<f32>
// CHECK:           %[[CONSTANT_23:.*]] = stablehlo.constant dense<5.000000e-01> : tensor<f32>
// CHECK:           %[[ADD_19:.*]] = stablehlo.add %[[CONVERT_0]], %[[CONSTANT_23]] : tensor<f32>
// CHECK:           %[[FLOOR_0:.*]] = stablehlo.floor %[[ADD_19]] : tensor<f32>
// CHECK:           %[[ABS_0:.*]] = stablehlo.abs %[[FLOOR_0]] : tensor<f32>
// CHECK:           %[[ADD_20:.*]] = stablehlo.add %[[CONVERT_0]], %[[ABS_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_24:.*]] = stablehlo.constant dense<3.14159274> : tensor<f32>
// CHECK:           %[[MULTIPLY_8:.*]] = stablehlo.multiply %[[CONSTANT_24]], %[[ADD_20]] : tensor<f32>
// CHECK:           %[[COSINE_0:.*]] = stablehlo.cosine %[[MULTIPLY_8]] : tensor<f32>
// CHECK:           %[[SINE_0:.*]] = stablehlo.sine %[[MULTIPLY_8]] : tensor<f32>
// CHECK:           %[[MULTIPLY_9:.*]] = stablehlo.multiply %[[CONSTANT_24]], %[[COSINE_0]] : tensor<f32>
// CHECK:           %[[DIVIDE_19:.*]] = stablehlo.divide %[[MULTIPLY_9]], %[[SINE_0]] : tensor<f32>
// CHECK:           %[[SUBTRACT_10:.*]] = stablehlo.subtract %[[SUBTRACT_9]], %[[DIVIDE_19]] : tensor<f32>
// CHECK:           %[[SELECT_1:.*]] = stablehlo.select %[[COMPARE_0]], %[[SUBTRACT_10]], %[[SUBTRACT_9]] : tensor<i1>, tensor<f32>
// CHECK:           %[[COMPARE_1:.*]] = stablehlo.compare  LE, %[[CONVERT_0]], %[[CONSTANT_2]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[FLOOR_1:.*]] = stablehlo.floor %[[CONVERT_0]] : tensor<f32>
// CHECK:           %[[COMPARE_2:.*]] = stablehlo.compare  EQ, %[[CONVERT_0]], %[[FLOOR_1]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[AND_0:.*]] = stablehlo.and %[[COMPARE_1]], %[[COMPARE_2]] : tensor<i1>
// CHECK:           %[[CONSTANT_25:.*]] = stablehlo.constant dense<0x7FC00000> : tensor<f32>
// CHECK:           %[[SELECT_2:.*]] = stablehlo.select %[[AND_0]], %[[CONSTANT_25]], %[[SELECT_1]] : tensor<i1>, tensor<f32>
// CHECK:           %[[CONVERT_1:.*]] = stablehlo.convert %[[SELECT_2]] : (tensor<f32>) -> tensor<f16>
// CHECK:           return %[[CONVERT_1]] : tensor<f16>
// CHECK:         }
func.func @digamma_f16(%arg : tensor<f16>) -> tensor<f16> {
  %1 = chlo.digamma %arg : tensor<f16> -> tensor<f16>
  func.return %1 : tensor<f16>
}

// -----

// CHECK-LABEL:   func.func @zeta_f16(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<f16>,
// CHECK-SAME:      %[[ARG1:.*]]: tensor<f16>) -> tensor<f16> {
// CHECK:           %[[CONVERT_0:.*]] = stablehlo.convert %[[ARG0]] : (tensor<f16>) -> tensor<f32>
// CHECK:           %[[CONVERT_1:.*]] = stablehlo.convert %[[ARG1]] : (tensor<f16>) -> tensor<f32>
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<f32>
// CHECK:           %[[CONSTANT_1:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[NEGATE_0:.*]] = stablehlo.negate %[[CONVERT_0]] : tensor<f32>
// CHECK:           %[[POWER_0:.*]] = stablehlo.power %[[CONVERT_1]], %[[NEGATE_0]] : tensor<f32>
// CHECK:           %[[ADD_0:.*]] = stablehlo.add %[[CONVERT_1]], %[[CONSTANT_1]] : tensor<f32>
// CHECK:           %[[POWER_1:.*]] = stablehlo.power %[[ADD_0]], %[[NEGATE_0]] : tensor<f32>
// CHECK:           %[[ADD_1:.*]] = stablehlo.add %[[POWER_0]], %[[POWER_1]] : tensor<f32>
// CHECK:           %[[ADD_2:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_1]] : tensor<f32>
// CHECK:           %[[POWER_2:.*]] = stablehlo.power %[[ADD_2]], %[[NEGATE_0]] : tensor<f32>
// CHECK:           %[[ADD_3:.*]] = stablehlo.add %[[ADD_1]], %[[POWER_2]] : tensor<f32>
// CHECK:           %[[ADD_4:.*]] = stablehlo.add %[[ADD_2]], %[[CONSTANT_1]] : tensor<f32>
// CHECK:           %[[POWER_3:.*]] = stablehlo.power %[[ADD_4]], %[[NEGATE_0]] : tensor<f32>
// CHECK:           %[[ADD_5:.*]] = stablehlo.add %[[ADD_3]], %[[POWER_3]] : tensor<f32>
// CHECK:           %[[ADD_6:.*]] = stablehlo.add %[[ADD_4]], %[[CONSTANT_1]] : tensor<f32>
// CHECK:           %[[POWER_4:.*]] = stablehlo.power %[[ADD_6]], %[[NEGATE_0]] : tensor<f32>
// CHECK:           %[[ADD_7:.*]] = stablehlo.add %[[ADD_5]], %[[POWER_4]] : tensor<f32>
// CHECK:           %[[ADD_8:.*]] = stablehlo.add %[[ADD_6]], %[[CONSTANT_1]] : tensor<f32>
// CHECK:           %[[POWER_5:.*]] = stablehlo.power %[[ADD_8]], %[[NEGATE_0]] : tensor<f32>
// CHECK:           %[[ADD_9:.*]] = stablehlo.add %[[ADD_7]], %[[POWER_5]] : tensor<f32>
// CHECK:           %[[ADD_10:.*]] = stablehlo.add %[[ADD_8]], %[[CONSTANT_1]] : tensor<f32>
// CHECK:           %[[POWER_6:.*]] = stablehlo.power %[[ADD_10]], %[[NEGATE_0]] : tensor<f32>
// CHECK:           %[[ADD_11:.*]] = stablehlo.add %[[ADD_9]], %[[POWER_6]] : tensor<f32>
// CHECK:           %[[ADD_12:.*]] = stablehlo.add %[[ADD_10]], %[[CONSTANT_1]] : tensor<f32>
// CHECK:           %[[POWER_7:.*]] = stablehlo.power %[[ADD_12]], %[[NEGATE_0]] : tensor<f32>
// CHECK:           %[[ADD_13:.*]] = stablehlo.add %[[ADD_11]], %[[POWER_7]] : tensor<f32>
// CHECK:           %[[ADD_14:.*]] = stablehlo.add %[[ADD_12]], %[[CONSTANT_1]] : tensor<f32>
// CHECK:           %[[POWER_8:.*]] = stablehlo.power %[[ADD_14]], %[[NEGATE_0]] : tensor<f32>
// CHECK:           %[[ADD_15:.*]] = stablehlo.add %[[ADD_13]], %[[POWER_8]] : tensor<f32>
// CHECK:           %[[ADD_16:.*]] = stablehlo.add %[[ADD_14]], %[[CONSTANT_1]] : tensor<f32>
// CHECK:           %[[POWER_9:.*]] = stablehlo.power %[[ADD_16]], %[[NEGATE_0]] : tensor<f32>
// CHECK:           %[[ADD_17:.*]] = stablehlo.add %[[ADD_15]], %[[POWER_9]] : tensor<f32>
// CHECK:           %[[ADD_18:.*]] = stablehlo.add %[[ADD_16]], %[[CONSTANT_1]] : tensor<f32>
// CHECK:           %[[POWER_10:.*]] = stablehlo.power %[[ADD_18]], %[[NEGATE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_2:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[MULTIPLY_0:.*]] = stablehlo.multiply %[[POWER_10]], %[[ADD_18]] : tensor<f32>
// CHECK:           %[[SUBTRACT_0:.*]] = stablehlo.subtract %[[CONVERT_0]], %[[CONSTANT_2]] : tensor<f32>
// CHECK:           %[[DIVIDE_0:.*]] = stablehlo.divide %[[MULTIPLY_0]], %[[SUBTRACT_0]] : tensor<f32>
// CHECK:           %[[MULTIPLY_1:.*]] = stablehlo.multiply %[[ADD_18]], %[[ADD_18]] : tensor<f32>
// CHECK:           %[[DIVIDE_1:.*]] = stablehlo.divide %[[CONSTANT_1]], %[[MULTIPLY_1]] : tensor<f32>
// CHECK:           %[[CONSTANT_3:.*]] = stablehlo.constant dense<2.200000e+01> : tensor<f32>
// CHECK:           %[[ADD_19:.*]] = stablehlo.add %[[CONVERT_0]], %[[CONSTANT_3]] : tensor<f32>
// CHECK:           %[[CONSTANT_4:.*]] = stablehlo.constant dense<2.100000e+01> : tensor<f32>
// CHECK:           %[[ADD_20:.*]] = stablehlo.add %[[CONVERT_0]], %[[CONSTANT_4]] : tensor<f32>
// CHECK:           %[[MULTIPLY_2:.*]] = stablehlo.multiply %[[ADD_19]], %[[ADD_20]] : tensor<f32>
// CHECK:           %[[CONSTANT_5:.*]] = stablehlo.constant dense<-1.39544646E-19> : tensor<f32>
// CHECK:           %[[ADD_21:.*]] = stablehlo.add %[[CONSTANT_0]], %[[CONSTANT_5]] : tensor<f32>
// CHECK:           %[[MULTIPLY_3:.*]] = stablehlo.multiply %[[DIVIDE_1]], %[[ADD_21]] : tensor<f32>
// CHECK:           %[[MULTIPLY_4:.*]] = stablehlo.multiply %[[MULTIPLY_2]], %[[MULTIPLY_3]] : tensor<f32>
// CHECK:           %[[CONSTANT_6:.*]] = stablehlo.constant dense<2.000000e+01> : tensor<f32>
// CHECK:           %[[ADD_22:.*]] = stablehlo.add %[[CONVERT_0]], %[[CONSTANT_6]] : tensor<f32>
// CHECK:           %[[CONSTANT_7:.*]] = stablehlo.constant dense<1.900000e+01> : tensor<f32>
// CHECK:           %[[ADD_23:.*]] = stablehlo.add %[[CONVERT_0]], %[[CONSTANT_7]] : tensor<f32>
// CHECK:           %[[MULTIPLY_5:.*]] = stablehlo.multiply %[[ADD_22]], %[[ADD_23]] : tensor<f32>
// CHECK:           %[[CONSTANT_8:.*]] = stablehlo.constant dense<5.50900303E-18> : tensor<f32>
// CHECK:           %[[ADD_24:.*]] = stablehlo.add %[[MULTIPLY_4]], %[[CONSTANT_8]] : tensor<f32>
// CHECK:           %[[MULTIPLY_6:.*]] = stablehlo.multiply %[[DIVIDE_1]], %[[ADD_24]] : tensor<f32>
// CHECK:           %[[MULTIPLY_7:.*]] = stablehlo.multiply %[[MULTIPLY_5]], %[[MULTIPLY_6]] : tensor<f32>
// CHECK:           %[[CONSTANT_9:.*]] = stablehlo.constant dense<1.800000e+01> : tensor<f32>
// CHECK:           %[[ADD_25:.*]] = stablehlo.add %[[CONVERT_0]], %[[CONSTANT_9]] : tensor<f32>
// CHECK:           %[[CONSTANT_10:.*]] = stablehlo.constant dense<1.700000e+01> : tensor<f32>
// CHECK:           %[[ADD_26:.*]] = stablehlo.add %[[CONVERT_0]], %[[CONSTANT_10]] : tensor<f32>
// CHECK:           %[[MULTIPLY_8:.*]] = stablehlo.multiply %[[ADD_25]], %[[ADD_26]] : tensor<f32>
// CHECK:           %[[CONSTANT_11:.*]] = stablehlo.constant dense<-2.17486866E-16> : tensor<f32>
// CHECK:           %[[ADD_27:.*]] = stablehlo.add %[[MULTIPLY_7]], %[[CONSTANT_11]] : tensor<f32>
// CHECK:           %[[MULTIPLY_9:.*]] = stablehlo.multiply %[[DIVIDE_1]], %[[ADD_27]] : tensor<f32>
// CHECK:           %[[MULTIPLY_10:.*]] = stablehlo.multiply %[[MULTIPLY_8]], %[[MULTIPLY_9]] : tensor<f32>
// CHECK:           %[[CONSTANT_12:.*]] = stablehlo.constant dense<1.600000e+01> : tensor<f32>
// CHECK:           %[[ADD_28:.*]] = stablehlo.add %[[CONVERT_0]], %[[CONSTANT_12]] : tensor<f32>
// CHECK:           %[[CONSTANT_13:.*]] = stablehlo.constant dense<1.500000e+01> : tensor<f32>
// CHECK:           %[[ADD_29:.*]] = stablehlo.add %[[CONVERT_0]], %[[CONSTANT_13]] : tensor<f32>
// CHECK:           %[[MULTIPLY_11:.*]] = stablehlo.multiply %[[ADD_28]], %[[ADD_29]] : tensor<f32>
// CHECK:           %[[CONSTANT_14:.*]] = stablehlo.constant dense<8.58606213E-15> : tensor<f32>
// CHECK:           %[[ADD_30:.*]] = stablehlo.add %[[MULTIPLY_10]], %[[CONSTANT_14]] : tensor<f32>
// CHECK:           %[[MULTIPLY_12:.*]] = stablehlo.multiply %[[DIVIDE_1]], %[[ADD_30]] : tensor<f32>
// CHECK:           %[[MULTIPLY_13:.*]] = stablehlo.multiply %[[MULTIPLY_11]], %[[MULTIPLY_12]] : tensor<f32>
// CHECK:           %[[CONSTANT_15:.*]] = stablehlo.constant dense<1.400000e+01> : tensor<f32>
// CHECK:           %[[ADD_31:.*]] = stablehlo.add %[[CONVERT_0]], %[[CONSTANT_15]] : tensor<f32>
// CHECK:           %[[CONSTANT_16:.*]] = stablehlo.constant dense<1.300000e+01> : tensor<f32>
// CHECK:           %[[ADD_32:.*]] = stablehlo.add %[[CONVERT_0]], %[[CONSTANT_16]] : tensor<f32>
// CHECK:           %[[MULTIPLY_14:.*]] = stablehlo.multiply %[[ADD_31]], %[[ADD_32]] : tensor<f32>
// CHECK:           %[[CONSTANT_17:.*]] = stablehlo.constant dense<-3.3896803E-13> : tensor<f32>
// CHECK:           %[[ADD_33:.*]] = stablehlo.add %[[MULTIPLY_13]], %[[CONSTANT_17]] : tensor<f32>
// CHECK:           %[[MULTIPLY_15:.*]] = stablehlo.multiply %[[DIVIDE_1]], %[[ADD_33]] : tensor<f32>
// CHECK:           %[[MULTIPLY_16:.*]] = stablehlo.multiply %[[MULTIPLY_14]], %[[MULTIPLY_15]] : tensor<f32>
// CHECK:           %[[CONSTANT_18:.*]] = stablehlo.constant dense<1.200000e+01> : tensor<f32>
// CHECK:           %[[ADD_34:.*]] = stablehlo.add %[[CONVERT_0]], %[[CONSTANT_18]] : tensor<f32>
// CHECK:           %[[CONSTANT_19:.*]] = stablehlo.constant dense<1.100000e+01> : tensor<f32>
// CHECK:           %[[ADD_35:.*]] = stablehlo.add %[[CONVERT_0]], %[[CONSTANT_19]] : tensor<f32>
// CHECK:           %[[MULTIPLY_17:.*]] = stablehlo.multiply %[[ADD_34]], %[[ADD_35]] : tensor<f32>
// CHECK:           %[[CONSTANT_20:.*]] = stablehlo.constant dense<1.33825364E-11> : tensor<f32>
// CHECK:           %[[ADD_36:.*]] = stablehlo.add %[[MULTIPLY_16]], %[[CONSTANT_20]] : tensor<f32>
// CHECK:           %[[MULTIPLY_18:.*]] = stablehlo.multiply %[[DIVIDE_1]], %[[ADD_36]] : tensor<f32>
// CHECK:           %[[MULTIPLY_19:.*]] = stablehlo.multiply %[[MULTIPLY_17]], %[[MULTIPLY_18]] : tensor<f32>
// CHECK:           %[[CONSTANT_21:.*]] = stablehlo.constant dense<1.000000e+01> : tensor<f32>
// CHECK:           %[[ADD_37:.*]] = stablehlo.add %[[CONVERT_0]], %[[CONSTANT_21]] : tensor<f32>
// CHECK:           %[[CONSTANT_22:.*]] = stablehlo.constant dense<9.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_38:.*]] = stablehlo.add %[[CONVERT_0]], %[[CONSTANT_22]] : tensor<f32>
// CHECK:           %[[MULTIPLY_20:.*]] = stablehlo.multiply %[[ADD_37]], %[[ADD_38]] : tensor<f32>
// CHECK:           %[[CONSTANT_23:.*]] = stablehlo.constant dense<-5.28419031E-10> : tensor<f32>
// CHECK:           %[[ADD_39:.*]] = stablehlo.add %[[MULTIPLY_19]], %[[CONSTANT_23]] : tensor<f32>
// CHECK:           %[[MULTIPLY_21:.*]] = stablehlo.multiply %[[DIVIDE_1]], %[[ADD_39]] : tensor<f32>
// CHECK:           %[[MULTIPLY_22:.*]] = stablehlo.multiply %[[MULTIPLY_20]], %[[MULTIPLY_21]] : tensor<f32>
// CHECK:           %[[CONSTANT_24:.*]] = stablehlo.constant dense<8.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_40:.*]] = stablehlo.add %[[CONVERT_0]], %[[CONSTANT_24]] : tensor<f32>
// CHECK:           %[[CONSTANT_25:.*]] = stablehlo.constant dense<7.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_41:.*]] = stablehlo.add %[[CONVERT_0]], %[[CONSTANT_25]] : tensor<f32>
// CHECK:           %[[MULTIPLY_23:.*]] = stablehlo.multiply %[[ADD_40]], %[[ADD_41]] : tensor<f32>
// CHECK:           %[[CONSTANT_26:.*]] = stablehlo.constant dense<2.08767563E-8> : tensor<f32>
// CHECK:           %[[ADD_42:.*]] = stablehlo.add %[[MULTIPLY_22]], %[[CONSTANT_26]] : tensor<f32>
// CHECK:           %[[MULTIPLY_24:.*]] = stablehlo.multiply %[[DIVIDE_1]], %[[ADD_42]] : tensor<f32>
// CHECK:           %[[MULTIPLY_25:.*]] = stablehlo.multiply %[[MULTIPLY_23]], %[[MULTIPLY_24]] : tensor<f32>
// CHECK:           %[[CONSTANT_27:.*]] = stablehlo.constant dense<6.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_43:.*]] = stablehlo.add %[[CONVERT_0]], %[[CONSTANT_27]] : tensor<f32>
// CHECK:           %[[CONSTANT_28:.*]] = stablehlo.constant dense<5.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_44:.*]] = stablehlo.add %[[CONVERT_0]], %[[CONSTANT_28]] : tensor<f32>
// CHECK:           %[[MULTIPLY_26:.*]] = stablehlo.multiply %[[ADD_43]], %[[ADD_44]] : tensor<f32>
// CHECK:           %[[CONSTANT_29:.*]] = stablehlo.constant dense<-8.26719599E-7> : tensor<f32>
// CHECK:           %[[ADD_45:.*]] = stablehlo.add %[[MULTIPLY_25]], %[[CONSTANT_29]] : tensor<f32>
// CHECK:           %[[MULTIPLY_27:.*]] = stablehlo.multiply %[[DIVIDE_1]], %[[ADD_45]] : tensor<f32>
// CHECK:           %[[MULTIPLY_28:.*]] = stablehlo.multiply %[[MULTIPLY_26]], %[[MULTIPLY_27]] : tensor<f32>
// CHECK:           %[[CONSTANT_30:.*]] = stablehlo.constant dense<4.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_46:.*]] = stablehlo.add %[[CONVERT_0]], %[[CONSTANT_30]] : tensor<f32>
// CHECK:           %[[CONSTANT_31:.*]] = stablehlo.constant dense<3.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_47:.*]] = stablehlo.add %[[CONVERT_0]], %[[CONSTANT_31]] : tensor<f32>
// CHECK:           %[[MULTIPLY_29:.*]] = stablehlo.multiply %[[ADD_46]], %[[ADD_47]] : tensor<f32>
// CHECK:           %[[CONSTANT_32:.*]] = stablehlo.constant dense<3.30687835E-5> : tensor<f32>
// CHECK:           %[[ADD_48:.*]] = stablehlo.add %[[MULTIPLY_28]], %[[CONSTANT_32]] : tensor<f32>
// CHECK:           %[[MULTIPLY_30:.*]] = stablehlo.multiply %[[DIVIDE_1]], %[[ADD_48]] : tensor<f32>
// CHECK:           %[[MULTIPLY_31:.*]] = stablehlo.multiply %[[MULTIPLY_29]], %[[MULTIPLY_30]] : tensor<f32>
// CHECK:           %[[CONSTANT_33:.*]] = stablehlo.constant dense<2.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_49:.*]] = stablehlo.add %[[CONVERT_0]], %[[CONSTANT_33]] : tensor<f32>
// CHECK:           %[[CONSTANT_34:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_50:.*]] = stablehlo.add %[[CONVERT_0]], %[[CONSTANT_34]] : tensor<f32>
// CHECK:           %[[MULTIPLY_32:.*]] = stablehlo.multiply %[[ADD_49]], %[[ADD_50]] : tensor<f32>
// CHECK:           %[[CONSTANT_35:.*]] = stablehlo.constant dense<-0.00138888892> : tensor<f32>
// CHECK:           %[[ADD_51:.*]] = stablehlo.add %[[MULTIPLY_31]], %[[CONSTANT_35]] : tensor<f32>
// CHECK:           %[[MULTIPLY_33:.*]] = stablehlo.multiply %[[DIVIDE_1]], %[[ADD_51]] : tensor<f32>
// CHECK:           %[[MULTIPLY_34:.*]] = stablehlo.multiply %[[MULTIPLY_32]], %[[MULTIPLY_33]] : tensor<f32>
// CHECK:           %[[CONSTANT_36:.*]] = stablehlo.constant dense<5.000000e-01> : tensor<f32>
// CHECK:           %[[DIVIDE_2:.*]] = stablehlo.divide %[[CONVERT_0]], %[[ADD_18]] : tensor<f32>
// CHECK:           %[[CONSTANT_37:.*]] = stablehlo.constant dense<0.0833333358> : tensor<f32>
// CHECK:           %[[ADD_52:.*]] = stablehlo.add %[[CONSTANT_37]], %[[MULTIPLY_34]] : tensor<f32>
// CHECK:           %[[MULTIPLY_35:.*]] = stablehlo.multiply %[[DIVIDE_2]], %[[ADD_52]] : tensor<f32>
// CHECK:           %[[ADD_53:.*]] = stablehlo.add %[[CONSTANT_36]], %[[MULTIPLY_35]] : tensor<f32>
// CHECK:           %[[MULTIPLY_36:.*]] = stablehlo.multiply %[[POWER_10]], %[[ADD_53]] : tensor<f32>
// CHECK:           %[[ADD_54:.*]] = stablehlo.add %[[ADD_17]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[ADD_55:.*]] = stablehlo.add %[[ADD_54]], %[[MULTIPLY_36]] : tensor<f32>
// CHECK:           %[[ABS_0:.*]] = stablehlo.abs %[[POWER_10]] : tensor<f32>
// CHECK:           %[[ABS_1:.*]] = stablehlo.abs %[[ADD_17]] : tensor<f32>
// CHECK:           %[[CONSTANT_38:.*]] = stablehlo.constant dense<1.401300e-45> : tensor<f32>
// CHECK:           %[[MULTIPLY_37:.*]] = stablehlo.multiply %[[ABS_1]], %[[CONSTANT_38]] : tensor<f32>
// CHECK:           %[[COMPARE_0:.*]] = stablehlo.compare  LT, %[[ABS_0]], %[[MULTIPLY_37]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[SELECT_0:.*]] = stablehlo.select %[[COMPARE_0]], %[[ADD_17]], %[[ADD_55]] : tensor<i1>, tensor<f32>
// CHECK:           %[[CONSTANT_39:.*]] = stablehlo.constant dense<0x7FC00000> : tensor<f32>
// CHECK:           %[[COMPARE_1:.*]] = stablehlo.compare  LT, %[[CONVERT_0]], %[[CONSTANT_2]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[SELECT_1:.*]] = stablehlo.select %[[COMPARE_1]], %[[CONSTANT_39]], %[[SELECT_0]] : tensor<i1>, tensor<f32>
// CHECK:           %[[COMPARE_2:.*]] = stablehlo.compare  LE, %[[CONVERT_1]], %[[CONSTANT_0]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[FLOOR_0:.*]] = stablehlo.floor %[[CONVERT_0]] : tensor<f32>
// CHECK:           %[[COMPARE_3:.*]] = stablehlo.compare  NE, %[[CONVERT_0]], %[[FLOOR_0]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[AND_0:.*]] = stablehlo.and %[[COMPARE_2]], %[[COMPARE_3]] : tensor<i1>
// CHECK:           %[[SELECT_2:.*]] = stablehlo.select %[[AND_0]], %[[CONSTANT_39]], %[[SELECT_1]] : tensor<i1>, tensor<f32>
// CHECK:           %[[CONSTANT_40:.*]] = stablehlo.constant dense<0x7F800000> : tensor<f32>
// CHECK:           %[[FLOOR_1:.*]] = stablehlo.floor %[[CONVERT_1]] : tensor<f32>
// CHECK:           %[[COMPARE_4:.*]] = stablehlo.compare  EQ, %[[CONVERT_1]], %[[FLOOR_1]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[AND_1:.*]] = stablehlo.and %[[COMPARE_2]], %[[COMPARE_4]] : tensor<i1>
// CHECK:           %[[CONSTANT_41:.*]] = stablehlo.constant dense<2.000000e+00> : tensor<f32>
// CHECK:           %[[FLOOR_2:.*]] = stablehlo.floor %[[CONVERT_0]] : tensor<f32>
// CHECK:           %[[COMPARE_5:.*]] = stablehlo.compare  EQ, %[[CONVERT_0]], %[[FLOOR_2]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[REMAINDER_0:.*]] = stablehlo.remainder %[[CONVERT_0]], %[[CONSTANT_41]] : tensor<f32>
// CHECK:           %[[COMPARE_6:.*]] = stablehlo.compare  EQ, %[[REMAINDER_0]], %[[CONSTANT_0]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[AND_2:.*]] = stablehlo.and %[[COMPARE_5]], %[[COMPARE_6]] : tensor<i1>
// CHECK:           %[[SELECT_3:.*]] = stablehlo.select %[[AND_2]], %[[CONSTANT_40]], %[[CONSTANT_39]] : tensor<i1>, tensor<f32>
// CHECK:           %[[SELECT_4:.*]] = stablehlo.select %[[AND_1]], %[[SELECT_3]], %[[SELECT_2]] : tensor<i1>, tensor<f32>
// CHECK:           %[[COMPARE_7:.*]] = stablehlo.compare  EQ, %[[CONVERT_0]], %[[CONSTANT_1]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[SELECT_5:.*]] = stablehlo.select %[[COMPARE_7]], %[[CONSTANT_40]], %[[SELECT_4]] : tensor<i1>, tensor<f32>
// CHECK:           %[[CONVERT_2:.*]] = stablehlo.convert %[[SELECT_5]] : (tensor<f32>) -> tensor<f16>
// CHECK:           return %[[CONVERT_2]] : tensor<f16>
// CHECK:         }
func.func @zeta_f16(%arg0: tensor<f16>, %arg1: tensor<f16>) -> tensor<f16> {
  %0 = chlo.zeta %arg0, %arg1 : tensor<f16>, tensor<f16> -> tensor<f16>
  func.return %0 : tensor<f16>
}

// -----

// CHECK-LABEL:   func.func @polygamma_f32(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<f32>,
// CHECK-SAME:      %[[ARG1:.*]]: tensor<f32>) -> tensor<f32> {
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[CONSTANT_1:.*]] = stablehlo.constant dense<2.000000e+00> : tensor<f32>
// CHECK:           %[[REMAINDER_0:.*]] = stablehlo.remainder %[[ARG0]], %[[CONSTANT_1]] : tensor<f32>
// CHECK:           %[[MULTIPLY_0:.*]] = stablehlo.multiply %[[CONSTANT_1]], %[[REMAINDER_0]] : tensor<f32>
// CHECK:           %[[SUBTRACT_0:.*]] = stablehlo.subtract %[[MULTIPLY_0]], %[[CONSTANT_0]] : tensor<f32>
// CHECK:           %[[ADD_0:.*]] = stablehlo.add %[[ARG0]], %[[CONSTANT_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_2:.*]] = stablehlo.constant dense<5.000000e-01> : tensor<f32>
// CHECK:           %[[COMPARE_0:.*]] = stablehlo.compare  LT, %[[ADD_0]], %[[CONSTANT_2]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[NEGATE_0:.*]] = stablehlo.negate %[[ADD_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_3:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[SUBTRACT_1:.*]] = stablehlo.subtract %[[ADD_0]], %[[CONSTANT_3]] : tensor<f32>
// CHECK:           %[[SELECT_0:.*]] = stablehlo.select %[[COMPARE_0]], %[[NEGATE_0]], %[[SUBTRACT_1]] : tensor<i1>, tensor<f32>
// CHECK:           %[[CONSTANT_4:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[CONSTANT_5:.*]] = stablehlo.constant dense<676.520386> : tensor<f32>
// CHECK:           %[[CONSTANT_6:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_1:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_6]] : tensor<f32>
// CHECK:           %[[DIVIDE_0:.*]] = stablehlo.divide %[[CONSTANT_5]], %[[ADD_1]] : tensor<f32>
// CHECK:           %[[ADD_2:.*]] = stablehlo.add %[[CONSTANT_4]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_7:.*]] = stablehlo.constant dense<-1259.13916> : tensor<f32>
// CHECK:           %[[CONSTANT_8:.*]] = stablehlo.constant dense<2.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_3:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_8]] : tensor<f32>
// CHECK:           %[[DIVIDE_1:.*]] = stablehlo.divide %[[CONSTANT_7]], %[[ADD_3]] : tensor<f32>
// CHECK:           %[[ADD_4:.*]] = stablehlo.add %[[ADD_2]], %[[DIVIDE_1]] : tensor<f32>
// CHECK:           %[[CONSTANT_9:.*]] = stablehlo.constant dense<771.323425> : tensor<f32>
// CHECK:           %[[CONSTANT_10:.*]] = stablehlo.constant dense<3.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_5:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_10]] : tensor<f32>
// CHECK:           %[[DIVIDE_2:.*]] = stablehlo.divide %[[CONSTANT_9]], %[[ADD_5]] : tensor<f32>
// CHECK:           %[[ADD_6:.*]] = stablehlo.add %[[ADD_4]], %[[DIVIDE_2]] : tensor<f32>
// CHECK:           %[[CONSTANT_11:.*]] = stablehlo.constant dense<-176.615036> : tensor<f32>
// CHECK:           %[[CONSTANT_12:.*]] = stablehlo.constant dense<4.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_7:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_12]] : tensor<f32>
// CHECK:           %[[DIVIDE_3:.*]] = stablehlo.divide %[[CONSTANT_11]], %[[ADD_7]] : tensor<f32>
// CHECK:           %[[ADD_8:.*]] = stablehlo.add %[[ADD_6]], %[[DIVIDE_3]] : tensor<f32>
// CHECK:           %[[CONSTANT_13:.*]] = stablehlo.constant dense<12.5073433> : tensor<f32>
// CHECK:           %[[CONSTANT_14:.*]] = stablehlo.constant dense<5.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_9:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_14]] : tensor<f32>
// CHECK:           %[[DIVIDE_4:.*]] = stablehlo.divide %[[CONSTANT_13]], %[[ADD_9]] : tensor<f32>
// CHECK:           %[[ADD_10:.*]] = stablehlo.add %[[ADD_8]], %[[DIVIDE_4]] : tensor<f32>
// CHECK:           %[[CONSTANT_15:.*]] = stablehlo.constant dense<-0.138571098> : tensor<f32>
// CHECK:           %[[CONSTANT_16:.*]] = stablehlo.constant dense<6.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_11:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_16]] : tensor<f32>
// CHECK:           %[[DIVIDE_5:.*]] = stablehlo.divide %[[CONSTANT_15]], %[[ADD_11]] : tensor<f32>
// CHECK:           %[[ADD_12:.*]] = stablehlo.add %[[ADD_10]], %[[DIVIDE_5]] : tensor<f32>
// CHECK:           %[[CONSTANT_17:.*]] = stablehlo.constant dense<9.98436917E-6> : tensor<f32>
// CHECK:           %[[CONSTANT_18:.*]] = stablehlo.constant dense<7.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_13:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_18]] : tensor<f32>
// CHECK:           %[[DIVIDE_6:.*]] = stablehlo.divide %[[CONSTANT_17]], %[[ADD_13]] : tensor<f32>
// CHECK:           %[[ADD_14:.*]] = stablehlo.add %[[ADD_12]], %[[DIVIDE_6]] : tensor<f32>
// CHECK:           %[[CONSTANT_19:.*]] = stablehlo.constant dense<1.50563267E-7> : tensor<f32>
// CHECK:           %[[CONSTANT_20:.*]] = stablehlo.constant dense<8.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_15:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_20]] : tensor<f32>
// CHECK:           %[[DIVIDE_7:.*]] = stablehlo.divide %[[CONSTANT_19]], %[[ADD_15]] : tensor<f32>
// CHECK:           %[[ADD_16:.*]] = stablehlo.add %[[ADD_14]], %[[DIVIDE_7]] : tensor<f32>
// CHECK:           %[[CONSTANT_21:.*]] = stablehlo.constant dense<7.500000e+00> : tensor<f32>
// CHECK:           %[[ADD_17:.*]] = stablehlo.add %[[CONSTANT_21]], %[[SELECT_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_22:.*]] = stablehlo.constant dense<2.01490307> : tensor<f32>
// CHECK:           %[[DIVIDE_8:.*]] = stablehlo.divide %[[SELECT_0]], %[[CONSTANT_21]] : tensor<f32>
// CHECK:           %[[LOG_PLUS_ONE_0:.*]] = stablehlo.log_plus_one %[[DIVIDE_8]] : tensor<f32>
// CHECK:           %[[ADD_18:.*]] = stablehlo.add %[[CONSTANT_22]], %[[LOG_PLUS_ONE_0]] : tensor<f32>
// CHECK:           %[[DIVIDE_9:.*]] = stablehlo.divide %[[ADD_17]], %[[ADD_18]] : tensor<f32>
// CHECK:           %[[ADD_19:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_2]] : tensor<f32>
// CHECK:           %[[SUBTRACT_2:.*]] = stablehlo.subtract %[[ADD_19]], %[[DIVIDE_9]] : tensor<f32>
// CHECK:           %[[MULTIPLY_1:.*]] = stablehlo.multiply %[[SUBTRACT_2]], %[[ADD_18]] : tensor<f32>
// CHECK:           %[[LOG_0:.*]] = stablehlo.log %[[ADD_16]] : tensor<f32>
// CHECK:           %[[CONSTANT_23:.*]] = stablehlo.constant dense<0.918938517> : tensor<f32>
// CHECK:           %[[ADD_20:.*]] = stablehlo.add %[[CONSTANT_23]], %[[MULTIPLY_1]] : tensor<f32>
// CHECK:           %[[ADD_21:.*]] = stablehlo.add %[[ADD_20]], %[[LOG_0]] : tensor<f32>
// CHECK:           %[[ABS_0:.*]] = stablehlo.abs %[[ADD_0]] : tensor<f32>
// CHECK:           %[[FLOOR_0:.*]] = stablehlo.floor %[[ABS_0]] : tensor<f32>
// CHECK:           %[[SUBTRACT_3:.*]] = stablehlo.subtract %[[ABS_0]], %[[FLOOR_0]] : tensor<f32>
// CHECK:           %[[COMPARE_1:.*]] = stablehlo.compare  LT, %[[CONSTANT_2]], %[[SUBTRACT_3]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[SUBTRACT_4:.*]] = stablehlo.subtract %[[CONSTANT_3]], %[[SUBTRACT_3]] : tensor<f32>
// CHECK:           %[[SELECT_1:.*]] = stablehlo.select %[[COMPARE_1]], %[[SUBTRACT_4]], %[[SUBTRACT_3]] : tensor<i1>, tensor<f32>
// CHECK:           %[[CONSTANT_24:.*]] = stablehlo.constant dense<3.14159274> : tensor<f32>
// CHECK:           %[[MULTIPLY_2:.*]] = stablehlo.multiply %[[CONSTANT_24]], %[[SELECT_1]] : tensor<f32>
// CHECK:           %[[SINE_0:.*]] = stablehlo.sine %[[MULTIPLY_2]] : tensor<f32>
// CHECK:           %[[LOG_1:.*]] = stablehlo.log %[[SINE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_25:.*]] = stablehlo.constant dense<1.14472985> : tensor<f32>
// CHECK:           %[[SUBTRACT_5:.*]] = stablehlo.subtract %[[CONSTANT_25]], %[[LOG_1]] : tensor<f32>
// CHECK:           %[[SUBTRACT_6:.*]] = stablehlo.subtract %[[SUBTRACT_5]], %[[ADD_21]] : tensor<f32>
// CHECK:           %[[IS_FINITE_0:.*]] = stablehlo.is_finite %[[LOG_1]] : (tensor<f32>) -> tensor<i1>
// CHECK:           %[[NEGATE_1:.*]] = stablehlo.negate %[[LOG_1]] : tensor<f32>
// CHECK:           %[[SELECT_2:.*]] = stablehlo.select %[[IS_FINITE_0]], %[[SUBTRACT_6]], %[[NEGATE_1]] : tensor<i1>, tensor<f32>
// CHECK:           %[[SELECT_3:.*]] = stablehlo.select %[[COMPARE_0]], %[[SELECT_2]], %[[ADD_21]] : tensor<i1>, tensor<f32>
// CHECK:           %[[ABS_1:.*]] = stablehlo.abs %[[ADD_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_26:.*]] = stablehlo.constant dense<0x7F800000> : tensor<f32>
// CHECK:           %[[COMPARE_2:.*]] = stablehlo.compare  EQ, %[[ABS_1]], %[[CONSTANT_26]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[CONSTANT_27:.*]] = stablehlo.constant dense<0x7F800000> : tensor<f32>
// CHECK:           %[[SELECT_4:.*]] = stablehlo.select %[[COMPARE_2]], %[[CONSTANT_27]], %[[SELECT_3]] : tensor<i1>, tensor<f32>
// CHECK:           %[[EXPONENTIAL_0:.*]] = stablehlo.exponential %[[SELECT_4]] : tensor<f32>
// CHECK:           %[[CONSTANT_28:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<f32>
// CHECK:           %[[CONSTANT_29:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[NEGATE_2:.*]] = stablehlo.negate %[[ADD_0]] : tensor<f32>
// CHECK:           %[[POWER_0:.*]] = stablehlo.power %[[ARG1]], %[[NEGATE_2]] : tensor<f32>
// CHECK:           %[[ADD_22:.*]] = stablehlo.add %[[ARG1]], %[[CONSTANT_29]] : tensor<f32>
// CHECK:           %[[POWER_1:.*]] = stablehlo.power %[[ADD_22]], %[[NEGATE_2]] : tensor<f32>
// CHECK:           %[[ADD_23:.*]] = stablehlo.add %[[POWER_0]], %[[POWER_1]] : tensor<f32>
// CHECK:           %[[ADD_24:.*]] = stablehlo.add %[[ADD_22]], %[[CONSTANT_29]] : tensor<f32>
// CHECK:           %[[POWER_2:.*]] = stablehlo.power %[[ADD_24]], %[[NEGATE_2]] : tensor<f32>
// CHECK:           %[[ADD_25:.*]] = stablehlo.add %[[ADD_23]], %[[POWER_2]] : tensor<f32>
// CHECK:           %[[ADD_26:.*]] = stablehlo.add %[[ADD_24]], %[[CONSTANT_29]] : tensor<f32>
// CHECK:           %[[POWER_3:.*]] = stablehlo.power %[[ADD_26]], %[[NEGATE_2]] : tensor<f32>
// CHECK:           %[[ADD_27:.*]] = stablehlo.add %[[ADD_25]], %[[POWER_3]] : tensor<f32>
// CHECK:           %[[ADD_28:.*]] = stablehlo.add %[[ADD_26]], %[[CONSTANT_29]] : tensor<f32>
// CHECK:           %[[POWER_4:.*]] = stablehlo.power %[[ADD_28]], %[[NEGATE_2]] : tensor<f32>
// CHECK:           %[[ADD_29:.*]] = stablehlo.add %[[ADD_27]], %[[POWER_4]] : tensor<f32>
// CHECK:           %[[ADD_30:.*]] = stablehlo.add %[[ADD_28]], %[[CONSTANT_29]] : tensor<f32>
// CHECK:           %[[POWER_5:.*]] = stablehlo.power %[[ADD_30]], %[[NEGATE_2]] : tensor<f32>
// CHECK:           %[[ADD_31:.*]] = stablehlo.add %[[ADD_29]], %[[POWER_5]] : tensor<f32>
// CHECK:           %[[ADD_32:.*]] = stablehlo.add %[[ADD_30]], %[[CONSTANT_29]] : tensor<f32>
// CHECK:           %[[POWER_6:.*]] = stablehlo.power %[[ADD_32]], %[[NEGATE_2]] : tensor<f32>
// CHECK:           %[[ADD_33:.*]] = stablehlo.add %[[ADD_31]], %[[POWER_6]] : tensor<f32>
// CHECK:           %[[ADD_34:.*]] = stablehlo.add %[[ADD_32]], %[[CONSTANT_29]] : tensor<f32>
// CHECK:           %[[POWER_7:.*]] = stablehlo.power %[[ADD_34]], %[[NEGATE_2]] : tensor<f32>
// CHECK:           %[[ADD_35:.*]] = stablehlo.add %[[ADD_33]], %[[POWER_7]] : tensor<f32>
// CHECK:           %[[ADD_36:.*]] = stablehlo.add %[[ADD_34]], %[[CONSTANT_29]] : tensor<f32>
// CHECK:           %[[POWER_8:.*]] = stablehlo.power %[[ADD_36]], %[[NEGATE_2]] : tensor<f32>
// CHECK:           %[[ADD_37:.*]] = stablehlo.add %[[ADD_35]], %[[POWER_8]] : tensor<f32>
// CHECK:           %[[ADD_38:.*]] = stablehlo.add %[[ADD_36]], %[[CONSTANT_29]] : tensor<f32>
// CHECK:           %[[POWER_9:.*]] = stablehlo.power %[[ADD_38]], %[[NEGATE_2]] : tensor<f32>
// CHECK:           %[[ADD_39:.*]] = stablehlo.add %[[ADD_37]], %[[POWER_9]] : tensor<f32>
// CHECK:           %[[ADD_40:.*]] = stablehlo.add %[[ADD_38]], %[[CONSTANT_29]] : tensor<f32>
// CHECK:           %[[POWER_10:.*]] = stablehlo.power %[[ADD_40]], %[[NEGATE_2]] : tensor<f32>
// CHECK:           %[[CONSTANT_30:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[MULTIPLY_3:.*]] = stablehlo.multiply %[[POWER_10]], %[[ADD_40]] : tensor<f32>
// CHECK:           %[[SUBTRACT_7:.*]] = stablehlo.subtract %[[ADD_0]], %[[CONSTANT_30]] : tensor<f32>
// CHECK:           %[[DIVIDE_10:.*]] = stablehlo.divide %[[MULTIPLY_3]], %[[SUBTRACT_7]] : tensor<f32>
// CHECK:           %[[MULTIPLY_4:.*]] = stablehlo.multiply %[[ADD_40]], %[[ADD_40]] : tensor<f32>
// CHECK:           %[[DIVIDE_11:.*]] = stablehlo.divide %[[CONSTANT_29]], %[[MULTIPLY_4]] : tensor<f32>
// CHECK:           %[[CONSTANT_31:.*]] = stablehlo.constant dense<2.200000e+01> : tensor<f32>
// CHECK:           %[[ADD_41:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_31]] : tensor<f32>
// CHECK:           %[[CONSTANT_32:.*]] = stablehlo.constant dense<2.100000e+01> : tensor<f32>
// CHECK:           %[[ADD_42:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_32]] : tensor<f32>
// CHECK:           %[[MULTIPLY_5:.*]] = stablehlo.multiply %[[ADD_41]], %[[ADD_42]] : tensor<f32>
// CHECK:           %[[CONSTANT_33:.*]] = stablehlo.constant dense<-1.39544646E-19> : tensor<f32>
// CHECK:           %[[ADD_43:.*]] = stablehlo.add %[[CONSTANT_28]], %[[CONSTANT_33]] : tensor<f32>
// CHECK:           %[[MULTIPLY_6:.*]] = stablehlo.multiply %[[DIVIDE_11]], %[[ADD_43]] : tensor<f32>
// CHECK:           %[[MULTIPLY_7:.*]] = stablehlo.multiply %[[MULTIPLY_5]], %[[MULTIPLY_6]] : tensor<f32>
// CHECK:           %[[CONSTANT_34:.*]] = stablehlo.constant dense<2.000000e+01> : tensor<f32>
// CHECK:           %[[ADD_44:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_34]] : tensor<f32>
// CHECK:           %[[CONSTANT_35:.*]] = stablehlo.constant dense<1.900000e+01> : tensor<f32>
// CHECK:           %[[ADD_45:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_35]] : tensor<f32>
// CHECK:           %[[MULTIPLY_8:.*]] = stablehlo.multiply %[[ADD_44]], %[[ADD_45]] : tensor<f32>
// CHECK:           %[[CONSTANT_36:.*]] = stablehlo.constant dense<5.50900303E-18> : tensor<f32>
// CHECK:           %[[ADD_46:.*]] = stablehlo.add %[[MULTIPLY_7]], %[[CONSTANT_36]] : tensor<f32>
// CHECK:           %[[MULTIPLY_9:.*]] = stablehlo.multiply %[[DIVIDE_11]], %[[ADD_46]] : tensor<f32>
// CHECK:           %[[MULTIPLY_10:.*]] = stablehlo.multiply %[[MULTIPLY_8]], %[[MULTIPLY_9]] : tensor<f32>
// CHECK:           %[[CONSTANT_37:.*]] = stablehlo.constant dense<1.800000e+01> : tensor<f32>
// CHECK:           %[[ADD_47:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_37]] : tensor<f32>
// CHECK:           %[[CONSTANT_38:.*]] = stablehlo.constant dense<1.700000e+01> : tensor<f32>
// CHECK:           %[[ADD_48:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_38]] : tensor<f32>
// CHECK:           %[[MULTIPLY_11:.*]] = stablehlo.multiply %[[ADD_47]], %[[ADD_48]] : tensor<f32>
// CHECK:           %[[CONSTANT_39:.*]] = stablehlo.constant dense<-2.17486866E-16> : tensor<f32>
// CHECK:           %[[ADD_49:.*]] = stablehlo.add %[[MULTIPLY_10]], %[[CONSTANT_39]] : tensor<f32>
// CHECK:           %[[MULTIPLY_12:.*]] = stablehlo.multiply %[[DIVIDE_11]], %[[ADD_49]] : tensor<f32>
// CHECK:           %[[MULTIPLY_13:.*]] = stablehlo.multiply %[[MULTIPLY_11]], %[[MULTIPLY_12]] : tensor<f32>
// CHECK:           %[[CONSTANT_40:.*]] = stablehlo.constant dense<1.600000e+01> : tensor<f32>
// CHECK:           %[[ADD_50:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_40]] : tensor<f32>
// CHECK:           %[[CONSTANT_41:.*]] = stablehlo.constant dense<1.500000e+01> : tensor<f32>
// CHECK:           %[[ADD_51:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_41]] : tensor<f32>
// CHECK:           %[[MULTIPLY_14:.*]] = stablehlo.multiply %[[ADD_50]], %[[ADD_51]] : tensor<f32>
// CHECK:           %[[CONSTANT_42:.*]] = stablehlo.constant dense<8.58606213E-15> : tensor<f32>
// CHECK:           %[[ADD_52:.*]] = stablehlo.add %[[MULTIPLY_13]], %[[CONSTANT_42]] : tensor<f32>
// CHECK:           %[[MULTIPLY_15:.*]] = stablehlo.multiply %[[DIVIDE_11]], %[[ADD_52]] : tensor<f32>
// CHECK:           %[[MULTIPLY_16:.*]] = stablehlo.multiply %[[MULTIPLY_14]], %[[MULTIPLY_15]] : tensor<f32>
// CHECK:           %[[CONSTANT_43:.*]] = stablehlo.constant dense<1.400000e+01> : tensor<f32>
// CHECK:           %[[ADD_53:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_43]] : tensor<f32>
// CHECK:           %[[CONSTANT_44:.*]] = stablehlo.constant dense<1.300000e+01> : tensor<f32>
// CHECK:           %[[ADD_54:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_44]] : tensor<f32>
// CHECK:           %[[MULTIPLY_17:.*]] = stablehlo.multiply %[[ADD_53]], %[[ADD_54]] : tensor<f32>
// CHECK:           %[[CONSTANT_45:.*]] = stablehlo.constant dense<-3.3896803E-13> : tensor<f32>
// CHECK:           %[[ADD_55:.*]] = stablehlo.add %[[MULTIPLY_16]], %[[CONSTANT_45]] : tensor<f32>
// CHECK:           %[[MULTIPLY_18:.*]] = stablehlo.multiply %[[DIVIDE_11]], %[[ADD_55]] : tensor<f32>
// CHECK:           %[[MULTIPLY_19:.*]] = stablehlo.multiply %[[MULTIPLY_17]], %[[MULTIPLY_18]] : tensor<f32>
// CHECK:           %[[CONSTANT_46:.*]] = stablehlo.constant dense<1.200000e+01> : tensor<f32>
// CHECK:           %[[ADD_56:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_46]] : tensor<f32>
// CHECK:           %[[CONSTANT_47:.*]] = stablehlo.constant dense<1.100000e+01> : tensor<f32>
// CHECK:           %[[ADD_57:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_47]] : tensor<f32>
// CHECK:           %[[MULTIPLY_20:.*]] = stablehlo.multiply %[[ADD_56]], %[[ADD_57]] : tensor<f32>
// CHECK:           %[[CONSTANT_48:.*]] = stablehlo.constant dense<1.33825364E-11> : tensor<f32>
// CHECK:           %[[ADD_58:.*]] = stablehlo.add %[[MULTIPLY_19]], %[[CONSTANT_48]] : tensor<f32>
// CHECK:           %[[MULTIPLY_21:.*]] = stablehlo.multiply %[[DIVIDE_11]], %[[ADD_58]] : tensor<f32>
// CHECK:           %[[MULTIPLY_22:.*]] = stablehlo.multiply %[[MULTIPLY_20]], %[[MULTIPLY_21]] : tensor<f32>
// CHECK:           %[[CONSTANT_49:.*]] = stablehlo.constant dense<1.000000e+01> : tensor<f32>
// CHECK:           %[[ADD_59:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_49]] : tensor<f32>
// CHECK:           %[[CONSTANT_50:.*]] = stablehlo.constant dense<9.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_60:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_50]] : tensor<f32>
// CHECK:           %[[MULTIPLY_23:.*]] = stablehlo.multiply %[[ADD_59]], %[[ADD_60]] : tensor<f32>
// CHECK:           %[[CONSTANT_51:.*]] = stablehlo.constant dense<-5.28419031E-10> : tensor<f32>
// CHECK:           %[[ADD_61:.*]] = stablehlo.add %[[MULTIPLY_22]], %[[CONSTANT_51]] : tensor<f32>
// CHECK:           %[[MULTIPLY_24:.*]] = stablehlo.multiply %[[DIVIDE_11]], %[[ADD_61]] : tensor<f32>
// CHECK:           %[[MULTIPLY_25:.*]] = stablehlo.multiply %[[MULTIPLY_23]], %[[MULTIPLY_24]] : tensor<f32>
// CHECK:           %[[CONSTANT_52:.*]] = stablehlo.constant dense<8.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_62:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_52]] : tensor<f32>
// CHECK:           %[[CONSTANT_53:.*]] = stablehlo.constant dense<7.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_63:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_53]] : tensor<f32>
// CHECK:           %[[MULTIPLY_26:.*]] = stablehlo.multiply %[[ADD_62]], %[[ADD_63]] : tensor<f32>
// CHECK:           %[[CONSTANT_54:.*]] = stablehlo.constant dense<2.08767563E-8> : tensor<f32>
// CHECK:           %[[ADD_64:.*]] = stablehlo.add %[[MULTIPLY_25]], %[[CONSTANT_54]] : tensor<f32>
// CHECK:           %[[MULTIPLY_27:.*]] = stablehlo.multiply %[[DIVIDE_11]], %[[ADD_64]] : tensor<f32>
// CHECK:           %[[MULTIPLY_28:.*]] = stablehlo.multiply %[[MULTIPLY_26]], %[[MULTIPLY_27]] : tensor<f32>
// CHECK:           %[[CONSTANT_55:.*]] = stablehlo.constant dense<6.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_65:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_55]] : tensor<f32>
// CHECK:           %[[CONSTANT_56:.*]] = stablehlo.constant dense<5.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_66:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_56]] : tensor<f32>
// CHECK:           %[[MULTIPLY_29:.*]] = stablehlo.multiply %[[ADD_65]], %[[ADD_66]] : tensor<f32>
// CHECK:           %[[CONSTANT_57:.*]] = stablehlo.constant dense<-8.26719599E-7> : tensor<f32>
// CHECK:           %[[ADD_67:.*]] = stablehlo.add %[[MULTIPLY_28]], %[[CONSTANT_57]] : tensor<f32>
// CHECK:           %[[MULTIPLY_30:.*]] = stablehlo.multiply %[[DIVIDE_11]], %[[ADD_67]] : tensor<f32>
// CHECK:           %[[MULTIPLY_31:.*]] = stablehlo.multiply %[[MULTIPLY_29]], %[[MULTIPLY_30]] : tensor<f32>
// CHECK:           %[[CONSTANT_58:.*]] = stablehlo.constant dense<4.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_68:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_58]] : tensor<f32>
// CHECK:           %[[CONSTANT_59:.*]] = stablehlo.constant dense<3.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_69:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_59]] : tensor<f32>
// CHECK:           %[[MULTIPLY_32:.*]] = stablehlo.multiply %[[ADD_68]], %[[ADD_69]] : tensor<f32>
// CHECK:           %[[CONSTANT_60:.*]] = stablehlo.constant dense<3.30687835E-5> : tensor<f32>
// CHECK:           %[[ADD_70:.*]] = stablehlo.add %[[MULTIPLY_31]], %[[CONSTANT_60]] : tensor<f32>
// CHECK:           %[[MULTIPLY_33:.*]] = stablehlo.multiply %[[DIVIDE_11]], %[[ADD_70]] : tensor<f32>
// CHECK:           %[[MULTIPLY_34:.*]] = stablehlo.multiply %[[MULTIPLY_32]], %[[MULTIPLY_33]] : tensor<f32>
// CHECK:           %[[CONSTANT_61:.*]] = stablehlo.constant dense<2.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_71:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_61]] : tensor<f32>
// CHECK:           %[[CONSTANT_62:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_72:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_62]] : tensor<f32>
// CHECK:           %[[MULTIPLY_35:.*]] = stablehlo.multiply %[[ADD_71]], %[[ADD_72]] : tensor<f32>
// CHECK:           %[[CONSTANT_63:.*]] = stablehlo.constant dense<-0.00138888892> : tensor<f32>
// CHECK:           %[[ADD_73:.*]] = stablehlo.add %[[MULTIPLY_34]], %[[CONSTANT_63]] : tensor<f32>
// CHECK:           %[[MULTIPLY_36:.*]] = stablehlo.multiply %[[DIVIDE_11]], %[[ADD_73]] : tensor<f32>
// CHECK:           %[[MULTIPLY_37:.*]] = stablehlo.multiply %[[MULTIPLY_35]], %[[MULTIPLY_36]] : tensor<f32>
// CHECK:           %[[CONSTANT_64:.*]] = stablehlo.constant dense<5.000000e-01> : tensor<f32>
// CHECK:           %[[DIVIDE_12:.*]] = stablehlo.divide %[[ADD_0]], %[[ADD_40]] : tensor<f32>
// CHECK:           %[[CONSTANT_65:.*]] = stablehlo.constant dense<0.0833333358> : tensor<f32>
// CHECK:           %[[ADD_74:.*]] = stablehlo.add %[[CONSTANT_65]], %[[MULTIPLY_37]] : tensor<f32>
// CHECK:           %[[MULTIPLY_38:.*]] = stablehlo.multiply %[[DIVIDE_12]], %[[ADD_74]] : tensor<f32>
// CHECK:           %[[ADD_75:.*]] = stablehlo.add %[[CONSTANT_64]], %[[MULTIPLY_38]] : tensor<f32>
// CHECK:           %[[MULTIPLY_39:.*]] = stablehlo.multiply %[[POWER_10]], %[[ADD_75]] : tensor<f32>
// CHECK:           %[[ADD_76:.*]] = stablehlo.add %[[ADD_39]], %[[DIVIDE_10]] : tensor<f32>
// CHECK:           %[[ADD_77:.*]] = stablehlo.add %[[ADD_76]], %[[MULTIPLY_39]] : tensor<f32>
// CHECK:           %[[ABS_2:.*]] = stablehlo.abs %[[POWER_10]] : tensor<f32>
// CHECK:           %[[ABS_3:.*]] = stablehlo.abs %[[ADD_39]] : tensor<f32>
// CHECK:           %[[CONSTANT_66:.*]] = stablehlo.constant dense<1.401300e-45> : tensor<f32>
// CHECK:           %[[MULTIPLY_40:.*]] = stablehlo.multiply %[[ABS_3]], %[[CONSTANT_66]] : tensor<f32>
// CHECK:           %[[COMPARE_3:.*]] = stablehlo.compare  LT, %[[ABS_2]], %[[MULTIPLY_40]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[SELECT_5:.*]] = stablehlo.select %[[COMPARE_3]], %[[ADD_39]], %[[ADD_77]] : tensor<i1>, tensor<f32>
// CHECK:           %[[CONSTANT_67:.*]] = stablehlo.constant dense<0x7FC00000> : tensor<f32>
// CHECK:           %[[COMPARE_4:.*]] = stablehlo.compare  LT, %[[ADD_0]], %[[CONSTANT_30]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[SELECT_6:.*]] = stablehlo.select %[[COMPARE_4]], %[[CONSTANT_67]], %[[SELECT_5]] : tensor<i1>, tensor<f32>
// CHECK:           %[[COMPARE_5:.*]] = stablehlo.compare  LE, %[[ARG1]], %[[CONSTANT_28]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[FLOOR_1:.*]] = stablehlo.floor %[[ADD_0]] : tensor<f32>
// CHECK:           %[[COMPARE_6:.*]] = stablehlo.compare  NE, %[[ADD_0]], %[[FLOOR_1]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[AND_0:.*]] = stablehlo.and %[[COMPARE_5]], %[[COMPARE_6]] : tensor<i1>
// CHECK:           %[[SELECT_7:.*]] = stablehlo.select %[[AND_0]], %[[CONSTANT_67]], %[[SELECT_6]] : tensor<i1>, tensor<f32>
// CHECK:           %[[CONSTANT_68:.*]] = stablehlo.constant dense<0x7F800000> : tensor<f32>
// CHECK:           %[[FLOOR_2:.*]] = stablehlo.floor %[[ARG1]] : tensor<f32>
// CHECK:           %[[COMPARE_7:.*]] = stablehlo.compare  EQ, %[[ARG1]], %[[FLOOR_2]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[AND_1:.*]] = stablehlo.and %[[COMPARE_5]], %[[COMPARE_7]] : tensor<i1>
// CHECK:           %[[CONSTANT_69:.*]] = stablehlo.constant dense<2.000000e+00> : tensor<f32>
// CHECK:           %[[FLOOR_3:.*]] = stablehlo.floor %[[ADD_0]] : tensor<f32>
// CHECK:           %[[COMPARE_8:.*]] = stablehlo.compare  EQ, %[[ADD_0]], %[[FLOOR_3]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[REMAINDER_1:.*]] = stablehlo.remainder %[[ADD_0]], %[[CONSTANT_69]] : tensor<f32>
// CHECK:           %[[COMPARE_9:.*]] = stablehlo.compare  EQ, %[[REMAINDER_1]], %[[CONSTANT_28]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[AND_2:.*]] = stablehlo.and %[[COMPARE_8]], %[[COMPARE_9]] : tensor<i1>
// CHECK:           %[[SELECT_8:.*]] = stablehlo.select %[[AND_2]], %[[CONSTANT_68]], %[[CONSTANT_67]] : tensor<i1>, tensor<f32>
// CHECK:           %[[SELECT_9:.*]] = stablehlo.select %[[AND_1]], %[[SELECT_8]], %[[SELECT_7]] : tensor<i1>, tensor<f32>
// CHECK:           %[[COMPARE_10:.*]] = stablehlo.compare  EQ, %[[ADD_0]], %[[CONSTANT_29]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[SELECT_10:.*]] = stablehlo.select %[[COMPARE_10]], %[[CONSTANT_68]], %[[SELECT_9]] : tensor<i1>, tensor<f32>
// CHECK:           %[[MULTIPLY_41:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[EXPONENTIAL_0]] : tensor<f32>
// CHECK:           %[[MULTIPLY_42:.*]] = stablehlo.multiply %[[MULTIPLY_41]], %[[SELECT_10]] : tensor<f32>
// CHECK:           %[[CONSTANT_70:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<f32>
// CHECK:           %[[COMPARE_11:.*]] = stablehlo.compare  EQ, %[[ARG0]], %[[CONSTANT_70]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[CONSTANT_71:.*]] = stablehlo.constant dense<5.000000e-01> : tensor<f32>
// CHECK:           %[[COMPARE_12:.*]] = stablehlo.compare  LT, %[[ARG1]], %[[CONSTANT_71]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[NEGATE_3:.*]] = stablehlo.negate %[[ARG1]] : tensor<f32>
// CHECK:           %[[CONSTANT_72:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[SUBTRACT_8:.*]] = stablehlo.subtract %[[ARG1]], %[[CONSTANT_72]] : tensor<f32>
// CHECK:           %[[SELECT_11:.*]] = stablehlo.select %[[COMPARE_12]], %[[NEGATE_3]], %[[SUBTRACT_8]] : tensor<i1>, tensor<f32>
// CHECK:           %[[CONSTANT_73:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<f32>
// CHECK:           %[[CONSTANT_74:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[CONSTANT_75:.*]] = stablehlo.constant dense<676.520386> : tensor<f32>
// CHECK:           %[[CONSTANT_76:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_78:.*]] = stablehlo.add %[[SELECT_11]], %[[CONSTANT_76]] : tensor<f32>
// CHECK:           %[[MULTIPLY_43:.*]] = stablehlo.multiply %[[ADD_78]], %[[ADD_78]] : tensor<f32>
// CHECK:           %[[DIVIDE_13:.*]] = stablehlo.divide %[[CONSTANT_75]], %[[MULTIPLY_43]] : tensor<f32>
// CHECK:           %[[SUBTRACT_9:.*]] = stablehlo.subtract %[[CONSTANT_73]], %[[DIVIDE_13]] : tensor<f32>
// CHECK:           %[[DIVIDE_14:.*]] = stablehlo.divide %[[CONSTANT_75]], %[[ADD_78]] : tensor<f32>
// CHECK:           %[[ADD_79:.*]] = stablehlo.add %[[CONSTANT_74]], %[[DIVIDE_14]] : tensor<f32>
// CHECK:           %[[CONSTANT_77:.*]] = stablehlo.constant dense<-1259.13916> : tensor<f32>
// CHECK:           %[[CONSTANT_78:.*]] = stablehlo.constant dense<2.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_80:.*]] = stablehlo.add %[[SELECT_11]], %[[CONSTANT_78]] : tensor<f32>
// CHECK:           %[[MULTIPLY_44:.*]] = stablehlo.multiply %[[ADD_80]], %[[ADD_80]] : tensor<f32>
// CHECK:           %[[DIVIDE_15:.*]] = stablehlo.divide %[[CONSTANT_77]], %[[MULTIPLY_44]] : tensor<f32>
// CHECK:           %[[SUBTRACT_10:.*]] = stablehlo.subtract %[[SUBTRACT_9]], %[[DIVIDE_15]] : tensor<f32>
// CHECK:           %[[DIVIDE_16:.*]] = stablehlo.divide %[[CONSTANT_77]], %[[ADD_80]] : tensor<f32>
// CHECK:           %[[ADD_81:.*]] = stablehlo.add %[[ADD_79]], %[[DIVIDE_16]] : tensor<f32>
// CHECK:           %[[CONSTANT_79:.*]] = stablehlo.constant dense<771.323425> : tensor<f32>
// CHECK:           %[[CONSTANT_80:.*]] = stablehlo.constant dense<3.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_82:.*]] = stablehlo.add %[[SELECT_11]], %[[CONSTANT_80]] : tensor<f32>
// CHECK:           %[[MULTIPLY_45:.*]] = stablehlo.multiply %[[ADD_82]], %[[ADD_82]] : tensor<f32>
// CHECK:           %[[DIVIDE_17:.*]] = stablehlo.divide %[[CONSTANT_79]], %[[MULTIPLY_45]] : tensor<f32>
// CHECK:           %[[SUBTRACT_11:.*]] = stablehlo.subtract %[[SUBTRACT_10]], %[[DIVIDE_17]] : tensor<f32>
// CHECK:           %[[DIVIDE_18:.*]] = stablehlo.divide %[[CONSTANT_79]], %[[ADD_82]] : tensor<f32>
// CHECK:           %[[ADD_83:.*]] = stablehlo.add %[[ADD_81]], %[[DIVIDE_18]] : tensor<f32>
// CHECK:           %[[CONSTANT_81:.*]] = stablehlo.constant dense<-176.615036> : tensor<f32>
// CHECK:           %[[CONSTANT_82:.*]] = stablehlo.constant dense<4.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_84:.*]] = stablehlo.add %[[SELECT_11]], %[[CONSTANT_82]] : tensor<f32>
// CHECK:           %[[MULTIPLY_46:.*]] = stablehlo.multiply %[[ADD_84]], %[[ADD_84]] : tensor<f32>
// CHECK:           %[[DIVIDE_19:.*]] = stablehlo.divide %[[CONSTANT_81]], %[[MULTIPLY_46]] : tensor<f32>
// CHECK:           %[[SUBTRACT_12:.*]] = stablehlo.subtract %[[SUBTRACT_11]], %[[DIVIDE_19]] : tensor<f32>
// CHECK:           %[[DIVIDE_20:.*]] = stablehlo.divide %[[CONSTANT_81]], %[[ADD_84]] : tensor<f32>
// CHECK:           %[[ADD_85:.*]] = stablehlo.add %[[ADD_83]], %[[DIVIDE_20]] : tensor<f32>
// CHECK:           %[[CONSTANT_83:.*]] = stablehlo.constant dense<12.5073433> : tensor<f32>
// CHECK:           %[[CONSTANT_84:.*]] = stablehlo.constant dense<5.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_86:.*]] = stablehlo.add %[[SELECT_11]], %[[CONSTANT_84]] : tensor<f32>
// CHECK:           %[[MULTIPLY_47:.*]] = stablehlo.multiply %[[ADD_86]], %[[ADD_86]] : tensor<f32>
// CHECK:           %[[DIVIDE_21:.*]] = stablehlo.divide %[[CONSTANT_83]], %[[MULTIPLY_47]] : tensor<f32>
// CHECK:           %[[SUBTRACT_13:.*]] = stablehlo.subtract %[[SUBTRACT_12]], %[[DIVIDE_21]] : tensor<f32>
// CHECK:           %[[DIVIDE_22:.*]] = stablehlo.divide %[[CONSTANT_83]], %[[ADD_86]] : tensor<f32>
// CHECK:           %[[ADD_87:.*]] = stablehlo.add %[[ADD_85]], %[[DIVIDE_22]] : tensor<f32>
// CHECK:           %[[CONSTANT_85:.*]] = stablehlo.constant dense<-0.138571098> : tensor<f32>
// CHECK:           %[[CONSTANT_86:.*]] = stablehlo.constant dense<6.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_88:.*]] = stablehlo.add %[[SELECT_11]], %[[CONSTANT_86]] : tensor<f32>
// CHECK:           %[[MULTIPLY_48:.*]] = stablehlo.multiply %[[ADD_88]], %[[ADD_88]] : tensor<f32>
// CHECK:           %[[DIVIDE_23:.*]] = stablehlo.divide %[[CONSTANT_85]], %[[MULTIPLY_48]] : tensor<f32>
// CHECK:           %[[SUBTRACT_14:.*]] = stablehlo.subtract %[[SUBTRACT_13]], %[[DIVIDE_23]] : tensor<f32>
// CHECK:           %[[DIVIDE_24:.*]] = stablehlo.divide %[[CONSTANT_85]], %[[ADD_88]] : tensor<f32>
// CHECK:           %[[ADD_89:.*]] = stablehlo.add %[[ADD_87]], %[[DIVIDE_24]] : tensor<f32>
// CHECK:           %[[CONSTANT_87:.*]] = stablehlo.constant dense<9.98436917E-6> : tensor<f32>
// CHECK:           %[[CONSTANT_88:.*]] = stablehlo.constant dense<7.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_90:.*]] = stablehlo.add %[[SELECT_11]], %[[CONSTANT_88]] : tensor<f32>
// CHECK:           %[[MULTIPLY_49:.*]] = stablehlo.multiply %[[ADD_90]], %[[ADD_90]] : tensor<f32>
// CHECK:           %[[DIVIDE_25:.*]] = stablehlo.divide %[[CONSTANT_87]], %[[MULTIPLY_49]] : tensor<f32>
// CHECK:           %[[SUBTRACT_15:.*]] = stablehlo.subtract %[[SUBTRACT_14]], %[[DIVIDE_25]] : tensor<f32>
// CHECK:           %[[DIVIDE_26:.*]] = stablehlo.divide %[[CONSTANT_87]], %[[ADD_90]] : tensor<f32>
// CHECK:           %[[ADD_91:.*]] = stablehlo.add %[[ADD_89]], %[[DIVIDE_26]] : tensor<f32>
// CHECK:           %[[CONSTANT_89:.*]] = stablehlo.constant dense<1.50563267E-7> : tensor<f32>
// CHECK:           %[[CONSTANT_90:.*]] = stablehlo.constant dense<8.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_92:.*]] = stablehlo.add %[[SELECT_11]], %[[CONSTANT_90]] : tensor<f32>
// CHECK:           %[[MULTIPLY_50:.*]] = stablehlo.multiply %[[ADD_92]], %[[ADD_92]] : tensor<f32>
// CHECK:           %[[DIVIDE_27:.*]] = stablehlo.divide %[[CONSTANT_89]], %[[MULTIPLY_50]] : tensor<f32>
// CHECK:           %[[SUBTRACT_16:.*]] = stablehlo.subtract %[[SUBTRACT_15]], %[[DIVIDE_27]] : tensor<f32>
// CHECK:           %[[DIVIDE_28:.*]] = stablehlo.divide %[[CONSTANT_89]], %[[ADD_92]] : tensor<f32>
// CHECK:           %[[ADD_93:.*]] = stablehlo.add %[[ADD_91]], %[[DIVIDE_28]] : tensor<f32>
// CHECK:           %[[CONSTANT_91:.*]] = stablehlo.constant dense<7.500000e+00> : tensor<f32>
// CHECK:           %[[ADD_94:.*]] = stablehlo.add %[[CONSTANT_91]], %[[SELECT_11]] : tensor<f32>
// CHECK:           %[[CONSTANT_92:.*]] = stablehlo.constant dense<2.01490307> : tensor<f32>
// CHECK:           %[[DIVIDE_29:.*]] = stablehlo.divide %[[SELECT_11]], %[[CONSTANT_91]] : tensor<f32>
// CHECK:           %[[LOG_PLUS_ONE_1:.*]] = stablehlo.log_plus_one %[[DIVIDE_29]] : tensor<f32>
// CHECK:           %[[ADD_95:.*]] = stablehlo.add %[[CONSTANT_92]], %[[LOG_PLUS_ONE_1]] : tensor<f32>
// CHECK:           %[[DIVIDE_30:.*]] = stablehlo.divide %[[SUBTRACT_16]], %[[ADD_93]] : tensor<f32>
// CHECK:           %[[CONSTANT_93:.*]] = stablehlo.constant dense<7.000000e+00> : tensor<f32>
// CHECK:           %[[DIVIDE_31:.*]] = stablehlo.divide %[[CONSTANT_93]], %[[ADD_94]] : tensor<f32>
// CHECK:           %[[ADD_96:.*]] = stablehlo.add %[[ADD_95]], %[[DIVIDE_30]] : tensor<f32>
// CHECK:           %[[SUBTRACT_17:.*]] = stablehlo.subtract %[[ADD_96]], %[[DIVIDE_31]] : tensor<f32>
// CHECK:           %[[CONSTANT_94:.*]] = stablehlo.constant dense<5.000000e-01> : tensor<f32>
// CHECK:           %[[ADD_97:.*]] = stablehlo.add %[[ARG1]], %[[CONSTANT_94]] : tensor<f32>
// CHECK:           %[[FLOOR_4:.*]] = stablehlo.floor %[[ADD_97]] : tensor<f32>
// CHECK:           %[[ABS_4:.*]] = stablehlo.abs %[[FLOOR_4]] : tensor<f32>
// CHECK:           %[[ADD_98:.*]] = stablehlo.add %[[ARG1]], %[[ABS_4]] : tensor<f32>
// CHECK:           %[[CONSTANT_95:.*]] = stablehlo.constant dense<3.14159274> : tensor<f32>
// CHECK:           %[[MULTIPLY_51:.*]] = stablehlo.multiply %[[CONSTANT_95]], %[[ADD_98]] : tensor<f32>
// CHECK:           %[[COSINE_0:.*]] = stablehlo.cosine %[[MULTIPLY_51]] : tensor<f32>
// CHECK:           %[[SINE_1:.*]] = stablehlo.sine %[[MULTIPLY_51]] : tensor<f32>
// CHECK:           %[[MULTIPLY_52:.*]] = stablehlo.multiply %[[CONSTANT_95]], %[[COSINE_0]] : tensor<f32>
// CHECK:           %[[DIVIDE_32:.*]] = stablehlo.divide %[[MULTIPLY_52]], %[[SINE_1]] : tensor<f32>
// CHECK:           %[[SUBTRACT_18:.*]] = stablehlo.subtract %[[SUBTRACT_17]], %[[DIVIDE_32]] : tensor<f32>
// CHECK:           %[[SELECT_12:.*]] = stablehlo.select %[[COMPARE_12]], %[[SUBTRACT_18]], %[[SUBTRACT_17]] : tensor<i1>, tensor<f32>
// CHECK:           %[[COMPARE_13:.*]] = stablehlo.compare  LE, %[[ARG1]], %[[CONSTANT_73]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[FLOOR_5:.*]] = stablehlo.floor %[[ARG1]] : tensor<f32>
// CHECK:           %[[COMPARE_14:.*]] = stablehlo.compare  EQ, %[[ARG1]], %[[FLOOR_5]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[AND_3:.*]] = stablehlo.and %[[COMPARE_13]], %[[COMPARE_14]] : tensor<i1>
// CHECK:           %[[CONSTANT_96:.*]] = stablehlo.constant dense<0x7FC00000> : tensor<f32>
// CHECK:           %[[SELECT_13:.*]] = stablehlo.select %[[AND_3]], %[[CONSTANT_96]], %[[SELECT_12]] : tensor<i1>, tensor<f32>
// CHECK:           %[[SELECT_14:.*]] = stablehlo.select %[[COMPARE_11]], %[[SELECT_13]], %[[MULTIPLY_42]] : tensor<i1>, tensor<f32>
// CHECK:           %[[FLOOR_6:.*]] = stablehlo.floor %[[ARG0]] : tensor<f32>
// CHECK:           %[[COMPARE_15:.*]] = stablehlo.compare  NE, %[[ARG0]], %[[FLOOR_6]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[COMPARE_16:.*]] = stablehlo.compare  LT, %[[ARG0]], %[[CONSTANT_70]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[OR_0:.*]] = stablehlo.or %[[COMPARE_15]], %[[COMPARE_16]] : tensor<i1>
// CHECK:           %[[CONSTANT_97:.*]] = stablehlo.constant dense<0x7FC00000> : tensor<f32>
// CHECK:           %[[SELECT_15:.*]] = stablehlo.select %[[OR_0]], %[[CONSTANT_97]], %[[SELECT_14]] : tensor<i1>, tensor<f32>
// CHECK:           return %[[SELECT_15]] : tensor<f32>
// CHECK:         }
func.func @polygamma_f32(%lhs : tensor<f32>, %rhs : tensor<f32>) -> tensor<f32> {
  %1 = chlo.polygamma %lhs, %rhs : tensor<f32>, tensor<f32> -> tensor<f32>
  func.return %1 : tensor<f32>
}

// -----

// CHECK-LABEL:   func.func @polygamma_f64(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<f64>,
// CHECK-SAME:      %[[ARG1:.*]]: tensor<f64>) -> tensor<f64> {
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f64>
// CHECK:           %[[CONSTANT_1:.*]] = stablehlo.constant dense<2.000000e+00> : tensor<f64>
// CHECK:           %[[REMAINDER_0:.*]] = stablehlo.remainder %[[ARG0]], %[[CONSTANT_1]] : tensor<f64>
// CHECK:           %[[MULTIPLY_0:.*]] = stablehlo.multiply %[[CONSTANT_1]], %[[REMAINDER_0]] : tensor<f64>
// CHECK:           %[[SUBTRACT_0:.*]] = stablehlo.subtract %[[MULTIPLY_0]], %[[CONSTANT_0]] : tensor<f64>
// CHECK:           %[[ADD_0:.*]] = stablehlo.add %[[ARG0]], %[[CONSTANT_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_2:.*]] = stablehlo.constant dense<5.000000e-01> : tensor<f64>
// CHECK:           %[[COMPARE_0:.*]] = stablehlo.compare  LT, %[[ADD_0]], %[[CONSTANT_2]] : (tensor<f64>, tensor<f64>) -> tensor<i1>
// CHECK:           %[[NEGATE_0:.*]] = stablehlo.negate %[[ADD_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_3:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f64>
// CHECK:           %[[SUBTRACT_1:.*]] = stablehlo.subtract %[[ADD_0]], %[[CONSTANT_3]] : tensor<f64>
// CHECK:           %[[SELECT_0:.*]] = stablehlo.select %[[COMPARE_0]], %[[NEGATE_0]], %[[SUBTRACT_1]] : tensor<i1>, tensor<f64>
// CHECK:           %[[CONSTANT_4:.*]] = stablehlo.constant dense<0.99999999999980993> : tensor<f64>
// CHECK:           %[[CONSTANT_5:.*]] = stablehlo.constant dense<676.5203681218851> : tensor<f64>
// CHECK:           %[[CONSTANT_6:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f64>
// CHECK:           %[[ADD_1:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_6]] : tensor<f64>
// CHECK:           %[[DIVIDE_0:.*]] = stablehlo.divide %[[CONSTANT_5]], %[[ADD_1]] : tensor<f64>
// CHECK:           %[[ADD_2:.*]] = stablehlo.add %[[CONSTANT_4]], %[[DIVIDE_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_7:.*]] = stablehlo.constant dense<-1259.1392167224028> : tensor<f64>
// CHECK:           %[[CONSTANT_8:.*]] = stablehlo.constant dense<2.000000e+00> : tensor<f64>
// CHECK:           %[[ADD_3:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_8]] : tensor<f64>
// CHECK:           %[[DIVIDE_1:.*]] = stablehlo.divide %[[CONSTANT_7]], %[[ADD_3]] : tensor<f64>
// CHECK:           %[[ADD_4:.*]] = stablehlo.add %[[ADD_2]], %[[DIVIDE_1]] : tensor<f64>
// CHECK:           %[[CONSTANT_9:.*]] = stablehlo.constant dense<771.32342877765313> : tensor<f64>
// CHECK:           %[[CONSTANT_10:.*]] = stablehlo.constant dense<3.000000e+00> : tensor<f64>
// CHECK:           %[[ADD_5:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_10]] : tensor<f64>
// CHECK:           %[[DIVIDE_2:.*]] = stablehlo.divide %[[CONSTANT_9]], %[[ADD_5]] : tensor<f64>
// CHECK:           %[[ADD_6:.*]] = stablehlo.add %[[ADD_4]], %[[DIVIDE_2]] : tensor<f64>
// CHECK:           %[[CONSTANT_11:.*]] = stablehlo.constant dense<-176.61502916214059> : tensor<f64>
// CHECK:           %[[CONSTANT_12:.*]] = stablehlo.constant dense<4.000000e+00> : tensor<f64>
// CHECK:           %[[ADD_7:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_12]] : tensor<f64>
// CHECK:           %[[DIVIDE_3:.*]] = stablehlo.divide %[[CONSTANT_11]], %[[ADD_7]] : tensor<f64>
// CHECK:           %[[ADD_8:.*]] = stablehlo.add %[[ADD_6]], %[[DIVIDE_3]] : tensor<f64>
// CHECK:           %[[CONSTANT_13:.*]] = stablehlo.constant dense<12.507343278686905> : tensor<f64>
// CHECK:           %[[CONSTANT_14:.*]] = stablehlo.constant dense<5.000000e+00> : tensor<f64>
// CHECK:           %[[ADD_9:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_14]] : tensor<f64>
// CHECK:           %[[DIVIDE_4:.*]] = stablehlo.divide %[[CONSTANT_13]], %[[ADD_9]] : tensor<f64>
// CHECK:           %[[ADD_10:.*]] = stablehlo.add %[[ADD_8]], %[[DIVIDE_4]] : tensor<f64>
// CHECK:           %[[CONSTANT_15:.*]] = stablehlo.constant dense<-0.13857109526572012> : tensor<f64>
// CHECK:           %[[CONSTANT_16:.*]] = stablehlo.constant dense<6.000000e+00> : tensor<f64>
// CHECK:           %[[ADD_11:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_16]] : tensor<f64>
// CHECK:           %[[DIVIDE_5:.*]] = stablehlo.divide %[[CONSTANT_15]], %[[ADD_11]] : tensor<f64>
// CHECK:           %[[ADD_12:.*]] = stablehlo.add %[[ADD_10]], %[[DIVIDE_5]] : tensor<f64>
// CHECK:           %[[CONSTANT_17:.*]] = stablehlo.constant dense<9.9843695780195716E-6> : tensor<f64>
// CHECK:           %[[CONSTANT_18:.*]] = stablehlo.constant dense<7.000000e+00> : tensor<f64>
// CHECK:           %[[ADD_13:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_18]] : tensor<f64>
// CHECK:           %[[DIVIDE_6:.*]] = stablehlo.divide %[[CONSTANT_17]], %[[ADD_13]] : tensor<f64>
// CHECK:           %[[ADD_14:.*]] = stablehlo.add %[[ADD_12]], %[[DIVIDE_6]] : tensor<f64>
// CHECK:           %[[CONSTANT_19:.*]] = stablehlo.constant dense<1.5056327351493116E-7> : tensor<f64>
// CHECK:           %[[CONSTANT_20:.*]] = stablehlo.constant dense<8.000000e+00> : tensor<f64>
// CHECK:           %[[ADD_15:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_20]] : tensor<f64>
// CHECK:           %[[DIVIDE_7:.*]] = stablehlo.divide %[[CONSTANT_19]], %[[ADD_15]] : tensor<f64>
// CHECK:           %[[ADD_16:.*]] = stablehlo.add %[[ADD_14]], %[[DIVIDE_7]] : tensor<f64>
// CHECK:           %[[CONSTANT_21:.*]] = stablehlo.constant dense<7.500000e+00> : tensor<f64>
// CHECK:           %[[ADD_17:.*]] = stablehlo.add %[[CONSTANT_21]], %[[SELECT_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_22:.*]] = stablehlo.constant dense<2.0149030205422647> : tensor<f64>
// CHECK:           %[[DIVIDE_8:.*]] = stablehlo.divide %[[SELECT_0]], %[[CONSTANT_21]] : tensor<f64>
// CHECK:           %[[LOG_PLUS_ONE_0:.*]] = stablehlo.log_plus_one %[[DIVIDE_8]] : tensor<f64>
// CHECK:           %[[ADD_18:.*]] = stablehlo.add %[[CONSTANT_22]], %[[LOG_PLUS_ONE_0]] : tensor<f64>
// CHECK:           %[[DIVIDE_9:.*]] = stablehlo.divide %[[ADD_17]], %[[ADD_18]] : tensor<f64>
// CHECK:           %[[ADD_19:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_2]] : tensor<f64>
// CHECK:           %[[SUBTRACT_2:.*]] = stablehlo.subtract %[[ADD_19]], %[[DIVIDE_9]] : tensor<f64>
// CHECK:           %[[MULTIPLY_1:.*]] = stablehlo.multiply %[[SUBTRACT_2]], %[[ADD_18]] : tensor<f64>
// CHECK:           %[[LOG_0:.*]] = stablehlo.log %[[ADD_16]] : tensor<f64>
// CHECK:           %[[CONSTANT_23:.*]] = stablehlo.constant dense<0.91893853320467266> : tensor<f64>
// CHECK:           %[[ADD_20:.*]] = stablehlo.add %[[CONSTANT_23]], %[[MULTIPLY_1]] : tensor<f64>
// CHECK:           %[[ADD_21:.*]] = stablehlo.add %[[ADD_20]], %[[LOG_0]] : tensor<f64>
// CHECK:           %[[ABS_0:.*]] = stablehlo.abs %[[ADD_0]] : tensor<f64>
// CHECK:           %[[FLOOR_0:.*]] = stablehlo.floor %[[ABS_0]] : tensor<f64>
// CHECK:           %[[SUBTRACT_3:.*]] = stablehlo.subtract %[[ABS_0]], %[[FLOOR_0]] : tensor<f64>
// CHECK:           %[[COMPARE_1:.*]] = stablehlo.compare  LT, %[[CONSTANT_2]], %[[SUBTRACT_3]] : (tensor<f64>, tensor<f64>) -> tensor<i1>
// CHECK:           %[[SUBTRACT_4:.*]] = stablehlo.subtract %[[CONSTANT_3]], %[[SUBTRACT_3]] : tensor<f64>
// CHECK:           %[[SELECT_1:.*]] = stablehlo.select %[[COMPARE_1]], %[[SUBTRACT_4]], %[[SUBTRACT_3]] : tensor<i1>, tensor<f64>
// CHECK:           %[[CONSTANT_24:.*]] = stablehlo.constant dense<3.1415926535897931> : tensor<f64>
// CHECK:           %[[MULTIPLY_2:.*]] = stablehlo.multiply %[[CONSTANT_24]], %[[SELECT_1]] : tensor<f64>
// CHECK:           %[[SINE_0:.*]] = stablehlo.sine %[[MULTIPLY_2]] : tensor<f64>
// CHECK:           %[[LOG_1:.*]] = stablehlo.log %[[SINE_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_25:.*]] = stablehlo.constant dense<1.1447298858494002> : tensor<f64>
// CHECK:           %[[SUBTRACT_5:.*]] = stablehlo.subtract %[[CONSTANT_25]], %[[LOG_1]] : tensor<f64>
// CHECK:           %[[SUBTRACT_6:.*]] = stablehlo.subtract %[[SUBTRACT_5]], %[[ADD_21]] : tensor<f64>
// CHECK:           %[[IS_FINITE_0:.*]] = stablehlo.is_finite %[[LOG_1]] : (tensor<f64>) -> tensor<i1>
// CHECK:           %[[NEGATE_1:.*]] = stablehlo.negate %[[LOG_1]] : tensor<f64>
// CHECK:           %[[SELECT_2:.*]] = stablehlo.select %[[IS_FINITE_0]], %[[SUBTRACT_6]], %[[NEGATE_1]] : tensor<i1>, tensor<f64>
// CHECK:           %[[SELECT_3:.*]] = stablehlo.select %[[COMPARE_0]], %[[SELECT_2]], %[[ADD_21]] : tensor<i1>, tensor<f64>
// CHECK:           %[[ABS_1:.*]] = stablehlo.abs %[[ADD_0]] : tensor<f64>
// CHECK:           %[[CONSTANT_26:.*]] = stablehlo.constant dense<0x7FF0000000000000> : tensor<f64>
// CHECK:           %[[COMPARE_2:.*]] = stablehlo.compare  EQ, %[[ABS_1]], %[[CONSTANT_26]] : (tensor<f64>, tensor<f64>) -> tensor<i1>
// CHECK:           %[[CONSTANT_27:.*]] = stablehlo.constant dense<0x7FF0000000000000> : tensor<f64>
// CHECK:           %[[SELECT_4:.*]] = stablehlo.select %[[COMPARE_2]], %[[CONSTANT_27]], %[[SELECT_3]] : tensor<i1>, tensor<f64>
// CHECK:           %[[EXPONENTIAL_0:.*]] = stablehlo.exponential %[[SELECT_4]] : tensor<f64>
// CHECK:           %[[CONSTANT_28:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<f64>
// CHECK:           %[[CONSTANT_29:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f64>
// CHECK:           %[[NEGATE_2:.*]] = stablehlo.negate %[[ADD_0]] : tensor<f64>
// CHECK:           %[[POWER_0:.*]] = stablehlo.power %[[ARG1]], %[[NEGATE_2]] : tensor<f64>
// CHECK:           %[[ADD_22:.*]] = stablehlo.add %[[ARG1]], %[[CONSTANT_29]] : tensor<f64>
// CHECK:           %[[POWER_1:.*]] = stablehlo.power %[[ADD_22]], %[[NEGATE_2]] : tensor<f64>
// CHECK:           %[[ADD_23:.*]] = stablehlo.add %[[POWER_0]], %[[POWER_1]] : tensor<f64>
// CHECK:           %[[ADD_24:.*]] = stablehlo.add %[[ADD_22]], %[[CONSTANT_29]] : tensor<f64>
// CHECK:           %[[POWER_2:.*]] = stablehlo.power %[[ADD_24]], %[[NEGATE_2]] : tensor<f64>
// CHECK:           %[[ADD_25:.*]] = stablehlo.add %[[ADD_23]], %[[POWER_2]] : tensor<f64>
// CHECK:           %[[ADD_26:.*]] = stablehlo.add %[[ADD_24]], %[[CONSTANT_29]] : tensor<f64>
// CHECK:           %[[POWER_3:.*]] = stablehlo.power %[[ADD_26]], %[[NEGATE_2]] : tensor<f64>
// CHECK:           %[[ADD_27:.*]] = stablehlo.add %[[ADD_25]], %[[POWER_3]] : tensor<f64>
// CHECK:           %[[ADD_28:.*]] = stablehlo.add %[[ADD_26]], %[[CONSTANT_29]] : tensor<f64>
// CHECK:           %[[POWER_4:.*]] = stablehlo.power %[[ADD_28]], %[[NEGATE_2]] : tensor<f64>
// CHECK:           %[[ADD_29:.*]] = stablehlo.add %[[ADD_27]], %[[POWER_4]] : tensor<f64>
// CHECK:           %[[ADD_30:.*]] = stablehlo.add %[[ADD_28]], %[[CONSTANT_29]] : tensor<f64>
// CHECK:           %[[POWER_5:.*]] = stablehlo.power %[[ADD_30]], %[[NEGATE_2]] : tensor<f64>
// CHECK:           %[[ADD_31:.*]] = stablehlo.add %[[ADD_29]], %[[POWER_5]] : tensor<f64>
// CHECK:           %[[ADD_32:.*]] = stablehlo.add %[[ADD_30]], %[[CONSTANT_29]] : tensor<f64>
// CHECK:           %[[POWER_6:.*]] = stablehlo.power %[[ADD_32]], %[[NEGATE_2]] : tensor<f64>
// CHECK:           %[[ADD_33:.*]] = stablehlo.add %[[ADD_31]], %[[POWER_6]] : tensor<f64>
// CHECK:           %[[ADD_34:.*]] = stablehlo.add %[[ADD_32]], %[[CONSTANT_29]] : tensor<f64>
// CHECK:           %[[POWER_7:.*]] = stablehlo.power %[[ADD_34]], %[[NEGATE_2]] : tensor<f64>
// CHECK:           %[[ADD_35:.*]] = stablehlo.add %[[ADD_33]], %[[POWER_7]] : tensor<f64>
// CHECK:           %[[ADD_36:.*]] = stablehlo.add %[[ADD_34]], %[[CONSTANT_29]] : tensor<f64>
// CHECK:           %[[POWER_8:.*]] = stablehlo.power %[[ADD_36]], %[[NEGATE_2]] : tensor<f64>
// CHECK:           %[[ADD_37:.*]] = stablehlo.add %[[ADD_35]], %[[POWER_8]] : tensor<f64>
// CHECK:           %[[ADD_38:.*]] = stablehlo.add %[[ADD_36]], %[[CONSTANT_29]] : tensor<f64>
// CHECK:           %[[POWER_9:.*]] = stablehlo.power %[[ADD_38]], %[[NEGATE_2]] : tensor<f64>
// CHECK:           %[[ADD_39:.*]] = stablehlo.add %[[ADD_37]], %[[POWER_9]] : tensor<f64>
// CHECK:           %[[ADD_40:.*]] = stablehlo.add %[[ADD_38]], %[[CONSTANT_29]] : tensor<f64>
// CHECK:           %[[POWER_10:.*]] = stablehlo.power %[[ADD_40]], %[[NEGATE_2]] : tensor<f64>
// CHECK:           %[[CONSTANT_30:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f64>
// CHECK:           %[[MULTIPLY_3:.*]] = stablehlo.multiply %[[POWER_10]], %[[ADD_40]] : tensor<f64>
// CHECK:           %[[SUBTRACT_7:.*]] = stablehlo.subtract %[[ADD_0]], %[[CONSTANT_30]] : tensor<f64>
// CHECK:           %[[DIVIDE_10:.*]] = stablehlo.divide %[[MULTIPLY_3]], %[[SUBTRACT_7]] : tensor<f64>
// CHECK:           %[[MULTIPLY_4:.*]] = stablehlo.multiply %[[ADD_40]], %[[ADD_40]] : tensor<f64>
// CHECK:           %[[DIVIDE_11:.*]] = stablehlo.divide %[[CONSTANT_29]], %[[MULTIPLY_4]] : tensor<f64>
// CHECK:           %[[CONSTANT_31:.*]] = stablehlo.constant dense<2.200000e+01> : tensor<f64>
// CHECK:           %[[ADD_41:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_31]] : tensor<f64>
// CHECK:           %[[CONSTANT_32:.*]] = stablehlo.constant dense<2.100000e+01> : tensor<f64>
// CHECK:           %[[ADD_42:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_32]] : tensor<f64>
// CHECK:           %[[MULTIPLY_5:.*]] = stablehlo.multiply %[[ADD_41]], %[[ADD_42]] : tensor<f64>
// CHECK:           %[[CONSTANT_33:.*]] = stablehlo.constant dense<-1.3954464685812522E-19> : tensor<f64>
// CHECK:           %[[ADD_43:.*]] = stablehlo.add %[[CONSTANT_28]], %[[CONSTANT_33]] : tensor<f64>
// CHECK:           %[[MULTIPLY_6:.*]] = stablehlo.multiply %[[DIVIDE_11]], %[[ADD_43]] : tensor<f64>
// CHECK:           %[[MULTIPLY_7:.*]] = stablehlo.multiply %[[MULTIPLY_5]], %[[MULTIPLY_6]] : tensor<f64>
// CHECK:           %[[CONSTANT_34:.*]] = stablehlo.constant dense<2.000000e+01> : tensor<f64>
// CHECK:           %[[ADD_44:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_34]] : tensor<f64>
// CHECK:           %[[CONSTANT_35:.*]] = stablehlo.constant dense<1.900000e+01> : tensor<f64>
// CHECK:           %[[ADD_45:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_35]] : tensor<f64>
// CHECK:           %[[MULTIPLY_8:.*]] = stablehlo.multiply %[[ADD_44]], %[[ADD_45]] : tensor<f64>
// CHECK:           %[[CONSTANT_36:.*]] = stablehlo.constant dense<5.5090028283602295E-18> : tensor<f64>
// CHECK:           %[[ADD_46:.*]] = stablehlo.add %[[MULTIPLY_7]], %[[CONSTANT_36]] : tensor<f64>
// CHECK:           %[[MULTIPLY_9:.*]] = stablehlo.multiply %[[DIVIDE_11]], %[[ADD_46]] : tensor<f64>
// CHECK:           %[[MULTIPLY_10:.*]] = stablehlo.multiply %[[MULTIPLY_8]], %[[MULTIPLY_9]] : tensor<f64>
// CHECK:           %[[CONSTANT_37:.*]] = stablehlo.constant dense<1.800000e+01> : tensor<f64>
// CHECK:           %[[ADD_47:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_37]] : tensor<f64>
// CHECK:           %[[CONSTANT_38:.*]] = stablehlo.constant dense<1.700000e+01> : tensor<f64>
// CHECK:           %[[ADD_48:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_38]] : tensor<f64>
// CHECK:           %[[MULTIPLY_11:.*]] = stablehlo.multiply %[[ADD_47]], %[[ADD_48]] : tensor<f64>
// CHECK:           %[[CONSTANT_39:.*]] = stablehlo.constant dense<-2.1748686985580617E-16> : tensor<f64>
// CHECK:           %[[ADD_49:.*]] = stablehlo.add %[[MULTIPLY_10]], %[[CONSTANT_39]] : tensor<f64>
// CHECK:           %[[MULTIPLY_12:.*]] = stablehlo.multiply %[[DIVIDE_11]], %[[ADD_49]] : tensor<f64>
// CHECK:           %[[MULTIPLY_13:.*]] = stablehlo.multiply %[[MULTIPLY_11]], %[[MULTIPLY_12]] : tensor<f64>
// CHECK:           %[[CONSTANT_40:.*]] = stablehlo.constant dense<1.600000e+01> : tensor<f64>
// CHECK:           %[[ADD_50:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_40]] : tensor<f64>
// CHECK:           %[[CONSTANT_41:.*]] = stablehlo.constant dense<1.500000e+01> : tensor<f64>
// CHECK:           %[[ADD_51:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_41]] : tensor<f64>
// CHECK:           %[[MULTIPLY_14:.*]] = stablehlo.multiply %[[ADD_50]], %[[ADD_51]] : tensor<f64>
// CHECK:           %[[CONSTANT_42:.*]] = stablehlo.constant dense<8.5860620562778452E-15> : tensor<f64>
// CHECK:           %[[ADD_52:.*]] = stablehlo.add %[[MULTIPLY_13]], %[[CONSTANT_42]] : tensor<f64>
// CHECK:           %[[MULTIPLY_15:.*]] = stablehlo.multiply %[[DIVIDE_11]], %[[ADD_52]] : tensor<f64>
// CHECK:           %[[MULTIPLY_16:.*]] = stablehlo.multiply %[[MULTIPLY_14]], %[[MULTIPLY_15]] : tensor<f64>
// CHECK:           %[[CONSTANT_43:.*]] = stablehlo.constant dense<1.400000e+01> : tensor<f64>
// CHECK:           %[[ADD_53:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_43]] : tensor<f64>
// CHECK:           %[[CONSTANT_44:.*]] = stablehlo.constant dense<1.300000e+01> : tensor<f64>
// CHECK:           %[[ADD_54:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_44]] : tensor<f64>
// CHECK:           %[[MULTIPLY_17:.*]] = stablehlo.multiply %[[ADD_53]], %[[ADD_54]] : tensor<f64>
// CHECK:           %[[CONSTANT_45:.*]] = stablehlo.constant dense<-3.3896802963225832E-13> : tensor<f64>
// CHECK:           %[[ADD_55:.*]] = stablehlo.add %[[MULTIPLY_16]], %[[CONSTANT_45]] : tensor<f64>
// CHECK:           %[[MULTIPLY_18:.*]] = stablehlo.multiply %[[DIVIDE_11]], %[[ADD_55]] : tensor<f64>
// CHECK:           %[[MULTIPLY_19:.*]] = stablehlo.multiply %[[MULTIPLY_17]], %[[MULTIPLY_18]] : tensor<f64>
// CHECK:           %[[CONSTANT_46:.*]] = stablehlo.constant dense<1.200000e+01> : tensor<f64>
// CHECK:           %[[ADD_56:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_46]] : tensor<f64>
// CHECK:           %[[CONSTANT_47:.*]] = stablehlo.constant dense<1.100000e+01> : tensor<f64>
// CHECK:           %[[ADD_57:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_47]] : tensor<f64>
// CHECK:           %[[MULTIPLY_20:.*]] = stablehlo.multiply %[[ADD_56]], %[[ADD_57]] : tensor<f64>
// CHECK:           %[[CONSTANT_48:.*]] = stablehlo.constant dense<1.3382536530684679E-11> : tensor<f64>
// CHECK:           %[[ADD_58:.*]] = stablehlo.add %[[MULTIPLY_19]], %[[CONSTANT_48]] : tensor<f64>
// CHECK:           %[[MULTIPLY_21:.*]] = stablehlo.multiply %[[DIVIDE_11]], %[[ADD_58]] : tensor<f64>
// CHECK:           %[[MULTIPLY_22:.*]] = stablehlo.multiply %[[MULTIPLY_20]], %[[MULTIPLY_21]] : tensor<f64>
// CHECK:           %[[CONSTANT_49:.*]] = stablehlo.constant dense<1.000000e+01> : tensor<f64>
// CHECK:           %[[ADD_59:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_49]] : tensor<f64>
// CHECK:           %[[CONSTANT_50:.*]] = stablehlo.constant dense<9.000000e+00> : tensor<f64>
// CHECK:           %[[ADD_60:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_50]] : tensor<f64>
// CHECK:           %[[MULTIPLY_23:.*]] = stablehlo.multiply %[[ADD_59]], %[[ADD_60]] : tensor<f64>
// CHECK:           %[[CONSTANT_51:.*]] = stablehlo.constant dense<-5.2841901386874932E-10> : tensor<f64>
// CHECK:           %[[ADD_61:.*]] = stablehlo.add %[[MULTIPLY_22]], %[[CONSTANT_51]] : tensor<f64>
// CHECK:           %[[MULTIPLY_24:.*]] = stablehlo.multiply %[[DIVIDE_11]], %[[ADD_61]] : tensor<f64>
// CHECK:           %[[MULTIPLY_25:.*]] = stablehlo.multiply %[[MULTIPLY_23]], %[[MULTIPLY_24]] : tensor<f64>
// CHECK:           %[[CONSTANT_52:.*]] = stablehlo.constant dense<8.000000e+00> : tensor<f64>
// CHECK:           %[[ADD_62:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_52]] : tensor<f64>
// CHECK:           %[[CONSTANT_53:.*]] = stablehlo.constant dense<7.000000e+00> : tensor<f64>
// CHECK:           %[[ADD_63:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_53]] : tensor<f64>
// CHECK:           %[[MULTIPLY_26:.*]] = stablehlo.multiply %[[ADD_62]], %[[ADD_63]] : tensor<f64>
// CHECK:           %[[CONSTANT_54:.*]] = stablehlo.constant dense<2.08767569878681E-8> : tensor<f64>
// CHECK:           %[[ADD_64:.*]] = stablehlo.add %[[MULTIPLY_25]], %[[CONSTANT_54]] : tensor<f64>
// CHECK:           %[[MULTIPLY_27:.*]] = stablehlo.multiply %[[DIVIDE_11]], %[[ADD_64]] : tensor<f64>
// CHECK:           %[[MULTIPLY_28:.*]] = stablehlo.multiply %[[MULTIPLY_26]], %[[MULTIPLY_27]] : tensor<f64>
// CHECK:           %[[CONSTANT_55:.*]] = stablehlo.constant dense<6.000000e+00> : tensor<f64>
// CHECK:           %[[ADD_65:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_55]] : tensor<f64>
// CHECK:           %[[CONSTANT_56:.*]] = stablehlo.constant dense<5.000000e+00> : tensor<f64>
// CHECK:           %[[ADD_66:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_56]] : tensor<f64>
// CHECK:           %[[MULTIPLY_29:.*]] = stablehlo.multiply %[[ADD_65]], %[[ADD_66]] : tensor<f64>
// CHECK:           %[[CONSTANT_57:.*]] = stablehlo.constant dense<-8.2671957671957675E-7> : tensor<f64>
// CHECK:           %[[ADD_67:.*]] = stablehlo.add %[[MULTIPLY_28]], %[[CONSTANT_57]] : tensor<f64>
// CHECK:           %[[MULTIPLY_30:.*]] = stablehlo.multiply %[[DIVIDE_11]], %[[ADD_67]] : tensor<f64>
// CHECK:           %[[MULTIPLY_31:.*]] = stablehlo.multiply %[[MULTIPLY_29]], %[[MULTIPLY_30]] : tensor<f64>
// CHECK:           %[[CONSTANT_58:.*]] = stablehlo.constant dense<4.000000e+00> : tensor<f64>
// CHECK:           %[[ADD_68:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_58]] : tensor<f64>
// CHECK:           %[[CONSTANT_59:.*]] = stablehlo.constant dense<3.000000e+00> : tensor<f64>
// CHECK:           %[[ADD_69:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_59]] : tensor<f64>
// CHECK:           %[[MULTIPLY_32:.*]] = stablehlo.multiply %[[ADD_68]], %[[ADD_69]] : tensor<f64>
// CHECK:           %[[CONSTANT_60:.*]] = stablehlo.constant dense<3.3068783068783071E-5> : tensor<f64>
// CHECK:           %[[ADD_70:.*]] = stablehlo.add %[[MULTIPLY_31]], %[[CONSTANT_60]] : tensor<f64>
// CHECK:           %[[MULTIPLY_33:.*]] = stablehlo.multiply %[[DIVIDE_11]], %[[ADD_70]] : tensor<f64>
// CHECK:           %[[MULTIPLY_34:.*]] = stablehlo.multiply %[[MULTIPLY_32]], %[[MULTIPLY_33]] : tensor<f64>
// CHECK:           %[[CONSTANT_61:.*]] = stablehlo.constant dense<2.000000e+00> : tensor<f64>
// CHECK:           %[[ADD_71:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_61]] : tensor<f64>
// CHECK:           %[[CONSTANT_62:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f64>
// CHECK:           %[[ADD_72:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_62]] : tensor<f64>
// CHECK:           %[[MULTIPLY_35:.*]] = stablehlo.multiply %[[ADD_71]], %[[ADD_72]] : tensor<f64>
// CHECK:           %[[CONSTANT_63:.*]] = stablehlo.constant dense<-0.0013888888888888889> : tensor<f64>
// CHECK:           %[[ADD_73:.*]] = stablehlo.add %[[MULTIPLY_34]], %[[CONSTANT_63]] : tensor<f64>
// CHECK:           %[[MULTIPLY_36:.*]] = stablehlo.multiply %[[DIVIDE_11]], %[[ADD_73]] : tensor<f64>
// CHECK:           %[[MULTIPLY_37:.*]] = stablehlo.multiply %[[MULTIPLY_35]], %[[MULTIPLY_36]] : tensor<f64>
// CHECK:           %[[CONSTANT_64:.*]] = stablehlo.constant dense<5.000000e-01> : tensor<f64>
// CHECK:           %[[DIVIDE_12:.*]] = stablehlo.divide %[[ADD_0]], %[[ADD_40]] : tensor<f64>
// CHECK:           %[[CONSTANT_65:.*]] = stablehlo.constant dense<0.083333333333333329> : tensor<f64>
// CHECK:           %[[ADD_74:.*]] = stablehlo.add %[[CONSTANT_65]], %[[MULTIPLY_37]] : tensor<f64>
// CHECK:           %[[MULTIPLY_38:.*]] = stablehlo.multiply %[[DIVIDE_12]], %[[ADD_74]] : tensor<f64>
// CHECK:           %[[ADD_75:.*]] = stablehlo.add %[[CONSTANT_64]], %[[MULTIPLY_38]] : tensor<f64>
// CHECK:           %[[MULTIPLY_39:.*]] = stablehlo.multiply %[[POWER_10]], %[[ADD_75]] : tensor<f64>
// CHECK:           %[[ADD_76:.*]] = stablehlo.add %[[ADD_39]], %[[DIVIDE_10]] : tensor<f64>
// CHECK:           %[[ADD_77:.*]] = stablehlo.add %[[ADD_76]], %[[MULTIPLY_39]] : tensor<f64>
// CHECK:           %[[ABS_2:.*]] = stablehlo.abs %[[POWER_10]] : tensor<f64>
// CHECK:           %[[ABS_3:.*]] = stablehlo.abs %[[ADD_39]] : tensor<f64>
// CHECK:           %[[CONSTANT_66:.*]] = stablehlo.constant dense<4.940660e-324> : tensor<f64>
// CHECK:           %[[MULTIPLY_40:.*]] = stablehlo.multiply %[[ABS_3]], %[[CONSTANT_66]] : tensor<f64>
// CHECK:           %[[COMPARE_3:.*]] = stablehlo.compare  LT, %[[ABS_2]], %[[MULTIPLY_40]] : (tensor<f64>, tensor<f64>) -> tensor<i1>
// CHECK:           %[[SELECT_5:.*]] = stablehlo.select %[[COMPARE_3]], %[[ADD_39]], %[[ADD_77]] : tensor<i1>, tensor<f64>
// CHECK:           %[[CONSTANT_67:.*]] = stablehlo.constant dense<0x7FF8000000000000> : tensor<f64>
// CHECK:           %[[COMPARE_4:.*]] = stablehlo.compare  LT, %[[ADD_0]], %[[CONSTANT_30]] : (tensor<f64>, tensor<f64>) -> tensor<i1>
// CHECK:           %[[SELECT_6:.*]] = stablehlo.select %[[COMPARE_4]], %[[CONSTANT_67]], %[[SELECT_5]] : tensor<i1>, tensor<f64>
// CHECK:           %[[COMPARE_5:.*]] = stablehlo.compare  LE, %[[ARG1]], %[[CONSTANT_28]] : (tensor<f64>, tensor<f64>) -> tensor<i1>
// CHECK:           %[[FLOOR_1:.*]] = stablehlo.floor %[[ADD_0]] : tensor<f64>
// CHECK:           %[[COMPARE_6:.*]] = stablehlo.compare  NE, %[[ADD_0]], %[[FLOOR_1]] : (tensor<f64>, tensor<f64>) -> tensor<i1>
// CHECK:           %[[AND_0:.*]] = stablehlo.and %[[COMPARE_5]], %[[COMPARE_6]] : tensor<i1>
// CHECK:           %[[SELECT_7:.*]] = stablehlo.select %[[AND_0]], %[[CONSTANT_67]], %[[SELECT_6]] : tensor<i1>, tensor<f64>
// CHECK:           %[[CONSTANT_68:.*]] = stablehlo.constant dense<0x7FF0000000000000> : tensor<f64>
// CHECK:           %[[FLOOR_2:.*]] = stablehlo.floor %[[ARG1]] : tensor<f64>
// CHECK:           %[[COMPARE_7:.*]] = stablehlo.compare  EQ, %[[ARG1]], %[[FLOOR_2]] : (tensor<f64>, tensor<f64>) -> tensor<i1>
// CHECK:           %[[AND_1:.*]] = stablehlo.and %[[COMPARE_5]], %[[COMPARE_7]] : tensor<i1>
// CHECK:           %[[CONSTANT_69:.*]] = stablehlo.constant dense<2.000000e+00> : tensor<f64>
// CHECK:           %[[FLOOR_3:.*]] = stablehlo.floor %[[ADD_0]] : tensor<f64>
// CHECK:           %[[COMPARE_8:.*]] = stablehlo.compare  EQ, %[[ADD_0]], %[[FLOOR_3]] : (tensor<f64>, tensor<f64>) -> tensor<i1>
// CHECK:           %[[REMAINDER_1:.*]] = stablehlo.remainder %[[ADD_0]], %[[CONSTANT_69]] : tensor<f64>
// CHECK:           %[[COMPARE_9:.*]] = stablehlo.compare  EQ, %[[REMAINDER_1]], %[[CONSTANT_28]] : (tensor<f64>, tensor<f64>) -> tensor<i1>
// CHECK:           %[[AND_2:.*]] = stablehlo.and %[[COMPARE_8]], %[[COMPARE_9]] : tensor<i1>
// CHECK:           %[[SELECT_8:.*]] = stablehlo.select %[[AND_2]], %[[CONSTANT_68]], %[[CONSTANT_67]] : tensor<i1>, tensor<f64>
// CHECK:           %[[SELECT_9:.*]] = stablehlo.select %[[AND_1]], %[[SELECT_8]], %[[SELECT_7]] : tensor<i1>, tensor<f64>
// CHECK:           %[[COMPARE_10:.*]] = stablehlo.compare  EQ, %[[ADD_0]], %[[CONSTANT_29]] : (tensor<f64>, tensor<f64>) -> tensor<i1>
// CHECK:           %[[SELECT_10:.*]] = stablehlo.select %[[COMPARE_10]], %[[CONSTANT_68]], %[[SELECT_9]] : tensor<i1>, tensor<f64>
// CHECK:           %[[MULTIPLY_41:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[EXPONENTIAL_0]] : tensor<f64>
// CHECK:           %[[MULTIPLY_42:.*]] = stablehlo.multiply %[[MULTIPLY_41]], %[[SELECT_10]] : tensor<f64>
// CHECK:           %[[CONSTANT_70:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<f64>
// CHECK:           %[[COMPARE_11:.*]] = stablehlo.compare  EQ, %[[ARG0]], %[[CONSTANT_70]] : (tensor<f64>, tensor<f64>) -> tensor<i1>
// CHECK:           %[[CONSTANT_71:.*]] = stablehlo.constant dense<5.000000e-01> : tensor<f64>
// CHECK:           %[[COMPARE_12:.*]] = stablehlo.compare  LT, %[[ARG1]], %[[CONSTANT_71]] : (tensor<f64>, tensor<f64>) -> tensor<i1>
// CHECK:           %[[NEGATE_3:.*]] = stablehlo.negate %[[ARG1]] : tensor<f64>
// CHECK:           %[[CONSTANT_72:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f64>
// CHECK:           %[[SUBTRACT_8:.*]] = stablehlo.subtract %[[ARG1]], %[[CONSTANT_72]] : tensor<f64>
// CHECK:           %[[SELECT_11:.*]] = stablehlo.select %[[COMPARE_12]], %[[NEGATE_3]], %[[SUBTRACT_8]] : tensor<i1>, tensor<f64>
// CHECK:           %[[CONSTANT_73:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<f64>
// CHECK:           %[[CONSTANT_74:.*]] = stablehlo.constant dense<0.99999999999980993> : tensor<f64>
// CHECK:           %[[CONSTANT_75:.*]] = stablehlo.constant dense<676.5203681218851> : tensor<f64>
// CHECK:           %[[CONSTANT_76:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f64>
// CHECK:           %[[ADD_78:.*]] = stablehlo.add %[[SELECT_11]], %[[CONSTANT_76]] : tensor<f64>
// CHECK:           %[[MULTIPLY_43:.*]] = stablehlo.multiply %[[ADD_78]], %[[ADD_78]] : tensor<f64>
// CHECK:           %[[DIVIDE_13:.*]] = stablehlo.divide %[[CONSTANT_75]], %[[MULTIPLY_43]] : tensor<f64>
// CHECK:           %[[SUBTRACT_9:.*]] = stablehlo.subtract %[[CONSTANT_73]], %[[DIVIDE_13]] : tensor<f64>
// CHECK:           %[[DIVIDE_14:.*]] = stablehlo.divide %[[CONSTANT_75]], %[[ADD_78]] : tensor<f64>
// CHECK:           %[[ADD_79:.*]] = stablehlo.add %[[CONSTANT_74]], %[[DIVIDE_14]] : tensor<f64>
// CHECK:           %[[CONSTANT_77:.*]] = stablehlo.constant dense<-1259.1392167224028> : tensor<f64>
// CHECK:           %[[CONSTANT_78:.*]] = stablehlo.constant dense<2.000000e+00> : tensor<f64>
// CHECK:           %[[ADD_80:.*]] = stablehlo.add %[[SELECT_11]], %[[CONSTANT_78]] : tensor<f64>
// CHECK:           %[[MULTIPLY_44:.*]] = stablehlo.multiply %[[ADD_80]], %[[ADD_80]] : tensor<f64>
// CHECK:           %[[DIVIDE_15:.*]] = stablehlo.divide %[[CONSTANT_77]], %[[MULTIPLY_44]] : tensor<f64>
// CHECK:           %[[SUBTRACT_10:.*]] = stablehlo.subtract %[[SUBTRACT_9]], %[[DIVIDE_15]] : tensor<f64>
// CHECK:           %[[DIVIDE_16:.*]] = stablehlo.divide %[[CONSTANT_77]], %[[ADD_80]] : tensor<f64>
// CHECK:           %[[ADD_81:.*]] = stablehlo.add %[[ADD_79]], %[[DIVIDE_16]] : tensor<f64>
// CHECK:           %[[CONSTANT_79:.*]] = stablehlo.constant dense<771.32342877765313> : tensor<f64>
// CHECK:           %[[CONSTANT_80:.*]] = stablehlo.constant dense<3.000000e+00> : tensor<f64>
// CHECK:           %[[ADD_82:.*]] = stablehlo.add %[[SELECT_11]], %[[CONSTANT_80]] : tensor<f64>
// CHECK:           %[[MULTIPLY_45:.*]] = stablehlo.multiply %[[ADD_82]], %[[ADD_82]] : tensor<f64>
// CHECK:           %[[DIVIDE_17:.*]] = stablehlo.divide %[[CONSTANT_79]], %[[MULTIPLY_45]] : tensor<f64>
// CHECK:           %[[SUBTRACT_11:.*]] = stablehlo.subtract %[[SUBTRACT_10]], %[[DIVIDE_17]] : tensor<f64>
// CHECK:           %[[DIVIDE_18:.*]] = stablehlo.divide %[[CONSTANT_79]], %[[ADD_82]] : tensor<f64>
// CHECK:           %[[ADD_83:.*]] = stablehlo.add %[[ADD_81]], %[[DIVIDE_18]] : tensor<f64>
// CHECK:           %[[CONSTANT_81:.*]] = stablehlo.constant dense<-176.61502916214059> : tensor<f64>
// CHECK:           %[[CONSTANT_82:.*]] = stablehlo.constant dense<4.000000e+00> : tensor<f64>
// CHECK:           %[[ADD_84:.*]] = stablehlo.add %[[SELECT_11]], %[[CONSTANT_82]] : tensor<f64>
// CHECK:           %[[MULTIPLY_46:.*]] = stablehlo.multiply %[[ADD_84]], %[[ADD_84]] : tensor<f64>
// CHECK:           %[[DIVIDE_19:.*]] = stablehlo.divide %[[CONSTANT_81]], %[[MULTIPLY_46]] : tensor<f64>
// CHECK:           %[[SUBTRACT_12:.*]] = stablehlo.subtract %[[SUBTRACT_11]], %[[DIVIDE_19]] : tensor<f64>
// CHECK:           %[[DIVIDE_20:.*]] = stablehlo.divide %[[CONSTANT_81]], %[[ADD_84]] : tensor<f64>
// CHECK:           %[[ADD_85:.*]] = stablehlo.add %[[ADD_83]], %[[DIVIDE_20]] : tensor<f64>
// CHECK:           %[[CONSTANT_83:.*]] = stablehlo.constant dense<12.507343278686905> : tensor<f64>
// CHECK:           %[[CONSTANT_84:.*]] = stablehlo.constant dense<5.000000e+00> : tensor<f64>
// CHECK:           %[[ADD_86:.*]] = stablehlo.add %[[SELECT_11]], %[[CONSTANT_84]] : tensor<f64>
// CHECK:           %[[MULTIPLY_47:.*]] = stablehlo.multiply %[[ADD_86]], %[[ADD_86]] : tensor<f64>
// CHECK:           %[[DIVIDE_21:.*]] = stablehlo.divide %[[CONSTANT_83]], %[[MULTIPLY_47]] : tensor<f64>
// CHECK:           %[[SUBTRACT_13:.*]] = stablehlo.subtract %[[SUBTRACT_12]], %[[DIVIDE_21]] : tensor<f64>
// CHECK:           %[[DIVIDE_22:.*]] = stablehlo.divide %[[CONSTANT_83]], %[[ADD_86]] : tensor<f64>
// CHECK:           %[[ADD_87:.*]] = stablehlo.add %[[ADD_85]], %[[DIVIDE_22]] : tensor<f64>
// CHECK:           %[[CONSTANT_85:.*]] = stablehlo.constant dense<-0.13857109526572012> : tensor<f64>
// CHECK:           %[[CONSTANT_86:.*]] = stablehlo.constant dense<6.000000e+00> : tensor<f64>
// CHECK:           %[[ADD_88:.*]] = stablehlo.add %[[SELECT_11]], %[[CONSTANT_86]] : tensor<f64>
// CHECK:           %[[MULTIPLY_48:.*]] = stablehlo.multiply %[[ADD_88]], %[[ADD_88]] : tensor<f64>
// CHECK:           %[[DIVIDE_23:.*]] = stablehlo.divide %[[CONSTANT_85]], %[[MULTIPLY_48]] : tensor<f64>
// CHECK:           %[[SUBTRACT_14:.*]] = stablehlo.subtract %[[SUBTRACT_13]], %[[DIVIDE_23]] : tensor<f64>
// CHECK:           %[[DIVIDE_24:.*]] = stablehlo.divide %[[CONSTANT_85]], %[[ADD_88]] : tensor<f64>
// CHECK:           %[[ADD_89:.*]] = stablehlo.add %[[ADD_87]], %[[DIVIDE_24]] : tensor<f64>
// CHECK:           %[[CONSTANT_87:.*]] = stablehlo.constant dense<9.9843695780195716E-6> : tensor<f64>
// CHECK:           %[[CONSTANT_88:.*]] = stablehlo.constant dense<7.000000e+00> : tensor<f64>
// CHECK:           %[[ADD_90:.*]] = stablehlo.add %[[SELECT_11]], %[[CONSTANT_88]] : tensor<f64>
// CHECK:           %[[MULTIPLY_49:.*]] = stablehlo.multiply %[[ADD_90]], %[[ADD_90]] : tensor<f64>
// CHECK:           %[[DIVIDE_25:.*]] = stablehlo.divide %[[CONSTANT_87]], %[[MULTIPLY_49]] : tensor<f64>
// CHECK:           %[[SUBTRACT_15:.*]] = stablehlo.subtract %[[SUBTRACT_14]], %[[DIVIDE_25]] : tensor<f64>
// CHECK:           %[[DIVIDE_26:.*]] = stablehlo.divide %[[CONSTANT_87]], %[[ADD_90]] : tensor<f64>
// CHECK:           %[[ADD_91:.*]] = stablehlo.add %[[ADD_89]], %[[DIVIDE_26]] : tensor<f64>
// CHECK:           %[[CONSTANT_89:.*]] = stablehlo.constant dense<1.5056327351493116E-7> : tensor<f64>
// CHECK:           %[[CONSTANT_90:.*]] = stablehlo.constant dense<8.000000e+00> : tensor<f64>
// CHECK:           %[[ADD_92:.*]] = stablehlo.add %[[SELECT_11]], %[[CONSTANT_90]] : tensor<f64>
// CHECK:           %[[MULTIPLY_50:.*]] = stablehlo.multiply %[[ADD_92]], %[[ADD_92]] : tensor<f64>
// CHECK:           %[[DIVIDE_27:.*]] = stablehlo.divide %[[CONSTANT_89]], %[[MULTIPLY_50]] : tensor<f64>
// CHECK:           %[[SUBTRACT_16:.*]] = stablehlo.subtract %[[SUBTRACT_15]], %[[DIVIDE_27]] : tensor<f64>
// CHECK:           %[[DIVIDE_28:.*]] = stablehlo.divide %[[CONSTANT_89]], %[[ADD_92]] : tensor<f64>
// CHECK:           %[[ADD_93:.*]] = stablehlo.add %[[ADD_91]], %[[DIVIDE_28]] : tensor<f64>
// CHECK:           %[[CONSTANT_91:.*]] = stablehlo.constant dense<7.500000e+00> : tensor<f64>
// CHECK:           %[[ADD_94:.*]] = stablehlo.add %[[CONSTANT_91]], %[[SELECT_11]] : tensor<f64>
// CHECK:           %[[CONSTANT_92:.*]] = stablehlo.constant dense<2.0149030205422647> : tensor<f64>
// CHECK:           %[[DIVIDE_29:.*]] = stablehlo.divide %[[SELECT_11]], %[[CONSTANT_91]] : tensor<f64>
// CHECK:           %[[LOG_PLUS_ONE_1:.*]] = stablehlo.log_plus_one %[[DIVIDE_29]] : tensor<f64>
// CHECK:           %[[ADD_95:.*]] = stablehlo.add %[[CONSTANT_92]], %[[LOG_PLUS_ONE_1]] : tensor<f64>
// CHECK:           %[[DIVIDE_30:.*]] = stablehlo.divide %[[SUBTRACT_16]], %[[ADD_93]] : tensor<f64>
// CHECK:           %[[CONSTANT_93:.*]] = stablehlo.constant dense<7.000000e+00> : tensor<f64>
// CHECK:           %[[DIVIDE_31:.*]] = stablehlo.divide %[[CONSTANT_93]], %[[ADD_94]] : tensor<f64>
// CHECK:           %[[ADD_96:.*]] = stablehlo.add %[[ADD_95]], %[[DIVIDE_30]] : tensor<f64>
// CHECK:           %[[SUBTRACT_17:.*]] = stablehlo.subtract %[[ADD_96]], %[[DIVIDE_31]] : tensor<f64>
// CHECK:           %[[CONSTANT_94:.*]] = stablehlo.constant dense<5.000000e-01> : tensor<f64>
// CHECK:           %[[ADD_97:.*]] = stablehlo.add %[[ARG1]], %[[CONSTANT_94]] : tensor<f64>
// CHECK:           %[[FLOOR_4:.*]] = stablehlo.floor %[[ADD_97]] : tensor<f64>
// CHECK:           %[[ABS_4:.*]] = stablehlo.abs %[[FLOOR_4]] : tensor<f64>
// CHECK:           %[[ADD_98:.*]] = stablehlo.add %[[ARG1]], %[[ABS_4]] : tensor<f64>
// CHECK:           %[[CONSTANT_95:.*]] = stablehlo.constant dense<3.1415926535897931> : tensor<f64>
// CHECK:           %[[MULTIPLY_51:.*]] = stablehlo.multiply %[[CONSTANT_95]], %[[ADD_98]] : tensor<f64>
// CHECK:           %[[COSINE_0:.*]] = stablehlo.cosine %[[MULTIPLY_51]] : tensor<f64>
// CHECK:           %[[SINE_1:.*]] = stablehlo.sine %[[MULTIPLY_51]] : tensor<f64>
// CHECK:           %[[MULTIPLY_52:.*]] = stablehlo.multiply %[[CONSTANT_95]], %[[COSINE_0]] : tensor<f64>
// CHECK:           %[[DIVIDE_32:.*]] = stablehlo.divide %[[MULTIPLY_52]], %[[SINE_1]] : tensor<f64>
// CHECK:           %[[SUBTRACT_18:.*]] = stablehlo.subtract %[[SUBTRACT_17]], %[[DIVIDE_32]] : tensor<f64>
// CHECK:           %[[SELECT_12:.*]] = stablehlo.select %[[COMPARE_12]], %[[SUBTRACT_18]], %[[SUBTRACT_17]] : tensor<i1>, tensor<f64>
// CHECK:           %[[COMPARE_13:.*]] = stablehlo.compare  LE, %[[ARG1]], %[[CONSTANT_73]] : (tensor<f64>, tensor<f64>) -> tensor<i1>
// CHECK:           %[[FLOOR_5:.*]] = stablehlo.floor %[[ARG1]] : tensor<f64>
// CHECK:           %[[COMPARE_14:.*]] = stablehlo.compare  EQ, %[[ARG1]], %[[FLOOR_5]] : (tensor<f64>, tensor<f64>) -> tensor<i1>
// CHECK:           %[[AND_3:.*]] = stablehlo.and %[[COMPARE_13]], %[[COMPARE_14]] : tensor<i1>
// CHECK:           %[[CONSTANT_96:.*]] = stablehlo.constant dense<0x7FF8000000000000> : tensor<f64>
// CHECK:           %[[SELECT_13:.*]] = stablehlo.select %[[AND_3]], %[[CONSTANT_96]], %[[SELECT_12]] : tensor<i1>, tensor<f64>
// CHECK:           %[[SELECT_14:.*]] = stablehlo.select %[[COMPARE_11]], %[[SELECT_13]], %[[MULTIPLY_42]] : tensor<i1>, tensor<f64>
// CHECK:           %[[FLOOR_6:.*]] = stablehlo.floor %[[ARG0]] : tensor<f64>
// CHECK:           %[[COMPARE_15:.*]] = stablehlo.compare  NE, %[[ARG0]], %[[FLOOR_6]] : (tensor<f64>, tensor<f64>) -> tensor<i1>
// CHECK:           %[[COMPARE_16:.*]] = stablehlo.compare  LT, %[[ARG0]], %[[CONSTANT_70]] : (tensor<f64>, tensor<f64>) -> tensor<i1>
// CHECK:           %[[OR_0:.*]] = stablehlo.or %[[COMPARE_15]], %[[COMPARE_16]] : tensor<i1>
// CHECK:           %[[CONSTANT_97:.*]] = stablehlo.constant dense<0x7FF8000000000000> : tensor<f64>
// CHECK:           %[[SELECT_15:.*]] = stablehlo.select %[[OR_0]], %[[CONSTANT_97]], %[[SELECT_14]] : tensor<i1>, tensor<f64>
// CHECK:           return %[[SELECT_15]] : tensor<f64>
// CHECK:         }
func.func @polygamma_f64(%lhs : tensor<f64>, %rhs : tensor<f64>) -> tensor<f64> {
  %1 = chlo.polygamma %lhs, %rhs : tensor<f64>, tensor<f64> -> tensor<f64>
  func.return %1 : tensor<f64>
}

// -----

// CHECK-LABEL:   func.func @polygamma_f16(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<f16>,
// CHECK-SAME:      %[[ARG1:.*]]: tensor<f16>) -> tensor<f16> {
// CHECK:           %[[CONVERT_0:.*]] = stablehlo.convert %[[ARG0]] : (tensor<f16>) -> tensor<f32>
// CHECK:           %[[CONVERT_1:.*]] = stablehlo.convert %[[ARG1]] : (tensor<f16>) -> tensor<f32>
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[CONSTANT_1:.*]] = stablehlo.constant dense<2.000000e+00> : tensor<f32>
// CHECK:           %[[REMAINDER_0:.*]] = stablehlo.remainder %[[CONVERT_0]], %[[CONSTANT_1]] : tensor<f32>
// CHECK:           %[[MULTIPLY_0:.*]] = stablehlo.multiply %[[CONSTANT_1]], %[[REMAINDER_0]] : tensor<f32>
// CHECK:           %[[SUBTRACT_0:.*]] = stablehlo.subtract %[[MULTIPLY_0]], %[[CONSTANT_0]] : tensor<f32>
// CHECK:           %[[ADD_0:.*]] = stablehlo.add %[[CONVERT_0]], %[[CONSTANT_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_2:.*]] = stablehlo.constant dense<5.000000e-01> : tensor<f32>
// CHECK:           %[[COMPARE_0:.*]] = stablehlo.compare  LT, %[[ADD_0]], %[[CONSTANT_2]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[NEGATE_0:.*]] = stablehlo.negate %[[ADD_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_3:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[SUBTRACT_1:.*]] = stablehlo.subtract %[[ADD_0]], %[[CONSTANT_3]] : tensor<f32>
// CHECK:           %[[SELECT_0:.*]] = stablehlo.select %[[COMPARE_0]], %[[NEGATE_0]], %[[SUBTRACT_1]] : tensor<i1>, tensor<f32>
// CHECK:           %[[CONSTANT_4:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[CONSTANT_5:.*]] = stablehlo.constant dense<676.520386> : tensor<f32>
// CHECK:           %[[CONSTANT_6:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_1:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_6]] : tensor<f32>
// CHECK:           %[[DIVIDE_0:.*]] = stablehlo.divide %[[CONSTANT_5]], %[[ADD_1]] : tensor<f32>
// CHECK:           %[[ADD_2:.*]] = stablehlo.add %[[CONSTANT_4]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_7:.*]] = stablehlo.constant dense<-1259.13916> : tensor<f32>
// CHECK:           %[[CONSTANT_8:.*]] = stablehlo.constant dense<2.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_3:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_8]] : tensor<f32>
// CHECK:           %[[DIVIDE_1:.*]] = stablehlo.divide %[[CONSTANT_7]], %[[ADD_3]] : tensor<f32>
// CHECK:           %[[ADD_4:.*]] = stablehlo.add %[[ADD_2]], %[[DIVIDE_1]] : tensor<f32>
// CHECK:           %[[CONSTANT_9:.*]] = stablehlo.constant dense<771.323425> : tensor<f32>
// CHECK:           %[[CONSTANT_10:.*]] = stablehlo.constant dense<3.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_5:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_10]] : tensor<f32>
// CHECK:           %[[DIVIDE_2:.*]] = stablehlo.divide %[[CONSTANT_9]], %[[ADD_5]] : tensor<f32>
// CHECK:           %[[ADD_6:.*]] = stablehlo.add %[[ADD_4]], %[[DIVIDE_2]] : tensor<f32>
// CHECK:           %[[CONSTANT_11:.*]] = stablehlo.constant dense<-176.615036> : tensor<f32>
// CHECK:           %[[CONSTANT_12:.*]] = stablehlo.constant dense<4.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_7:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_12]] : tensor<f32>
// CHECK:           %[[DIVIDE_3:.*]] = stablehlo.divide %[[CONSTANT_11]], %[[ADD_7]] : tensor<f32>
// CHECK:           %[[ADD_8:.*]] = stablehlo.add %[[ADD_6]], %[[DIVIDE_3]] : tensor<f32>
// CHECK:           %[[CONSTANT_13:.*]] = stablehlo.constant dense<12.5073433> : tensor<f32>
// CHECK:           %[[CONSTANT_14:.*]] = stablehlo.constant dense<5.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_9:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_14]] : tensor<f32>
// CHECK:           %[[DIVIDE_4:.*]] = stablehlo.divide %[[CONSTANT_13]], %[[ADD_9]] : tensor<f32>
// CHECK:           %[[ADD_10:.*]] = stablehlo.add %[[ADD_8]], %[[DIVIDE_4]] : tensor<f32>
// CHECK:           %[[CONSTANT_15:.*]] = stablehlo.constant dense<-0.138571098> : tensor<f32>
// CHECK:           %[[CONSTANT_16:.*]] = stablehlo.constant dense<6.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_11:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_16]] : tensor<f32>
// CHECK:           %[[DIVIDE_5:.*]] = stablehlo.divide %[[CONSTANT_15]], %[[ADD_11]] : tensor<f32>
// CHECK:           %[[ADD_12:.*]] = stablehlo.add %[[ADD_10]], %[[DIVIDE_5]] : tensor<f32>
// CHECK:           %[[CONSTANT_17:.*]] = stablehlo.constant dense<9.98436917E-6> : tensor<f32>
// CHECK:           %[[CONSTANT_18:.*]] = stablehlo.constant dense<7.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_13:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_18]] : tensor<f32>
// CHECK:           %[[DIVIDE_6:.*]] = stablehlo.divide %[[CONSTANT_17]], %[[ADD_13]] : tensor<f32>
// CHECK:           %[[ADD_14:.*]] = stablehlo.add %[[ADD_12]], %[[DIVIDE_6]] : tensor<f32>
// CHECK:           %[[CONSTANT_19:.*]] = stablehlo.constant dense<1.50563267E-7> : tensor<f32>
// CHECK:           %[[CONSTANT_20:.*]] = stablehlo.constant dense<8.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_15:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_20]] : tensor<f32>
// CHECK:           %[[DIVIDE_7:.*]] = stablehlo.divide %[[CONSTANT_19]], %[[ADD_15]] : tensor<f32>
// CHECK:           %[[ADD_16:.*]] = stablehlo.add %[[ADD_14]], %[[DIVIDE_7]] : tensor<f32>
// CHECK:           %[[CONSTANT_21:.*]] = stablehlo.constant dense<7.500000e+00> : tensor<f32>
// CHECK:           %[[ADD_17:.*]] = stablehlo.add %[[CONSTANT_21]], %[[SELECT_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_22:.*]] = stablehlo.constant dense<2.01490307> : tensor<f32>
// CHECK:           %[[DIVIDE_8:.*]] = stablehlo.divide %[[SELECT_0]], %[[CONSTANT_21]] : tensor<f32>
// CHECK:           %[[LOG_PLUS_ONE_0:.*]] = stablehlo.log_plus_one %[[DIVIDE_8]] : tensor<f32>
// CHECK:           %[[ADD_18:.*]] = stablehlo.add %[[CONSTANT_22]], %[[LOG_PLUS_ONE_0]] : tensor<f32>
// CHECK:           %[[DIVIDE_9:.*]] = stablehlo.divide %[[ADD_17]], %[[ADD_18]] : tensor<f32>
// CHECK:           %[[ADD_19:.*]] = stablehlo.add %[[SELECT_0]], %[[CONSTANT_2]] : tensor<f32>
// CHECK:           %[[SUBTRACT_2:.*]] = stablehlo.subtract %[[ADD_19]], %[[DIVIDE_9]] : tensor<f32>
// CHECK:           %[[MULTIPLY_1:.*]] = stablehlo.multiply %[[SUBTRACT_2]], %[[ADD_18]] : tensor<f32>
// CHECK:           %[[LOG_0:.*]] = stablehlo.log %[[ADD_16]] : tensor<f32>
// CHECK:           %[[CONSTANT_23:.*]] = stablehlo.constant dense<0.918938517> : tensor<f32>
// CHECK:           %[[ADD_20:.*]] = stablehlo.add %[[CONSTANT_23]], %[[MULTIPLY_1]] : tensor<f32>
// CHECK:           %[[ADD_21:.*]] = stablehlo.add %[[ADD_20]], %[[LOG_0]] : tensor<f32>
// CHECK:           %[[ABS_0:.*]] = stablehlo.abs %[[ADD_0]] : tensor<f32>
// CHECK:           %[[FLOOR_0:.*]] = stablehlo.floor %[[ABS_0]] : tensor<f32>
// CHECK:           %[[SUBTRACT_3:.*]] = stablehlo.subtract %[[ABS_0]], %[[FLOOR_0]] : tensor<f32>
// CHECK:           %[[COMPARE_1:.*]] = stablehlo.compare  LT, %[[CONSTANT_2]], %[[SUBTRACT_3]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[SUBTRACT_4:.*]] = stablehlo.subtract %[[CONSTANT_3]], %[[SUBTRACT_3]] : tensor<f32>
// CHECK:           %[[SELECT_1:.*]] = stablehlo.select %[[COMPARE_1]], %[[SUBTRACT_4]], %[[SUBTRACT_3]] : tensor<i1>, tensor<f32>
// CHECK:           %[[CONSTANT_24:.*]] = stablehlo.constant dense<3.14159274> : tensor<f32>
// CHECK:           %[[MULTIPLY_2:.*]] = stablehlo.multiply %[[CONSTANT_24]], %[[SELECT_1]] : tensor<f32>
// CHECK:           %[[SINE_0:.*]] = stablehlo.sine %[[MULTIPLY_2]] : tensor<f32>
// CHECK:           %[[LOG_1:.*]] = stablehlo.log %[[SINE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_25:.*]] = stablehlo.constant dense<1.14472985> : tensor<f32>
// CHECK:           %[[SUBTRACT_5:.*]] = stablehlo.subtract %[[CONSTANT_25]], %[[LOG_1]] : tensor<f32>
// CHECK:           %[[SUBTRACT_6:.*]] = stablehlo.subtract %[[SUBTRACT_5]], %[[ADD_21]] : tensor<f32>
// CHECK:           %[[IS_FINITE_0:.*]] = stablehlo.is_finite %[[LOG_1]] : (tensor<f32>) -> tensor<i1>
// CHECK:           %[[NEGATE_1:.*]] = stablehlo.negate %[[LOG_1]] : tensor<f32>
// CHECK:           %[[SELECT_2:.*]] = stablehlo.select %[[IS_FINITE_0]], %[[SUBTRACT_6]], %[[NEGATE_1]] : tensor<i1>, tensor<f32>
// CHECK:           %[[SELECT_3:.*]] = stablehlo.select %[[COMPARE_0]], %[[SELECT_2]], %[[ADD_21]] : tensor<i1>, tensor<f32>
// CHECK:           %[[ABS_1:.*]] = stablehlo.abs %[[ADD_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_26:.*]] = stablehlo.constant dense<0x7F800000> : tensor<f32>
// CHECK:           %[[COMPARE_2:.*]] = stablehlo.compare  EQ, %[[ABS_1]], %[[CONSTANT_26]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[CONSTANT_27:.*]] = stablehlo.constant dense<0x7F800000> : tensor<f32>
// CHECK:           %[[SELECT_4:.*]] = stablehlo.select %[[COMPARE_2]], %[[CONSTANT_27]], %[[SELECT_3]] : tensor<i1>, tensor<f32>
// CHECK:           %[[EXPONENTIAL_0:.*]] = stablehlo.exponential %[[SELECT_4]] : tensor<f32>
// CHECK:           %[[CONSTANT_28:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<f32>
// CHECK:           %[[CONSTANT_29:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[NEGATE_2:.*]] = stablehlo.negate %[[ADD_0]] : tensor<f32>
// CHECK:           %[[POWER_0:.*]] = stablehlo.power %[[CONVERT_1]], %[[NEGATE_2]] : tensor<f32>
// CHECK:           %[[ADD_22:.*]] = stablehlo.add %[[CONVERT_1]], %[[CONSTANT_29]] : tensor<f32>
// CHECK:           %[[POWER_1:.*]] = stablehlo.power %[[ADD_22]], %[[NEGATE_2]] : tensor<f32>
// CHECK:           %[[ADD_23:.*]] = stablehlo.add %[[POWER_0]], %[[POWER_1]] : tensor<f32>
// CHECK:           %[[ADD_24:.*]] = stablehlo.add %[[ADD_22]], %[[CONSTANT_29]] : tensor<f32>
// CHECK:           %[[POWER_2:.*]] = stablehlo.power %[[ADD_24]], %[[NEGATE_2]] : tensor<f32>
// CHECK:           %[[ADD_25:.*]] = stablehlo.add %[[ADD_23]], %[[POWER_2]] : tensor<f32>
// CHECK:           %[[ADD_26:.*]] = stablehlo.add %[[ADD_24]], %[[CONSTANT_29]] : tensor<f32>
// CHECK:           %[[POWER_3:.*]] = stablehlo.power %[[ADD_26]], %[[NEGATE_2]] : tensor<f32>
// CHECK:           %[[ADD_27:.*]] = stablehlo.add %[[ADD_25]], %[[POWER_3]] : tensor<f32>
// CHECK:           %[[ADD_28:.*]] = stablehlo.add %[[ADD_26]], %[[CONSTANT_29]] : tensor<f32>
// CHECK:           %[[POWER_4:.*]] = stablehlo.power %[[ADD_28]], %[[NEGATE_2]] : tensor<f32>
// CHECK:           %[[ADD_29:.*]] = stablehlo.add %[[ADD_27]], %[[POWER_4]] : tensor<f32>
// CHECK:           %[[ADD_30:.*]] = stablehlo.add %[[ADD_28]], %[[CONSTANT_29]] : tensor<f32>
// CHECK:           %[[POWER_5:.*]] = stablehlo.power %[[ADD_30]], %[[NEGATE_2]] : tensor<f32>
// CHECK:           %[[ADD_31:.*]] = stablehlo.add %[[ADD_29]], %[[POWER_5]] : tensor<f32>
// CHECK:           %[[ADD_32:.*]] = stablehlo.add %[[ADD_30]], %[[CONSTANT_29]] : tensor<f32>
// CHECK:           %[[POWER_6:.*]] = stablehlo.power %[[ADD_32]], %[[NEGATE_2]] : tensor<f32>
// CHECK:           %[[ADD_33:.*]] = stablehlo.add %[[ADD_31]], %[[POWER_6]] : tensor<f32>
// CHECK:           %[[ADD_34:.*]] = stablehlo.add %[[ADD_32]], %[[CONSTANT_29]] : tensor<f32>
// CHECK:           %[[POWER_7:.*]] = stablehlo.power %[[ADD_34]], %[[NEGATE_2]] : tensor<f32>
// CHECK:           %[[ADD_35:.*]] = stablehlo.add %[[ADD_33]], %[[POWER_7]] : tensor<f32>
// CHECK:           %[[ADD_36:.*]] = stablehlo.add %[[ADD_34]], %[[CONSTANT_29]] : tensor<f32>
// CHECK:           %[[POWER_8:.*]] = stablehlo.power %[[ADD_36]], %[[NEGATE_2]] : tensor<f32>
// CHECK:           %[[ADD_37:.*]] = stablehlo.add %[[ADD_35]], %[[POWER_8]] : tensor<f32>
// CHECK:           %[[ADD_38:.*]] = stablehlo.add %[[ADD_36]], %[[CONSTANT_29]] : tensor<f32>
// CHECK:           %[[POWER_9:.*]] = stablehlo.power %[[ADD_38]], %[[NEGATE_2]] : tensor<f32>
// CHECK:           %[[ADD_39:.*]] = stablehlo.add %[[ADD_37]], %[[POWER_9]] : tensor<f32>
// CHECK:           %[[ADD_40:.*]] = stablehlo.add %[[ADD_38]], %[[CONSTANT_29]] : tensor<f32>
// CHECK:           %[[POWER_10:.*]] = stablehlo.power %[[ADD_40]], %[[NEGATE_2]] : tensor<f32>
// CHECK:           %[[CONSTANT_30:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[MULTIPLY_3:.*]] = stablehlo.multiply %[[POWER_10]], %[[ADD_40]] : tensor<f32>
// CHECK:           %[[SUBTRACT_7:.*]] = stablehlo.subtract %[[ADD_0]], %[[CONSTANT_30]] : tensor<f32>
// CHECK:           %[[DIVIDE_10:.*]] = stablehlo.divide %[[MULTIPLY_3]], %[[SUBTRACT_7]] : tensor<f32>
// CHECK:           %[[MULTIPLY_4:.*]] = stablehlo.multiply %[[ADD_40]], %[[ADD_40]] : tensor<f32>
// CHECK:           %[[DIVIDE_11:.*]] = stablehlo.divide %[[CONSTANT_29]], %[[MULTIPLY_4]] : tensor<f32>
// CHECK:           %[[CONSTANT_31:.*]] = stablehlo.constant dense<2.200000e+01> : tensor<f32>
// CHECK:           %[[ADD_41:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_31]] : tensor<f32>
// CHECK:           %[[CONSTANT_32:.*]] = stablehlo.constant dense<2.100000e+01> : tensor<f32>
// CHECK:           %[[ADD_42:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_32]] : tensor<f32>
// CHECK:           %[[MULTIPLY_5:.*]] = stablehlo.multiply %[[ADD_41]], %[[ADD_42]] : tensor<f32>
// CHECK:           %[[CONSTANT_33:.*]] = stablehlo.constant dense<-1.39544646E-19> : tensor<f32>
// CHECK:           %[[ADD_43:.*]] = stablehlo.add %[[CONSTANT_28]], %[[CONSTANT_33]] : tensor<f32>
// CHECK:           %[[MULTIPLY_6:.*]] = stablehlo.multiply %[[DIVIDE_11]], %[[ADD_43]] : tensor<f32>
// CHECK:           %[[MULTIPLY_7:.*]] = stablehlo.multiply %[[MULTIPLY_5]], %[[MULTIPLY_6]] : tensor<f32>
// CHECK:           %[[CONSTANT_34:.*]] = stablehlo.constant dense<2.000000e+01> : tensor<f32>
// CHECK:           %[[ADD_44:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_34]] : tensor<f32>
// CHECK:           %[[CONSTANT_35:.*]] = stablehlo.constant dense<1.900000e+01> : tensor<f32>
// CHECK:           %[[ADD_45:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_35]] : tensor<f32>
// CHECK:           %[[MULTIPLY_8:.*]] = stablehlo.multiply %[[ADD_44]], %[[ADD_45]] : tensor<f32>
// CHECK:           %[[CONSTANT_36:.*]] = stablehlo.constant dense<5.50900303E-18> : tensor<f32>
// CHECK:           %[[ADD_46:.*]] = stablehlo.add %[[MULTIPLY_7]], %[[CONSTANT_36]] : tensor<f32>
// CHECK:           %[[MULTIPLY_9:.*]] = stablehlo.multiply %[[DIVIDE_11]], %[[ADD_46]] : tensor<f32>
// CHECK:           %[[MULTIPLY_10:.*]] = stablehlo.multiply %[[MULTIPLY_8]], %[[MULTIPLY_9]] : tensor<f32>
// CHECK:           %[[CONSTANT_37:.*]] = stablehlo.constant dense<1.800000e+01> : tensor<f32>
// CHECK:           %[[ADD_47:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_37]] : tensor<f32>
// CHECK:           %[[CONSTANT_38:.*]] = stablehlo.constant dense<1.700000e+01> : tensor<f32>
// CHECK:           %[[ADD_48:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_38]] : tensor<f32>
// CHECK:           %[[MULTIPLY_11:.*]] = stablehlo.multiply %[[ADD_47]], %[[ADD_48]] : tensor<f32>
// CHECK:           %[[CONSTANT_39:.*]] = stablehlo.constant dense<-2.17486866E-16> : tensor<f32>
// CHECK:           %[[ADD_49:.*]] = stablehlo.add %[[MULTIPLY_10]], %[[CONSTANT_39]] : tensor<f32>
// CHECK:           %[[MULTIPLY_12:.*]] = stablehlo.multiply %[[DIVIDE_11]], %[[ADD_49]] : tensor<f32>
// CHECK:           %[[MULTIPLY_13:.*]] = stablehlo.multiply %[[MULTIPLY_11]], %[[MULTIPLY_12]] : tensor<f32>
// CHECK:           %[[CONSTANT_40:.*]] = stablehlo.constant dense<1.600000e+01> : tensor<f32>
// CHECK:           %[[ADD_50:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_40]] : tensor<f32>
// CHECK:           %[[CONSTANT_41:.*]] = stablehlo.constant dense<1.500000e+01> : tensor<f32>
// CHECK:           %[[ADD_51:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_41]] : tensor<f32>
// CHECK:           %[[MULTIPLY_14:.*]] = stablehlo.multiply %[[ADD_50]], %[[ADD_51]] : tensor<f32>
// CHECK:           %[[CONSTANT_42:.*]] = stablehlo.constant dense<8.58606213E-15> : tensor<f32>
// CHECK:           %[[ADD_52:.*]] = stablehlo.add %[[MULTIPLY_13]], %[[CONSTANT_42]] : tensor<f32>
// CHECK:           %[[MULTIPLY_15:.*]] = stablehlo.multiply %[[DIVIDE_11]], %[[ADD_52]] : tensor<f32>
// CHECK:           %[[MULTIPLY_16:.*]] = stablehlo.multiply %[[MULTIPLY_14]], %[[MULTIPLY_15]] : tensor<f32>
// CHECK:           %[[CONSTANT_43:.*]] = stablehlo.constant dense<1.400000e+01> : tensor<f32>
// CHECK:           %[[ADD_53:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_43]] : tensor<f32>
// CHECK:           %[[CONSTANT_44:.*]] = stablehlo.constant dense<1.300000e+01> : tensor<f32>
// CHECK:           %[[ADD_54:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_44]] : tensor<f32>
// CHECK:           %[[MULTIPLY_17:.*]] = stablehlo.multiply %[[ADD_53]], %[[ADD_54]] : tensor<f32>
// CHECK:           %[[CONSTANT_45:.*]] = stablehlo.constant dense<-3.3896803E-13> : tensor<f32>
// CHECK:           %[[ADD_55:.*]] = stablehlo.add %[[MULTIPLY_16]], %[[CONSTANT_45]] : tensor<f32>
// CHECK:           %[[MULTIPLY_18:.*]] = stablehlo.multiply %[[DIVIDE_11]], %[[ADD_55]] : tensor<f32>
// CHECK:           %[[MULTIPLY_19:.*]] = stablehlo.multiply %[[MULTIPLY_17]], %[[MULTIPLY_18]] : tensor<f32>
// CHECK:           %[[CONSTANT_46:.*]] = stablehlo.constant dense<1.200000e+01> : tensor<f32>
// CHECK:           %[[ADD_56:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_46]] : tensor<f32>
// CHECK:           %[[CONSTANT_47:.*]] = stablehlo.constant dense<1.100000e+01> : tensor<f32>
// CHECK:           %[[ADD_57:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_47]] : tensor<f32>
// CHECK:           %[[MULTIPLY_20:.*]] = stablehlo.multiply %[[ADD_56]], %[[ADD_57]] : tensor<f32>
// CHECK:           %[[CONSTANT_48:.*]] = stablehlo.constant dense<1.33825364E-11> : tensor<f32>
// CHECK:           %[[ADD_58:.*]] = stablehlo.add %[[MULTIPLY_19]], %[[CONSTANT_48]] : tensor<f32>
// CHECK:           %[[MULTIPLY_21:.*]] = stablehlo.multiply %[[DIVIDE_11]], %[[ADD_58]] : tensor<f32>
// CHECK:           %[[MULTIPLY_22:.*]] = stablehlo.multiply %[[MULTIPLY_20]], %[[MULTIPLY_21]] : tensor<f32>
// CHECK:           %[[CONSTANT_49:.*]] = stablehlo.constant dense<1.000000e+01> : tensor<f32>
// CHECK:           %[[ADD_59:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_49]] : tensor<f32>
// CHECK:           %[[CONSTANT_50:.*]] = stablehlo.constant dense<9.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_60:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_50]] : tensor<f32>
// CHECK:           %[[MULTIPLY_23:.*]] = stablehlo.multiply %[[ADD_59]], %[[ADD_60]] : tensor<f32>
// CHECK:           %[[CONSTANT_51:.*]] = stablehlo.constant dense<-5.28419031E-10> : tensor<f32>
// CHECK:           %[[ADD_61:.*]] = stablehlo.add %[[MULTIPLY_22]], %[[CONSTANT_51]] : tensor<f32>
// CHECK:           %[[MULTIPLY_24:.*]] = stablehlo.multiply %[[DIVIDE_11]], %[[ADD_61]] : tensor<f32>
// CHECK:           %[[MULTIPLY_25:.*]] = stablehlo.multiply %[[MULTIPLY_23]], %[[MULTIPLY_24]] : tensor<f32>
// CHECK:           %[[CONSTANT_52:.*]] = stablehlo.constant dense<8.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_62:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_52]] : tensor<f32>
// CHECK:           %[[CONSTANT_53:.*]] = stablehlo.constant dense<7.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_63:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_53]] : tensor<f32>
// CHECK:           %[[MULTIPLY_26:.*]] = stablehlo.multiply %[[ADD_62]], %[[ADD_63]] : tensor<f32>
// CHECK:           %[[CONSTANT_54:.*]] = stablehlo.constant dense<2.08767563E-8> : tensor<f32>
// CHECK:           %[[ADD_64:.*]] = stablehlo.add %[[MULTIPLY_25]], %[[CONSTANT_54]] : tensor<f32>
// CHECK:           %[[MULTIPLY_27:.*]] = stablehlo.multiply %[[DIVIDE_11]], %[[ADD_64]] : tensor<f32>
// CHECK:           %[[MULTIPLY_28:.*]] = stablehlo.multiply %[[MULTIPLY_26]], %[[MULTIPLY_27]] : tensor<f32>
// CHECK:           %[[CONSTANT_55:.*]] = stablehlo.constant dense<6.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_65:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_55]] : tensor<f32>
// CHECK:           %[[CONSTANT_56:.*]] = stablehlo.constant dense<5.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_66:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_56]] : tensor<f32>
// CHECK:           %[[MULTIPLY_29:.*]] = stablehlo.multiply %[[ADD_65]], %[[ADD_66]] : tensor<f32>
// CHECK:           %[[CONSTANT_57:.*]] = stablehlo.constant dense<-8.26719599E-7> : tensor<f32>
// CHECK:           %[[ADD_67:.*]] = stablehlo.add %[[MULTIPLY_28]], %[[CONSTANT_57]] : tensor<f32>
// CHECK:           %[[MULTIPLY_30:.*]] = stablehlo.multiply %[[DIVIDE_11]], %[[ADD_67]] : tensor<f32>
// CHECK:           %[[MULTIPLY_31:.*]] = stablehlo.multiply %[[MULTIPLY_29]], %[[MULTIPLY_30]] : tensor<f32>
// CHECK:           %[[CONSTANT_58:.*]] = stablehlo.constant dense<4.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_68:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_58]] : tensor<f32>
// CHECK:           %[[CONSTANT_59:.*]] = stablehlo.constant dense<3.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_69:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_59]] : tensor<f32>
// CHECK:           %[[MULTIPLY_32:.*]] = stablehlo.multiply %[[ADD_68]], %[[ADD_69]] : tensor<f32>
// CHECK:           %[[CONSTANT_60:.*]] = stablehlo.constant dense<3.30687835E-5> : tensor<f32>
// CHECK:           %[[ADD_70:.*]] = stablehlo.add %[[MULTIPLY_31]], %[[CONSTANT_60]] : tensor<f32>
// CHECK:           %[[MULTIPLY_33:.*]] = stablehlo.multiply %[[DIVIDE_11]], %[[ADD_70]] : tensor<f32>
// CHECK:           %[[MULTIPLY_34:.*]] = stablehlo.multiply %[[MULTIPLY_32]], %[[MULTIPLY_33]] : tensor<f32>
// CHECK:           %[[CONSTANT_61:.*]] = stablehlo.constant dense<2.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_71:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_61]] : tensor<f32>
// CHECK:           %[[CONSTANT_62:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_72:.*]] = stablehlo.add %[[ADD_0]], %[[CONSTANT_62]] : tensor<f32>
// CHECK:           %[[MULTIPLY_35:.*]] = stablehlo.multiply %[[ADD_71]], %[[ADD_72]] : tensor<f32>
// CHECK:           %[[CONSTANT_63:.*]] = stablehlo.constant dense<-0.00138888892> : tensor<f32>
// CHECK:           %[[ADD_73:.*]] = stablehlo.add %[[MULTIPLY_34]], %[[CONSTANT_63]] : tensor<f32>
// CHECK:           %[[MULTIPLY_36:.*]] = stablehlo.multiply %[[DIVIDE_11]], %[[ADD_73]] : tensor<f32>
// CHECK:           %[[MULTIPLY_37:.*]] = stablehlo.multiply %[[MULTIPLY_35]], %[[MULTIPLY_36]] : tensor<f32>
// CHECK:           %[[CONSTANT_64:.*]] = stablehlo.constant dense<5.000000e-01> : tensor<f32>
// CHECK:           %[[DIVIDE_12:.*]] = stablehlo.divide %[[ADD_0]], %[[ADD_40]] : tensor<f32>
// CHECK:           %[[CONSTANT_65:.*]] = stablehlo.constant dense<0.0833333358> : tensor<f32>
// CHECK:           %[[ADD_74:.*]] = stablehlo.add %[[CONSTANT_65]], %[[MULTIPLY_37]] : tensor<f32>
// CHECK:           %[[MULTIPLY_38:.*]] = stablehlo.multiply %[[DIVIDE_12]], %[[ADD_74]] : tensor<f32>
// CHECK:           %[[ADD_75:.*]] = stablehlo.add %[[CONSTANT_64]], %[[MULTIPLY_38]] : tensor<f32>
// CHECK:           %[[MULTIPLY_39:.*]] = stablehlo.multiply %[[POWER_10]], %[[ADD_75]] : tensor<f32>
// CHECK:           %[[ADD_76:.*]] = stablehlo.add %[[ADD_39]], %[[DIVIDE_10]] : tensor<f32>
// CHECK:           %[[ADD_77:.*]] = stablehlo.add %[[ADD_76]], %[[MULTIPLY_39]] : tensor<f32>
// CHECK:           %[[ABS_2:.*]] = stablehlo.abs %[[POWER_10]] : tensor<f32>
// CHECK:           %[[ABS_3:.*]] = stablehlo.abs %[[ADD_39]] : tensor<f32>
// CHECK:           %[[CONSTANT_66:.*]] = stablehlo.constant dense<1.401300e-45> : tensor<f32>
// CHECK:           %[[MULTIPLY_40:.*]] = stablehlo.multiply %[[ABS_3]], %[[CONSTANT_66]] : tensor<f32>
// CHECK:           %[[COMPARE_3:.*]] = stablehlo.compare  LT, %[[ABS_2]], %[[MULTIPLY_40]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[SELECT_5:.*]] = stablehlo.select %[[COMPARE_3]], %[[ADD_39]], %[[ADD_77]] : tensor<i1>, tensor<f32>
// CHECK:           %[[CONSTANT_67:.*]] = stablehlo.constant dense<0x7FC00000> : tensor<f32>
// CHECK:           %[[COMPARE_4:.*]] = stablehlo.compare  LT, %[[ADD_0]], %[[CONSTANT_30]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[SELECT_6:.*]] = stablehlo.select %[[COMPARE_4]], %[[CONSTANT_67]], %[[SELECT_5]] : tensor<i1>, tensor<f32>
// CHECK:           %[[COMPARE_5:.*]] = stablehlo.compare  LE, %[[CONVERT_1]], %[[CONSTANT_28]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[FLOOR_1:.*]] = stablehlo.floor %[[ADD_0]] : tensor<f32>
// CHECK:           %[[COMPARE_6:.*]] = stablehlo.compare  NE, %[[ADD_0]], %[[FLOOR_1]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[AND_0:.*]] = stablehlo.and %[[COMPARE_5]], %[[COMPARE_6]] : tensor<i1>
// CHECK:           %[[SELECT_7:.*]] = stablehlo.select %[[AND_0]], %[[CONSTANT_67]], %[[SELECT_6]] : tensor<i1>, tensor<f32>
// CHECK:           %[[CONSTANT_68:.*]] = stablehlo.constant dense<0x7F800000> : tensor<f32>
// CHECK:           %[[FLOOR_2:.*]] = stablehlo.floor %[[CONVERT_1]] : tensor<f32>
// CHECK:           %[[COMPARE_7:.*]] = stablehlo.compare  EQ, %[[CONVERT_1]], %[[FLOOR_2]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[AND_1:.*]] = stablehlo.and %[[COMPARE_5]], %[[COMPARE_7]] : tensor<i1>
// CHECK:           %[[CONSTANT_69:.*]] = stablehlo.constant dense<2.000000e+00> : tensor<f32>
// CHECK:           %[[FLOOR_3:.*]] = stablehlo.floor %[[ADD_0]] : tensor<f32>
// CHECK:           %[[COMPARE_8:.*]] = stablehlo.compare  EQ, %[[ADD_0]], %[[FLOOR_3]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[REMAINDER_1:.*]] = stablehlo.remainder %[[ADD_0]], %[[CONSTANT_69]] : tensor<f32>
// CHECK:           %[[COMPARE_9:.*]] = stablehlo.compare  EQ, %[[REMAINDER_1]], %[[CONSTANT_28]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[AND_2:.*]] = stablehlo.and %[[COMPARE_8]], %[[COMPARE_9]] : tensor<i1>
// CHECK:           %[[SELECT_8:.*]] = stablehlo.select %[[AND_2]], %[[CONSTANT_68]], %[[CONSTANT_67]] : tensor<i1>, tensor<f32>
// CHECK:           %[[SELECT_9:.*]] = stablehlo.select %[[AND_1]], %[[SELECT_8]], %[[SELECT_7]] : tensor<i1>, tensor<f32>
// CHECK:           %[[COMPARE_10:.*]] = stablehlo.compare  EQ, %[[ADD_0]], %[[CONSTANT_29]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[SELECT_10:.*]] = stablehlo.select %[[COMPARE_10]], %[[CONSTANT_68]], %[[SELECT_9]] : tensor<i1>, tensor<f32>
// CHECK:           %[[MULTIPLY_41:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[EXPONENTIAL_0]] : tensor<f32>
// CHECK:           %[[MULTIPLY_42:.*]] = stablehlo.multiply %[[MULTIPLY_41]], %[[SELECT_10]] : tensor<f32>
// CHECK:           %[[CONSTANT_70:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<f32>
// CHECK:           %[[COMPARE_11:.*]] = stablehlo.compare  EQ, %[[CONVERT_0]], %[[CONSTANT_70]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[CONSTANT_71:.*]] = stablehlo.constant dense<5.000000e-01> : tensor<f32>
// CHECK:           %[[COMPARE_12:.*]] = stablehlo.compare  LT, %[[CONVERT_1]], %[[CONSTANT_71]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[NEGATE_3:.*]] = stablehlo.negate %[[CONVERT_1]] : tensor<f32>
// CHECK:           %[[CONSTANT_72:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[SUBTRACT_8:.*]] = stablehlo.subtract %[[CONVERT_1]], %[[CONSTANT_72]] : tensor<f32>
// CHECK:           %[[SELECT_11:.*]] = stablehlo.select %[[COMPARE_12]], %[[NEGATE_3]], %[[SUBTRACT_8]] : tensor<i1>, tensor<f32>
// CHECK:           %[[CONSTANT_73:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<f32>
// CHECK:           %[[CONSTANT_74:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[CONSTANT_75:.*]] = stablehlo.constant dense<676.520386> : tensor<f32>
// CHECK:           %[[CONSTANT_76:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_78:.*]] = stablehlo.add %[[SELECT_11]], %[[CONSTANT_76]] : tensor<f32>
// CHECK:           %[[MULTIPLY_43:.*]] = stablehlo.multiply %[[ADD_78]], %[[ADD_78]] : tensor<f32>
// CHECK:           %[[DIVIDE_13:.*]] = stablehlo.divide %[[CONSTANT_75]], %[[MULTIPLY_43]] : tensor<f32>
// CHECK:           %[[SUBTRACT_9:.*]] = stablehlo.subtract %[[CONSTANT_73]], %[[DIVIDE_13]] : tensor<f32>
// CHECK:           %[[DIVIDE_14:.*]] = stablehlo.divide %[[CONSTANT_75]], %[[ADD_78]] : tensor<f32>
// CHECK:           %[[ADD_79:.*]] = stablehlo.add %[[CONSTANT_74]], %[[DIVIDE_14]] : tensor<f32>
// CHECK:           %[[CONSTANT_77:.*]] = stablehlo.constant dense<-1259.13916> : tensor<f32>
// CHECK:           %[[CONSTANT_78:.*]] = stablehlo.constant dense<2.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_80:.*]] = stablehlo.add %[[SELECT_11]], %[[CONSTANT_78]] : tensor<f32>
// CHECK:           %[[MULTIPLY_44:.*]] = stablehlo.multiply %[[ADD_80]], %[[ADD_80]] : tensor<f32>
// CHECK:           %[[DIVIDE_15:.*]] = stablehlo.divide %[[CONSTANT_77]], %[[MULTIPLY_44]] : tensor<f32>
// CHECK:           %[[SUBTRACT_10:.*]] = stablehlo.subtract %[[SUBTRACT_9]], %[[DIVIDE_15]] : tensor<f32>
// CHECK:           %[[DIVIDE_16:.*]] = stablehlo.divide %[[CONSTANT_77]], %[[ADD_80]] : tensor<f32>
// CHECK:           %[[ADD_81:.*]] = stablehlo.add %[[ADD_79]], %[[DIVIDE_16]] : tensor<f32>
// CHECK:           %[[CONSTANT_79:.*]] = stablehlo.constant dense<771.323425> : tensor<f32>
// CHECK:           %[[CONSTANT_80:.*]] = stablehlo.constant dense<3.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_82:.*]] = stablehlo.add %[[SELECT_11]], %[[CONSTANT_80]] : tensor<f32>
// CHECK:           %[[MULTIPLY_45:.*]] = stablehlo.multiply %[[ADD_82]], %[[ADD_82]] : tensor<f32>
// CHECK:           %[[DIVIDE_17:.*]] = stablehlo.divide %[[CONSTANT_79]], %[[MULTIPLY_45]] : tensor<f32>
// CHECK:           %[[SUBTRACT_11:.*]] = stablehlo.subtract %[[SUBTRACT_10]], %[[DIVIDE_17]] : tensor<f32>
// CHECK:           %[[DIVIDE_18:.*]] = stablehlo.divide %[[CONSTANT_79]], %[[ADD_82]] : tensor<f32>
// CHECK:           %[[ADD_83:.*]] = stablehlo.add %[[ADD_81]], %[[DIVIDE_18]] : tensor<f32>
// CHECK:           %[[CONSTANT_81:.*]] = stablehlo.constant dense<-176.615036> : tensor<f32>
// CHECK:           %[[CONSTANT_82:.*]] = stablehlo.constant dense<4.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_84:.*]] = stablehlo.add %[[SELECT_11]], %[[CONSTANT_82]] : tensor<f32>
// CHECK:           %[[MULTIPLY_46:.*]] = stablehlo.multiply %[[ADD_84]], %[[ADD_84]] : tensor<f32>
// CHECK:           %[[DIVIDE_19:.*]] = stablehlo.divide %[[CONSTANT_81]], %[[MULTIPLY_46]] : tensor<f32>
// CHECK:           %[[SUBTRACT_12:.*]] = stablehlo.subtract %[[SUBTRACT_11]], %[[DIVIDE_19]] : tensor<f32>
// CHECK:           %[[DIVIDE_20:.*]] = stablehlo.divide %[[CONSTANT_81]], %[[ADD_84]] : tensor<f32>
// CHECK:           %[[ADD_85:.*]] = stablehlo.add %[[ADD_83]], %[[DIVIDE_20]] : tensor<f32>
// CHECK:           %[[CONSTANT_83:.*]] = stablehlo.constant dense<12.5073433> : tensor<f32>
// CHECK:           %[[CONSTANT_84:.*]] = stablehlo.constant dense<5.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_86:.*]] = stablehlo.add %[[SELECT_11]], %[[CONSTANT_84]] : tensor<f32>
// CHECK:           %[[MULTIPLY_47:.*]] = stablehlo.multiply %[[ADD_86]], %[[ADD_86]] : tensor<f32>
// CHECK:           %[[DIVIDE_21:.*]] = stablehlo.divide %[[CONSTANT_83]], %[[MULTIPLY_47]] : tensor<f32>
// CHECK:           %[[SUBTRACT_13:.*]] = stablehlo.subtract %[[SUBTRACT_12]], %[[DIVIDE_21]] : tensor<f32>
// CHECK:           %[[DIVIDE_22:.*]] = stablehlo.divide %[[CONSTANT_83]], %[[ADD_86]] : tensor<f32>
// CHECK:           %[[ADD_87:.*]] = stablehlo.add %[[ADD_85]], %[[DIVIDE_22]] : tensor<f32>
// CHECK:           %[[CONSTANT_85:.*]] = stablehlo.constant dense<-0.138571098> : tensor<f32>
// CHECK:           %[[CONSTANT_86:.*]] = stablehlo.constant dense<6.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_88:.*]] = stablehlo.add %[[SELECT_11]], %[[CONSTANT_86]] : tensor<f32>
// CHECK:           %[[MULTIPLY_48:.*]] = stablehlo.multiply %[[ADD_88]], %[[ADD_88]] : tensor<f32>
// CHECK:           %[[DIVIDE_23:.*]] = stablehlo.divide %[[CONSTANT_85]], %[[MULTIPLY_48]] : tensor<f32>
// CHECK:           %[[SUBTRACT_14:.*]] = stablehlo.subtract %[[SUBTRACT_13]], %[[DIVIDE_23]] : tensor<f32>
// CHECK:           %[[DIVIDE_24:.*]] = stablehlo.divide %[[CONSTANT_85]], %[[ADD_88]] : tensor<f32>
// CHECK:           %[[ADD_89:.*]] = stablehlo.add %[[ADD_87]], %[[DIVIDE_24]] : tensor<f32>
// CHECK:           %[[CONSTANT_87:.*]] = stablehlo.constant dense<9.98436917E-6> : tensor<f32>
// CHECK:           %[[CONSTANT_88:.*]] = stablehlo.constant dense<7.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_90:.*]] = stablehlo.add %[[SELECT_11]], %[[CONSTANT_88]] : tensor<f32>
// CHECK:           %[[MULTIPLY_49:.*]] = stablehlo.multiply %[[ADD_90]], %[[ADD_90]] : tensor<f32>
// CHECK:           %[[DIVIDE_25:.*]] = stablehlo.divide %[[CONSTANT_87]], %[[MULTIPLY_49]] : tensor<f32>
// CHECK:           %[[SUBTRACT_15:.*]] = stablehlo.subtract %[[SUBTRACT_14]], %[[DIVIDE_25]] : tensor<f32>
// CHECK:           %[[DIVIDE_26:.*]] = stablehlo.divide %[[CONSTANT_87]], %[[ADD_90]] : tensor<f32>
// CHECK:           %[[ADD_91:.*]] = stablehlo.add %[[ADD_89]], %[[DIVIDE_26]] : tensor<f32>
// CHECK:           %[[CONSTANT_89:.*]] = stablehlo.constant dense<1.50563267E-7> : tensor<f32>
// CHECK:           %[[CONSTANT_90:.*]] = stablehlo.constant dense<8.000000e+00> : tensor<f32>
// CHECK:           %[[ADD_92:.*]] = stablehlo.add %[[SELECT_11]], %[[CONSTANT_90]] : tensor<f32>
// CHECK:           %[[MULTIPLY_50:.*]] = stablehlo.multiply %[[ADD_92]], %[[ADD_92]] : tensor<f32>
// CHECK:           %[[DIVIDE_27:.*]] = stablehlo.divide %[[CONSTANT_89]], %[[MULTIPLY_50]] : tensor<f32>
// CHECK:           %[[SUBTRACT_16:.*]] = stablehlo.subtract %[[SUBTRACT_15]], %[[DIVIDE_27]] : tensor<f32>
// CHECK:           %[[DIVIDE_28:.*]] = stablehlo.divide %[[CONSTANT_89]], %[[ADD_92]] : tensor<f32>
// CHECK:           %[[ADD_93:.*]] = stablehlo.add %[[ADD_91]], %[[DIVIDE_28]] : tensor<f32>
// CHECK:           %[[CONSTANT_91:.*]] = stablehlo.constant dense<7.500000e+00> : tensor<f32>
// CHECK:           %[[ADD_94:.*]] = stablehlo.add %[[CONSTANT_91]], %[[SELECT_11]] : tensor<f32>
// CHECK:           %[[CONSTANT_92:.*]] = stablehlo.constant dense<2.01490307> : tensor<f32>
// CHECK:           %[[DIVIDE_29:.*]] = stablehlo.divide %[[SELECT_11]], %[[CONSTANT_91]] : tensor<f32>
// CHECK:           %[[LOG_PLUS_ONE_1:.*]] = stablehlo.log_plus_one %[[DIVIDE_29]] : tensor<f32>
// CHECK:           %[[ADD_95:.*]] = stablehlo.add %[[CONSTANT_92]], %[[LOG_PLUS_ONE_1]] : tensor<f32>
// CHECK:           %[[DIVIDE_30:.*]] = stablehlo.divide %[[SUBTRACT_16]], %[[ADD_93]] : tensor<f32>
// CHECK:           %[[CONSTANT_93:.*]] = stablehlo.constant dense<7.000000e+00> : tensor<f32>
// CHECK:           %[[DIVIDE_31:.*]] = stablehlo.divide %[[CONSTANT_93]], %[[ADD_94]] : tensor<f32>
// CHECK:           %[[ADD_96:.*]] = stablehlo.add %[[ADD_95]], %[[DIVIDE_30]] : tensor<f32>
// CHECK:           %[[SUBTRACT_17:.*]] = stablehlo.subtract %[[ADD_96]], %[[DIVIDE_31]] : tensor<f32>
// CHECK:           %[[CONSTANT_94:.*]] = stablehlo.constant dense<5.000000e-01> : tensor<f32>
// CHECK:           %[[ADD_97:.*]] = stablehlo.add %[[CONVERT_1]], %[[CONSTANT_94]] : tensor<f32>
// CHECK:           %[[FLOOR_4:.*]] = stablehlo.floor %[[ADD_97]] : tensor<f32>
// CHECK:           %[[ABS_4:.*]] = stablehlo.abs %[[FLOOR_4]] : tensor<f32>
// CHECK:           %[[ADD_98:.*]] = stablehlo.add %[[CONVERT_1]], %[[ABS_4]] : tensor<f32>
// CHECK:           %[[CONSTANT_95:.*]] = stablehlo.constant dense<3.14159274> : tensor<f32>
// CHECK:           %[[MULTIPLY_51:.*]] = stablehlo.multiply %[[CONSTANT_95]], %[[ADD_98]] : tensor<f32>
// CHECK:           %[[COSINE_0:.*]] = stablehlo.cosine %[[MULTIPLY_51]] : tensor<f32>
// CHECK:           %[[SINE_1:.*]] = stablehlo.sine %[[MULTIPLY_51]] : tensor<f32>
// CHECK:           %[[MULTIPLY_52:.*]] = stablehlo.multiply %[[CONSTANT_95]], %[[COSINE_0]] : tensor<f32>
// CHECK:           %[[DIVIDE_32:.*]] = stablehlo.divide %[[MULTIPLY_52]], %[[SINE_1]] : tensor<f32>
// CHECK:           %[[SUBTRACT_18:.*]] = stablehlo.subtract %[[SUBTRACT_17]], %[[DIVIDE_32]] : tensor<f32>
// CHECK:           %[[SELECT_12:.*]] = stablehlo.select %[[COMPARE_12]], %[[SUBTRACT_18]], %[[SUBTRACT_17]] : tensor<i1>, tensor<f32>
// CHECK:           %[[COMPARE_13:.*]] = stablehlo.compare  LE, %[[CONVERT_1]], %[[CONSTANT_73]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[FLOOR_5:.*]] = stablehlo.floor %[[CONVERT_1]] : tensor<f32>
// CHECK:           %[[COMPARE_14:.*]] = stablehlo.compare  EQ, %[[CONVERT_1]], %[[FLOOR_5]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[AND_3:.*]] = stablehlo.and %[[COMPARE_13]], %[[COMPARE_14]] : tensor<i1>
// CHECK:           %[[CONSTANT_96:.*]] = stablehlo.constant dense<0x7FC00000> : tensor<f32>
// CHECK:           %[[SELECT_13:.*]] = stablehlo.select %[[AND_3]], %[[CONSTANT_96]], %[[SELECT_12]] : tensor<i1>, tensor<f32>
// CHECK:           %[[SELECT_14:.*]] = stablehlo.select %[[COMPARE_11]], %[[SELECT_13]], %[[MULTIPLY_42]] : tensor<i1>, tensor<f32>
// CHECK:           %[[FLOOR_6:.*]] = stablehlo.floor %[[CONVERT_0]] : tensor<f32>
// CHECK:           %[[COMPARE_15:.*]] = stablehlo.compare  NE, %[[CONVERT_0]], %[[FLOOR_6]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[COMPARE_16:.*]] = stablehlo.compare  LT, %[[CONVERT_0]], %[[CONSTANT_70]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[OR_0:.*]] = stablehlo.or %[[COMPARE_15]], %[[COMPARE_16]] : tensor<i1>
// CHECK:           %[[CONSTANT_97:.*]] = stablehlo.constant dense<0x7FC00000> : tensor<f32>
// CHECK:           %[[SELECT_15:.*]] = stablehlo.select %[[OR_0]], %[[CONSTANT_97]], %[[SELECT_14]] : tensor<i1>, tensor<f32>
// CHECK:           %[[CONVERT_2:.*]] = stablehlo.convert %[[SELECT_15]] : (tensor<f32>) -> tensor<f16>
// CHECK:           return %[[CONVERT_2]] : tensor<f16>
// CHECK:         }
func.func @polygamma_f16(%lhs : tensor<f16>, %rhs : tensor<f16>) -> tensor<f16> {
  %1 = chlo.polygamma %lhs, %rhs : tensor<f16>, tensor<f16> -> tensor<f16>
  func.return %1 : tensor<f16>
}

// -----

// CHECK-LABEL:   func.func @sinh_f32(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<f32>) -> tensor<f32> {
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<5.000000e-01> : tensor<f32>
// CHECK:           %[[LOG_0:.*]] = stablehlo.log %[[CONSTANT_0]] : tensor<f32>
// CHECK:           %[[ADD_0:.*]] = stablehlo.add %[[ARG0]], %[[LOG_0]] : tensor<f32>
// CHECK:           %[[EXPONENTIAL_0:.*]] = stablehlo.exponential %[[ADD_0]] : tensor<f32>
// CHECK:           %[[SUBTRACT_0:.*]] = stablehlo.subtract %[[LOG_0]], %[[ARG0]] : tensor<f32>
// CHECK:           %[[EXPONENTIAL_1:.*]] = stablehlo.exponential %[[SUBTRACT_0]] : tensor<f32>
// CHECK:           %[[SUBTRACT_1:.*]] = stablehlo.subtract %[[EXPONENTIAL_0]], %[[EXPONENTIAL_1]] : tensor<f32>
// CHECK:           %[[EXPONENTIAL_MINUS_ONE_0:.*]] = stablehlo.exponential_minus_one %[[ARG0]] : tensor<f32>
// CHECK:           %[[CONSTANT_1:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[CONSTANT_2:.*]] = stablehlo.constant dense<5.000000e-01> : tensor<f32>
// CHECK:           %[[ADD_1:.*]] = stablehlo.add %[[EXPONENTIAL_MINUS_ONE_0]], %[[CONSTANT_1]] : tensor<f32>
// CHECK:           %[[DIVIDE_0:.*]] = stablehlo.divide %[[EXPONENTIAL_MINUS_ONE_0]], %[[ADD_1]] : tensor<f32>
// CHECK:           %[[ADD_2:.*]] = stablehlo.add %[[EXPONENTIAL_MINUS_ONE_0]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[MULTIPLY_0:.*]] = stablehlo.multiply %[[CONSTANT_2]], %[[ADD_2]] : tensor<f32>
// CHECK:           %[[ABS_0:.*]] = stablehlo.abs %[[ARG0]] : tensor<f32>
// CHECK:           %[[COMPARE_0:.*]] = stablehlo.compare  LT, %[[ABS_0]], %[[CONSTANT_1]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[SELECT_0:.*]] = stablehlo.select %[[COMPARE_0]], %[[MULTIPLY_0]], %[[SUBTRACT_1]] : tensor<i1>, tensor<f32>
// CHECK:           return %[[SELECT_0]] : tensor<f32>
// CHECK:         }
func.func @sinh_f32(%x : tensor<f32>) -> tensor<f32> {
  %1 = chlo.sinh %x : tensor<f32> -> tensor<f32>
  func.return %1 : tensor<f32>
}

// -----

// CHECK-LABEL:   func.func @sinh_f16(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<f16>) -> tensor<f16> {
// CHECK:           %[[CONVERT_0:.*]] = stablehlo.convert %[[ARG0]] : (tensor<f16>) -> tensor<f32>
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<5.000000e-01> : tensor<f32>
// CHECK:           %[[LOG_0:.*]] = stablehlo.log %[[CONSTANT_0]] : tensor<f32>
// CHECK:           %[[ADD_0:.*]] = stablehlo.add %[[CONVERT_0]], %[[LOG_0]] : tensor<f32>
// CHECK:           %[[EXPONENTIAL_0:.*]] = stablehlo.exponential %[[ADD_0]] : tensor<f32>
// CHECK:           %[[SUBTRACT_0:.*]] = stablehlo.subtract %[[LOG_0]], %[[CONVERT_0]] : tensor<f32>
// CHECK:           %[[EXPONENTIAL_1:.*]] = stablehlo.exponential %[[SUBTRACT_0]] : tensor<f32>
// CHECK:           %[[SUBTRACT_1:.*]] = stablehlo.subtract %[[EXPONENTIAL_0]], %[[EXPONENTIAL_1]] : tensor<f32>
// CHECK:           %[[EXPONENTIAL_MINUS_ONE_0:.*]] = stablehlo.exponential_minus_one %[[CONVERT_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_1:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[CONSTANT_2:.*]] = stablehlo.constant dense<5.000000e-01> : tensor<f32>
// CHECK:           %[[ADD_1:.*]] = stablehlo.add %[[EXPONENTIAL_MINUS_ONE_0]], %[[CONSTANT_1]] : tensor<f32>
// CHECK:           %[[DIVIDE_0:.*]] = stablehlo.divide %[[EXPONENTIAL_MINUS_ONE_0]], %[[ADD_1]] : tensor<f32>
// CHECK:           %[[ADD_2:.*]] = stablehlo.add %[[EXPONENTIAL_MINUS_ONE_0]], %[[DIVIDE_0]] : tensor<f32>
// CHECK:           %[[MULTIPLY_0:.*]] = stablehlo.multiply %[[CONSTANT_2]], %[[ADD_2]] : tensor<f32>
// CHECK:           %[[ABS_0:.*]] = stablehlo.abs %[[CONVERT_0]] : tensor<f32>
// CHECK:           %[[COMPARE_0:.*]] = stablehlo.compare  LT, %[[ABS_0]], %[[CONSTANT_1]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[SELECT_0:.*]] = stablehlo.select %[[COMPARE_0]], %[[MULTIPLY_0]], %[[SUBTRACT_1]] : tensor<i1>, tensor<f32>
// CHECK:           %[[CONVERT_1:.*]] = stablehlo.convert %[[SELECT_0]] : (tensor<f32>) -> tensor<f16>
// CHECK:           return %[[CONVERT_1]] : tensor<f16>
// CHECK:         }
func.func @sinh_f16(%x : tensor<f16>) -> tensor<f16> {
  %1 = chlo.sinh %x : tensor<f16> -> tensor<f16>
  func.return %1 : tensor<f16>
}

// -----

// CHECK-LABEL:   func.func @sinh_complex(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<2xcomplex<f32>>) -> tensor<2xcomplex<f32>> {
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<(5.000000e-01,0.000000e+00)> : tensor<2xcomplex<f32>>
// CHECK:           %[[LOG_0:.*]] = stablehlo.log %[[CONSTANT_0]] : tensor<2xcomplex<f32>>
// CHECK:           %[[ADD_0:.*]] = stablehlo.add %[[ARG0]], %[[LOG_0]] : tensor<2xcomplex<f32>>
// CHECK:           %[[EXPONENTIAL_0:.*]] = stablehlo.exponential %[[ADD_0]] : tensor<2xcomplex<f32>>
// CHECK:           %[[SUBTRACT_0:.*]] = stablehlo.subtract %[[LOG_0]], %[[ARG0]] : tensor<2xcomplex<f32>>
// CHECK:           %[[EXPONENTIAL_1:.*]] = stablehlo.exponential %[[SUBTRACT_0]] : tensor<2xcomplex<f32>>
// CHECK:           %[[SUBTRACT_1:.*]] = stablehlo.subtract %[[EXPONENTIAL_0]], %[[EXPONENTIAL_1]] : tensor<2xcomplex<f32>>
// CHECK:           return %[[SUBTRACT_1]] : tensor<2xcomplex<f32>>
// CHECK:         }
func.func @sinh_complex(%x : tensor<2xcomplex<f32>>) -> tensor<2xcomplex<f32>> {
  %1 = chlo.sinh %x : tensor<2xcomplex<f32>> -> tensor<2xcomplex<f32>>
  func.return %1 : tensor<2xcomplex<f32>>
}

// -----

// CHECK-LABEL:   func.func @cosh_f32(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<f32>) -> tensor<f32> {
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<5.000000e-01> : tensor<f32>
// CHECK:           %[[LOG_0:.*]] = stablehlo.log %[[CONSTANT_0]] : tensor<f32>
// CHECK:           %[[ADD_0:.*]] = stablehlo.add %[[ARG0]], %[[LOG_0]] : tensor<f32>
// CHECK:           %[[EXPONENTIAL_0:.*]] = stablehlo.exponential %[[ADD_0]] : tensor<f32>
// CHECK:           %[[SUBTRACT_0:.*]] = stablehlo.subtract %[[LOG_0]], %[[ARG0]] : tensor<f32>
// CHECK:           %[[EXPONENTIAL_1:.*]] = stablehlo.exponential %[[SUBTRACT_0]] : tensor<f32>
// CHECK:           %[[ADD_1:.*]] = stablehlo.add %[[EXPONENTIAL_0]], %[[EXPONENTIAL_1]] : tensor<f32>
// CHECK:           return %[[ADD_1]] : tensor<f32>
// CHECK:         }
func.func @cosh_f32(%x : tensor<f32>) -> tensor<f32> {
  %1 = chlo.cosh %x : tensor<f32> -> tensor<f32>
  func.return %1 : tensor<f32>
}

// -----

// CHECK-LABEL:   func.func @cosh_f16(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<f16>) -> tensor<f16> {
// CHECK:           %[[CONVERT_0:.*]] = stablehlo.convert %[[ARG0]] : (tensor<f16>) -> tensor<f32>
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<5.000000e-01> : tensor<f32>
// CHECK:           %[[LOG_0:.*]] = stablehlo.log %[[CONSTANT_0]] : tensor<f32>
// CHECK:           %[[ADD_0:.*]] = stablehlo.add %[[CONVERT_0]], %[[LOG_0]] : tensor<f32>
// CHECK:           %[[EXPONENTIAL_0:.*]] = stablehlo.exponential %[[ADD_0]] : tensor<f32>
// CHECK:           %[[SUBTRACT_0:.*]] = stablehlo.subtract %[[LOG_0]], %[[CONVERT_0]] : tensor<f32>
// CHECK:           %[[EXPONENTIAL_1:.*]] = stablehlo.exponential %[[SUBTRACT_0]] : tensor<f32>
// CHECK:           %[[ADD_1:.*]] = stablehlo.add %[[EXPONENTIAL_0]], %[[EXPONENTIAL_1]] : tensor<f32>
// CHECK:           %[[CONVERT_1:.*]] = stablehlo.convert %[[ADD_1]] : (tensor<f32>) -> tensor<f16>
// CHECK:           return %[[CONVERT_1]] : tensor<f16>
// CHECK:         }
func.func @cosh_f16(%x : tensor<f16>) -> tensor<f16> {
  %1 = chlo.cosh %x : tensor<f16> -> tensor<f16>
  func.return %1 : tensor<f16>
}

// -----

// CHECK-LABEL:   func.func @cosh_complex_f32(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<complex<f32>>) -> tensor<complex<f32>> {
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<(5.000000e-01,0.000000e+00)> : tensor<complex<f32>>
// CHECK:           %[[LOG_0:.*]] = stablehlo.log %[[CONSTANT_0]] : tensor<complex<f32>>
// CHECK:           %[[ADD_0:.*]] = stablehlo.add %[[ARG0]], %[[LOG_0]] : tensor<complex<f32>>
// CHECK:           %[[EXPONENTIAL_0:.*]] = stablehlo.exponential %[[ADD_0]] : tensor<complex<f32>>
// CHECK:           %[[SUBTRACT_0:.*]] = stablehlo.subtract %[[LOG_0]], %[[ARG0]] : tensor<complex<f32>>
// CHECK:           %[[EXPONENTIAL_1:.*]] = stablehlo.exponential %[[SUBTRACT_0]] : tensor<complex<f32>>
// CHECK:           %[[ADD_1:.*]] = stablehlo.add %[[EXPONENTIAL_0]], %[[EXPONENTIAL_1]] : tensor<complex<f32>>
// CHECK:           return %[[ADD_1]] : tensor<complex<f32>>
// CHECK:         }
func.func @cosh_complex_f32(%x : tensor<complex<f32>>) -> tensor<complex<f32>> {
  %1 = chlo.cosh %x : tensor<complex<f32>> -> tensor<complex<f32>>
  func.return %1 : tensor<complex<f32>>
}

// -----

// CHECK-LABEL:   func.func @atanh_f32(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<f32>) -> tensor<f32> {
// CHECK:           %[[ABS_0:.*]] = stablehlo.abs %[[ARG0]] : tensor<f32>
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[COMPARE_0:.*]] = stablehlo.compare  GT, %[[ABS_0]], %[[CONSTANT_0]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[CONSTANT_1:.*]] = stablehlo.constant dense<0x7FC00000> : tensor<f32>
// CHECK:           %[[LOG_PLUS_ONE_0:.*]] = stablehlo.log_plus_one %[[ARG0]] : tensor<f32>
// CHECK:           %[[NEGATE_0:.*]] = stablehlo.negate %[[ARG0]] : tensor<f32>
// CHECK:           %[[LOG_PLUS_ONE_1:.*]] = stablehlo.log_plus_one %[[NEGATE_0]] : tensor<f32>
// CHECK:           %[[SUBTRACT_0:.*]] = stablehlo.subtract %[[LOG_PLUS_ONE_0]], %[[LOG_PLUS_ONE_1]] : tensor<f32>
// CHECK:           %[[CONSTANT_2:.*]] = stablehlo.constant dense<5.000000e-01> : tensor<f32>
// CHECK:           %[[MULTIPLY_0:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[CONSTANT_2]] : tensor<f32>
// CHECK:           %[[SELECT_0:.*]] = stablehlo.select %[[COMPARE_0]], %[[CONSTANT_1]], %[[MULTIPLY_0]] : tensor<i1>, tensor<f32>
// CHECK:           return %[[SELECT_0]] : tensor<f32>
// CHECK:         }
func.func @atanh_f32(%arg : tensor<f32>) -> tensor<f32> {
  %result = "chlo.atanh"(%arg) : (tensor<f32>) -> tensor<f32>
  func.return %result : tensor<f32>
}

// -----

// CHECK-LABEL:   func.func @atanh_complex_f32(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<complex<f32>>) -> tensor<complex<f32>> {
// CHECK:           %[[REAL_0:.*]] = stablehlo.real %[[ARG0]] : (tensor<complex<f32>>) -> tensor<f32>
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<f32>
// CHECK:           %[[COMPARE_0:.*]] = stablehlo.compare  GE, %[[REAL_0]], %[[CONSTANT_0]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[CONSTANT_1:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[CONSTANT_2:.*]] = stablehlo.constant dense<-1.000000e+00> : tensor<f32>
// CHECK:           %[[SELECT_0:.*]] = stablehlo.select %[[COMPARE_0]], %[[CONSTANT_1]], %[[CONSTANT_2]] : tensor<i1>, tensor<f32>
// CHECK:           %[[CONSTANT_3:.*]] = stablehlo.constant dense<4.000000e+00> : tensor<f32>
// CHECK:           %[[ABS_0:.*]] = stablehlo.abs %[[REAL_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_4:.*]] = stablehlo.constant dense<3.40282347E+38> : tensor<f32>
// CHECK:           %[[CONSTANT_5:.*]] = stablehlo.constant dense<0x7F800000> : tensor<f32>
// CHECK:           %[[COMPARE_1:.*]] = stablehlo.compare  GT, %[[CONSTANT_4]], %[[CONSTANT_5]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[CONSTANT_6:.*]] = stablehlo.constant dense<9.00719925E+15> : tensor<f32>
// CHECK:           %[[CONSTANT_7:.*]] = stablehlo.constant dense<9.99999968E+37> : tensor<f32>
// CHECK:           %[[COMPARE_2:.*]] = stablehlo.compare  GT, %[[CONSTANT_4]], %[[CONSTANT_7]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[CONSTANT_8:.*]] = stablehlo.constant dense<0x4B800001> : tensor<f32>
// CHECK:           %[[CONSTANT_9:.*]] = stablehlo.constant dense<2.050000e+03> : tensor<f32>
// CHECK:           %[[SELECT_1:.*]] = stablehlo.select %[[COMPARE_2]], %[[CONSTANT_8]], %[[CONSTANT_9]] : tensor<i1>, tensor<f32>
// CHECK:           %[[SELECT_2:.*]] = stablehlo.select %[[COMPARE_1]], %[[CONSTANT_6]], %[[SELECT_1]] : tensor<i1>, tensor<f32>
// CHECK:           %[[MULTIPLY_0:.*]] = stablehlo.multiply %[[SELECT_2]], %[[SELECT_2]] : tensor<f32>
// CHECK:           %[[COMPARE_3:.*]] = stablehlo.compare  LT, %[[ABS_0]], %[[MULTIPLY_0]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[IMAG_0:.*]] = stablehlo.imag %[[ARG0]] : (tensor<complex<f32>>) -> tensor<f32>
// CHECK:           %[[ABS_1:.*]] = stablehlo.abs %[[IMAG_0]] : tensor<f32>
// CHECK:           %[[COMPARE_4:.*]] = stablehlo.compare  LT, %[[ABS_1]], %[[MULTIPLY_0]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[AND_0:.*]] = stablehlo.and %[[COMPARE_3]], %[[COMPARE_4]] : tensor<i1>
// CHECK:           %[[SUBTRACT_0:.*]] = stablehlo.subtract %[[CONSTANT_1]], %[[ABS_0]] : tensor<f32>
// CHECK:           %[[MULTIPLY_1:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[SUBTRACT_0]] : tensor<f32>
// CHECK:           %[[MULTIPLY_2:.*]] = stablehlo.multiply %[[IMAG_0]], %[[IMAG_0]] : tensor<f32>
// CHECK:           %[[ADD_0:.*]] = stablehlo.add %[[MULTIPLY_1]], %[[MULTIPLY_2]] : tensor<f32>
// CHECK:           %[[DIVIDE_0:.*]] = stablehlo.divide %[[ABS_0]], %[[ADD_0]] : tensor<f32>
// CHECK:           %[[MULTIPLY_3:.*]] = stablehlo.multiply %[[ABS_1]], %[[SELECT_2]] : tensor<f32>
// CHECK:           %[[COMPARE_5:.*]] = stablehlo.compare  LT, %[[MULTIPLY_3]], %[[ABS_0]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[DIVIDE_1:.*]] = stablehlo.divide %[[CONSTANT_1]], %[[ABS_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_10:.*]] = stablehlo.constant dense<0x7F800000> : tensor<f32>
// CHECK:           %[[COMPARE_6:.*]] = stablehlo.compare  EQ, %[[REAL_0]], %[[CONSTANT_10]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[CONSTANT_11:.*]] = stablehlo.constant dense<0xFF800000> : tensor<f32>
// CHECK:           %[[COMPARE_7:.*]] = stablehlo.compare  EQ, %[[REAL_0]], %[[CONSTANT_11]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[OR_0:.*]] = stablehlo.or %[[COMPARE_6]], %[[COMPARE_7]] : tensor<i1>
// CHECK:           %[[COMPARE_8:.*]] = stablehlo.compare  EQ, %[[IMAG_0]], %[[CONSTANT_10]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[COMPARE_9:.*]] = stablehlo.compare  EQ, %[[IMAG_0]], %[[CONSTANT_11]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[OR_1:.*]] = stablehlo.or %[[COMPARE_8]], %[[COMPARE_9]] : tensor<i1>
// CHECK:           %[[OR_2:.*]] = stablehlo.or %[[OR_0]], %[[OR_1]] : tensor<i1>
// CHECK:           %[[DIVIDE_2:.*]] = stablehlo.divide %[[ABS_0]], %[[IMAG_0]] : tensor<f32>
// CHECK:           %[[DIVIDE_3:.*]] = stablehlo.divide %[[IMAG_0]], %[[ABS_0]] : tensor<f32>
// CHECK:           %[[ADD_1:.*]] = stablehlo.add %[[DIVIDE_2]], %[[DIVIDE_3]] : tensor<f32>
// CHECK:           %[[DIVIDE_4:.*]] = stablehlo.divide %[[CONSTANT_1]], %[[ADD_1]] : tensor<f32>
// CHECK:           %[[DIVIDE_5:.*]] = stablehlo.divide %[[DIVIDE_4]], %[[IMAG_0]] : tensor<f32>
// CHECK:           %[[SELECT_3:.*]] = stablehlo.select %[[OR_2]], %[[CONSTANT_0]], %[[DIVIDE_5]] : tensor<i1>, tensor<f32>
// CHECK:           %[[SELECT_4:.*]] = stablehlo.select %[[COMPARE_5]], %[[DIVIDE_1]], %[[SELECT_3]] : tensor<i1>, tensor<f32>
// CHECK:           %[[SELECT_5:.*]] = stablehlo.select %[[AND_0]], %[[DIVIDE_0]], %[[SELECT_4]] : tensor<i1>, tensor<f32>
// CHECK:           %[[MULTIPLY_4:.*]] = stablehlo.multiply %[[CONSTANT_3]], %[[SELECT_5]] : tensor<f32>
// CHECK:           %[[LOG_PLUS_ONE_0:.*]] = stablehlo.log_plus_one %[[MULTIPLY_4]] : tensor<f32>
// CHECK:           %[[MULTIPLY_5:.*]] = stablehlo.multiply %[[SELECT_0]], %[[LOG_PLUS_ONE_0]] : tensor<f32>
// CHECK:           %[[CONSTANT_12:.*]] = stablehlo.constant dense<2.500000e-01> : tensor<f32>
// CHECK:           %[[MULTIPLY_6:.*]] = stablehlo.multiply %[[MULTIPLY_5]], %[[CONSTANT_12]] : tensor<f32>
// CHECK:           %[[ADD_2:.*]] = stablehlo.add %[[IMAG_0]], %[[IMAG_0]] : tensor<f32>
// CHECK:           %[[ADD_3:.*]] = stablehlo.add %[[CONSTANT_1]], %[[ABS_0]] : tensor<f32>
// CHECK:           %[[MULTIPLY_7:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_3]] : tensor<f32>
// CHECK:           %[[SUBTRACT_1:.*]] = stablehlo.subtract %[[MULTIPLY_7]], %[[MULTIPLY_2]] : tensor<f32>
// CHECK:           %[[VAL_0:.*]] = stablehlo.atan2 %[[ADD_2]], %[[SUBTRACT_1]] : tensor<f32>
// CHECK:           %[[CONSTANT_13:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<f32>
// CHECK:           %[[COMPARE_10:.*]] = stablehlo.compare  GE, %[[IMAG_0]], %[[CONSTANT_13]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[SELECT_6:.*]] = stablehlo.select %[[COMPARE_10]], %[[CONSTANT_1]], %[[CONSTANT_2]] : tensor<i1>, tensor<f32>
// CHECK:           %[[CONSTANT_14:.*]] = stablehlo.constant dense<3.14159274> : tensor<f32>
// CHECK:           %[[MULTIPLY_8:.*]] = stablehlo.multiply %[[SELECT_6]], %[[CONSTANT_14]] : tensor<f32>
// CHECK:           %[[SELECT_7:.*]] = stablehlo.select %[[AND_0]], %[[VAL_0]], %[[MULTIPLY_8]] : tensor<i1>, tensor<f32>
// CHECK:           %[[CONSTANT_15:.*]] = stablehlo.constant dense<5.000000e-01> : tensor<f32>
// CHECK:           %[[MULTIPLY_9:.*]] = stablehlo.multiply %[[SELECT_7]], %[[CONSTANT_15]] : tensor<f32>
// CHECK:           %[[COMPLEX_0:.*]] = stablehlo.complex %[[MULTIPLY_6]], %[[MULTIPLY_9]] : tensor<complex<f32>>
// CHECK:           return %[[COMPLEX_0]] : tensor<complex<f32>>
// CHECK:         }
func.func @atanh_complex_f32(%arg : tensor<complex<f32>>) -> tensor<complex<f32>> {
  %result = "chlo.atanh"(%arg) : (tensor<complex<f32>>) -> tensor<complex<f32>>
  func.return %result : tensor<complex<f32>>
}

// -----

// CHECK-LABEL:   func.func @next_after_f32(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<2xf32>,
// CHECK-SAME:      %[[ARG1:.*]]: tensor<2xf32>) -> tensor<2xf32> {
// CHECK:           %[[BITCAST_CONVERT_0:.*]] = stablehlo.bitcast_convert %[[ARG0]] : (tensor<2xf32>) -> tensor<2xi32>
// CHECK:           %[[BITCAST_CONVERT_1:.*]] = stablehlo.bitcast_convert %[[ARG1]] : (tensor<2xf32>) -> tensor<2xi32>
// CHECK:           %[[COMPARE_0:.*]] = stablehlo.compare  NE, %[[ARG0]], %[[ARG0]] : (tensor<2xf32>, tensor<2xf32>) -> tensor<2xi1>
// CHECK:           %[[COMPARE_1:.*]] = stablehlo.compare  NE, %[[ARG1]], %[[ARG1]] : (tensor<2xf32>, tensor<2xf32>) -> tensor<2xi1>
// CHECK:           %[[OR_0:.*]] = stablehlo.or %[[COMPARE_0]], %[[COMPARE_1]] : tensor<2xi1>
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<0x7FC00000> : tensor<2xf32>
// CHECK:           %[[BITCAST_CONVERT_2:.*]] = stablehlo.bitcast_convert %[[CONSTANT_0]] : (tensor<2xf32>) -> tensor<2xi32>
// CHECK:           %[[CONSTANT_1:.*]] = stablehlo.constant dense<-2147483648> : tensor<2xi32>
// CHECK:           %[[CONSTANT_2:.*]] = stablehlo.constant dense<2147483647> : tensor<2xi32>
// CHECK:           %[[AND_0:.*]] = stablehlo.and %[[BITCAST_CONVERT_0]], %[[CONSTANT_2]] : tensor<2xi32>
// CHECK:           %[[AND_1:.*]] = stablehlo.and %[[BITCAST_CONVERT_1]], %[[CONSTANT_2]] : tensor<2xi32>
// CHECK:           %[[COMPARE_2:.*]] = stablehlo.compare  EQ, %[[ARG0]], %[[ARG1]] : (tensor<2xf32>, tensor<2xf32>) -> tensor<2xi1>
// CHECK:           %[[CONSTANT_3:.*]] = stablehlo.constant dense<0> : tensor<2xi32>
// CHECK:           %[[COMPARE_3:.*]] = stablehlo.compare  EQ, %[[AND_0]], %[[CONSTANT_3]] : (tensor<2xi32>, tensor<2xi32>) -> tensor<2xi1>
// CHECK:           %[[COMPARE_4:.*]] = stablehlo.compare  EQ, %[[AND_1]], %[[CONSTANT_3]] : (tensor<2xi32>, tensor<2xi32>) -> tensor<2xi1>
// CHECK:           %[[AND_2:.*]] = stablehlo.and %[[BITCAST_CONVERT_0]], %[[CONSTANT_1]] : tensor<2xi32>
// CHECK:           %[[AND_3:.*]] = stablehlo.and %[[BITCAST_CONVERT_1]], %[[CONSTANT_1]] : tensor<2xi32>
// CHECK:           %[[CONSTANT_4:.*]] = stablehlo.constant dense<1> : tensor<2xi32>
// CHECK:           %[[OR_1:.*]] = stablehlo.or %[[AND_3]], %[[CONSTANT_4]] : tensor<2xi32>
// CHECK:           %[[COMPARE_5:.*]] = stablehlo.compare  NE, %[[AND_2]], %[[AND_3]] : (tensor<2xi32>, tensor<2xi32>) -> tensor<2xi1>
// CHECK:           %[[COMPARE_6:.*]] = stablehlo.compare  GT, %[[AND_0]], %[[AND_1]] : (tensor<2xi32>, tensor<2xi32>) -> tensor<2xi1>
// CHECK:           %[[OR_2:.*]] = stablehlo.or %[[COMPARE_6]], %[[COMPARE_5]] : tensor<2xi1>
// CHECK:           %[[CONSTANT_5:.*]] = stablehlo.constant dense<-1> : tensor<2xi32>
// CHECK:           %[[SELECT_0:.*]] = stablehlo.select %[[OR_2]], %[[CONSTANT_5]], %[[CONSTANT_4]] : tensor<2xi1>, tensor<2xi32>
// CHECK:           %[[ADD_0:.*]] = stablehlo.add %[[BITCAST_CONVERT_0]], %[[SELECT_0]] : tensor<2xi32>
// CHECK:           %[[SELECT_1:.*]] = stablehlo.select %[[COMPARE_4]], %[[BITCAST_CONVERT_1]], %[[OR_1]] : tensor<2xi1>, tensor<2xi32>
// CHECK:           %[[SELECT_2:.*]] = stablehlo.select %[[COMPARE_3]], %[[SELECT_1]], %[[ADD_0]] : tensor<2xi1>, tensor<2xi32>
// CHECK:           %[[SELECT_3:.*]] = stablehlo.select %[[COMPARE_2]], %[[BITCAST_CONVERT_1]], %[[SELECT_2]] : tensor<2xi1>, tensor<2xi32>
// CHECK:           %[[SELECT_4:.*]] = stablehlo.select %[[OR_0]], %[[BITCAST_CONVERT_2]], %[[SELECT_3]] : tensor<2xi1>, tensor<2xi32>
// CHECK:           %[[BITCAST_CONVERT_3:.*]] = stablehlo.bitcast_convert %[[SELECT_4]] : (tensor<2xi32>) -> tensor<2xf32>
// CHECK:           return %[[BITCAST_CONVERT_3]] : tensor<2xf32>
// CHECK:         }
func.func @next_after_f32(%x: tensor<2xf32>, %y: tensor<2xf32>) -> tensor<2xf32> {
  %1 = chlo.broadcast_next_after %x, %y : (tensor<2xf32>, tensor<2xf32>) -> tensor<2xf32>
  func.return %1 : tensor<2xf32>
}

// -----

// CHECK-LABEL:   func.func @tan_f32(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<f32>) -> tensor<f32> {
// CHECK:           %[[TAN_0:.*]] = stablehlo.tan %[[ARG0]] : tensor<f32>
// CHECK:           return %[[TAN_0]] : tensor<f32>
// CHECK:         }
func.func @tan_f32(%arg : tensor<f32>) -> tensor<f32> {
  %1 = chlo.tan %arg : tensor<f32> -> tensor<f32>
  func.return %1 : tensor<f32>
}

// -----

// CHECK-LABEL:   func.func @tan_complexf32(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<1xf32>,
// CHECK-SAME:      %[[ARG1:.*]]: tensor<1xf32>) -> (tensor<1xf32>, tensor<1xf32>) {
// CHECK:           %[[COMPLEX_0:.*]] = stablehlo.complex %[[ARG0]], %[[ARG1]] : tensor<1xcomplex<f32>>
// CHECK:           %[[TAN_0:.*]] = stablehlo.tan %[[COMPLEX_0]] : tensor<1xcomplex<f32>>
// CHECK:           %[[REAL_0:.*]] = stablehlo.real %[[TAN_0]] : (tensor<1xcomplex<f32>>) -> tensor<1xf32>
// CHECK:           %[[IMAG_0:.*]] = stablehlo.imag %[[TAN_0]] : (tensor<1xcomplex<f32>>) -> tensor<1xf32>
// CHECK:           return %[[REAL_0]], %[[IMAG_0]] : tensor<1xf32>, tensor<1xf32>
// CHECK:         }
func.func @tan_complexf32(%arg0 : tensor<1xf32>, %arg1 : tensor<1xf32>) -> (tensor<1xf32>, tensor<1xf32>) {
  %0 = stablehlo.complex %arg0, %arg1 : tensor<1xcomplex<f32>>
  %1 = chlo.tan %0 : tensor<1xcomplex<f32>> -> tensor<1xcomplex<f32>>
  %2 = stablehlo.real %1 : (tensor<1xcomplex<f32>>) -> tensor<1xf32>
  %3 = stablehlo.imag %1 : (tensor<1xcomplex<f32>>) -> tensor<1xf32>
  func.return %2, %3 : tensor<1xf32>, tensor<1xf32>
}

// -----

// CHECK-LABEL:   func.func @top_k(
// CHECK-SAME:                     %[[ARG0:.*]]: tensor<16x16xf32>) -> (tensor<16x8xf32>, tensor<16x8xi32>) {
// CHECK:           %[[IOTA_0:.*]] = stablehlo.iota dim = 1 : tensor<16x16xi32>
// CHECK:           %[[VAL_0:.*]]:2 = "stablehlo.sort"(%[[ARG0]], %[[IOTA_0]]) <{dimension = 1 : i64, is_stable = true}> ({
// CHECK:           ^bb0(%[[VAL_1:.*]]: tensor<f32>, %[[VAL_2:.*]]: tensor<f32>, %[[VAL_3:.*]]: tensor<i32>, %[[VAL_4:.*]]: tensor<i32>):
// CHECK:             %[[COMPARE_0:.*]] = stablehlo.compare  GT, %[[VAL_1]], %[[VAL_2]],  TOTALORDER : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:             stablehlo.return %[[COMPARE_0]] : tensor<i1>
// CHECK:           }) : (tensor<16x16xf32>, tensor<16x16xi32>) -> (tensor<16x16xf32>, tensor<16x16xi32>)
// CHECK:           %[[SLICE_0:.*]] = stablehlo.slice %[[VAL_5:.*]]#0 [0:16, 0:8] : (tensor<16x16xf32>) -> tensor<16x8xf32>
// CHECK:           %[[SLICE_1:.*]] = stablehlo.slice %[[VAL_5]]#1 [0:16, 0:8] : (tensor<16x16xi32>) -> tensor<16x8xi32>
// CHECK:           return %[[SLICE_0]], %[[SLICE_1]] : tensor<16x8xf32>, tensor<16x8xi32>
// CHECK:         }
func.func @top_k(%arg : tensor<16x16xf32>) -> (tensor<16x8xf32>, tensor<16x8xi32>) {
  %1:2 = chlo.top_k(%arg, k=8) : tensor<16x16xf32> -> (tensor<16x8xf32>, tensor<16x8xi32>)
  func.return %1#0, %1#1 : tensor<16x8xf32>, tensor<16x8xi32>
}

// -----

// CHECK-LABEL:   func.func @dyn_top_k(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<?x5x?xi1>) -> (tensor<?x5x2xi1>, tensor<?x5x2xi32>) {
// CHECK:           %[[GET_DIMENSION_SIZE_0:.*]] = stablehlo.get_dimension_size %[[ARG0]], dim = 0 : (tensor<?x5x?xi1>) -> tensor<i32>
// CHECK:           %[[RESHAPE_0:.*]] = stablehlo.reshape %[[GET_DIMENSION_SIZE_0]] : (tensor<i32>) -> tensor<1xi32>
// CHECK:           %[[GET_DIMENSION_SIZE_1:.*]] = stablehlo.get_dimension_size %[[ARG0]], dim = 1 : (tensor<?x5x?xi1>) -> tensor<i32>
// CHECK:           %[[RESHAPE_1:.*]] = stablehlo.reshape %[[GET_DIMENSION_SIZE_1]] : (tensor<i32>) -> tensor<1xi32>
// CHECK:           %[[GET_DIMENSION_SIZE_2:.*]] = stablehlo.get_dimension_size %[[ARG0]], dim = 2 : (tensor<?x5x?xi1>) -> tensor<i32>
// CHECK:           %[[RESHAPE_2:.*]] = stablehlo.reshape %[[GET_DIMENSION_SIZE_2]] : (tensor<i32>) -> tensor<1xi32>
// CHECK:           %[[CONCATENATE_0:.*]] = stablehlo.concatenate %[[RESHAPE_0]], %[[RESHAPE_1]], %[[RESHAPE_2]], dim = 0 : (tensor<1xi32>, tensor<1xi32>, tensor<1xi32>) -> tensor<3xi32>
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<2> : tensor<i32>
// CHECK:           %[[RESHAPE_3:.*]] = stablehlo.reshape %[[CONSTANT_0]] : (tensor<i32>) -> tensor<1xi32>
// CHECK:           %[[CONCATENATE_1:.*]] = stablehlo.concatenate %[[RESHAPE_0]], %[[RESHAPE_1]], %[[RESHAPE_3]], dim = 0 : (tensor<1xi32>, tensor<1xi32>, tensor<1xi32>) -> tensor<3xi32>
// CHECK:           %[[DYNAMIC_IOTA_0:.*]] = stablehlo.dynamic_iota %[[CONCATENATE_0]], dim = 2 : (tensor<3xi32>) -> tensor<?x5x?xi32>
// CHECK:           %[[VAL_0:.*]]:2 = "stablehlo.sort"(%[[ARG0]], %[[DYNAMIC_IOTA_0]]) <{dimension = 2 : i64, is_stable = true}> ({
// CHECK:           ^bb0(%[[VAL_1:.*]]: tensor<i1>, %[[VAL_2:.*]]: tensor<i1>, %[[VAL_3:.*]]: tensor<i32>, %[[VAL_4:.*]]: tensor<i32>):
// CHECK:             %[[COMPARE_0:.*]] = stablehlo.compare  GT, %[[VAL_1]], %[[VAL_2]] : (tensor<i1>, tensor<i1>) -> tensor<i1>
// CHECK:             stablehlo.return %[[COMPARE_0]] : tensor<i1>
// CHECK:           }) : (tensor<?x5x?xi1>, tensor<?x5x?xi32>) -> (tensor<?x5x?xi1>, tensor<?x5x?xi32>)
// CHECK:           %[[CONSTANT_1:.*]] = stablehlo.constant dense<0> : tensor<3xi64>
// CHECK:           %[[CONVERT_0:.*]] = stablehlo.convert %[[CONCATENATE_1]] : (tensor<3xi32>) -> tensor<3xi64>
// CHECK:           %[[CONSTANT_2:.*]] = stablehlo.constant dense<1> : tensor<3xi64>
// CHECK:           %[[REAL_DYNAMIC_SLICE_0:.*]] = stablehlo.real_dynamic_slice %[[VAL_5:.*]]#0, %[[CONSTANT_1]], %[[CONVERT_0]], %[[CONSTANT_2]] : (tensor<?x5x?xi1>, tensor<3xi64>, tensor<3xi64>, tensor<3xi64>) -> tensor<?x5x2xi1>
// CHECK:           %[[REAL_DYNAMIC_SLICE_1:.*]] = stablehlo.real_dynamic_slice %[[VAL_5]]#1, %[[CONSTANT_1]], %[[CONVERT_0]], %[[CONSTANT_2]] : (tensor<?x5x?xi32>, tensor<3xi64>, tensor<3xi64>, tensor<3xi64>) -> tensor<?x5x2xi32>
// CHECK:           return %[[REAL_DYNAMIC_SLICE_0]], %[[REAL_DYNAMIC_SLICE_1]] : tensor<?x5x2xi1>, tensor<?x5x2xi32>
// CHECK:         }
func.func @dyn_top_k(%arg0: tensor<?x5x?xi1>) -> (tensor<?x5x2xi1>, tensor<?x5x2xi32>) {
  %values, %indices = chlo.top_k(%arg0, k = 2) : tensor<?x5x?xi1> -> (tensor<?x5x2xi1>, tensor<?x5x2xi32>)
  return %values, %indices : tensor<?x5x2xi1>, tensor<?x5x2xi32>
}

// -----

// Verify bessel_i1e operator for f16, f32, f64 separately as they use
// different coefficients.

// CHECK-LABEL:   func.func @bessel_i1e_f16(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<16x16xf16>) -> tensor<16x16xf16> {
// CHECK:           %[[CONVERT_0:.*]] = stablehlo.convert %[[ARG0]] : (tensor<16x16xf16>) -> tensor<16x16xf32>
// CHECK:           %[[ABS_0:.*]] = stablehlo.abs %[[CONVERT_0]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<5.000000e-01> : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_1:.*]] = stablehlo.constant dense<2.000000e+00> : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_2:.*]] = stablehlo.constant dense<3.200000e+01> : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_3:.*]] = stablehlo.constant dense<8.000000e+00> : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_0:.*]] = stablehlo.multiply %[[CONSTANT_0]], %[[ABS_0]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_0:.*]] = stablehlo.subtract %[[MULTIPLY_0]], %[[CONSTANT_1]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_4:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_5:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_6:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_1:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[CONSTANT_4]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_1:.*]] = stablehlo.subtract %[[MULTIPLY_1]], %[[CONSTANT_5]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_7:.*]] = stablehlo.constant dense<9.38153732E-9> : tensor<16x16xf32>
// CHECK:           %[[ADD_0:.*]] = stablehlo.add %[[SUBTRACT_1]], %[[CONSTANT_7]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_2:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_0]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_2:.*]] = stablehlo.subtract %[[MULTIPLY_2]], %[[CONSTANT_4]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_8:.*]] = stablehlo.constant dense<-4.44505908E-8> : tensor<16x16xf32>
// CHECK:           %[[ADD_1:.*]] = stablehlo.add %[[SUBTRACT_2]], %[[CONSTANT_8]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_3:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_1]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_3:.*]] = stablehlo.subtract %[[MULTIPLY_3]], %[[ADD_0]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_9:.*]] = stablehlo.constant dense<2.00329481E-7> : tensor<16x16xf32>
// CHECK:           %[[ADD_2:.*]] = stablehlo.add %[[SUBTRACT_3]], %[[CONSTANT_9]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_4:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_2]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_4:.*]] = stablehlo.subtract %[[MULTIPLY_4]], %[[ADD_1]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_10:.*]] = stablehlo.constant dense<-8.568720e-07> : tensor<16x16xf32>
// CHECK:           %[[ADD_3:.*]] = stablehlo.add %[[SUBTRACT_4]], %[[CONSTANT_10]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_5:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_3]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_5:.*]] = stablehlo.subtract %[[MULTIPLY_5]], %[[ADD_2]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_11:.*]] = stablehlo.constant dense<3.47025139E-6> : tensor<16x16xf32>
// CHECK:           %[[ADD_4:.*]] = stablehlo.add %[[SUBTRACT_5]], %[[CONSTANT_11]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_6:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_4]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_6:.*]] = stablehlo.subtract %[[MULTIPLY_6]], %[[ADD_3]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_12:.*]] = stablehlo.constant dense<-1.32731639E-5> : tensor<16x16xf32>
// CHECK:           %[[ADD_5:.*]] = stablehlo.add %[[SUBTRACT_6]], %[[CONSTANT_12]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_7:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_5]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_7:.*]] = stablehlo.subtract %[[MULTIPLY_7]], %[[ADD_4]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_13:.*]] = stablehlo.constant dense<4.78156508E-5> : tensor<16x16xf32>
// CHECK:           %[[ADD_6:.*]] = stablehlo.add %[[SUBTRACT_7]], %[[CONSTANT_13]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_8:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_6]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_8:.*]] = stablehlo.subtract %[[MULTIPLY_8]], %[[ADD_5]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_14:.*]] = stablehlo.constant dense<-1.61760821E-4> : tensor<16x16xf32>
// CHECK:           %[[ADD_7:.*]] = stablehlo.add %[[SUBTRACT_8]], %[[CONSTANT_14]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_9:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_7]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_9:.*]] = stablehlo.subtract %[[MULTIPLY_9]], %[[ADD_6]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_15:.*]] = stablehlo.constant dense<5.122860e-04> : tensor<16x16xf32>
// CHECK:           %[[ADD_8:.*]] = stablehlo.add %[[SUBTRACT_9]], %[[CONSTANT_15]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_10:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_8]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_10:.*]] = stablehlo.subtract %[[MULTIPLY_10]], %[[ADD_7]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_16:.*]] = stablehlo.constant dense<-0.00151357241> : tensor<16x16xf32>
// CHECK:           %[[ADD_9:.*]] = stablehlo.add %[[SUBTRACT_10]], %[[CONSTANT_16]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_11:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_9]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_11:.*]] = stablehlo.subtract %[[MULTIPLY_11]], %[[ADD_8]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_17:.*]] = stablehlo.constant dense<0.0041564228> : tensor<16x16xf32>
// CHECK:           %[[ADD_10:.*]] = stablehlo.add %[[SUBTRACT_11]], %[[CONSTANT_17]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_12:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_10]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_12:.*]] = stablehlo.subtract %[[MULTIPLY_12]], %[[ADD_9]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_18:.*]] = stablehlo.constant dense<-0.0105640851> : tensor<16x16xf32>
// CHECK:           %[[ADD_11:.*]] = stablehlo.add %[[SUBTRACT_12]], %[[CONSTANT_18]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_13:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_11]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_13:.*]] = stablehlo.subtract %[[MULTIPLY_13]], %[[ADD_10]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_19:.*]] = stablehlo.constant dense<0.0247264486> : tensor<16x16xf32>
// CHECK:           %[[ADD_12:.*]] = stablehlo.add %[[SUBTRACT_13]], %[[CONSTANT_19]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_14:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_12]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_14:.*]] = stablehlo.subtract %[[MULTIPLY_14]], %[[ADD_11]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_20:.*]] = stablehlo.constant dense<-0.0529459827> : tensor<16x16xf32>
// CHECK:           %[[ADD_13:.*]] = stablehlo.add %[[SUBTRACT_14]], %[[CONSTANT_20]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_15:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_13]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_15:.*]] = stablehlo.subtract %[[MULTIPLY_15]], %[[ADD_12]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_21:.*]] = stablehlo.constant dense<0.102643661> : tensor<16x16xf32>
// CHECK:           %[[ADD_14:.*]] = stablehlo.add %[[SUBTRACT_15]], %[[CONSTANT_21]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_16:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_14]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_16:.*]] = stablehlo.subtract %[[MULTIPLY_16]], %[[ADD_13]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_22:.*]] = stablehlo.constant dense<-0.176416516> : tensor<16x16xf32>
// CHECK:           %[[ADD_15:.*]] = stablehlo.add %[[SUBTRACT_16]], %[[CONSTANT_22]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_17:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_15]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_17:.*]] = stablehlo.subtract %[[MULTIPLY_17]], %[[ADD_14]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_23:.*]] = stablehlo.constant dense<0.252587199> : tensor<16x16xf32>
// CHECK:           %[[ADD_16:.*]] = stablehlo.add %[[SUBTRACT_17]], %[[CONSTANT_23]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_18:.*]] = stablehlo.subtract %[[ADD_16]], %[[ADD_14]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_24:.*]] = stablehlo.constant dense<5.000000e-01> : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_18:.*]] = stablehlo.multiply %[[SUBTRACT_18]], %[[CONSTANT_24]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_19:.*]] = stablehlo.multiply %[[ABS_0]], %[[MULTIPLY_18]] : tensor<16x16xf32>
// CHECK:           %[[DIVIDE_0:.*]] = stablehlo.divide %[[CONSTANT_2]], %[[ABS_0]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_19:.*]] = stablehlo.subtract %[[DIVIDE_0]], %[[CONSTANT_1]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_25:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_26:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_27:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_20:.*]] = stablehlo.multiply %[[SUBTRACT_19]], %[[CONSTANT_25]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_20:.*]] = stablehlo.subtract %[[MULTIPLY_20]], %[[CONSTANT_26]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_28:.*]] = stablehlo.constant dense<-3.83538046E-9> : tensor<16x16xf32>
// CHECK:           %[[ADD_17:.*]] = stablehlo.add %[[SUBTRACT_20]], %[[CONSTANT_28]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_21:.*]] = stablehlo.multiply %[[SUBTRACT_19]], %[[ADD_17]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_21:.*]] = stablehlo.subtract %[[MULTIPLY_21]], %[[CONSTANT_25]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_29:.*]] = stablehlo.constant dense<-2.63146891E-8> : tensor<16x16xf32>
// CHECK:           %[[ADD_18:.*]] = stablehlo.add %[[SUBTRACT_21]], %[[CONSTANT_29]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_22:.*]] = stablehlo.multiply %[[SUBTRACT_19]], %[[ADD_18]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_22:.*]] = stablehlo.subtract %[[MULTIPLY_22]], %[[ADD_17]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_30:.*]] = stablehlo.constant dense<-2.51223611E-7> : tensor<16x16xf32>
// CHECK:           %[[ADD_19:.*]] = stablehlo.add %[[SUBTRACT_22]], %[[CONSTANT_30]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_23:.*]] = stablehlo.multiply %[[SUBTRACT_19]], %[[ADD_19]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_23:.*]] = stablehlo.subtract %[[MULTIPLY_23]], %[[ADD_18]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_31:.*]] = stablehlo.constant dense<-3.88256467E-6> : tensor<16x16xf32>
// CHECK:           %[[ADD_20:.*]] = stablehlo.add %[[SUBTRACT_23]], %[[CONSTANT_31]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_24:.*]] = stablehlo.multiply %[[SUBTRACT_19]], %[[ADD_20]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_24:.*]] = stablehlo.subtract %[[MULTIPLY_24]], %[[ADD_19]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_32:.*]] = stablehlo.constant dense<-1.10588939E-4> : tensor<16x16xf32>
// CHECK:           %[[ADD_21:.*]] = stablehlo.add %[[SUBTRACT_24]], %[[CONSTANT_32]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_25:.*]] = stablehlo.multiply %[[SUBTRACT_19]], %[[ADD_21]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_25:.*]] = stablehlo.subtract %[[MULTIPLY_25]], %[[ADD_20]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_33:.*]] = stablehlo.constant dense<-0.00976109784> : tensor<16x16xf32>
// CHECK:           %[[ADD_22:.*]] = stablehlo.add %[[SUBTRACT_25]], %[[CONSTANT_33]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_26:.*]] = stablehlo.multiply %[[SUBTRACT_19]], %[[ADD_22]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_26:.*]] = stablehlo.subtract %[[MULTIPLY_26]], %[[ADD_21]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_34:.*]] = stablehlo.constant dense<0.778576254> : tensor<16x16xf32>
// CHECK:           %[[ADD_23:.*]] = stablehlo.add %[[SUBTRACT_26]], %[[CONSTANT_34]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_27:.*]] = stablehlo.subtract %[[ADD_23]], %[[ADD_21]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_35:.*]] = stablehlo.constant dense<5.000000e-01> : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_27:.*]] = stablehlo.multiply %[[SUBTRACT_27]], %[[CONSTANT_35]] : tensor<16x16xf32>
// CHECK:           %[[SQRT_0:.*]] = stablehlo.sqrt %[[ABS_0]] : tensor<16x16xf32>
// CHECK:           %[[DIVIDE_1:.*]] = stablehlo.divide %[[MULTIPLY_27]], %[[SQRT_0]] : tensor<16x16xf32>
// CHECK:           %[[COMPARE_0:.*]] = stablehlo.compare  LE, %[[ABS_0]], %[[CONSTANT_3]] : (tensor<16x16xf32>, tensor<16x16xf32>) -> tensor<16x16xi1>
// CHECK:           %[[SELECT_0:.*]] = stablehlo.select %[[COMPARE_0]], %[[MULTIPLY_19]], %[[DIVIDE_1]] : tensor<16x16xi1>, tensor<16x16xf32>
// CHECK:           %[[SIGN_0:.*]] = stablehlo.sign %[[CONVERT_0]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_28:.*]] = stablehlo.multiply %[[SIGN_0]], %[[SELECT_0]] : tensor<16x16xf32>
// CHECK:           %[[CONVERT_1:.*]] = stablehlo.convert %[[MULTIPLY_28]] : (tensor<16x16xf32>) -> tensor<16x16xf16>
// CHECK:           return %[[CONVERT_1]] : tensor<16x16xf16>
// CHECK:         }
func.func @bessel_i1e_f16(%arg: tensor<16x16xf16>) -> tensor<16x16xf16> {
  %0 = chlo.bessel_i1e %arg : tensor<16x16xf16> -> tensor<16x16xf16>
  func.return %0 : tensor<16x16xf16>
}

// -----

// CHECK-LABEL:   func.func @bessel_i1e_f32(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<16x16xf32>) -> tensor<16x16xf32> {
// CHECK:           %[[ABS_0:.*]] = stablehlo.abs %[[ARG0]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<5.000000e-01> : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_1:.*]] = stablehlo.constant dense<2.000000e+00> : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_2:.*]] = stablehlo.constant dense<3.200000e+01> : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_3:.*]] = stablehlo.constant dense<8.000000e+00> : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_0:.*]] = stablehlo.multiply %[[CONSTANT_0]], %[[ABS_0]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_0:.*]] = stablehlo.subtract %[[MULTIPLY_0]], %[[CONSTANT_1]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_4:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_5:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_6:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_1:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[CONSTANT_4]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_1:.*]] = stablehlo.subtract %[[MULTIPLY_1]], %[[CONSTANT_5]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_7:.*]] = stablehlo.constant dense<9.38153732E-9> : tensor<16x16xf32>
// CHECK:           %[[ADD_0:.*]] = stablehlo.add %[[SUBTRACT_1]], %[[CONSTANT_7]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_2:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_0]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_2:.*]] = stablehlo.subtract %[[MULTIPLY_2]], %[[CONSTANT_4]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_8:.*]] = stablehlo.constant dense<-4.44505908E-8> : tensor<16x16xf32>
// CHECK:           %[[ADD_1:.*]] = stablehlo.add %[[SUBTRACT_2]], %[[CONSTANT_8]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_3:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_1]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_3:.*]] = stablehlo.subtract %[[MULTIPLY_3]], %[[ADD_0]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_9:.*]] = stablehlo.constant dense<2.00329481E-7> : tensor<16x16xf32>
// CHECK:           %[[ADD_2:.*]] = stablehlo.add %[[SUBTRACT_3]], %[[CONSTANT_9]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_4:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_2]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_4:.*]] = stablehlo.subtract %[[MULTIPLY_4]], %[[ADD_1]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_10:.*]] = stablehlo.constant dense<-8.568720e-07> : tensor<16x16xf32>
// CHECK:           %[[ADD_3:.*]] = stablehlo.add %[[SUBTRACT_4]], %[[CONSTANT_10]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_5:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_3]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_5:.*]] = stablehlo.subtract %[[MULTIPLY_5]], %[[ADD_2]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_11:.*]] = stablehlo.constant dense<3.47025139E-6> : tensor<16x16xf32>
// CHECK:           %[[ADD_4:.*]] = stablehlo.add %[[SUBTRACT_5]], %[[CONSTANT_11]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_6:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_4]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_6:.*]] = stablehlo.subtract %[[MULTIPLY_6]], %[[ADD_3]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_12:.*]] = stablehlo.constant dense<-1.32731639E-5> : tensor<16x16xf32>
// CHECK:           %[[ADD_5:.*]] = stablehlo.add %[[SUBTRACT_6]], %[[CONSTANT_12]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_7:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_5]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_7:.*]] = stablehlo.subtract %[[MULTIPLY_7]], %[[ADD_4]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_13:.*]] = stablehlo.constant dense<4.78156508E-5> : tensor<16x16xf32>
// CHECK:           %[[ADD_6:.*]] = stablehlo.add %[[SUBTRACT_7]], %[[CONSTANT_13]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_8:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_6]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_8:.*]] = stablehlo.subtract %[[MULTIPLY_8]], %[[ADD_5]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_14:.*]] = stablehlo.constant dense<-1.61760821E-4> : tensor<16x16xf32>
// CHECK:           %[[ADD_7:.*]] = stablehlo.add %[[SUBTRACT_8]], %[[CONSTANT_14]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_9:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_7]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_9:.*]] = stablehlo.subtract %[[MULTIPLY_9]], %[[ADD_6]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_15:.*]] = stablehlo.constant dense<5.122860e-04> : tensor<16x16xf32>
// CHECK:           %[[ADD_8:.*]] = stablehlo.add %[[SUBTRACT_9]], %[[CONSTANT_15]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_10:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_8]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_10:.*]] = stablehlo.subtract %[[MULTIPLY_10]], %[[ADD_7]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_16:.*]] = stablehlo.constant dense<-0.00151357241> : tensor<16x16xf32>
// CHECK:           %[[ADD_9:.*]] = stablehlo.add %[[SUBTRACT_10]], %[[CONSTANT_16]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_11:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_9]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_11:.*]] = stablehlo.subtract %[[MULTIPLY_11]], %[[ADD_8]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_17:.*]] = stablehlo.constant dense<0.0041564228> : tensor<16x16xf32>
// CHECK:           %[[ADD_10:.*]] = stablehlo.add %[[SUBTRACT_11]], %[[CONSTANT_17]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_12:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_10]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_12:.*]] = stablehlo.subtract %[[MULTIPLY_12]], %[[ADD_9]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_18:.*]] = stablehlo.constant dense<-0.0105640851> : tensor<16x16xf32>
// CHECK:           %[[ADD_11:.*]] = stablehlo.add %[[SUBTRACT_12]], %[[CONSTANT_18]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_13:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_11]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_13:.*]] = stablehlo.subtract %[[MULTIPLY_13]], %[[ADD_10]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_19:.*]] = stablehlo.constant dense<0.0247264486> : tensor<16x16xf32>
// CHECK:           %[[ADD_12:.*]] = stablehlo.add %[[SUBTRACT_13]], %[[CONSTANT_19]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_14:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_12]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_14:.*]] = stablehlo.subtract %[[MULTIPLY_14]], %[[ADD_11]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_20:.*]] = stablehlo.constant dense<-0.0529459827> : tensor<16x16xf32>
// CHECK:           %[[ADD_13:.*]] = stablehlo.add %[[SUBTRACT_14]], %[[CONSTANT_20]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_15:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_13]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_15:.*]] = stablehlo.subtract %[[MULTIPLY_15]], %[[ADD_12]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_21:.*]] = stablehlo.constant dense<0.102643661> : tensor<16x16xf32>
// CHECK:           %[[ADD_14:.*]] = stablehlo.add %[[SUBTRACT_15]], %[[CONSTANT_21]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_16:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_14]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_16:.*]] = stablehlo.subtract %[[MULTIPLY_16]], %[[ADD_13]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_22:.*]] = stablehlo.constant dense<-0.176416516> : tensor<16x16xf32>
// CHECK:           %[[ADD_15:.*]] = stablehlo.add %[[SUBTRACT_16]], %[[CONSTANT_22]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_17:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_15]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_17:.*]] = stablehlo.subtract %[[MULTIPLY_17]], %[[ADD_14]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_23:.*]] = stablehlo.constant dense<0.252587199> : tensor<16x16xf32>
// CHECK:           %[[ADD_16:.*]] = stablehlo.add %[[SUBTRACT_17]], %[[CONSTANT_23]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_18:.*]] = stablehlo.subtract %[[ADD_16]], %[[ADD_14]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_24:.*]] = stablehlo.constant dense<5.000000e-01> : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_18:.*]] = stablehlo.multiply %[[SUBTRACT_18]], %[[CONSTANT_24]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_19:.*]] = stablehlo.multiply %[[ABS_0]], %[[MULTIPLY_18]] : tensor<16x16xf32>
// CHECK:           %[[DIVIDE_0:.*]] = stablehlo.divide %[[CONSTANT_2]], %[[ABS_0]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_19:.*]] = stablehlo.subtract %[[DIVIDE_0]], %[[CONSTANT_1]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_25:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_26:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_27:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_20:.*]] = stablehlo.multiply %[[SUBTRACT_19]], %[[CONSTANT_25]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_20:.*]] = stablehlo.subtract %[[MULTIPLY_20]], %[[CONSTANT_26]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_28:.*]] = stablehlo.constant dense<-3.83538046E-9> : tensor<16x16xf32>
// CHECK:           %[[ADD_17:.*]] = stablehlo.add %[[SUBTRACT_20]], %[[CONSTANT_28]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_21:.*]] = stablehlo.multiply %[[SUBTRACT_19]], %[[ADD_17]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_21:.*]] = stablehlo.subtract %[[MULTIPLY_21]], %[[CONSTANT_25]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_29:.*]] = stablehlo.constant dense<-2.63146891E-8> : tensor<16x16xf32>
// CHECK:           %[[ADD_18:.*]] = stablehlo.add %[[SUBTRACT_21]], %[[CONSTANT_29]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_22:.*]] = stablehlo.multiply %[[SUBTRACT_19]], %[[ADD_18]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_22:.*]] = stablehlo.subtract %[[MULTIPLY_22]], %[[ADD_17]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_30:.*]] = stablehlo.constant dense<-2.51223611E-7> : tensor<16x16xf32>
// CHECK:           %[[ADD_19:.*]] = stablehlo.add %[[SUBTRACT_22]], %[[CONSTANT_30]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_23:.*]] = stablehlo.multiply %[[SUBTRACT_19]], %[[ADD_19]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_23:.*]] = stablehlo.subtract %[[MULTIPLY_23]], %[[ADD_18]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_31:.*]] = stablehlo.constant dense<-3.88256467E-6> : tensor<16x16xf32>
// CHECK:           %[[ADD_20:.*]] = stablehlo.add %[[SUBTRACT_23]], %[[CONSTANT_31]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_24:.*]] = stablehlo.multiply %[[SUBTRACT_19]], %[[ADD_20]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_24:.*]] = stablehlo.subtract %[[MULTIPLY_24]], %[[ADD_19]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_32:.*]] = stablehlo.constant dense<-1.10588939E-4> : tensor<16x16xf32>
// CHECK:           %[[ADD_21:.*]] = stablehlo.add %[[SUBTRACT_24]], %[[CONSTANT_32]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_25:.*]] = stablehlo.multiply %[[SUBTRACT_19]], %[[ADD_21]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_25:.*]] = stablehlo.subtract %[[MULTIPLY_25]], %[[ADD_20]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_33:.*]] = stablehlo.constant dense<-0.00976109784> : tensor<16x16xf32>
// CHECK:           %[[ADD_22:.*]] = stablehlo.add %[[SUBTRACT_25]], %[[CONSTANT_33]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_26:.*]] = stablehlo.multiply %[[SUBTRACT_19]], %[[ADD_22]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_26:.*]] = stablehlo.subtract %[[MULTIPLY_26]], %[[ADD_21]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_34:.*]] = stablehlo.constant dense<0.778576254> : tensor<16x16xf32>
// CHECK:           %[[ADD_23:.*]] = stablehlo.add %[[SUBTRACT_26]], %[[CONSTANT_34]] : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_27:.*]] = stablehlo.subtract %[[ADD_23]], %[[ADD_21]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_35:.*]] = stablehlo.constant dense<5.000000e-01> : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_27:.*]] = stablehlo.multiply %[[SUBTRACT_27]], %[[CONSTANT_35]] : tensor<16x16xf32>
// CHECK:           %[[SQRT_0:.*]] = stablehlo.sqrt %[[ABS_0]] : tensor<16x16xf32>
// CHECK:           %[[DIVIDE_1:.*]] = stablehlo.divide %[[MULTIPLY_27]], %[[SQRT_0]] : tensor<16x16xf32>
// CHECK:           %[[COMPARE_0:.*]] = stablehlo.compare  LE, %[[ABS_0]], %[[CONSTANT_3]] : (tensor<16x16xf32>, tensor<16x16xf32>) -> tensor<16x16xi1>
// CHECK:           %[[SELECT_0:.*]] = stablehlo.select %[[COMPARE_0]], %[[MULTIPLY_19]], %[[DIVIDE_1]] : tensor<16x16xi1>, tensor<16x16xf32>
// CHECK:           %[[SIGN_0:.*]] = stablehlo.sign %[[ARG0]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_28:.*]] = stablehlo.multiply %[[SIGN_0]], %[[SELECT_0]] : tensor<16x16xf32>
// CHECK:           return %[[MULTIPLY_28]] : tensor<16x16xf32>
// CHECK:         }
func.func @bessel_i1e_f32(%arg : tensor<16x16xf32>) -> tensor<16x16xf32> {
  %0 = chlo.bessel_i1e %arg : tensor<16x16xf32> -> tensor<16x16xf32>
  func.return %0 : tensor<16x16xf32>
}

// -----

// CHECK-LABEL:   func.func @bessel_i1e_f64(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<16x16xf64>) -> tensor<16x16xf64> {
// CHECK:           %[[ABS_0:.*]] = stablehlo.abs %[[ARG0]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<5.000000e-01> : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_1:.*]] = stablehlo.constant dense<2.000000e+00> : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_2:.*]] = stablehlo.constant dense<3.200000e+01> : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_3:.*]] = stablehlo.constant dense<8.000000e+00> : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_0:.*]] = stablehlo.multiply %[[CONSTANT_0]], %[[ABS_0]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_0:.*]] = stablehlo.subtract %[[MULTIPLY_0]], %[[CONSTANT_1]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_4:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_5:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_6:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_1:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[CONSTANT_4]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_1:.*]] = stablehlo.subtract %[[MULTIPLY_1]], %[[CONSTANT_5]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_7:.*]] = stablehlo.constant dense<2.7779141127610464E-18> : tensor<16x16xf64>
// CHECK:           %[[ADD_0:.*]] = stablehlo.add %[[SUBTRACT_1]], %[[CONSTANT_7]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_2:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_0]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_2:.*]] = stablehlo.subtract %[[MULTIPLY_2]], %[[CONSTANT_4]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_8:.*]] = stablehlo.constant dense<-2.111421214358166E-17> : tensor<16x16xf64>
// CHECK:           %[[ADD_1:.*]] = stablehlo.add %[[SUBTRACT_2]], %[[CONSTANT_8]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_3:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_1]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_3:.*]] = stablehlo.subtract %[[MULTIPLY_3]], %[[ADD_0]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_9:.*]] = stablehlo.constant dense<1.5536319577362005E-16> : tensor<16x16xf64>
// CHECK:           %[[ADD_2:.*]] = stablehlo.add %[[SUBTRACT_3]], %[[CONSTANT_9]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_4:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_2]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_4:.*]] = stablehlo.subtract %[[MULTIPLY_4]], %[[ADD_1]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_10:.*]] = stablehlo.constant dense<-1.1055969477353862E-15> : tensor<16x16xf64>
// CHECK:           %[[ADD_3:.*]] = stablehlo.add %[[SUBTRACT_4]], %[[CONSTANT_10]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_5:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_3]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_5:.*]] = stablehlo.subtract %[[MULTIPLY_5]], %[[ADD_2]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_11:.*]] = stablehlo.constant dense<7.6006842947354077E-15> : tensor<16x16xf64>
// CHECK:           %[[ADD_4:.*]] = stablehlo.add %[[SUBTRACT_5]], %[[CONSTANT_11]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_6:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_4]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_6:.*]] = stablehlo.subtract %[[MULTIPLY_6]], %[[ADD_3]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_12:.*]] = stablehlo.constant dense<-5.0421855047279118E-14> : tensor<16x16xf64>
// CHECK:           %[[ADD_5:.*]] = stablehlo.add %[[SUBTRACT_6]], %[[CONSTANT_12]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_7:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_5]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_7:.*]] = stablehlo.subtract %[[MULTIPLY_7]], %[[ADD_4]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_13:.*]] = stablehlo.constant dense<3.2237933659455748E-13> : tensor<16x16xf64>
// CHECK:           %[[ADD_6:.*]] = stablehlo.add %[[SUBTRACT_7]], %[[CONSTANT_13]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_8:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_6]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_8:.*]] = stablehlo.subtract %[[MULTIPLY_8]], %[[ADD_5]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_14:.*]] = stablehlo.constant dense<-1.9839743977649436E-12> : tensor<16x16xf64>
// CHECK:           %[[ADD_7:.*]] = stablehlo.add %[[SUBTRACT_8]], %[[CONSTANT_14]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_9:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_7]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_9:.*]] = stablehlo.subtract %[[MULTIPLY_9]], %[[ADD_6]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_15:.*]] = stablehlo.constant dense<1.1736186298890901E-11> : tensor<16x16xf64>
// CHECK:           %[[ADD_8:.*]] = stablehlo.add %[[SUBTRACT_9]], %[[CONSTANT_15]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_10:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_8]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_10:.*]] = stablehlo.subtract %[[MULTIPLY_10]], %[[ADD_7]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_16:.*]] = stablehlo.constant dense<-6.6634897235020271E-11> : tensor<16x16xf64>
// CHECK:           %[[ADD_9:.*]] = stablehlo.add %[[SUBTRACT_10]], %[[CONSTANT_16]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_11:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_9]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_11:.*]] = stablehlo.subtract %[[MULTIPLY_11]], %[[ADD_8]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_17:.*]] = stablehlo.constant dense<3.6255902815521172E-10> : tensor<16x16xf64>
// CHECK:           %[[ADD_10:.*]] = stablehlo.add %[[SUBTRACT_11]], %[[CONSTANT_17]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_12:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_10]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_12:.*]] = stablehlo.subtract %[[MULTIPLY_12]], %[[ADD_9]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_18:.*]] = stablehlo.constant dense<-1.8872497517228294E-9> : tensor<16x16xf64>
// CHECK:           %[[ADD_11:.*]] = stablehlo.add %[[SUBTRACT_12]], %[[CONSTANT_18]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_13:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_11]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_13:.*]] = stablehlo.subtract %[[MULTIPLY_13]], %[[ADD_10]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_19:.*]] = stablehlo.constant dense<9.3815373864957726E-9> : tensor<16x16xf64>
// CHECK:           %[[ADD_12:.*]] = stablehlo.add %[[SUBTRACT_13]], %[[CONSTANT_19]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_14:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_12]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_14:.*]] = stablehlo.subtract %[[MULTIPLY_14]], %[[ADD_11]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_20:.*]] = stablehlo.constant dense<-4.4450591287963281E-8> : tensor<16x16xf64>
// CHECK:           %[[ADD_13:.*]] = stablehlo.add %[[SUBTRACT_14]], %[[CONSTANT_20]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_15:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_13]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_15:.*]] = stablehlo.subtract %[[MULTIPLY_15]], %[[ADD_12]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_21:.*]] = stablehlo.constant dense<2.0032947535521353E-7> : tensor<16x16xf64>
// CHECK:           %[[ADD_14:.*]] = stablehlo.add %[[SUBTRACT_15]], %[[CONSTANT_21]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_16:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_14]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_16:.*]] = stablehlo.subtract %[[MULTIPLY_16]], %[[ADD_13]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_22:.*]] = stablehlo.constant dense<-8.5687202646954547E-7> : tensor<16x16xf64>
// CHECK:           %[[ADD_15:.*]] = stablehlo.add %[[SUBTRACT_16]], %[[CONSTANT_22]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_17:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_15]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_17:.*]] = stablehlo.subtract %[[MULTIPLY_17]], %[[ADD_14]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_23:.*]] = stablehlo.constant dense<3.4702513081376785E-6> : tensor<16x16xf64>
// CHECK:           %[[ADD_16:.*]] = stablehlo.add %[[SUBTRACT_17]], %[[CONSTANT_23]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_18:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_16]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_18:.*]] = stablehlo.subtract %[[MULTIPLY_18]], %[[ADD_15]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_24:.*]] = stablehlo.constant dense<-1.3273163656039436E-5> : tensor<16x16xf64>
// CHECK:           %[[ADD_17:.*]] = stablehlo.add %[[SUBTRACT_18]], %[[CONSTANT_24]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_19:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_17]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_19:.*]] = stablehlo.subtract %[[MULTIPLY_19]], %[[ADD_16]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_25:.*]] = stablehlo.constant dense<4.7815651075500542E-5> : tensor<16x16xf64>
// CHECK:           %[[ADD_18:.*]] = stablehlo.add %[[SUBTRACT_19]], %[[CONSTANT_25]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_20:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_18]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_20:.*]] = stablehlo.subtract %[[MULTIPLY_20]], %[[ADD_17]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_26:.*]] = stablehlo.constant dense<-1.6176081582589674E-4> : tensor<16x16xf64>
// CHECK:           %[[ADD_19:.*]] = stablehlo.add %[[SUBTRACT_20]], %[[CONSTANT_26]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_21:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_19]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_21:.*]] = stablehlo.subtract %[[MULTIPLY_21]], %[[ADD_18]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_27:.*]] = stablehlo.constant dense<5.1228595616857576E-4> : tensor<16x16xf64>
// CHECK:           %[[ADD_20:.*]] = stablehlo.add %[[SUBTRACT_21]], %[[CONSTANT_27]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_22:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_20]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_22:.*]] = stablehlo.subtract %[[MULTIPLY_22]], %[[ADD_19]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_28:.*]] = stablehlo.constant dense<-0.0015135724506312532> : tensor<16x16xf64>
// CHECK:           %[[ADD_21:.*]] = stablehlo.add %[[SUBTRACT_22]], %[[CONSTANT_28]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_23:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_21]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_23:.*]] = stablehlo.subtract %[[MULTIPLY_23]], %[[ADD_20]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_29:.*]] = stablehlo.constant dense<0.0041564229443128882> : tensor<16x16xf64>
// CHECK:           %[[ADD_22:.*]] = stablehlo.add %[[SUBTRACT_23]], %[[CONSTANT_29]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_24:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_22]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_24:.*]] = stablehlo.subtract %[[MULTIPLY_24]], %[[ADD_21]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_30:.*]] = stablehlo.constant dense<-0.010564084894626197> : tensor<16x16xf64>
// CHECK:           %[[ADD_23:.*]] = stablehlo.add %[[SUBTRACT_24]], %[[CONSTANT_30]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_25:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_23]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_25:.*]] = stablehlo.subtract %[[MULTIPLY_25]], %[[ADD_22]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_31:.*]] = stablehlo.constant dense<0.024726449030626516> : tensor<16x16xf64>
// CHECK:           %[[ADD_24:.*]] = stablehlo.add %[[SUBTRACT_25]], %[[CONSTANT_31]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_26:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_24]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_26:.*]] = stablehlo.subtract %[[MULTIPLY_26]], %[[ADD_23]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_32:.*]] = stablehlo.constant dense<-0.052945981208094989> : tensor<16x16xf64>
// CHECK:           %[[ADD_25:.*]] = stablehlo.add %[[SUBTRACT_26]], %[[CONSTANT_32]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_27:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_25]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_27:.*]] = stablehlo.subtract %[[MULTIPLY_27]], %[[ADD_24]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_33:.*]] = stablehlo.constant dense<0.10264365868984709> : tensor<16x16xf64>
// CHECK:           %[[ADD_26:.*]] = stablehlo.add %[[SUBTRACT_27]], %[[CONSTANT_33]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_28:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_26]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_28:.*]] = stablehlo.subtract %[[MULTIPLY_28]], %[[ADD_25]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_34:.*]] = stablehlo.constant dense<-0.17641651835783406> : tensor<16x16xf64>
// CHECK:           %[[ADD_27:.*]] = stablehlo.add %[[SUBTRACT_28]], %[[CONSTANT_34]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_29:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_27]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_29:.*]] = stablehlo.subtract %[[MULTIPLY_29]], %[[ADD_26]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_35:.*]] = stablehlo.constant dense<0.25258718644363365> : tensor<16x16xf64>
// CHECK:           %[[ADD_28:.*]] = stablehlo.add %[[SUBTRACT_29]], %[[CONSTANT_35]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_30:.*]] = stablehlo.subtract %[[ADD_28]], %[[ADD_26]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_36:.*]] = stablehlo.constant dense<5.000000e-01> : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_30:.*]] = stablehlo.multiply %[[SUBTRACT_30]], %[[CONSTANT_36]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_31:.*]] = stablehlo.multiply %[[ABS_0]], %[[MULTIPLY_30]] : tensor<16x16xf64>
// CHECK:           %[[DIVIDE_0:.*]] = stablehlo.divide %[[CONSTANT_2]], %[[ABS_0]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_31:.*]] = stablehlo.subtract %[[DIVIDE_0]], %[[CONSTANT_1]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_37:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_38:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_39:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_32:.*]] = stablehlo.multiply %[[SUBTRACT_31]], %[[CONSTANT_37]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_32:.*]] = stablehlo.subtract %[[MULTIPLY_32]], %[[CONSTANT_38]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_40:.*]] = stablehlo.constant dense<7.5172963108421052E-18> : tensor<16x16xf64>
// CHECK:           %[[ADD_29:.*]] = stablehlo.add %[[SUBTRACT_32]], %[[CONSTANT_40]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_33:.*]] = stablehlo.multiply %[[SUBTRACT_31]], %[[ADD_29]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_33:.*]] = stablehlo.subtract %[[MULTIPLY_33]], %[[CONSTANT_37]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_41:.*]] = stablehlo.constant dense<4.4143483230717077E-18> : tensor<16x16xf64>
// CHECK:           %[[ADD_30:.*]] = stablehlo.add %[[SUBTRACT_33]], %[[CONSTANT_41]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_34:.*]] = stablehlo.multiply %[[SUBTRACT_31]], %[[ADD_30]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_34:.*]] = stablehlo.subtract %[[MULTIPLY_34]], %[[ADD_29]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_42:.*]] = stablehlo.constant dense<-4.6503053684893586E-17> : tensor<16x16xf64>
// CHECK:           %[[ADD_31:.*]] = stablehlo.add %[[SUBTRACT_34]], %[[CONSTANT_42]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_35:.*]] = stablehlo.multiply %[[SUBTRACT_31]], %[[ADD_31]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_35:.*]] = stablehlo.subtract %[[MULTIPLY_35]], %[[ADD_30]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_43:.*]] = stablehlo.constant dense<-3.2095259219934238E-17> : tensor<16x16xf64>
// CHECK:           %[[ADD_32:.*]] = stablehlo.add %[[SUBTRACT_35]], %[[CONSTANT_43]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_36:.*]] = stablehlo.multiply %[[SUBTRACT_31]], %[[ADD_32]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_36:.*]] = stablehlo.subtract %[[MULTIPLY_36]], %[[ADD_31]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_44:.*]] = stablehlo.constant dense<2.9626289976459501E-16> : tensor<16x16xf64>
// CHECK:           %[[ADD_33:.*]] = stablehlo.add %[[SUBTRACT_36]], %[[CONSTANT_44]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_37:.*]] = stablehlo.multiply %[[SUBTRACT_31]], %[[ADD_33]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_37:.*]] = stablehlo.subtract %[[MULTIPLY_37]], %[[ADD_32]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_45:.*]] = stablehlo.constant dense<3.3082023109209285E-16> : tensor<16x16xf64>
// CHECK:           %[[ADD_34:.*]] = stablehlo.add %[[SUBTRACT_37]], %[[CONSTANT_45]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_38:.*]] = stablehlo.multiply %[[SUBTRACT_31]], %[[ADD_34]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_38:.*]] = stablehlo.subtract %[[MULTIPLY_38]], %[[ADD_33]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_46:.*]] = stablehlo.constant dense<-1.8803547755107825E-15> : tensor<16x16xf64>
// CHECK:           %[[ADD_35:.*]] = stablehlo.add %[[SUBTRACT_38]], %[[CONSTANT_46]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_39:.*]] = stablehlo.multiply %[[SUBTRACT_31]], %[[ADD_35]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_39:.*]] = stablehlo.subtract %[[MULTIPLY_39]], %[[ADD_34]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_47:.*]] = stablehlo.constant dense<-3.8144030724370075E-15> : tensor<16x16xf64>
// CHECK:           %[[ADD_36:.*]] = stablehlo.add %[[SUBTRACT_39]], %[[CONSTANT_47]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_40:.*]] = stablehlo.multiply %[[SUBTRACT_31]], %[[ADD_36]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_40:.*]] = stablehlo.subtract %[[MULTIPLY_40]], %[[ADD_35]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_48:.*]] = stablehlo.constant dense<1.0420276984128802E-14> : tensor<16x16xf64>
// CHECK:           %[[ADD_37:.*]] = stablehlo.add %[[SUBTRACT_40]], %[[CONSTANT_48]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_41:.*]] = stablehlo.multiply %[[SUBTRACT_31]], %[[ADD_37]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_41:.*]] = stablehlo.subtract %[[MULTIPLY_41]], %[[ADD_36]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_49:.*]] = stablehlo.constant dense<4.272440016711951E-14> : tensor<16x16xf64>
// CHECK:           %[[ADD_38:.*]] = stablehlo.add %[[SUBTRACT_41]], %[[CONSTANT_49]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_42:.*]] = stablehlo.multiply %[[SUBTRACT_31]], %[[ADD_38]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_42:.*]] = stablehlo.subtract %[[MULTIPLY_42]], %[[ADD_37]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_50:.*]] = stablehlo.constant dense<-2.1015418427726643E-14> : tensor<16x16xf64>
// CHECK:           %[[ADD_39:.*]] = stablehlo.add %[[SUBTRACT_42]], %[[CONSTANT_50]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_43:.*]] = stablehlo.multiply %[[SUBTRACT_31]], %[[ADD_39]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_43:.*]] = stablehlo.subtract %[[MULTIPLY_43]], %[[ADD_38]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_51:.*]] = stablehlo.constant dense<-4.0835511110921974E-13> : tensor<16x16xf64>
// CHECK:           %[[ADD_40:.*]] = stablehlo.add %[[SUBTRACT_43]], %[[CONSTANT_51]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_44:.*]] = stablehlo.multiply %[[SUBTRACT_31]], %[[ADD_40]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_44:.*]] = stablehlo.subtract %[[MULTIPLY_44]], %[[ADD_39]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_52:.*]] = stablehlo.constant dense<-7.1985517762459084E-13> : tensor<16x16xf64>
// CHECK:           %[[ADD_41:.*]] = stablehlo.add %[[SUBTRACT_44]], %[[CONSTANT_52]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_45:.*]] = stablehlo.multiply %[[SUBTRACT_31]], %[[ADD_41]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_45:.*]] = stablehlo.subtract %[[MULTIPLY_45]], %[[ADD_40]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_53:.*]] = stablehlo.constant dense<2.0356285441470896E-12> : tensor<16x16xf64>
// CHECK:           %[[ADD_42:.*]] = stablehlo.add %[[SUBTRACT_45]], %[[CONSTANT_53]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_46:.*]] = stablehlo.multiply %[[SUBTRACT_31]], %[[ADD_42]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_46:.*]] = stablehlo.subtract %[[MULTIPLY_46]], %[[ADD_41]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_54:.*]] = stablehlo.constant dense<1.4125807436613782E-11> : tensor<16x16xf64>
// CHECK:           %[[ADD_43:.*]] = stablehlo.add %[[SUBTRACT_46]], %[[CONSTANT_54]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_47:.*]] = stablehlo.multiply %[[SUBTRACT_31]], %[[ADD_43]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_47:.*]] = stablehlo.subtract %[[MULTIPLY_47]], %[[ADD_42]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_55:.*]] = stablehlo.constant dense<3.2526035830154884E-11> : tensor<16x16xf64>
// CHECK:           %[[ADD_44:.*]] = stablehlo.add %[[SUBTRACT_47]], %[[CONSTANT_55]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_48:.*]] = stablehlo.multiply %[[SUBTRACT_31]], %[[ADD_44]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_48:.*]] = stablehlo.subtract %[[MULTIPLY_48]], %[[ADD_43]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_56:.*]] = stablehlo.constant dense<-1.8974958123505413E-11> : tensor<16x16xf64>
// CHECK:           %[[ADD_45:.*]] = stablehlo.add %[[SUBTRACT_48]], %[[CONSTANT_56]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_49:.*]] = stablehlo.multiply %[[SUBTRACT_31]], %[[ADD_45]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_49:.*]] = stablehlo.subtract %[[MULTIPLY_49]], %[[ADD_44]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_57:.*]] = stablehlo.constant dense<-5.5897434621965838E-10> : tensor<16x16xf64>
// CHECK:           %[[ADD_46:.*]] = stablehlo.add %[[SUBTRACT_49]], %[[CONSTANT_57]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_50:.*]] = stablehlo.multiply %[[SUBTRACT_31]], %[[ADD_46]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_50:.*]] = stablehlo.subtract %[[MULTIPLY_50]], %[[ADD_45]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_58:.*]] = stablehlo.constant dense<-3.835380385964237E-9> : tensor<16x16xf64>
// CHECK:           %[[ADD_47:.*]] = stablehlo.add %[[SUBTRACT_50]], %[[CONSTANT_58]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_51:.*]] = stablehlo.multiply %[[SUBTRACT_31]], %[[ADD_47]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_51:.*]] = stablehlo.subtract %[[MULTIPLY_51]], %[[ADD_46]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_59:.*]] = stablehlo.constant dense<-2.6314688468895196E-8> : tensor<16x16xf64>
// CHECK:           %[[ADD_48:.*]] = stablehlo.add %[[SUBTRACT_51]], %[[CONSTANT_59]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_52:.*]] = stablehlo.multiply %[[SUBTRACT_31]], %[[ADD_48]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_52:.*]] = stablehlo.subtract %[[MULTIPLY_52]], %[[ADD_47]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_60:.*]] = stablehlo.constant dense<-2.5122362378702088E-7> : tensor<16x16xf64>
// CHECK:           %[[ADD_49:.*]] = stablehlo.add %[[SUBTRACT_52]], %[[CONSTANT_60]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_53:.*]] = stablehlo.multiply %[[SUBTRACT_31]], %[[ADD_49]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_53:.*]] = stablehlo.subtract %[[MULTIPLY_53]], %[[ADD_48]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_61:.*]] = stablehlo.constant dense<-3.8825648088776906E-6> : tensor<16x16xf64>
// CHECK:           %[[ADD_50:.*]] = stablehlo.add %[[SUBTRACT_53]], %[[CONSTANT_61]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_54:.*]] = stablehlo.multiply %[[SUBTRACT_31]], %[[ADD_50]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_54:.*]] = stablehlo.subtract %[[MULTIPLY_54]], %[[ADD_49]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_62:.*]] = stablehlo.constant dense<-1.1058893876262371E-4> : tensor<16x16xf64>
// CHECK:           %[[ADD_51:.*]] = stablehlo.add %[[SUBTRACT_54]], %[[CONSTANT_62]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_55:.*]] = stablehlo.multiply %[[SUBTRACT_31]], %[[ADD_51]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_55:.*]] = stablehlo.subtract %[[MULTIPLY_55]], %[[ADD_50]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_63:.*]] = stablehlo.constant dense<-0.0097610974913614687> : tensor<16x16xf64>
// CHECK:           %[[ADD_52:.*]] = stablehlo.add %[[SUBTRACT_55]], %[[CONSTANT_63]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_56:.*]] = stablehlo.multiply %[[SUBTRACT_31]], %[[ADD_52]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_56:.*]] = stablehlo.subtract %[[MULTIPLY_56]], %[[ADD_51]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_64:.*]] = stablehlo.constant dense<0.7785762350182801> : tensor<16x16xf64>
// CHECK:           %[[ADD_53:.*]] = stablehlo.add %[[SUBTRACT_56]], %[[CONSTANT_64]] : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_57:.*]] = stablehlo.subtract %[[ADD_53]], %[[ADD_51]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_65:.*]] = stablehlo.constant dense<5.000000e-01> : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_57:.*]] = stablehlo.multiply %[[SUBTRACT_57]], %[[CONSTANT_65]] : tensor<16x16xf64>
// CHECK:           %[[SQRT_0:.*]] = stablehlo.sqrt %[[ABS_0]] : tensor<16x16xf64>
// CHECK:           %[[DIVIDE_1:.*]] = stablehlo.divide %[[MULTIPLY_57]], %[[SQRT_0]] : tensor<16x16xf64>
// CHECK:           %[[COMPARE_0:.*]] = stablehlo.compare  LE, %[[ABS_0]], %[[CONSTANT_3]] : (tensor<16x16xf64>, tensor<16x16xf64>) -> tensor<16x16xi1>
// CHECK:           %[[SELECT_0:.*]] = stablehlo.select %[[COMPARE_0]], %[[MULTIPLY_31]], %[[DIVIDE_1]] : tensor<16x16xi1>, tensor<16x16xf64>
// CHECK:           %[[SIGN_0:.*]] = stablehlo.sign %[[ARG0]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_58:.*]] = stablehlo.multiply %[[SIGN_0]], %[[SELECT_0]] : tensor<16x16xf64>
// CHECK:           return %[[MULTIPLY_58]] : tensor<16x16xf64>
// CHECK:         }
func.func @bessel_i1e_f64(%arg : tensor<16x16xf64>) -> tensor<16x16xf64> {
  %0 = chlo.bessel_i1e %arg : tensor<16x16xf64> -> tensor<16x16xf64>
  func.return %0 : tensor<16x16xf64>
}

// -----

// CHECK-LABEL:   func.func @erf_inv(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<16x16xf32>) {
// CHECK:           %[[NEGATE_0:.*]] = stablehlo.negate %[[ARG0]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_0:.*]] = stablehlo.multiply %[[ARG0]], %[[NEGATE_0]] : tensor<16x16xf32>
// CHECK:           %[[LOG_PLUS_ONE_0:.*]] = stablehlo.log_plus_one %[[MULTIPLY_0]] : tensor<16x16xf32>
// CHECK:           %[[NEGATE_1:.*]] = stablehlo.negate %[[LOG_PLUS_ONE_0]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<5.000000e+00> : tensor<16x16xf32>
// CHECK:           %[[COMPARE_0:.*]] = stablehlo.compare  LT, %[[NEGATE_1]], %[[CONSTANT_0]] : (tensor<16x16xf32>, tensor<16x16xf32>) -> tensor<16x16xi1>
// CHECK:           %[[CONSTANT_1:.*]] = stablehlo.constant dense<2.500000e+00> : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_0:.*]] = stablehlo.subtract %[[NEGATE_1]], %[[CONSTANT_1]] : tensor<16x16xf32>
// CHECK:           %[[SQRT_0:.*]] = stablehlo.sqrt %[[NEGATE_1]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_2:.*]] = stablehlo.constant dense<3.000000e+00> : tensor<16x16xf32>
// CHECK:           %[[SUBTRACT_1:.*]] = stablehlo.subtract %[[SQRT_0]], %[[CONSTANT_2]] : tensor<16x16xf32>
// CHECK:           %[[SELECT_0:.*]] = stablehlo.select %[[COMPARE_0]], %[[SUBTRACT_0]], %[[SUBTRACT_1]] : tensor<16x16xi1>, tensor<16x16xf32>
// CHECK:           %[[CONSTANT_3:.*]] = stablehlo.constant dense<2.81022636E-8> : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_4:.*]] = stablehlo.constant dense<-2.00214257E-4> : tensor<16x16xf32>
// CHECK:           %[[SELECT_1:.*]] = stablehlo.select %[[COMPARE_0]], %[[CONSTANT_3]], %[[CONSTANT_4]] : tensor<16x16xi1>, tensor<16x16xf32>
// CHECK:           %[[CONSTANT_5:.*]] = stablehlo.constant dense<3.43273939E-7> : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_6:.*]] = stablehlo.constant dense<1.00950558E-4> : tensor<16x16xf32>
// CHECK:           %[[SELECT_2:.*]] = stablehlo.select %[[COMPARE_0]], %[[CONSTANT_5]], %[[CONSTANT_6]] : tensor<16x16xi1>, tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_1:.*]] = stablehlo.multiply %[[SELECT_1]], %[[SELECT_0]] : tensor<16x16xf32>
// CHECK:           %[[ADD_0:.*]] = stablehlo.add %[[SELECT_2]], %[[MULTIPLY_1]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_7:.*]] = stablehlo.constant dense<-3.5233877E-6> : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_8:.*]] = stablehlo.constant dense<0.00134934322> : tensor<16x16xf32>
// CHECK:           %[[SELECT_3:.*]] = stablehlo.select %[[COMPARE_0]], %[[CONSTANT_7]], %[[CONSTANT_8]] : tensor<16x16xi1>, tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_2:.*]] = stablehlo.multiply %[[ADD_0]], %[[SELECT_0]] : tensor<16x16xf32>
// CHECK:           %[[ADD_1:.*]] = stablehlo.add %[[SELECT_3]], %[[MULTIPLY_2]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_9:.*]] = stablehlo.constant dense<-4.39150654E-6> : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_10:.*]] = stablehlo.constant dense<-0.00367342844> : tensor<16x16xf32>
// CHECK:           %[[SELECT_4:.*]] = stablehlo.select %[[COMPARE_0]], %[[CONSTANT_9]], %[[CONSTANT_10]] : tensor<16x16xi1>, tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_3:.*]] = stablehlo.multiply %[[ADD_1]], %[[SELECT_0]] : tensor<16x16xf32>
// CHECK:           %[[ADD_2:.*]] = stablehlo.add %[[SELECT_4]], %[[MULTIPLY_3]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_11:.*]] = stablehlo.constant dense<2.1858087E-4> : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_12:.*]] = stablehlo.constant dense<0.00573950773> : tensor<16x16xf32>
// CHECK:           %[[SELECT_5:.*]] = stablehlo.select %[[COMPARE_0]], %[[CONSTANT_11]], %[[CONSTANT_12]] : tensor<16x16xi1>, tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_4:.*]] = stablehlo.multiply %[[ADD_2]], %[[SELECT_0]] : tensor<16x16xf32>
// CHECK:           %[[ADD_3:.*]] = stablehlo.add %[[SELECT_5]], %[[MULTIPLY_4]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_13:.*]] = stablehlo.constant dense<-0.00125372503> : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_14:.*]] = stablehlo.constant dense<-0.0076224613> : tensor<16x16xf32>
// CHECK:           %[[SELECT_6:.*]] = stablehlo.select %[[COMPARE_0]], %[[CONSTANT_13]], %[[CONSTANT_14]] : tensor<16x16xi1>, tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_5:.*]] = stablehlo.multiply %[[ADD_3]], %[[SELECT_0]] : tensor<16x16xf32>
// CHECK:           %[[ADD_4:.*]] = stablehlo.add %[[SELECT_6]], %[[MULTIPLY_5]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_15:.*]] = stablehlo.constant dense<-0.00417768164> : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_16:.*]] = stablehlo.constant dense<0.00943887047> : tensor<16x16xf32>
// CHECK:           %[[SELECT_7:.*]] = stablehlo.select %[[COMPARE_0]], %[[CONSTANT_15]], %[[CONSTANT_16]] : tensor<16x16xi1>, tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_6:.*]] = stablehlo.multiply %[[ADD_4]], %[[SELECT_0]] : tensor<16x16xf32>
// CHECK:           %[[ADD_5:.*]] = stablehlo.add %[[SELECT_7]], %[[MULTIPLY_6]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_17:.*]] = stablehlo.constant dense<0.246640727> : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_18:.*]] = stablehlo.constant dense<1.00167406> : tensor<16x16xf32>
// CHECK:           %[[SELECT_8:.*]] = stablehlo.select %[[COMPARE_0]], %[[CONSTANT_17]], %[[CONSTANT_18]] : tensor<16x16xi1>, tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_7:.*]] = stablehlo.multiply %[[ADD_5]], %[[SELECT_0]] : tensor<16x16xf32>
// CHECK:           %[[ADD_6:.*]] = stablehlo.add %[[SELECT_8]], %[[MULTIPLY_7]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_19:.*]] = stablehlo.constant dense<1.50140941> : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_20:.*]] = stablehlo.constant dense<2.83297682> : tensor<16x16xf32>
// CHECK:           %[[SELECT_9:.*]] = stablehlo.select %[[COMPARE_0]], %[[CONSTANT_19]], %[[CONSTANT_20]] : tensor<16x16xi1>, tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_8:.*]] = stablehlo.multiply %[[ADD_6]], %[[SELECT_0]] : tensor<16x16xf32>
// CHECK:           %[[ADD_7:.*]] = stablehlo.add %[[SELECT_9]], %[[MULTIPLY_8]] : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_9:.*]] = stablehlo.multiply %[[ADD_7]], %[[ARG0]] : tensor<16x16xf32>
// CHECK:           %[[ABS_0:.*]] = stablehlo.abs %[[ARG0]] : tensor<16x16xf32>
// CHECK:           %[[CONSTANT_21:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<16x16xf32>
// CHECK:           %[[COMPARE_1:.*]] = stablehlo.compare  EQ, %[[ABS_0]], %[[CONSTANT_21]] : (tensor<16x16xf32>, tensor<16x16xf32>) -> tensor<16x16xi1>
// CHECK:           %[[CONSTANT_22:.*]] = stablehlo.constant dense<0x7F800000> : tensor<16x16xf32>
// CHECK:           %[[MULTIPLY_10:.*]] = stablehlo.multiply %[[ARG0]], %[[CONSTANT_22]] : tensor<16x16xf32>
// CHECK:           %[[SELECT_10:.*]] = stablehlo.select %[[COMPARE_1]], %[[MULTIPLY_10]], %[[MULTIPLY_9]] : tensor<16x16xi1>, tensor<16x16xf32>
// CHECK:           return
// CHECK:         }
func.func @erf_inv(%arg0 : tensor<16x16xf32>) {
  %0 = chlo.erf_inv %arg0 : tensor<16x16xf32> -> tensor<16x16xf32>
  return
}

// -----

// CHECK-LABEL:   func.func @erf_inv_wide(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<16x16xf64>) {
// CHECK:           %[[NEGATE_0:.*]] = stablehlo.negate %[[ARG0]] : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_0:.*]] = stablehlo.multiply %[[ARG0]], %[[NEGATE_0]] : tensor<16x16xf64>
// CHECK:           %[[LOG_PLUS_ONE_0:.*]] = stablehlo.log_plus_one %[[MULTIPLY_0]] : tensor<16x16xf64>
// CHECK:           %[[NEGATE_1:.*]] = stablehlo.negate %[[LOG_PLUS_ONE_0]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<6.250000e+00> : tensor<16x16xf64>
// CHECK:           %[[COMPARE_0:.*]] = stablehlo.compare  LT, %[[NEGATE_1]], %[[CONSTANT_0]] : (tensor<16x16xf64>, tensor<16x16xf64>) -> tensor<16x16xi1>
// CHECK:           %[[CONSTANT_1:.*]] = stablehlo.constant dense<1.600000e+01> : tensor<16x16xf64>
// CHECK:           %[[COMPARE_1:.*]] = stablehlo.compare  LT, %[[NEGATE_1]], %[[CONSTANT_1]] : (tensor<16x16xf64>, tensor<16x16xf64>) -> tensor<16x16xi1>
// CHECK:           %[[SQRT_0:.*]] = stablehlo.sqrt %[[NEGATE_1]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_2:.*]] = stablehlo.constant dense<3.125000e+00> : tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_0:.*]] = stablehlo.subtract %[[NEGATE_1]], %[[CONSTANT_2]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_3:.*]] = stablehlo.constant dense<3.250000e+00> : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_4:.*]] = stablehlo.constant dense<5.000000e+00> : tensor<16x16xf64>
// CHECK:           %[[SELECT_0:.*]] = stablehlo.select %[[COMPARE_1]], %[[CONSTANT_3]], %[[CONSTANT_4]] : tensor<16x16xi1>, tensor<16x16xf64>
// CHECK:           %[[SUBTRACT_1:.*]] = stablehlo.subtract %[[SQRT_0]], %[[SELECT_0]] : tensor<16x16xf64>
// CHECK:           %[[SELECT_1:.*]] = stablehlo.select %[[COMPARE_0]], %[[SUBTRACT_0]], %[[SUBTRACT_1]] : tensor<16x16xi1>, tensor<16x16xf64>
// CHECK:           %[[CONSTANT_5:.*]] = stablehlo.constant dense<-3.6444120640178197E-21> : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_6:.*]] = stablehlo.constant dense<2.2137376921775787E-9> : tensor<16x16xf64>
// CHECK:           %[[SELECT_2:.*]] = stablehlo.select %[[COMPARE_0]], %[[CONSTANT_5]], %[[CONSTANT_6]] : tensor<16x16xi1>, tensor<16x16xf64>
// CHECK:           %[[CONSTANT_7:.*]] = stablehlo.constant dense<-2.7109920616438573E-11> : tensor<16x16xf64>
// CHECK:           %[[SELECT_3:.*]] = stablehlo.select %[[COMPARE_1]], %[[SELECT_2]], %[[CONSTANT_7]] : tensor<16x16xi1>, tensor<16x16xf64>
// CHECK:           %[[CONSTANT_8:.*]] = stablehlo.constant dense<-1.6850591381820166E-19> : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_9:.*]] = stablehlo.constant dense<9.075656193888539E-8> : tensor<16x16xf64>
// CHECK:           %[[SELECT_4:.*]] = stablehlo.select %[[COMPARE_0]], %[[CONSTANT_8]], %[[CONSTANT_9]] : tensor<16x16xi1>, tensor<16x16xf64>
// CHECK:           %[[CONSTANT_10:.*]] = stablehlo.constant dense<-2.5556418169965252E-10> : tensor<16x16xf64>
// CHECK:           %[[SELECT_5:.*]] = stablehlo.select %[[COMPARE_1]], %[[SELECT_4]], %[[CONSTANT_10]] : tensor<16x16xi1>, tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_1:.*]] = stablehlo.multiply %[[SELECT_3]], %[[SELECT_1]] : tensor<16x16xf64>
// CHECK:           %[[ADD_0:.*]] = stablehlo.add %[[SELECT_5]], %[[MULTIPLY_1]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_11:.*]] = stablehlo.constant dense<1.28584807152564E-18> : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_12:.*]] = stablehlo.constant dense<-2.7517406297064545E-7> : tensor<16x16xf64>
// CHECK:           %[[SELECT_6:.*]] = stablehlo.select %[[COMPARE_0]], %[[CONSTANT_11]], %[[CONSTANT_12]] : tensor<16x16xi1>, tensor<16x16xf64>
// CHECK:           %[[CONSTANT_13:.*]] = stablehlo.constant dense<1.5076572693500548E-9> : tensor<16x16xf64>
// CHECK:           %[[SELECT_7:.*]] = stablehlo.select %[[COMPARE_1]], %[[SELECT_6]], %[[CONSTANT_13]] : tensor<16x16xi1>, tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_2:.*]] = stablehlo.multiply %[[ADD_0]], %[[SELECT_1]] : tensor<16x16xf64>
// CHECK:           %[[ADD_1:.*]] = stablehlo.add %[[SELECT_7]], %[[MULTIPLY_2]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_14:.*]] = stablehlo.constant dense<1.1157877678025181E-17> : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_15:.*]] = stablehlo.constant dense<1.8239629214389228E-8> : tensor<16x16xf64>
// CHECK:           %[[SELECT_8:.*]] = stablehlo.select %[[COMPARE_0]], %[[CONSTANT_14]], %[[CONSTANT_15]] : tensor<16x16xi1>, tensor<16x16xf64>
// CHECK:           %[[CONSTANT_16:.*]] = stablehlo.constant dense<-3.789465440126737E-9> : tensor<16x16xf64>
// CHECK:           %[[SELECT_9:.*]] = stablehlo.select %[[COMPARE_1]], %[[SELECT_8]], %[[CONSTANT_16]] : tensor<16x16xi1>, tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_3:.*]] = stablehlo.multiply %[[ADD_1]], %[[SELECT_1]] : tensor<16x16xf64>
// CHECK:           %[[ADD_2:.*]] = stablehlo.add %[[SELECT_9]], %[[MULTIPLY_3]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_17:.*]] = stablehlo.constant dense<-1.3331716628546209E-16> : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_18:.*]] = stablehlo.constant dense<1.5027403968909828E-6> : tensor<16x16xf64>
// CHECK:           %[[SELECT_10:.*]] = stablehlo.select %[[COMPARE_0]], %[[CONSTANT_17]], %[[CONSTANT_18]] : tensor<16x16xi1>, tensor<16x16xf64>
// CHECK:           %[[CONSTANT_19:.*]] = stablehlo.constant dense<7.6157012080783394E-9> : tensor<16x16xf64>
// CHECK:           %[[SELECT_11:.*]] = stablehlo.select %[[COMPARE_1]], %[[SELECT_10]], %[[CONSTANT_19]] : tensor<16x16xi1>, tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_4:.*]] = stablehlo.multiply %[[ADD_2]], %[[SELECT_1]] : tensor<16x16xf64>
// CHECK:           %[[ADD_3:.*]] = stablehlo.add %[[SELECT_11]], %[[MULTIPLY_4]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_20:.*]] = stablehlo.constant dense<2.0972767875968562E-17> : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_21:.*]] = stablehlo.constant dense<-4.013867526981546E-6> : tensor<16x16xf64>
// CHECK:           %[[SELECT_12:.*]] = stablehlo.select %[[COMPARE_0]], %[[CONSTANT_20]], %[[CONSTANT_21]] : tensor<16x16xi1>, tensor<16x16xf64>
// CHECK:           %[[CONSTANT_22:.*]] = stablehlo.constant dense<-1.496002662714924E-8> : tensor<16x16xf64>
// CHECK:           %[[SELECT_13:.*]] = stablehlo.select %[[COMPARE_1]], %[[SELECT_12]], %[[CONSTANT_22]] : tensor<16x16xi1>, tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_5:.*]] = stablehlo.multiply %[[ADD_3]], %[[SELECT_1]] : tensor<16x16xf64>
// CHECK:           %[[ADD_4:.*]] = stablehlo.add %[[SELECT_13]], %[[MULTIPLY_5]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_23:.*]] = stablehlo.constant dense<6.6376381343583238E-15> : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_24:.*]] = stablehlo.constant dense<2.9234449089955446E-6> : tensor<16x16xf64>
// CHECK:           %[[SELECT_14:.*]] = stablehlo.select %[[COMPARE_0]], %[[CONSTANT_23]], %[[CONSTANT_24]] : tensor<16x16xi1>, tensor<16x16xf64>
// CHECK:           %[[CONSTANT_25:.*]] = stablehlo.constant dense<2.9147953450901081E-8> : tensor<16x16xf64>
// CHECK:           %[[SELECT_15:.*]] = stablehlo.select %[[COMPARE_1]], %[[SELECT_14]], %[[CONSTANT_25]] : tensor<16x16xi1>, tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_6:.*]] = stablehlo.multiply %[[ADD_4]], %[[SELECT_1]] : tensor<16x16xf64>
// CHECK:           %[[ADD_5:.*]] = stablehlo.add %[[SELECT_15]], %[[MULTIPLY_6]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_26:.*]] = stablehlo.constant dense<-4.0545662729752069E-14> : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_27:.*]] = stablehlo.constant dense<1.2475304481671779E-5> : tensor<16x16xf64>
// CHECK:           %[[SELECT_16:.*]] = stablehlo.select %[[COMPARE_0]], %[[CONSTANT_26]], %[[CONSTANT_27]] : tensor<16x16xi1>, tensor<16x16xf64>
// CHECK:           %[[CONSTANT_28:.*]] = stablehlo.constant dense<-6.7711997758452339E-8> : tensor<16x16xf64>
// CHECK:           %[[SELECT_17:.*]] = stablehlo.select %[[COMPARE_1]], %[[SELECT_16]], %[[CONSTANT_28]] : tensor<16x16xi1>, tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_7:.*]] = stablehlo.multiply %[[ADD_5]], %[[SELECT_1]] : tensor<16x16xf64>
// CHECK:           %[[ADD_6:.*]] = stablehlo.add %[[SELECT_17]], %[[MULTIPLY_7]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_29:.*]] = stablehlo.constant dense<-8.1519341976054721E-14> : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_30:.*]] = stablehlo.constant dense<-4.7318229009055734E-5> : tensor<16x16xf64>
// CHECK:           %[[SELECT_18:.*]] = stablehlo.select %[[COMPARE_0]], %[[CONSTANT_29]], %[[CONSTANT_30]] : tensor<16x16xi1>, tensor<16x16xf64>
// CHECK:           %[[CONSTANT_31:.*]] = stablehlo.constant dense<2.2900482228026655E-7> : tensor<16x16xf64>
// CHECK:           %[[SELECT_19:.*]] = stablehlo.select %[[COMPARE_1]], %[[SELECT_18]], %[[CONSTANT_31]] : tensor<16x16xi1>, tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_8:.*]] = stablehlo.multiply %[[ADD_6]], %[[SELECT_1]] : tensor<16x16xf64>
// CHECK:           %[[ADD_7:.*]] = stablehlo.add %[[SELECT_19]], %[[MULTIPLY_8]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_32:.*]] = stablehlo.constant dense<2.6335093153082323E-12> : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_33:.*]] = stablehlo.constant dense<6.8284851459573175E-5> : tensor<16x16xf64>
// CHECK:           %[[SELECT_20:.*]] = stablehlo.select %[[COMPARE_0]], %[[CONSTANT_32]], %[[CONSTANT_33]] : tensor<16x16xi1>, tensor<16x16xf64>
// CHECK:           %[[CONSTANT_34:.*]] = stablehlo.constant dense<-9.9298272942317003E-7> : tensor<16x16xf64>
// CHECK:           %[[SELECT_21:.*]] = stablehlo.select %[[COMPARE_1]], %[[SELECT_20]], %[[CONSTANT_34]] : tensor<16x16xi1>, tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_9:.*]] = stablehlo.multiply %[[ADD_7]], %[[SELECT_1]] : tensor<16x16xf64>
// CHECK:           %[[ADD_8:.*]] = stablehlo.add %[[SELECT_21]], %[[MULTIPLY_9]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_35:.*]] = stablehlo.constant dense<-1.2975133253453532E-11> : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_36:.*]] = stablehlo.constant dense<2.4031110387097894E-5> : tensor<16x16xf64>
// CHECK:           %[[SELECT_22:.*]] = stablehlo.select %[[COMPARE_0]], %[[CONSTANT_35]], %[[CONSTANT_36]] : tensor<16x16xi1>, tensor<16x16xf64>
// CHECK:           %[[CONSTANT_37:.*]] = stablehlo.constant dense<4.5260625972231537E-6> : tensor<16x16xf64>
// CHECK:           %[[SELECT_23:.*]] = stablehlo.select %[[COMPARE_1]], %[[SELECT_22]], %[[CONSTANT_37]] : tensor<16x16xi1>, tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_10:.*]] = stablehlo.multiply %[[ADD_8]], %[[SELECT_1]] : tensor<16x16xf64>
// CHECK:           %[[ADD_9:.*]] = stablehlo.add %[[SELECT_23]], %[[MULTIPLY_10]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_38:.*]] = stablehlo.constant dense<-5.4154120542946279E-11> : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_39:.*]] = stablehlo.constant dense<-3.5503752036284748E-4> : tensor<16x16xf64>
// CHECK:           %[[SELECT_24:.*]] = stablehlo.select %[[COMPARE_0]], %[[CONSTANT_38]], %[[CONSTANT_39]] : tensor<16x16xi1>, tensor<16x16xf64>
// CHECK:           %[[CONSTANT_40:.*]] = stablehlo.constant dense<-1.9681778105531671E-5> : tensor<16x16xf64>
// CHECK:           %[[SELECT_25:.*]] = stablehlo.select %[[COMPARE_1]], %[[SELECT_24]], %[[CONSTANT_40]] : tensor<16x16xi1>, tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_11:.*]] = stablehlo.multiply %[[ADD_9]], %[[SELECT_1]] : tensor<16x16xf64>
// CHECK:           %[[ADD_10:.*]] = stablehlo.add %[[SELECT_25]], %[[MULTIPLY_11]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_41:.*]] = stablehlo.constant dense<1.0512122733215323E-9> : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_42:.*]] = stablehlo.constant dense<9.5328937973738049E-4> : tensor<16x16xf64>
// CHECK:           %[[SELECT_26:.*]] = stablehlo.select %[[COMPARE_0]], %[[CONSTANT_41]], %[[CONSTANT_42]] : tensor<16x16xi1>, tensor<16x16xf64>
// CHECK:           %[[CONSTANT_43:.*]] = stablehlo.constant dense<7.5995277030017761E-5> : tensor<16x16xf64>
// CHECK:           %[[SELECT_27:.*]] = stablehlo.select %[[COMPARE_1]], %[[SELECT_26]], %[[CONSTANT_43]] : tensor<16x16xi1>, tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_12:.*]] = stablehlo.multiply %[[ADD_10]], %[[SELECT_1]] : tensor<16x16xf64>
// CHECK:           %[[ADD_11:.*]] = stablehlo.add %[[SELECT_27]], %[[MULTIPLY_12]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_44:.*]] = stablehlo.constant dense<-4.1126339803469837E-9> : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_45:.*]] = stablehlo.constant dense<-0.0016882755560235047> : tensor<16x16xf64>
// CHECK:           %[[SELECT_28:.*]] = stablehlo.select %[[COMPARE_0]], %[[CONSTANT_44]], %[[CONSTANT_45]] : tensor<16x16xi1>, tensor<16x16xf64>
// CHECK:           %[[CONSTANT_46:.*]] = stablehlo.constant dense<-2.1503011930044477E-4> : tensor<16x16xf64>
// CHECK:           %[[SELECT_29:.*]] = stablehlo.select %[[COMPARE_1]], %[[SELECT_28]], %[[CONSTANT_46]] : tensor<16x16xi1>, tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_13:.*]] = stablehlo.multiply %[[ADD_11]], %[[SELECT_1]] : tensor<16x16xf64>
// CHECK:           %[[ADD_12:.*]] = stablehlo.add %[[SELECT_29]], %[[MULTIPLY_13]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_47:.*]] = stablehlo.constant dense<-2.9070369957882005E-8> : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_48:.*]] = stablehlo.constant dense<0.0024914420961078508> : tensor<16x16xf64>
// CHECK:           %[[SELECT_30:.*]] = stablehlo.select %[[COMPARE_0]], %[[CONSTANT_47]], %[[CONSTANT_48]] : tensor<16x16xi1>, tensor<16x16xf64>
// CHECK:           %[[CONSTANT_49:.*]] = stablehlo.constant dense<-1.3871931833623122E-4> : tensor<16x16xf64>
// CHECK:           %[[SELECT_31:.*]] = stablehlo.select %[[COMPARE_1]], %[[SELECT_30]], %[[CONSTANT_49]] : tensor<16x16xi1>, tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_14:.*]] = stablehlo.multiply %[[ADD_12]], %[[SELECT_1]] : tensor<16x16xf64>
// CHECK:           %[[ADD_13:.*]] = stablehlo.add %[[SELECT_31]], %[[MULTIPLY_14]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_50:.*]] = stablehlo.constant dense<4.2347877827932404E-7> : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_51:.*]] = stablehlo.constant dense<-0.0037512085075692412> : tensor<16x16xf64>
// CHECK:           %[[SELECT_32:.*]] = stablehlo.select %[[COMPARE_0]], %[[CONSTANT_50]], %[[CONSTANT_51]] : tensor<16x16xi1>, tensor<16x16xf64>
// CHECK:           %[[CONSTANT_52:.*]] = stablehlo.constant dense<1.0103004648645344> : tensor<16x16xf64>
// CHECK:           %[[SELECT_33:.*]] = stablehlo.select %[[COMPARE_1]], %[[SELECT_32]], %[[CONSTANT_52]] : tensor<16x16xi1>, tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_15:.*]] = stablehlo.multiply %[[ADD_13]], %[[SELECT_1]] : tensor<16x16xf64>
// CHECK:           %[[ADD_14:.*]] = stablehlo.add %[[SELECT_33]], %[[MULTIPLY_15]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_53:.*]] = stablehlo.constant dense<-1.3654692000834679E-6> : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_54:.*]] = stablehlo.constant dense<0.0053709145535900636> : tensor<16x16xf64>
// CHECK:           %[[SELECT_34:.*]] = stablehlo.select %[[COMPARE_0]], %[[CONSTANT_53]], %[[CONSTANT_54]] : tensor<16x16xi1>, tensor<16x16xf64>
// CHECK:           %[[CONSTANT_55:.*]] = stablehlo.constant dense<4.8499064014085844> : tensor<16x16xf64>
// CHECK:           %[[SELECT_35:.*]] = stablehlo.select %[[COMPARE_1]], %[[SELECT_34]], %[[CONSTANT_55]] : tensor<16x16xi1>, tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_16:.*]] = stablehlo.multiply %[[ADD_14]], %[[SELECT_1]] : tensor<16x16xf64>
// CHECK:           %[[ADD_15:.*]] = stablehlo.add %[[SELECT_35]], %[[MULTIPLY_16]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_56:.*]] = stablehlo.constant dense<-1.3882523362786469E-5> : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_57:.*]] = stablehlo.constant dense<1.0052589676941592> : tensor<16x16xf64>
// CHECK:           %[[SELECT_36:.*]] = stablehlo.select %[[COMPARE_0]], %[[CONSTANT_56]], %[[CONSTANT_57]] : tensor<16x16xi1>, tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_17:.*]] = stablehlo.multiply %[[ADD_15]], %[[SELECT_1]] : tensor<16x16xf64>
// CHECK:           %[[ADD_16:.*]] = stablehlo.add %[[SELECT_36]], %[[MULTIPLY_17]] : tensor<16x16xf64>
// CHECK:           %[[SELECT_37:.*]] = stablehlo.select %[[COMPARE_1]], %[[ADD_16]], %[[ADD_15]] : tensor<16x16xi1>, tensor<16x16xf64>
// CHECK:           %[[CONSTANT_58:.*]] = stablehlo.constant dense<1.8673420803405714E-4> : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_59:.*]] = stablehlo.constant dense<3.0838856104922208> : tensor<16x16xf64>
// CHECK:           %[[SELECT_38:.*]] = stablehlo.select %[[COMPARE_0]], %[[CONSTANT_58]], %[[CONSTANT_59]] : tensor<16x16xi1>, tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_18:.*]] = stablehlo.multiply %[[SELECT_37]], %[[SELECT_1]] : tensor<16x16xf64>
// CHECK:           %[[ADD_17:.*]] = stablehlo.add %[[SELECT_38]], %[[MULTIPLY_18]] : tensor<16x16xf64>
// CHECK:           %[[SELECT_39:.*]] = stablehlo.select %[[COMPARE_1]], %[[ADD_17]], %[[SELECT_37]] : tensor<16x16xi1>, tensor<16x16xf64>
// CHECK:           %[[CONSTANT_60:.*]] = stablehlo.constant dense<-7.4070253416626698E-4> : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_19:.*]] = stablehlo.multiply %[[SELECT_39]], %[[SELECT_1]] : tensor<16x16xf64>
// CHECK:           %[[ADD_18:.*]] = stablehlo.add %[[CONSTANT_60]], %[[MULTIPLY_19]] : tensor<16x16xf64>
// CHECK:           %[[SELECT_40:.*]] = stablehlo.select %[[COMPARE_0]], %[[ADD_18]], %[[SELECT_39]] : tensor<16x16xi1>, tensor<16x16xf64>
// CHECK:           %[[CONSTANT_61:.*]] = stablehlo.constant dense<-0.0060336708714301491> : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_20:.*]] = stablehlo.multiply %[[SELECT_40]], %[[SELECT_1]] : tensor<16x16xf64>
// CHECK:           %[[ADD_19:.*]] = stablehlo.add %[[CONSTANT_61]], %[[MULTIPLY_20]] : tensor<16x16xf64>
// CHECK:           %[[SELECT_41:.*]] = stablehlo.select %[[COMPARE_0]], %[[ADD_19]], %[[SELECT_40]] : tensor<16x16xi1>, tensor<16x16xf64>
// CHECK:           %[[CONSTANT_62:.*]] = stablehlo.constant dense<0.24015818242558962> : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_21:.*]] = stablehlo.multiply %[[SELECT_41]], %[[SELECT_1]] : tensor<16x16xf64>
// CHECK:           %[[ADD_20:.*]] = stablehlo.add %[[CONSTANT_62]], %[[MULTIPLY_21]] : tensor<16x16xf64>
// CHECK:           %[[SELECT_42:.*]] = stablehlo.select %[[COMPARE_0]], %[[ADD_20]], %[[SELECT_41]] : tensor<16x16xi1>, tensor<16x16xf64>
// CHECK:           %[[CONSTANT_63:.*]] = stablehlo.constant dense<1.6536545626831027> : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_22:.*]] = stablehlo.multiply %[[SELECT_42]], %[[SELECT_1]] : tensor<16x16xf64>
// CHECK:           %[[ADD_21:.*]] = stablehlo.add %[[CONSTANT_63]], %[[MULTIPLY_22]] : tensor<16x16xf64>
// CHECK:           %[[SELECT_43:.*]] = stablehlo.select %[[COMPARE_0]], %[[ADD_21]], %[[SELECT_42]] : tensor<16x16xi1>, tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_23:.*]] = stablehlo.multiply %[[SELECT_43]], %[[ARG0]] : tensor<16x16xf64>
// CHECK:           %[[ABS_0:.*]] = stablehlo.abs %[[ARG0]] : tensor<16x16xf64>
// CHECK:           %[[CONSTANT_64:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<16x16xf64>
// CHECK:           %[[COMPARE_2:.*]] = stablehlo.compare  EQ, %[[ABS_0]], %[[CONSTANT_64]] : (tensor<16x16xf64>, tensor<16x16xf64>) -> tensor<16x16xi1>
// CHECK:           %[[CONSTANT_65:.*]] = stablehlo.constant dense<0x7FF0000000000000> : tensor<16x16xf64>
// CHECK:           %[[MULTIPLY_24:.*]] = stablehlo.multiply %[[ARG0]], %[[CONSTANT_65]] : tensor<16x16xf64>
// CHECK:           %[[SELECT_44:.*]] = stablehlo.select %[[COMPARE_2]], %[[MULTIPLY_24]], %[[MULTIPLY_23]] : tensor<16x16xi1>, tensor<16x16xf64>
// CHECK:           return
// CHECK:         }
func.func @erf_inv_wide(%arg0 : tensor<16x16xf64>) {
  %0 = chlo.erf_inv %arg0 : tensor<16x16xf64> -> tensor<16x16xf64>
  return
}

// -----

!bounded_type = tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK-LABEL:   func.func @erf_inv_bounded(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<?x16xf32, #stablehlo.bounds<16, ?>>) {
// CHECK:           %[[NEGATE_0:.*]] = stablehlo.negate %[[ARG0]] : tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[MULTIPLY_0:.*]] = stablehlo.multiply %[[ARG0]], %[[NEGATE_0]] : tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[LOG_PLUS_ONE_0:.*]] = stablehlo.log_plus_one %[[MULTIPLY_0]] : tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[NEGATE_1:.*]] = stablehlo.negate %[[LOG_PLUS_ONE_0]] : tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<5.000000e+00> : tensor<f32>
// CHECK:           %[[BROADCAST_IN_DIM_0:.*]] = stablehlo.broadcast_in_dim %[[CONSTANT_0]], dims = [] : (tensor<f32>) -> tensor<16x16xf32>
// CHECK:           %[[GET_DIMENSION_SIZE_0:.*]] = stablehlo.get_dimension_size %[[ARG0]], dim = 0 : (tensor<?x16xf32, #stablehlo.bounds<16, ?>>) -> tensor<i32>
// CHECK:           %[[SET_DIMENSION_SIZE_0:.*]] = stablehlo.set_dimension_size %[[BROADCAST_IN_DIM_0]], %[[GET_DIMENSION_SIZE_0]], dim = 0 : (tensor<16x16xf32>, tensor<i32>) -> tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[COMPARE_0:.*]] = stablehlo.compare  LT, %[[NEGATE_1]], %[[SET_DIMENSION_SIZE_0]] : (tensor<?x16xf32, #stablehlo.bounds<16, ?>>, tensor<?x16xf32, #stablehlo.bounds<16, ?>>) -> tensor<?x16xi1, #stablehlo.bounds<16, ?>>
// CHECK:           %[[CONSTANT_1:.*]] = stablehlo.constant dense<2.500000e+00> : tensor<f32>
// CHECK:           %[[BROADCAST_IN_DIM_1:.*]] = stablehlo.broadcast_in_dim %[[CONSTANT_1]], dims = [] : (tensor<f32>) -> tensor<16x16xf32>
// CHECK:           %[[GET_DIMENSION_SIZE_1:.*]] = stablehlo.get_dimension_size %[[ARG0]], dim = 0 : (tensor<?x16xf32, #stablehlo.bounds<16, ?>>) -> tensor<i32>
// CHECK:           %[[SET_DIMENSION_SIZE_1:.*]] = stablehlo.set_dimension_size %[[BROADCAST_IN_DIM_1]], %[[GET_DIMENSION_SIZE_1]], dim = 0 : (tensor<16x16xf32>, tensor<i32>) -> tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[SUBTRACT_0:.*]] = stablehlo.subtract %[[NEGATE_1]], %[[SET_DIMENSION_SIZE_1]] : tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[SQRT_0:.*]] = stablehlo.sqrt %[[NEGATE_1]] : tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[CONSTANT_2:.*]] = stablehlo.constant dense<3.000000e+00> : tensor<f32>
// CHECK:           %[[BROADCAST_IN_DIM_2:.*]] = stablehlo.broadcast_in_dim %[[CONSTANT_2]], dims = [] : (tensor<f32>) -> tensor<16x16xf32>
// CHECK:           %[[GET_DIMENSION_SIZE_2:.*]] = stablehlo.get_dimension_size %[[ARG0]], dim = 0 : (tensor<?x16xf32, #stablehlo.bounds<16, ?>>) -> tensor<i32>
// CHECK:           %[[SET_DIMENSION_SIZE_2:.*]] = stablehlo.set_dimension_size %[[BROADCAST_IN_DIM_2]], %[[GET_DIMENSION_SIZE_2]], dim = 0 : (tensor<16x16xf32>, tensor<i32>) -> tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[SUBTRACT_1:.*]] = stablehlo.subtract %[[SQRT_0]], %[[SET_DIMENSION_SIZE_2]] : tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[SELECT_0:.*]] = stablehlo.select %[[COMPARE_0]], %[[SUBTRACT_0]], %[[SUBTRACT_1]] : tensor<?x16xi1, #stablehlo.bounds<16, ?>>, tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[CONSTANT_3:.*]] = stablehlo.constant dense<2.81022636E-8> : tensor<f32>
// CHECK:           %[[BROADCAST_IN_DIM_3:.*]] = stablehlo.broadcast_in_dim %[[CONSTANT_3]], dims = [] : (tensor<f32>) -> tensor<16x16xf32>
// CHECK:           %[[GET_DIMENSION_SIZE_3:.*]] = stablehlo.get_dimension_size %[[ARG0]], dim = 0 : (tensor<?x16xf32, #stablehlo.bounds<16, ?>>) -> tensor<i32>
// CHECK:           %[[SET_DIMENSION_SIZE_3:.*]] = stablehlo.set_dimension_size %[[BROADCAST_IN_DIM_3]], %[[GET_DIMENSION_SIZE_3]], dim = 0 : (tensor<16x16xf32>, tensor<i32>) -> tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[CONSTANT_4:.*]] = stablehlo.constant dense<-2.00214257E-4> : tensor<f32>
// CHECK:           %[[BROADCAST_IN_DIM_4:.*]] = stablehlo.broadcast_in_dim %[[CONSTANT_4]], dims = [] : (tensor<f32>) -> tensor<16x16xf32>
// CHECK:           %[[GET_DIMENSION_SIZE_4:.*]] = stablehlo.get_dimension_size %[[ARG0]], dim = 0 : (tensor<?x16xf32, #stablehlo.bounds<16, ?>>) -> tensor<i32>
// CHECK:           %[[SET_DIMENSION_SIZE_4:.*]] = stablehlo.set_dimension_size %[[BROADCAST_IN_DIM_4]], %[[GET_DIMENSION_SIZE_4]], dim = 0 : (tensor<16x16xf32>, tensor<i32>) -> tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[SELECT_1:.*]] = stablehlo.select %[[COMPARE_0]], %[[SET_DIMENSION_SIZE_3]], %[[SET_DIMENSION_SIZE_4]] : tensor<?x16xi1, #stablehlo.bounds<16, ?>>, tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[CONSTANT_5:.*]] = stablehlo.constant dense<3.43273939E-7> : tensor<f32>
// CHECK:           %[[BROADCAST_IN_DIM_5:.*]] = stablehlo.broadcast_in_dim %[[CONSTANT_5]], dims = [] : (tensor<f32>) -> tensor<16x16xf32>
// CHECK:           %[[GET_DIMENSION_SIZE_5:.*]] = stablehlo.get_dimension_size %[[ARG0]], dim = 0 : (tensor<?x16xf32, #stablehlo.bounds<16, ?>>) -> tensor<i32>
// CHECK:           %[[SET_DIMENSION_SIZE_5:.*]] = stablehlo.set_dimension_size %[[BROADCAST_IN_DIM_5]], %[[GET_DIMENSION_SIZE_5]], dim = 0 : (tensor<16x16xf32>, tensor<i32>) -> tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[CONSTANT_6:.*]] = stablehlo.constant dense<1.00950558E-4> : tensor<f32>
// CHECK:           %[[BROADCAST_IN_DIM_6:.*]] = stablehlo.broadcast_in_dim %[[CONSTANT_6]], dims = [] : (tensor<f32>) -> tensor<16x16xf32>
// CHECK:           %[[GET_DIMENSION_SIZE_6:.*]] = stablehlo.get_dimension_size %[[ARG0]], dim = 0 : (tensor<?x16xf32, #stablehlo.bounds<16, ?>>) -> tensor<i32>
// CHECK:           %[[SET_DIMENSION_SIZE_6:.*]] = stablehlo.set_dimension_size %[[BROADCAST_IN_DIM_6]], %[[GET_DIMENSION_SIZE_6]], dim = 0 : (tensor<16x16xf32>, tensor<i32>) -> tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[SELECT_2:.*]] = stablehlo.select %[[COMPARE_0]], %[[SET_DIMENSION_SIZE_5]], %[[SET_DIMENSION_SIZE_6]] : tensor<?x16xi1, #stablehlo.bounds<16, ?>>, tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[MULTIPLY_1:.*]] = stablehlo.multiply %[[SELECT_1]], %[[SELECT_0]] : tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[ADD_0:.*]] = stablehlo.add %[[SELECT_2]], %[[MULTIPLY_1]] : tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[CONSTANT_7:.*]] = stablehlo.constant dense<-3.5233877E-6> : tensor<f32>
// CHECK:           %[[BROADCAST_IN_DIM_7:.*]] = stablehlo.broadcast_in_dim %[[CONSTANT_7]], dims = [] : (tensor<f32>) -> tensor<16x16xf32>
// CHECK:           %[[GET_DIMENSION_SIZE_7:.*]] = stablehlo.get_dimension_size %[[ARG0]], dim = 0 : (tensor<?x16xf32, #stablehlo.bounds<16, ?>>) -> tensor<i32>
// CHECK:           %[[SET_DIMENSION_SIZE_7:.*]] = stablehlo.set_dimension_size %[[BROADCAST_IN_DIM_7]], %[[GET_DIMENSION_SIZE_7]], dim = 0 : (tensor<16x16xf32>, tensor<i32>) -> tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[CONSTANT_8:.*]] = stablehlo.constant dense<0.00134934322> : tensor<f32>
// CHECK:           %[[BROADCAST_IN_DIM_8:.*]] = stablehlo.broadcast_in_dim %[[CONSTANT_8]], dims = [] : (tensor<f32>) -> tensor<16x16xf32>
// CHECK:           %[[GET_DIMENSION_SIZE_8:.*]] = stablehlo.get_dimension_size %[[ARG0]], dim = 0 : (tensor<?x16xf32, #stablehlo.bounds<16, ?>>) -> tensor<i32>
// CHECK:           %[[SET_DIMENSION_SIZE_8:.*]] = stablehlo.set_dimension_size %[[BROADCAST_IN_DIM_8]], %[[GET_DIMENSION_SIZE_8]], dim = 0 : (tensor<16x16xf32>, tensor<i32>) -> tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[SELECT_3:.*]] = stablehlo.select %[[COMPARE_0]], %[[SET_DIMENSION_SIZE_7]], %[[SET_DIMENSION_SIZE_8]] : tensor<?x16xi1, #stablehlo.bounds<16, ?>>, tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[MULTIPLY_2:.*]] = stablehlo.multiply %[[ADD_0]], %[[SELECT_0]] : tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[ADD_1:.*]] = stablehlo.add %[[SELECT_3]], %[[MULTIPLY_2]] : tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[CONSTANT_9:.*]] = stablehlo.constant dense<-4.39150654E-6> : tensor<f32>
// CHECK:           %[[BROADCAST_IN_DIM_9:.*]] = stablehlo.broadcast_in_dim %[[CONSTANT_9]], dims = [] : (tensor<f32>) -> tensor<16x16xf32>
// CHECK:           %[[GET_DIMENSION_SIZE_9:.*]] = stablehlo.get_dimension_size %[[ARG0]], dim = 0 : (tensor<?x16xf32, #stablehlo.bounds<16, ?>>) -> tensor<i32>
// CHECK:           %[[SET_DIMENSION_SIZE_9:.*]] = stablehlo.set_dimension_size %[[BROADCAST_IN_DIM_9]], %[[GET_DIMENSION_SIZE_9]], dim = 0 : (tensor<16x16xf32>, tensor<i32>) -> tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[CONSTANT_10:.*]] = stablehlo.constant dense<-0.00367342844> : tensor<f32>
// CHECK:           %[[BROADCAST_IN_DIM_10:.*]] = stablehlo.broadcast_in_dim %[[CONSTANT_10]], dims = [] : (tensor<f32>) -> tensor<16x16xf32>
// CHECK:           %[[GET_DIMENSION_SIZE_10:.*]] = stablehlo.get_dimension_size %[[ARG0]], dim = 0 : (tensor<?x16xf32, #stablehlo.bounds<16, ?>>) -> tensor<i32>
// CHECK:           %[[SET_DIMENSION_SIZE_10:.*]] = stablehlo.set_dimension_size %[[BROADCAST_IN_DIM_10]], %[[GET_DIMENSION_SIZE_10]], dim = 0 : (tensor<16x16xf32>, tensor<i32>) -> tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[SELECT_4:.*]] = stablehlo.select %[[COMPARE_0]], %[[SET_DIMENSION_SIZE_9]], %[[SET_DIMENSION_SIZE_10]] : tensor<?x16xi1, #stablehlo.bounds<16, ?>>, tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[MULTIPLY_3:.*]] = stablehlo.multiply %[[ADD_1]], %[[SELECT_0]] : tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[ADD_2:.*]] = stablehlo.add %[[SELECT_4]], %[[MULTIPLY_3]] : tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[CONSTANT_11:.*]] = stablehlo.constant dense<2.1858087E-4> : tensor<f32>
// CHECK:           %[[BROADCAST_IN_DIM_11:.*]] = stablehlo.broadcast_in_dim %[[CONSTANT_11]], dims = [] : (tensor<f32>) -> tensor<16x16xf32>
// CHECK:           %[[GET_DIMENSION_SIZE_11:.*]] = stablehlo.get_dimension_size %[[ARG0]], dim = 0 : (tensor<?x16xf32, #stablehlo.bounds<16, ?>>) -> tensor<i32>
// CHECK:           %[[SET_DIMENSION_SIZE_11:.*]] = stablehlo.set_dimension_size %[[BROADCAST_IN_DIM_11]], %[[GET_DIMENSION_SIZE_11]], dim = 0 : (tensor<16x16xf32>, tensor<i32>) -> tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[CONSTANT_12:.*]] = stablehlo.constant dense<0.00573950773> : tensor<f32>
// CHECK:           %[[BROADCAST_IN_DIM_12:.*]] = stablehlo.broadcast_in_dim %[[CONSTANT_12]], dims = [] : (tensor<f32>) -> tensor<16x16xf32>
// CHECK:           %[[GET_DIMENSION_SIZE_12:.*]] = stablehlo.get_dimension_size %[[ARG0]], dim = 0 : (tensor<?x16xf32, #stablehlo.bounds<16, ?>>) -> tensor<i32>
// CHECK:           %[[SET_DIMENSION_SIZE_12:.*]] = stablehlo.set_dimension_size %[[BROADCAST_IN_DIM_12]], %[[GET_DIMENSION_SIZE_12]], dim = 0 : (tensor<16x16xf32>, tensor<i32>) -> tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[SELECT_5:.*]] = stablehlo.select %[[COMPARE_0]], %[[SET_DIMENSION_SIZE_11]], %[[SET_DIMENSION_SIZE_12]] : tensor<?x16xi1, #stablehlo.bounds<16, ?>>, tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[MULTIPLY_4:.*]] = stablehlo.multiply %[[ADD_2]], %[[SELECT_0]] : tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[ADD_3:.*]] = stablehlo.add %[[SELECT_5]], %[[MULTIPLY_4]] : tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[CONSTANT_13:.*]] = stablehlo.constant dense<-0.00125372503> : tensor<f32>
// CHECK:           %[[BROADCAST_IN_DIM_13:.*]] = stablehlo.broadcast_in_dim %[[CONSTANT_13]], dims = [] : (tensor<f32>) -> tensor<16x16xf32>
// CHECK:           %[[GET_DIMENSION_SIZE_13:.*]] = stablehlo.get_dimension_size %[[ARG0]], dim = 0 : (tensor<?x16xf32, #stablehlo.bounds<16, ?>>) -> tensor<i32>
// CHECK:           %[[SET_DIMENSION_SIZE_13:.*]] = stablehlo.set_dimension_size %[[BROADCAST_IN_DIM_13]], %[[GET_DIMENSION_SIZE_13]], dim = 0 : (tensor<16x16xf32>, tensor<i32>) -> tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[CONSTANT_14:.*]] = stablehlo.constant dense<-0.0076224613> : tensor<f32>
// CHECK:           %[[BROADCAST_IN_DIM_14:.*]] = stablehlo.broadcast_in_dim %[[CONSTANT_14]], dims = [] : (tensor<f32>) -> tensor<16x16xf32>
// CHECK:           %[[GET_DIMENSION_SIZE_14:.*]] = stablehlo.get_dimension_size %[[ARG0]], dim = 0 : (tensor<?x16xf32, #stablehlo.bounds<16, ?>>) -> tensor<i32>
// CHECK:           %[[SET_DIMENSION_SIZE_14:.*]] = stablehlo.set_dimension_size %[[BROADCAST_IN_DIM_14]], %[[GET_DIMENSION_SIZE_14]], dim = 0 : (tensor<16x16xf32>, tensor<i32>) -> tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[SELECT_6:.*]] = stablehlo.select %[[COMPARE_0]], %[[SET_DIMENSION_SIZE_13]], %[[SET_DIMENSION_SIZE_14]] : tensor<?x16xi1, #stablehlo.bounds<16, ?>>, tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[MULTIPLY_5:.*]] = stablehlo.multiply %[[ADD_3]], %[[SELECT_0]] : tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[ADD_4:.*]] = stablehlo.add %[[SELECT_6]], %[[MULTIPLY_5]] : tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[CONSTANT_15:.*]] = stablehlo.constant dense<-0.00417768164> : tensor<f32>
// CHECK:           %[[BROADCAST_IN_DIM_15:.*]] = stablehlo.broadcast_in_dim %[[CONSTANT_15]], dims = [] : (tensor<f32>) -> tensor<16x16xf32>
// CHECK:           %[[GET_DIMENSION_SIZE_15:.*]] = stablehlo.get_dimension_size %[[ARG0]], dim = 0 : (tensor<?x16xf32, #stablehlo.bounds<16, ?>>) -> tensor<i32>
// CHECK:           %[[SET_DIMENSION_SIZE_15:.*]] = stablehlo.set_dimension_size %[[BROADCAST_IN_DIM_15]], %[[GET_DIMENSION_SIZE_15]], dim = 0 : (tensor<16x16xf32>, tensor<i32>) -> tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[CONSTANT_16:.*]] = stablehlo.constant dense<0.00943887047> : tensor<f32>
// CHECK:           %[[BROADCAST_IN_DIM_16:.*]] = stablehlo.broadcast_in_dim %[[CONSTANT_16]], dims = [] : (tensor<f32>) -> tensor<16x16xf32>
// CHECK:           %[[GET_DIMENSION_SIZE_16:.*]] = stablehlo.get_dimension_size %[[ARG0]], dim = 0 : (tensor<?x16xf32, #stablehlo.bounds<16, ?>>) -> tensor<i32>
// CHECK:           %[[SET_DIMENSION_SIZE_16:.*]] = stablehlo.set_dimension_size %[[BROADCAST_IN_DIM_16]], %[[GET_DIMENSION_SIZE_16]], dim = 0 : (tensor<16x16xf32>, tensor<i32>) -> tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[SELECT_7:.*]] = stablehlo.select %[[COMPARE_0]], %[[SET_DIMENSION_SIZE_15]], %[[SET_DIMENSION_SIZE_16]] : tensor<?x16xi1, #stablehlo.bounds<16, ?>>, tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[MULTIPLY_6:.*]] = stablehlo.multiply %[[ADD_4]], %[[SELECT_0]] : tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[ADD_5:.*]] = stablehlo.add %[[SELECT_7]], %[[MULTIPLY_6]] : tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[CONSTANT_17:.*]] = stablehlo.constant dense<0.246640727> : tensor<f32>
// CHECK:           %[[BROADCAST_IN_DIM_17:.*]] = stablehlo.broadcast_in_dim %[[CONSTANT_17]], dims = [] : (tensor<f32>) -> tensor<16x16xf32>
// CHECK:           %[[GET_DIMENSION_SIZE_17:.*]] = stablehlo.get_dimension_size %[[ARG0]], dim = 0 : (tensor<?x16xf32, #stablehlo.bounds<16, ?>>) -> tensor<i32>
// CHECK:           %[[SET_DIMENSION_SIZE_17:.*]] = stablehlo.set_dimension_size %[[BROADCAST_IN_DIM_17]], %[[GET_DIMENSION_SIZE_17]], dim = 0 : (tensor<16x16xf32>, tensor<i32>) -> tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[CONSTANT_18:.*]] = stablehlo.constant dense<1.00167406> : tensor<f32>
// CHECK:           %[[BROADCAST_IN_DIM_18:.*]] = stablehlo.broadcast_in_dim %[[CONSTANT_18]], dims = [] : (tensor<f32>) -> tensor<16x16xf32>
// CHECK:           %[[GET_DIMENSION_SIZE_18:.*]] = stablehlo.get_dimension_size %[[ARG0]], dim = 0 : (tensor<?x16xf32, #stablehlo.bounds<16, ?>>) -> tensor<i32>
// CHECK:           %[[SET_DIMENSION_SIZE_18:.*]] = stablehlo.set_dimension_size %[[BROADCAST_IN_DIM_18]], %[[GET_DIMENSION_SIZE_18]], dim = 0 : (tensor<16x16xf32>, tensor<i32>) -> tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[SELECT_8:.*]] = stablehlo.select %[[COMPARE_0]], %[[SET_DIMENSION_SIZE_17]], %[[SET_DIMENSION_SIZE_18]] : tensor<?x16xi1, #stablehlo.bounds<16, ?>>, tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[MULTIPLY_7:.*]] = stablehlo.multiply %[[ADD_5]], %[[SELECT_0]] : tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[ADD_6:.*]] = stablehlo.add %[[SELECT_8]], %[[MULTIPLY_7]] : tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[CONSTANT_19:.*]] = stablehlo.constant dense<1.50140941> : tensor<f32>
// CHECK:           %[[BROADCAST_IN_DIM_19:.*]] = stablehlo.broadcast_in_dim %[[CONSTANT_19]], dims = [] : (tensor<f32>) -> tensor<16x16xf32>
// CHECK:           %[[GET_DIMENSION_SIZE_19:.*]] = stablehlo.get_dimension_size %[[ARG0]], dim = 0 : (tensor<?x16xf32, #stablehlo.bounds<16, ?>>) -> tensor<i32>
// CHECK:           %[[SET_DIMENSION_SIZE_19:.*]] = stablehlo.set_dimension_size %[[BROADCAST_IN_DIM_19]], %[[GET_DIMENSION_SIZE_19]], dim = 0 : (tensor<16x16xf32>, tensor<i32>) -> tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[CONSTANT_20:.*]] = stablehlo.constant dense<2.83297682> : tensor<f32>
// CHECK:           %[[BROADCAST_IN_DIM_20:.*]] = stablehlo.broadcast_in_dim %[[CONSTANT_20]], dims = [] : (tensor<f32>) -> tensor<16x16xf32>
// CHECK:           %[[GET_DIMENSION_SIZE_20:.*]] = stablehlo.get_dimension_size %[[ARG0]], dim = 0 : (tensor<?x16xf32, #stablehlo.bounds<16, ?>>) -> tensor<i32>
// CHECK:           %[[SET_DIMENSION_SIZE_20:.*]] = stablehlo.set_dimension_size %[[BROADCAST_IN_DIM_20]], %[[GET_DIMENSION_SIZE_20]], dim = 0 : (tensor<16x16xf32>, tensor<i32>) -> tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[SELECT_9:.*]] = stablehlo.select %[[COMPARE_0]], %[[SET_DIMENSION_SIZE_19]], %[[SET_DIMENSION_SIZE_20]] : tensor<?x16xi1, #stablehlo.bounds<16, ?>>, tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[MULTIPLY_8:.*]] = stablehlo.multiply %[[ADD_6]], %[[SELECT_0]] : tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[ADD_7:.*]] = stablehlo.add %[[SELECT_9]], %[[MULTIPLY_8]] : tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[MULTIPLY_9:.*]] = stablehlo.multiply %[[ADD_7]], %[[ARG0]] : tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[ABS_0:.*]] = stablehlo.abs %[[ARG0]] : tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[CONSTANT_21:.*]] = stablehlo.constant dense<1.000000e+00> : tensor<f32>
// CHECK:           %[[BROADCAST_IN_DIM_21:.*]] = stablehlo.broadcast_in_dim %[[CONSTANT_21]], dims = [] : (tensor<f32>) -> tensor<16x16xf32>
// CHECK:           %[[GET_DIMENSION_SIZE_21:.*]] = stablehlo.get_dimension_size %[[ARG0]], dim = 0 : (tensor<?x16xf32, #stablehlo.bounds<16, ?>>) -> tensor<i32>
// CHECK:           %[[SET_DIMENSION_SIZE_21:.*]] = stablehlo.set_dimension_size %[[BROADCAST_IN_DIM_21]], %[[GET_DIMENSION_SIZE_21]], dim = 0 : (tensor<16x16xf32>, tensor<i32>) -> tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[COMPARE_1:.*]] = stablehlo.compare  EQ, %[[ABS_0]], %[[SET_DIMENSION_SIZE_21]] : (tensor<?x16xf32, #stablehlo.bounds<16, ?>>, tensor<?x16xf32, #stablehlo.bounds<16, ?>>) -> tensor<?x16xi1, #stablehlo.bounds<16, ?>>
// CHECK:           %[[CONSTANT_22:.*]] = stablehlo.constant dense<0x7F800000> : tensor<f32>
// CHECK:           %[[BROADCAST_IN_DIM_22:.*]] = stablehlo.broadcast_in_dim %[[CONSTANT_22]], dims = [] : (tensor<f32>) -> tensor<16x16xf32>
// CHECK:           %[[GET_DIMENSION_SIZE_22:.*]] = stablehlo.get_dimension_size %[[ARG0]], dim = 0 : (tensor<?x16xf32, #stablehlo.bounds<16, ?>>) -> tensor<i32>
// CHECK:           %[[SET_DIMENSION_SIZE_22:.*]] = stablehlo.set_dimension_size %[[BROADCAST_IN_DIM_22]], %[[GET_DIMENSION_SIZE_22]], dim = 0 : (tensor<16x16xf32>, tensor<i32>) -> tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[MULTIPLY_10:.*]] = stablehlo.multiply %[[ARG0]], %[[SET_DIMENSION_SIZE_22]] : tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           %[[SELECT_10:.*]] = stablehlo.select %[[COMPARE_1]], %[[MULTIPLY_10]], %[[MULTIPLY_9]] : tensor<?x16xi1, #stablehlo.bounds<16, ?>>, tensor<?x16xf32, #stablehlo.bounds<16, ?>>
// CHECK:           return
// CHECK:         }
func.func @erf_inv_bounded(%arg0 : !bounded_type) {
  %0 = chlo.erf_inv %arg0 : !bounded_type -> !bounded_type
  return
}

// -----

// CHECK-LABEL:   func.func @square_complex_f32(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<complex<f32>>) -> tensor<complex<f32>> {
// CHECK:           %[[REAL_0:.*]] = stablehlo.real %[[ARG0]] : (tensor<complex<f32>>) -> tensor<f32>
// CHECK:           %[[IS_FINITE_0:.*]] = stablehlo.is_finite %[[REAL_0]] : (tensor<f32>) -> tensor<i1>
// CHECK:           %[[ABS_0:.*]] = stablehlo.abs %[[REAL_0]] : tensor<f32>
// CHECK:           %[[IMAG_0:.*]] = stablehlo.imag %[[ARG0]] : (tensor<complex<f32>>) -> tensor<f32>
// CHECK:           %[[ABS_1:.*]] = stablehlo.abs %[[IMAG_0]] : tensor<f32>
// CHECK:           %[[COMPARE_0:.*]] = stablehlo.compare  EQ, %[[ABS_0]], %[[ABS_1]] : (tensor<f32>, tensor<f32>) -> tensor<i1>
// CHECK:           %[[AND_0:.*]] = stablehlo.and %[[IS_FINITE_0]], %[[COMPARE_0]] : tensor<i1>
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<f32>
// CHECK:           %[[SUBTRACT_0:.*]] = stablehlo.subtract %[[REAL_0]], %[[IMAG_0]] : tensor<f32>
// CHECK:           %[[ADD_0:.*]] = stablehlo.add %[[REAL_0]], %[[IMAG_0]] : tensor<f32>
// CHECK:           %[[MULTIPLY_0:.*]] = stablehlo.multiply %[[SUBTRACT_0]], %[[ADD_0]] : tensor<f32>
// CHECK:           %[[SELECT_0:.*]] = stablehlo.select %[[AND_0]], %[[CONSTANT_0]], %[[MULTIPLY_0]] : tensor<i1>, tensor<f32>
// CHECK:           %[[CONSTANT_1:.*]] = stablehlo.constant dense<2.000000e+00> : tensor<f32>
// CHECK:           %[[MULTIPLY_1:.*]] = stablehlo.multiply %[[REAL_0]], %[[IMAG_0]] : tensor<f32>
// CHECK:           %[[MULTIPLY_2:.*]] = stablehlo.multiply %[[CONSTANT_1]], %[[MULTIPLY_1]] : tensor<f32>
// CHECK:           %[[COMPLEX_0:.*]] = stablehlo.complex %[[SELECT_0]], %[[MULTIPLY_2]] : tensor<complex<f32>>
// CHECK:           return %[[COMPLEX_0]] : tensor<complex<f32>>
// CHECK:         }
func.func @square_complex_f32(%arg : tensor<complex<f32>>) -> tensor<complex<f32>> {
  %result = "chlo.square"(%arg) : (tensor<complex<f32>>) -> tensor<complex<f32>>
  func.return %result : tensor<complex<f32>>
}

// -----

// CHECK-LABEL:   func.func @square_f32(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<f32>) -> tensor<f32> {
// CHECK:           %[[MULTIPLY_0:.*]] = stablehlo.multiply %[[ARG0]], %[[ARG0]] : tensor<f32>
// CHECK:           return %[[MULTIPLY_0]] : tensor<f32>
// CHECK:         }
func.func @square_f32(%arg : tensor<f32>) -> tensor<f32> {
  %result = "chlo.square"(%arg) : (tensor<f32>) -> tensor<f32>
  func.return %result : tensor<f32>
}

// -----

// CHECK-LABEL:   func.func @ragged_dot_mode_1(
// CHECK-SAME:      %[[ARG0:.*]]: tensor<2x11x5xf32>,
// CHECK-SAME:      %[[ARG1:.*]]: tensor<3x2x5x7xf32>,
// CHECK-SAME:      %[[ARG2:.*]]: tensor<3xi64>) -> tensor<2x11x7xf32> {
// CHECK:           %[[IOTA_0:.*]] = stablehlo.iota dim = 1 : tensor<1x11x1xi64>
// CHECK:           %[[CONSTANT_0:.*]] = stablehlo.constant dense<0> : tensor<1xi64>
// CHECK:           %[[CONSTANT_1:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<2x11x7xf32>
// CHECK:           %[[CONSTANT_2:.*]] = stablehlo.constant dense<0.000000e+00> : tensor<2x11x7xf32>
// CHECK:           %[[SLICE_0:.*]] = stablehlo.slice %[[ARG2]] [0:1] : (tensor<3xi64>) -> tensor<1xi64>
// CHECK:           %[[BROADCAST_IN_DIM_0:.*]] = stablehlo.broadcast_in_dim %[[CONSTANT_0]], dims = [0] : (tensor<1xi64>) -> tensor<1x11x1xi64>
// CHECK:           %[[COMPARE_0:.*]] = stablehlo.compare  LE, %[[BROADCAST_IN_DIM_0]], %[[IOTA_0]] : (tensor<1x11x1xi64>, tensor<1x11x1xi64>) -> tensor<1x11x1xi1>
// CHECK:           %[[ADD_0:.*]] = stablehlo.add %[[CONSTANT_0]], %[[SLICE_0]] : tensor<1xi64>
// CHECK:           %[[BROADCAST_IN_DIM_1:.*]] = stablehlo.broadcast_in_dim %[[ADD_0]], dims = [0] : (tensor<1xi64>) -> tensor<1x11x1xi64>
// CHECK:           %[[COMPARE_1:.*]] = stablehlo.compare  LT, %[[IOTA_0]], %[[BROADCAST_IN_DIM_1]] : (tensor<1x11x1xi64>, tensor<1x11x1xi64>) -> tensor<1x11x1xi1>
// CHECK:           %[[AND_0:.*]] = stablehlo.and %[[COMPARE_0]], %[[COMPARE_1]] : tensor<1x11x1xi1>
// CHECK:           %[[BROADCAST_IN_DIM_2:.*]] = stablehlo.broadcast_in_dim %[[AND_0]], dims = [0, 1, 2] : (tensor<1x11x1xi1>) -> tensor<2x11x7xi1>
// CHECK:           %[[SLICE_1:.*]] = stablehlo.slice %[[ARG1]] [0:1, 0:2, 0:5, 0:7] : (tensor<3x2x5x7xf32>) -> tensor<1x2x5x7xf32>
// CHECK:           %[[RESHAPE_0:.*]] = stablehlo.reshape %[[SLICE_1]] : (tensor<1x2x5x7xf32>) -> tensor<2x5x7xf32>
// CHECK:           %[[DOT_GENERAL_0:.*]] = stablehlo.dot_general %[[ARG0]], %[[RESHAPE_0]], batching_dims = [0] x [0], contracting_dims = [2] x [1], precision = [DEFAULT, DEFAULT] : (tensor<2x11x5xf32>, tensor<2x5x7xf32>) -> tensor<2x11x7xf32>
// CHECK:           %[[SELECT_0:.*]] = stablehlo.select %[[BROADCAST_IN_DIM_2]], %[[DOT_GENERAL_0]], %[[CONSTANT_2]] : tensor<2x11x7xi1>, tensor<2x11x7xf32>
// CHECK:           %[[ADD_1:.*]] = stablehlo.add %[[CONSTANT_1]], %[[SELECT_0]] : tensor<2x11x7xf32>
// CHECK:           %[[ADD_2:.*]] = stablehlo.add %[[CONSTANT_0]], %[[SLICE_0]] : tensor<1xi64>
// CHECK:           %[[SLICE_2:.*]] = stablehlo.slice %[[ARG2]] [1:2] : (tensor<3xi64>) -> tensor<1xi64>
// CHECK:           %[[BROADCAST_IN_DIM_3:.*]] = stablehlo.broadcast_in_dim %[[ADD_2]], dims = [0] : (tensor<1xi64>) -> tensor<1x11x1xi64>
// CHECK:           %[[COMPARE_2:.*]] = stablehlo.compare  LE, %[[BROADCAST_IN_DIM_3]], %[[IOTA_0]] : (tensor<1x11x1xi64>, tensor<1x11x1xi64>) -> tensor<1x11x1xi1>
// CHECK:           %[[ADD_3:.*]] = stablehlo.add %[[ADD_2]], %[[SLICE_2]] : tensor<1xi64>
// CHECK:           %[[BROADCAST_IN_DIM_4:.*]] = stablehlo.broadcast_in_dim %[[ADD_3]], dims = [0] : (tensor<1xi64>) -> tensor<1x11x1xi64>
// CHECK:           %[[COMPARE_3:.*]] = stablehlo.compare  LT, %[[IOTA_0]], %[[BROADCAST_IN_DIM_4]] : (tensor<1x11x1xi64>, tensor<1x11x1xi64>) -> tensor<1x11x1xi1>
// CHECK:           %[[AND_1:.*]] = stablehlo.and %[[COMPARE_2]], %[[COMPARE_3]] : tensor<1x11x1xi1>
// CHECK:           %[[BROADCAST_IN_DIM_5:.*]] = stablehlo.broadcast_in_dim %[[AND_1]], dims = [0, 1, 2] : (tensor<1x11x1xi1>) -> tensor<2x11x7xi1>
// CHECK:           %[[SLICE_3:.*]] = stablehlo.slice %[[ARG1]] [1:2, 0:2, 0:5, 0:7] : (tensor<3x2x5x7xf32>) -> tensor<1x2x5x7xf32>
// CHECK:           %[[RESHAPE_1:.*]] = stablehlo.reshape %[[SLICE_3]] : (tensor<1x2x5x7xf32>) -> tensor<2x5x7xf32>
// CHECK:           %[[DOT_GENERAL_1:.*]] = stablehlo.dot_general %[[ARG0]], %[[RESHAPE_1]], batching_dims = [0] x [0], contracting_dims = [2] x [1], precision = [DEFAULT, DEFAULT] : (tensor<2x11x5xf32>, tensor<2x5x7xf32>) -> tensor<2x11x7xf32>
// CHECK:           %[[SELECT_1:.*]] = stablehlo.select %[[BROADCAST_IN_DIM_5]], %[[DOT_GENERAL_1]], %[[CONSTANT_2]] : tensor<2x11x7xi1>, tensor<2x11x7xf32>
// CHECK:           %[[ADD_4:.*]] = stablehlo.add %[[ADD_1]], %[[SELECT_1]] : tensor<2x11x7xf32>
// CHECK:           %[[ADD_5:.*]] = stablehlo.add %[[ADD_2]], %[[SLICE_2]] : tensor<1xi64>
// CHECK:           %[[SLICE_4:.*]] = stablehlo.slice %[[ARG2]] [2:3] : (tensor<3xi64>) -> tensor<1xi64>
// CHECK:           %[[BROADCAST_IN_DIM_6:.*]] = stablehlo.broadcast_in_dim %[[ADD_5]], dims = [0] : (tensor<1xi64>) -> tensor<1x11x1xi64>
// CHECK:           %[[COMPARE_4:.*]] = stablehlo.compare  LE, %[[BROADCAST_IN_DIM_6]], %[[IOTA_0]] : (tensor<1x11x1xi64>, tensor<1x11x1xi64>) -> tensor<1x11x1xi1>
// CHECK:           %[[ADD_6:.*]] = stablehlo.add %[[ADD_5]], %[[SLICE_4]] : tensor<1xi64>
// CHECK:           %[[BROADCAST_IN_DIM_7:.*]] = stablehlo.broadcast_in_dim %[[ADD_6]], dims = [0] : (tensor<1xi64>) -> tensor<1x11x1xi64>
// CHECK:           %[[COMPARE_5:.*]] = stablehlo.compare  LT, %[[IOTA_0]], %[[BROADCAST_IN_DIM_7]] : (tensor<1x11x1xi64>, tensor<1x11x1xi64>) -> tensor<1x11x1xi1>
// CHECK:           %[[AND_2:.*]] = stablehlo.and %[[COMPARE_4]], %[[COMPARE_5]] : tensor<1x11x1xi1>
// CHECK:           %[[BROADCAST_IN_DIM_8:.*]] = stablehlo.broadcast_in_dim %[[AND_2]], dims = [0, 1, 2] : (tensor<1x11x1xi1>) -> tensor<2x11x7xi1>
// CHECK:           %[[SLICE_5:.*]] = stablehlo.slice %[[ARG1]] [2:3, 0:2, 0:5, 0:7] : (tensor<3x2x5x7xf32>) -> tensor<1x2x5x7xf32>
// CHECK:           %[[RESHAPE_2:.*]] = stablehlo.reshape %[[SLICE_5]] : (tensor<1x2x5x7xf32>) -> tensor<2x5x7xf32>
// CHECK:           %[[DOT_GENERAL_2:.*]] = stablehlo.dot_general %[[ARG0]], %[[RESHAPE_2]], batching_dims = [0] x [0], contracting_dims = [2] x [1], precision = [DEFAULT, DEFAULT] : (tensor<2x11x5xf32>, tensor<2x5x7xf32>) -> tensor<2x11x7xf32>
// CHECK:           %[[SELECT_2:.*]] = stablehlo.select %[[BROADCAST_IN_DIM_8]], %[[DOT_GENERAL_2]], %[[CONSTANT_2]] : tensor<2x11x7xi1>, tensor<2x11x7xf32>
// CHECK:           %[[ADD_7:.*]] = stablehlo.add %[[ADD_4]], %[[SELECT_2]] : tensor<2x11x7xf32>
// CHECK:           %[[ADD_8:.*]] = stablehlo.add %[[ADD_5]], %[[SLICE_4]] : tensor<1xi64>
// CHECK:           return %[[ADD_7]] : tensor<2x11x7xf32>
// CHECK:         }
func.func @ragged_dot_mode_1(%lhs : tensor<2x11x5xf32>, %rhs : tensor<3x2x5x7xf32>, %group_sizes : tensor<3xi64>) -> tensor<2x11x7xf32> {
  %0 = "chlo.ragged_dot"(%lhs, %rhs, %group_sizes) {
    ragged_dot_dimension_numbers = #chlo.ragged_dot<
      lhs_batching_dimensions = [0],
      rhs_batching_dimensions = [1],
      lhs_contracting_dimensions = [2],
      rhs_contracting_dimensions = [2],
      lhs_ragged_dimensions = [1],
      rhs_group_dimensions = [0]
    >,
    precision_config = [#chlo<precision DEFAULT>, #chlo<precision DEFAULT>]
  } : (tensor<2x11x5xf32>, tensor<3x2x5x7xf32>, tensor<3xi64>) -> tensor<2x11x7xf32>
  func.return %0 : tensor<2x11x7xf32>
}
