cc_test(
    name = "add_op_test",
    srcs = [
        "AddOpTest.cpp",
    ],
    deps = [
        "//experimental/users/burmako/interpreter",
        "//experimental/users/burmako/interpreter:tensor",
        "//testing/base/public:gunit",
        "//testing/base/public:gunit_main",
        "//third_party/llvm/llvm-project/llvm:Support",
        "//third_party/llvm/llvm-project/mlir:AsmParser",
        "//third_party/llvm/llvm-project/mlir:FuncDialect",
        "//third_party/llvm/llvm-project/mlir:IR",
        "//third_party/tensorflow/compiler/xla/mlir_hlo",
    ],
)
