name: 🐞 Bug Report
description: Report an issue
body:
  - type: markdown
    attributes:
      value: |
        :star2: Thanks for taking the time to report this issue! :star2:

        Please search through [other recent issues](https://github.com/openxla/stablehlo/issues) to see if your report overlaps with an existing issue.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: |
        Also tell us, what did you expect to happen?

        Include any MLIR output leading up to whatever error occurred where possible.
      placeholder: Tell us what you see! Please also copy/paste or link to any relevant log output.
    validations:
      required: true
  - type: textarea
    id: reproducing
    attributes:
      label: Steps to reproduce your issue
      description: |
        Include any commands that you ran.
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
  - type: textarea
    id: version
    attributes:
      label: Version information
      description: What version of our software are you using?
      placeholder: This could be a git commit hash.
