name: ➕ Feature Request
description: Ask for a new feature to be added
body:
  - type: markdown
    attributes:
      value: |
        :star2: Thanks for taking the time to file this request! :star2:

        We also work closely with upstream communities like the MLIR project, which uses the [MLIR Discourse forum](https://discourse.llvm.org/c/mlir/31) for coordination.
  - type: textarea
    id: overview
    attributes:
      label: Request description
      description: |
        What would you like added or changed?
    validations:
      required: true
