# Copyright 2022 The StableHLO Authors.

# The setup-build action gets everything needed by buildAndTest into the workspace.
name: "Setup build environment (ninja, ccache, llvm, lld)"

inputs:
  llvm-version:
    description: |
      LLVM version for checkout and build. Used for ccache value and checkout.
    required: true

runs:
  # This is a composite action - has a list of steps to execute.
  using: "composite"

  steps:
  # Checkout llvm at version specified in input argument.
  - uses: actions/checkout@v2
    with:
      repository: llvm/llvm-project
      ref: ${{ inputs.llvm-version }}
      path: llvm-project
      fetch-depth: 1

  # Get ninja for cmake build.
  - name: Install Ninja
    uses: llvm/actions/install-ninja@55d844821959226fab4911f96f37071c1d4c3268

  # Get LLD - Improves build speed on Linux
  - name: Install LLD
    if: "runner.os == 'Linux'"
    shell: bash
    run: |
      sudo apt-get install -y lld

  # Setup C++ caching using ccache.
  # Cache key is a combination of OS arch and LLVM version.
  - name: Ccache for C++ compilation
    uses: hendrikmuhs/ccache-action@v1.2
    with:
      key: ${{ runner.os }}-stablehlo_build_assets-${{ inputs.llvm-version }}
      max-size: 4G
