# Copyright 2023 The StableHLO Authors.

name: Bazel Build

on:
  pull_request:
    paths: ['**.txt', 'WORKSPACE']
  workflow_dispatch:

inputs:
  llvm-version:
    description: |
      LLVM version for checkout and build. Used for ccache value and checkout.
    required: true

jobs:
  bazel-build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout StableHLO
      uses: actions/checkout@v2

    # Read LLVM version from `build_tools/llvm_version.txt`
    - name: Get LLVM Version
      id: llvm-version
      shell: bash
      run: |
        echo "version=$(cat ${{ github.workspace }}/build_tools/llvm_version.txt)" >> $GITHUB_OUTPUT

    # Setup Bazelisk and caching using GitHub cache
    - name: Setup Bazelisk
      uses: bazelbuild/setup-bazelisk@v2

    - name: Mount bazel cache
      uses: actions/cache@v3
      with:
        path: "~/.cache/bazel"
        key: ${{ runner.os }}-stablehlo_build_assets-${{ inputs.llvm-version }}-bazelbuild

    # Run Bazel build
    - name: Build StableHLO using Bazel
      shell: bash
      run: |
        ./build_tools/github_actions/ci_build_bazel.sh
