# Copyright 2023 The StableHLO Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: CMake Build

on:
  pull_request:
    branches: [ main ]
    paths-ignore: ['**.md', 'docs/**']
  push:
    branches: [ main ]
    paths-ignore: ['**.md', 'docs/**']
  schedule:
    # Run once a day
    - cron:  '0 12 * * *'
  workflow_dispatch:

# Ensure that only a single job or workflow using the same
# concurrency group will run at a time. This would cancel
# any in-progress jobs in the same github workflow and github
# ref (e.g. refs/heads/main or refs/pull/<pr_number>/merge).
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cmake-build:
    env:
      LLVM_PROJECT_DIR: "llvm-project"
      LLVM_BUILD_DIR: "llvm-build"
      STABLEHLO_BUILD_DIR: "stablehlo-build"
      STABLEHLO_PYTHON_BUILD_DIR: "stablehlo-python-build"
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout StableHLO
      uses: actions/checkout@v2

    - name: Get LLVM Version
      id: llvm-version
      shell: bash
      run: |
        echo "version=$(cat ${{ github.workspace }}/build_tools/llvm_version.txt)" >> $GITHUB_OUTPUT

    - name: Setup workspace
      uses: ./.github/actions/setup-build
      with:
        llvm-version: ${{ steps.llvm-version.outputs.version }}

    - name: Configure and Build LLVM
      shell: bash
      run: |
        ./build_tools/github_actions/ci_build_llvm.sh "$LLVM_PROJECT_DIR" "$LLVM_BUILD_DIR"

    - name: Build and Test StableHLO
      shell: bash
      run: |
        ./build_tools/github_actions/ci_build_stablehlo.sh "$LLVM_BUILD_DIR" "$STABLEHLO_BUILD_DIR"

    - name: Build and Test StableHLO Python API
      shell: bash
      run: |
        ./build_tools/github_actions/ci_build_stablehlo_python_api.sh "$LLVM_PROJECT_DIR" "$STABLEHLO_PYTHON_BUILD_DIR" "$GITHUB_WORKSPACE"
