# Copyright 2024 The StableHLO Authors. All Rights Reserved.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#      https://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Execute Tutorial Notebooks

on:
  push:
    paths:
      - 'docs/tutorials/**.ipynb'
      - .github/workflows/execute_tutorials.yml
  schedule:
    # Run once a day
    - cron:  '0 20 * * *'
  workflow_dispatch:

jobs:
  test-notebooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python and install dependencies
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run:  |
          pip install --upgrade pip
          pip install ipython ipykernel nbclient

      - name: Execute tutorial notebooks
        run: |
          jupyter execute docs/tutorials/*.ipynb
        shell: bash
