# Copyright 2022 The StableHLO Authors.

name: Markdown Lint

on:
  workflow_dispatch:
  push:
#  pull_request:
#    paths:
#      - '**.md'

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run markdownlint
      run: |
        ./build_tools/github_actions/lint_markdown.sh "./**/*.md"
