# Copyright 2022 The StableHLO Authors.

name: Docs Lint

on:
  workflow_dispatch:
#  pull_request:
#    paths:
#      - '**.md'

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run markdownlint
      uses: nosborn/github-action-markdown-cli@v3.2.0
      with:
        files: "./**/*.md"
        config_file: docs/markdownlint.yaml
