# Copyright 2026 The StableHLO Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Reset "Approve Copybara" Label

# The 'synchronize' event fires whenever new commits are pushed to the PR.
on:
  pull_request:
    types: [synchronize]

jobs:
  remove-label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  # Required to modify PR labels.
    steps:
      - name: Unset "Approve Copybara"
        # Only run if the label is actually present.
        if: contains(github.event.pull_request.labels.*.name, 'Approve Copybara')
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --remove-label "Approve Copybara" || true
